### ISSUE TITLE
Viewing account + adding one made difficult due to the size of the window

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#100]
RA/RM> Account management

Frame for viewing accounts is limited in size and does not fill up the entire page, user is required to scroll inside the small frame, especially to be able to see the cross to add a new account. 

Question for TF: Is there a design reason for embedding this small frame inside the window?

Desired functionality: list of user accounts takes up all available screen real estate and use the browser scroll bar to scroll up and down (instead of a small scroll bar embedded in a frame inside the window) + having the "Add Account" button outside the window.

**Comment by justinlewis** [comment]
There was a reason for that layout at the time but that can be revisited.

**Comment by dtreatman** [comment]
Agree that this should be changed. The UI should always optimize use of screen real estate, and not be arbitrarily limited by an iFrame, unless there is a clear functional reason to do so.

**Comment by SteeveEbener** [comment]
This has been adjusted => closing this ticket
