### ISSUE TITLE
 "Disabled" check option unclear in account management

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#101]
RA/RM>Account management>Add new user

The "Disabled" check option under "Confirm password" is unclear => what is this field for?

**Comment by justinlewis** [comment]
The UI needs to be updated for more clarrity. Disabling allows for deactivating without fully removing them from the system.

**Comment by dtreatman** [comment]
Suggest that this is not critical for Sprint 0.7. Should address as part of a later sprint, in addition to adding help text or other clarifications in other areas where they may be needed.

**Comment by SteeveEbener** [comment]
The UI seems to have been updated in version 0.7.0
