### ISSUE TITLE
Can't delete an account for which requests for update have been submitted

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#102]
RA/RM>Account Management

I can't delete my contributor's account, most problay because I submitted some request for changes. The error message provided is "Cannot delete [C_Steeve]. Attribute [Owner] on type [Id Record] references it and is a required attribute."

**Comment by justinlewis** [comment]
@steeveebener - I believe this is invalid because we've removed the ability to delete users in a recent release. Now they can only be deactivated.

**Comment by justinlewis** [comment]
closing because this functionality doesn't exist anymore.
