### ISSUE TITLE
Revise module labels

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#105]
RA/RM>Burger Menu

We should remove the mention of "Manager" in the list of admin functions to reduce the number of "managers" in the tool => "Localization" instead of "Localization manager" and "Accounts" instead of "Manage accounts".  WIll the term "Localization" actually be understood? Shall we not more talk about "Language setting"

**Comment by dtreatman** [comment]
Suggest revision of this issue title to "Revise module labels"

Agree that the term "Manager" should be removed from all labels unless it is deemed necessary for understanding the function. 

Also agree that "Languages" is more intuitive than "Localization".

Suggest modules be labeled the following. Will request review and agreement by Steeve and CHAI on this proposal.

1. Master Lists
2. Geospatial Data (to be added)
3. Change Requests
4. GeoObjects and Hierarchies
5. Import / Export 
6. Navigator
7. Accounts
8. Languages
9. Icons
10. Email Server

**Comment by SteeveEbener** [comment]
Agrees except for the:
-  first one in view of the new comment included in issues #78  => " Lists"  instead of " Master Lists" 
- "Import/Export": as discussed in NY with Nate the export function should be removed from this module and only accessible from the Lists and Geospatial data managers  => " Import"

**Comment by justinlewis** [comment]
We should change Navigator in the above list to Explorer.

**Comment by SteeveEbener** [comment]
...and we will need to add the curation module at some point

**Comment by justinlewis** [comment]
I changed everything except for what steve mentioned in the comment above.
- "Import/Export": as discussed in NY with Nate the export function should be removed from this module and only accessible from the Lists and Geospatial data managers => " Import"

Seperating this functionality should be a separate ticket.

**Comment by SteeveEbener** [comment]
The changes have been performed in the burger menu but should also be applied to the home screen,  module title (when open), and any other references made to modules in the UI as per Derek's message here on Jan 29.

**Comment by SteeveEbener** [comment]
The import/export issue that has not been implemented here is now captured in issue #149

**Comment by justinlewis** [comment]
> The changes have been performed in the burger menu but should also be applied to the home screen, module title (when open), and any other references made to modules in the UI as per Derek's message here on Jan 29.

Yep I went through all the pages to change these labels everywhere.

**Comment by SteeveEbener** [comment]
The changes have still not been implemented on the name of the different modules appearing on the home page.

For example, we still have "Hierarchy Manager" instead of "GeoObjects and Hierarchies" or "Master list manager" instead of "Lists"

![Home page](https://user-images.githubusercontent.com/12602163/80792109-4378d800-8bc6-11ea-89fc-b81eb03d3cff.jpg)

The order of the module on this window does also not match the order in the burger menu.

=> these should be changed to ensure consistency as discussed in this issue

**Comment by SteeveEbener** [comment]
The relabeling of the "Tasks" module into "Curation" should also happen as part of this ticket

**Comment by justinlewis** [comment]
Let's try this again:

![Screenshot from 2020-06-25 23-09-03.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/771aa6af-d18e-44a2-a7e0-433a9e5d7edb)

**Comment by SteeveEbener** [comment]
Jackpot! Thanks in advance for implementing this as presented on this image. Thanks @justinlewis

**Comment by CarlyNel** [comment]
Hi @justinlewis and @SteeveEbener, sorry to be the bearer of bad news but it seems that the "tasks" title has not yet been changed to "curation" in the hamburger menu. See below screenshot. All other module names match your above screenshot and the hamburger drop down options.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/476b52cd-3ded-41f1-b597-cc55a475a93b)

**Comment by CarlyNel** [comment]
Update: I've just deleted my previous comment as the inconsistent names on the Curation module vs in the hamburger drop down menu was as a result of my cache. I've now cleared my cache and refreshed my browser and the names are now matching. See screenshot below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/1ed8501e-a60d-4ffa-ba4a-0005eab752eb)

**Comment by SteeveEbener** [comment]
This ticket has been implemented. I am closing it.
