### ISSUE TITLE
Check button too small for add new user

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#106]
RA/RM>Administrator>Account management>Add new user

The check button to select the role is too small. Can't see well which option I have selected on my screen => Could we increase the size?

**Comment by dtreatman** [comment]
Agree, would be preferable to have larger radio buttons.

There are additional issues with this list of user roles that should also be addressed. The list of roles does not match the CGR specification.  Noting this here in case it is not already included in another ticket. User roles should be:

- Super Registry Administrator (SRA)
- Registry Administrator (RA)
- Registry Maintainer (RM)
- Registry Contributor (RC)
- Application Programming Interface Consumer (AC)
- Anonymous User (AU)

**Comment by SteeveEbener** [comment]
This issue is linked to issue #58 
=> See my comment regarding the SRA role that should be removed from the list.

**Comment by SteeveEbener** [comment]
This issue should be closed as not pertinent anymore since version 0.7.0
