### ISSUE TITLE
Account management window title

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#107]
RA/RM>Administrator>Account management

If we keep the same title for the page then we should rename it as "Accounts management" (plural)

**Comment by dtreatman** [comment]
Suggest this ticket be closed. All label changes have been consolidated into ticket #105 https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/105

**Comment by justinlewis** [comment]
Closing because of consolidated tickets.
