### ISSUE TITLE
Design UI/UX for the new GeoPrism application navigation

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#109]
**See requirements doc for conceptual mockups:**  
- https://terraframe.atlassian.net/wiki/spaces/GGR/pages/1010073642/GeoPrism+Platform+Re-structure

**Complete when mockups are created for:**
- [ ] Home page
- [ ] Domain specific functionality page whcn clicking into an app (no CGR core functionality)
- [ ] Version of domain specific functionality page whcn clicking into an app when seeing GeoPrism core functionality as well
- [ ] Any header changes.

**Comment by aleecodes** [comment]
I wanted to get this on your radar before I did too much more. Right now it's just a home page and a example of drilling into the Common Geo-Registry hierarchy.

My thinking was to visually categorize these in a simple to view way yet letting users know where they are in the hierarchy.  

[https://app.zenhub.com/files/142912671/919eec14-af2d-48c5-95a7-406976022f5b/download](https://app.zenhub.com/files/142912671/919eec14-af2d-48c5-95a7-406976022f5b/download)

**Comment by nmceachen** [comment]
I like it
