### ISSUE TITLE
Manage data overrides when duplicates are detected in bulk uploads

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#115]
## User stories
1. When I do a bulk import; I want to detect conflicts before they are taken in

## Problems this relates to
When RM bulk uploads the system with automatically overwrite values when a GeoObject match is detected (matching by the ID). This can be can result in unwanted overrides.

## Proposed solution
Add an ability to specify if the upload is new or to update existing data.
1. If is to update we can allow overrides.
2. If is new we detect conflicts (e.g. duplicate ID's) and expose those issues to the user in the conflict manager.

**Comment by SteeveEbener** [comment]
Case 1 (update) is still tricky and would require for a message to appear to the user indicating that choosing this option will result in overwrite and make sure he wants to proceed

**Comment by justinlewis** [comment]
@SteeveEbener Adding that message is no problem. I expect that kind of detail to be planned in the design process but it's good to have that note here.
