### ISSUE TITLE
Design UI/UX for finding orphaned GeoObjects

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#118]
## User stories
1. As a RM I need to find orphaned villages and work to link or apply them to facilities.

## Problems this relates to
1. Orphaned GeoObjects may be hard to detect from the existing interfaces (e.g. master lists, the explorer). It can be important to ensure that all the parent/child relationships are established.

**Comment by SteeveEbener** [comment]
There will always be orphans in hierarchies that combines GeoObject types under the authority of different RAs (village and health facilities to define the catchment area for example.l

=> Finding such orphans is meant to take place in the curation module
