### ISSUE TITLE
Design UI/UX for new role managment 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#127]
## Conceptual Sketches
- [Rough napkin sketch mockup to sort out functionality](https://www.lucidchart.com/invitations/accept/65197e7b-2f55-43fc-a889-a848cd808b5b).

## Design Mockups
- [Working doc](https://docs.google.com/document/d/1wM9Fmm8uMLQYIEm7bmj1_AU1X2khymfvqru1xvqSj44/edit?usp=sharing)

**Comment by aleecodes** [comment]
`Updated the working doc
