### ISSUE TITLE
Issues to be addressed in preparation for the forthcoming CGR demos

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#148]
Here is the list of the "cosmetic" issues I think it would be important to complete before the forthcoming CGR demos:

- #63 
- #81 
- #93 
- #97 
- #98 
- #105 
- #137 
- #143 
- #144 
- #145

**Comment by justinlewis** [comment]
Closing because I added a 'demo priority' tag and tagged all these ticket with it to replace this ticket.
