### ISSUE TITLE
Master vs. Non-Master Lists

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#15]
It is important to allow the CGR governing body to manage a master list as well as program partners to reuse the master and to create and manage non-master or program-specific lists.  It is possible as well that non-master lists may re-use dimensions of a master list.  This epic is intended to enhance the user interface, data management, and sharing across the different types of lists.  

Epic documentation and user stories can be found here: [Shared Google Doc](https://docs.google.com/document/d/1gGx7eH94mRkpazqGatGR8D8Q6JEgpFXo75hUcCgyyUo/edit#)

**Comment by dtreatman** [comment]
Questions:

- Should an RM have the ability to add GeoObjects to an operational list that are not part of the master list? Or should an operational list ONLY allow subsetting of a master list?

**Comment by nmceachen** [comment]
GeoObjects that do not exist in a master list can be added to an operational list. For example, from an operational standpoint, locations will be treated as villages that the government does not recognize as formal villages.

**Comment by dtreatman** [comment]
Hi @justinlewis - some of the functionality around non-master lists still needs to be implemented (copied from the Epic doc below). I don't think we have open issues covering these stories, so making a note here that they need to be added in.

1. Should we allow for programmatic villages (e.g., MIMU) so we can handle new geo-objects that are from non-master lists?
2. If so, will the same master attributes carry over from the official master source? 
3. If so, can the non-master RA potentially add additional non-master attributes?

Answer: yes to all

**Comment by SteeveEbener** [comment]
There are other points reported in the table at the bottom of the Epic google doc that will have to be addressed/discussed before looking into this: 
    4. How should identifiers for non-master objects be assigned? **Answer:** Master IDs couldn’t be applied to non-master objects.  Need a new second ID for non-master objects.
    6. What about if there are non-master villages, could they be submitted as changes to the master list (and still maintain the history from non-master)? **Answer:** Yes but only if the user in question is recognized as being a RC by the organization having the curation mandate over the master list
    8. What permissions and governance is needed to support the creation and management of the non-master list?  Hybrid lists? **Answer:** Hybrid lists are created and managed by approved RA/RM (might require to have an additional concept to master and non-master)
    9. Lists can be hybrid - part master, part non-master. Question: what do you call this? and 10. The moment you add non-master items it becomes a non-master list. The moment you diverge from master; could the whole list become non-master? **Answer:** A hybrid list. The moment you add non-master items it becomes a hybrid list. For diverging from the master, this will have to be defined.
