### ISSUE TITLE
In preparation for the transition from the Navigator to the Explorer

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#151]
We should not be able to modify, edit synonyms or delete a location from the navigator in general and in any case when the option to edit the GeoObject type in the web is not checked.

**Comment by justinlewis** [comment]
TODO: add this to the planning process and/or a requirements doc.

**Comment by justinlewis** [comment]
@steeveebener I believe this was taken care of in release 0.14.1

**Comment by SteeveEbener** [comment]
I don't know and I am not sure this is still valid. In any case, there is so much to be changed in the current version of the explorer that we can definitively close this ticket. Doing it now.
