### ISSUE TITLE
GeoObject type not mentioned when looking at a master list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#155]
## User stories
1. When I look at a master list I want to know to which GeoObject type it corresponds

## Problems this relates to
1. The GeoObject Type is not mentioned on top of the window displaying the master list for that GeoObject type 

## Proposed solution
1. Mention the GeoObject Type on top of the window showing the master list

## Considered alternatives
1. None

## Additional context
None

**Comment by justinlewis** [comment]
Tested on v 0.12.1 on Staging.

![Screenshot from 2020-11-13 14-23-03.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/7b404d71-457d-4034-8a5b-3d656e9ede48)

**Comment by SteeveEbener** [comment]
Tested and working. I am closing this ticket.
