### ISSUE TITLE
Header of the window to edit the values for a particular field in the master list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#156]
## User stories
1. As a RM I want to make sure that I am doing changes to the correct field  

## Problems this relates to
1. The label of the field that you are about to edit from the master list is not mentioned on top of the window in question

## Proposed solution
1. Display the label of the field, and potentially the description attached to the field in question, on top of the window in which the editing can take place

## Considered alternatives
1. None

## Additional context
None

**Comment by justinlewis** [comment]
Can you list out the steps to re-create this?  We're having a hard time understanding the scenario you described.

**Comment by SteeveEbener** [comment]
Here you go (As RA/RM):
1. Go to the lists module
2. Open a list on which you have the curation mandate
3. Click the edit pen button
4. Go to the attributes window
5. click edit for any of the fields
6. There is no information in the window that opens indicating on which attribute (field) you are working 

=> Proposed solution: adding the attribute label in the window title as shown here:

![image](https://user-images.githubusercontent.com/12602163/89697285-128b0a80-d94e-11ea-9ec1-b6655f7cc35b.png)

**Comment by SteeveEbener** [comment]
Tested under ve 0.13.0 and working. I am closing this ticket
