### ISSUE TITLE
Users can see lists they don't have access to

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#166]
**List the CGR version information**
- CGR version v0.7.0

**Description**
Private lists in organizations I don't belong to still appear.

**To Reproduce**
As a RA or RM I was going to manage data that I have access to. 
1. I went to the Master List Manager
2. I saw data for organizations I don’t below to

**Expected behavior**
I expected to only see data for which I was given permission

**Screenshots**
![Screenshot from 2020-04-16 16-25-17.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/ca35424b-6ef7-4f9e-8052-2655e3886e04)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser Chrome
 - Version n/a

**Comment by SteeveEbener** [comment]
I just tested this and the RA from organization B can't now see a private list created by organization A. This ticket can be closed
