### ISSUE TITLE
Error trying to accept a user invite 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#168]
**List the CGR version information**
- CGR version v0.7.0

**Describe the bug**
An unspecified error is thrown when trying to submit a new account form from an email invite link. I suspect this is because of a short validity period for the invite.

**To Reproduce**
As an SRA I was trying to invite another SRA to the CGR
1. Invite a new user
2. Wait for about 2 hours.
3. Open the link from the invite sent to the invited user. Be sure to logout of any existing sessions if this is being tested in a loclat development environment.
4. Fill out the form.
5. Submit
6. Unspecified error is thrown

**Expected behavior**
I expected the invite would stay valid and they could get started at least 1 month after invite.

**Screenshots**
![Screenshot from 2020-04-16 16-46-33.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/da9e7494-0242-44bc-ba1a-0f6708303faf)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
**Potential Causes:**
Single use invite link w/o completing the form and closing the window? 
- Perhaps clarify that links are single use and improve error handling before they fill out the form - -  “link no longer active, contact the admin” message...

**Comment by rrowlands** [comment]
This has nothing to do with expiration of invite links. It occurs when accepting an invite of a user who is not an SRA.
