### ISSUE TITLE
SRA Missing Home Page Options

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#171]
**List the CGR version information**
- CGR version v0.7.0

**Describe the bug**
App navigation options (icons) are missing in the home page that are available in the header dropdown. 

**To Reproduce**
1. Go to the home page as an SRA

**Expected behavior**
I expected that the hamburger options and the home page be the same.  That the SRA would have all the options.

**Screenshots**
![Screenshot from 2020-04-16 17-21-42.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/6542c6fc-4d17-4940-a4df-424ff2476a13)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Comment by justinlewis** [comment]
See duplicate ticket for more detail:  https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/248

**Comment by rrowlands** [comment]
I made these changes intentionally, with the rationale that while an SRA _can_ perform certain actions, there are some actions that an SRA should not be performing without very good reason (submitting a change request is a good example).

The icons on the home page for the SRA were curated as a suggestion of what the SRA _should_ be doing, with the hamburger menu being thought of like an override.

**Comment by SteeveEbener** [comment]
Issue #248 was not a full duplicate as it was indicating what should and what should not be accessible to a SRA. I am transferring these points here to support the implementation of the changes that remains to be implemented as the other issue has been closed:

Because the SRA is linked to the cross sectoral governance mechanism, he should:

- have access to the following modules without editing rights from the home page: lists, explorer (accessible from the burger menu though)

- NOT have access to the import, change request, scheduled jobs and tasks modules (also accessible from the burger)

**Comment by rrowlands** [comment]
OK I think I can see that you want the following added to the SRA homepage: lists, explorer. I think that you also want tasks removed from the SRA homepage.

Are you also saying that you want (change request, scheduled jobs and tasks modules) removed from the hamburger menu?

**Comment by SteeveEbener** [comment]
Yes, the  content in the burger menu and the "Icons" on the page should match.

Before making any changes, let's first make sure that we are all on the same page regarding the rights by role google spreadsheet as this will confirm the list of the modules that each role should be able to see and use

**Comment by SteeveEbener** [comment]
The changes in the burger menu and the home page have been implemented but the SRA still have editing right across all items (GeoObject types, hierarchies, lists,...) and all organizations in the CGR.

How do you want to address this? As part of this ticket or a new one?

**Comment by rrowlands** [comment]
If you would like additional changes to the SRA permissions please create a new ticket.

**Comment by SteeveEbener** [comment]
This was not an additional change but something included in this ticket, reason why I was asking. I will generate a new ticket then.
