### ISSUE TITLE
Missing Settings Button on Home Screen

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#172]
**List the CGR version information**
- CGR version v0.7.0

**Describe the bug**
Missing Settings Button on Home Screen

**To Reproduce**
As a RA I was wanting to work on adding users for my organizations.
1. Go to the home screen
2. The settings icon doesn't appear.

**Expected behavior**
I expected that similar to the SRA; there would be a settings button among the home screen options.

**Screenshots**
![Screenshot from 2020-04-16 19-16-01.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/c1fc9a2b-7a3d-4c19-aec3-5d093ef203d3)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Comment by CarlyNel** [comment]
I can confirm that this fix has been implemented and that the settings icon is now visible on the home screen when logged in as an RA.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/f5195366-c4ac-48bc-90d3-709f6956446e)

**Comment by SteeveEbener** [comment]
Yes except that it is not in the right place (order) as indicated in issue #105. Will be taken care from there I guess
