### ISSUE TITLE
Default locale labels on organization modal needs improvement

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#173]
As a SRA I was I just created a new organization
- There are messy “defaultLocale” headers. 
- The field name is shifted up off the form field.

I expected to see "[EN] English" or whatever languages was set AS the default locale, instead of showing "defaultLocale", and any other locales added would have language labels appropriately labeled with their UTF codes and names.

![Screenshot from 2020-04-16 19-23-58.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/1cd02658-e880-4f4d-ae95-cf83e1a8eec3)

**Comment by CarlyNel** [comment]
Hi Justin, I created a similar ticket so linking it [here](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/337).
