### ISSUE TITLE
Can't create a new GeoObject through the form on the Change Request page

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#176]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
Cant submit the form.

**To Reproduce**
1. Go to the change requests main page. 
2. Click on the 'submit' tab.
3. Select the type
4. Typed in a new province
5. Tried to hit submit and nothing happened.

**Expected behavior (clear and concise)**
To be able to submit.

**Screenshots**
![Screenshot from 2020-04-16 19-52-36.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/d97a25a0-b1fa-4020-9892-8ef3b82bdbb1)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by justinlewis** [comment]
Marking as invalid because creating objects through this form is not supported.

**Comment by SteeveEbener** [comment]
Do you mean that for the moment a RC can not "announce" the opening of a new health facility for example?

**Comment by justinlewis** [comment]
@SteeveEbener This is the same functionality as before. You can still create GeoObjects from the lists page.
