### ISSUE TITLE
Error message for improper role on organization incorrect

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#183]
The error message in the screenshot below is wrong. It should say "Super Registry Administrator (SRA)" rather than "Registry Administrator".

![Screenshot from 2020-04-16 21-44-53.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/42a92801-f955-4557-8e4f-a65fa4a968de)

**Comment by SteeveEbener** [comment]
Actually, the "+Add" button should not even be activated for the RA, RM and RC role
