### ISSUE TITLE
[geoobjecttype] RM cant publish exploratory versions

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#184]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
[geoobjecttype] RM cant publish exploratory versions

**To Reproduce**
1. Go to a list that the logged in user is a [geoobjecttype] RM for
2. Click on the 'exploratory' tab
3. Look for widget to publish version.

**Expected behavior (clear and concise)**
[geoobjecttype] RM should be able to publish exploratory lists.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by jsmethie** [comment]
I can not recreate the issue.  See the screenshot.  There is the Publish New Version button above the list of exploratory versions. ![Screenshot from 2020-05-26 11-22-06.png](https://images.zenhubusercontent.com/5dfa5d1390d23b3f03995016/81894a29-b5b0-46e4-aae9-9e04fc791317)

**Comment by justinlewis** [comment]
Closing because we can't reproduce
