### ISSUE TITLE
Label incorrect at top of create list modal

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#185]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
Label should say "Create List" at top of create list modal

![Screenshot from 2020-04-22 10-57-47.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/02e795e2-a05a-46f1-8ddd-aa499c0af188)

**Comment by SteeveEbener** [comment]
That indeed needed to be changed but the problem now is that it still says "Create list" when opening the metadata.

If the title of any given window is to remain the same independently from when we access it (create vs consult for example) we need to take this into account when choosing the labels.

If this is the case, then we should call this window "_GeoObject Type_ list Metadata" (for Example "Health facilities list Metadata")
