### ISSUE TITLE
Error message on Published lists page

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#189]
This error message is flashing repeatedly on screen. User: LaoPDR-MOH-HF-RM

![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/7eec1f02-dae9-450b-8c05-c9c65e8a5b68)

**Comment by justinlewis** [comment]
@dtreatman - I know why this message is flashing but I can't remember how the issue was created in the first place. If I remember right you published a list but I'm not sure what list and what data you used to build the list.

**Comment by dtreatman** [comment]
@justinlewis - I don't remember exactly what I did. Suggest closing this ticket and re-opening if it reoccurs.
