### ISSUE TITLE
Only shows fields for defaultLocale for custom attributes

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#191]
I added a new field "Long Name" and then tried to upload a spreadsheet as an RA, for an existing GeoObject "Health Facility". The upload field mapping modal only showed "Long Name (English)" and did not show the Lao version. 

![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/0c17baf8-495f-4388-9930-cd95515bddb1)

Same issue in master list:
![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/87d1399e-25b2-4e23-ae29-21fc3055033a)

Here is the custom attribute added:
![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/fd8e24c7-9e71-49ab-83e7-96057674ba23)

**Comment by jsmethie** [comment]
I think there is a misconception going on here. You are only creating a single attribute, but it has a different label depending if the user's browser locale is set to Laos LA vs anything else.  That is why you only see the single attribute on the importer and master list pages.  The system does not make duplicates attributes per locale.
