### ISSUE TITLE
System version number not incrementing with releases

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#192]
Following the 0.7.1 release of fixes on Apr 23, the version number in the system remained the same, at 0.7.0

![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/248a26e3-12ee-4f5c-bdcc-b2f5943360e0)

**Comment by justinlewis** [comment]
This was a result of our release process having an issue when releasing minor versions (e.g. x.x.[number]). Going forward every release will have a versioned release number for major and minor versions.

**Comment by CarlyNel** [comment]
I can confirm that the minor release versions are now visible:

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/86b0babf-207b-42b2-8e52-bc54f553f6c5)
