### ISSUE TITLE
Changes to GeoObject Type label not immediately reflected after saving

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#194]
**List the CGR version information**
- CGR version: 0.7.0 (DEMO)

**Describe the bug (clear and concise)**
When trying to change the lower-case "c" for "country" to uppercase, after hitting submit, no changes are immediately visible. User must exit the module and return to see the changes.

**To Reproduce**
1. Go to Hierarchy Manager
2. Try to update the label of a GeoObject Type and press submit - nothing happens
3. Exit the module and return, the change is then displayed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/cd79aa56-9896-4358-abd0-787626667df3)

![image.png](https://images.zenhubusercontent.com/5dfcfd403da7a2fba63fee9a/c49539a3-ca86-4ac0-a456-730cfabc3cc4)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by CarlyNel** [comment]
@justinlewis I've just recreated Derek's steps above to test this fix but am unfortunately experiencing the same issue. Steps I took:

1. Logged into staging as an SRA
2. Navigated to Hierarchy Manager
3. Edited the first entry and changed the 'c' in College to lower case
4. Submitted my change
-> The hierarchy manager screen still displays the Capital C. If I navigate back to the home page and then come back to the hierarchy manager, only then is my change visible.

NOTE: The bizarre part is that when I repeated the above and changed the second label to begin with a lower case and then submitted, the change was immediately visible.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/369a3692-0236-41bc-b4ee-293abff1e4c3)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/c1d8d267-204c-4cfb-afbe-4def6a9dc09c)

**Comment by CarlyNel** [comment]
Hi @justinlewis. I've just retested this and changes that are made to a GeoObjectType's name still do not reflect after the change is submitted. A change only reflects after the page is refreshed. See screenshots below. Could this have something to do with my cache?

Change already submitted but not reflecting:

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/00fa47ec-932b-48e0-b95b-0f7cb5a8a3d3)


Change reflects after I refresh the page:

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/94c5d6ea-23b5-455f-823b-9b15b3fec3f2)

**Comment by justinlewis** [comment]
Thiis ticket is invalid because it reference the old UI but I just checked against the new hierarchy manager and the data updates.
