### ISSUE TITLE
Creating new version of a GeoObject name as contributor generates change request with assign parents action

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#198]
**List the CGR version information**
- CGR version: 0.7.1

**Describe the bug (clear and concise)**
When you submit a change request for a GO, e.g., create a new version in time for a GO name (as shown in screenshot), it also generates a change request to assign the parents of that GO. I recall you saying this needs to happen, technically, but just wanted to confirm the explanation for this so we can explain it to users since it is not intuitive to see two change requests result from a single request submitted. Also, I have not tested what would happen if the RM rejected the "Set parents" part of the request and would like to do so when next possible (pending Steeve's setup of Tolkeinland on STG).

**To Reproduce**
1. Go to a list as a contributor
2. Click on edit for a GeoObject
3. add a new version of the GeoObject label.
4. submit as a change request
5. login as an admin who can manage that change request
6. click on the new change request and see the assign parent action

**Expected behavior (clear and concise)**
Changing a GeoObject label should not require a new parent assignment.

**Screenshots**
![image (15).png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/a147c6e5-f156-43ba-b5c3-60a0732e3c5f)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by dtreatman** [comment]
Note: If the RC submits a change request through the Change Request module, this issue does not happen.

**Comment by SteeveEbener** [comment]
This is maybe one more example that requires for us to ensure that what happens when a RC clicks on the "edit pen" in a list (misleading icon by the way) is that he is redirected to the change request module (main window pre-filled with the information of the GeoObject in question) instead of taken through windows that look differently and seem to generate a different result.

That would also help ensure that the RC understand he is submitting a change request and not directly editing in the graph.

**Comment by SteeveEbener** [comment]
How has this ticket been resolved or just closed? I am asking because the original issue relates to ticket #349.

**Comment by justinlewis** [comment]
@steeveebener The new parent assignment is now not created when generating a change request for a label change. ![Screenshot from 2020-08-27 17-53-29.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/1e4fa07d-3946-4f4f-818f-cf98095d9c51)

Ticket #349 was not looked at when working on this ticket. It will be handled separately.
