### ISSUE TITLE
RA>System settings>User accounts> Manage accounts

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#201]
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RA can see all the users that have been created in the CGR and, even if it can’t submit changes he can edit their information even if not part of its own organization. 

**To Reproduce**
As a RA:
1. Go to System settings>User accounts 
2. Click on Manage accounts
3. See error: list of all the users 

**Expected behavior (clear and concise)**
The RA should only: 

1. See the SRA and the other users attached to his organization in the list; 
2. See and not edit the information for these users if not part of its organization
3. See and edit the information for the users that are part of its organization

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
The solution we are implementing covers #3 above:
- See and edit the information for the users that are part of its organization

We can not support #1 and #2 currently.

**Comment by SteeveEbener** [comment]
This ticket actually need to be adjusted as follow in view of the content of the rights by role google spreadsheet:

The RA should:

1. View but not edit the SRA information
2. View and be able to create/edit/delete RM and RC accounts for its own organization

If I understand Justin's last message correctly, point 2 here will be implemented but point 1 is not possible at this stage.

What about then having the SRA information as a new section under setting (before "Organizations")? Would that be feasible?

**Comment by justinlewis** [comment]
Let me look into that. I like that idea because it gives a place to list information an RA might need to know about who is managing & responsible for parts of the system. I created a ticket so we can take that into another thread.

https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/307

**Comment by SteeveEbener** [comment]
Great. Thanks Justin

**Comment by SteeveEbener** [comment]
Point 2 in my message dated June 18th has been implemented and point 1 is now addressed through ticket #307.

=> I am closing this ticket
