### ISSUE TITLE
RA>System settings>Branding: RA can change branding, localization and email information as well as access the add a new organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#202]
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RA can change the branding, localization and email information while it applies to all the organization and not only for his own organization + can also add a new organization

**To Reproduce**
As a RA:
1. Go to System settings
3. See error: the RA can modify the Branding, Localisation or Email as well as access the add a new organization

**Expected behavior (clear and concise)**
If the branding change is for the moment to be applied to the entire CGR (all organizations) then we should only allow the SRA to adjust it at this stage.

Localization and add an organization should themselves definitively only be accessible to the SRA. 

I am not clear regarding the email information. If this is CGR wide, then this should also only be access to the SRA

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
For all users who are NOT SRA I removed:
1. organization admin controls (buttons for edit and delete)
2. branding section
3. localization section
4. email section

**Comment by SteeveEbener** [comment]
Checked and implemented. I am closing this issue
