### ISSUE TITLE
Possibility to add an attribute to a GeoObject type created by another organization or to delete the GeoObject type in question (same applies to hierarchies)

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#206]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
It is currently possible for the RA of a given organization to:

- add an attribute to a GeoObject type created by another organization and for the field to be visible to all the organizations in the CGR

- delete a GeoObject type created by another organization

**To Reproduce**
Log in as organization A
1. Go to the "Hierarchy Manager" (labels which should have been changed  => we need to re-open issue #105)
2. Create a GeoObject type
3. Log out

Log in as organization B
1. Go to the Hierarchy Manager" 
2. Observe that both the "delete" and "edit" symbols are accessible for the GeoObject type created by organization A
3. Add an attribute (you can then log out as B and log in again as A to see that the attribute in question is visible and editable from there) (first error)
4. Change the name created by the other organization and save it (see error: the name has changed
4. Once point 3 has been checked you can delete the GeoObject type created by A while this should not be the case (third error)

**Expected behavior (clear and concise)**
1. Only the organization that has created a specific GeoObject type can edit its attributes (caveats: we have been discussing the possibility for an organization A to add CGR-specific attributes to a GeoObject type created by another organization B but, in this case, such attributes should only be visible and manageable by organization A)
2. Only the organization that has created a specific GeoObject type can delete such GeoObject type
3. Any organization should be able to see the GeoObject types created by the other organizations and the list and have access to its metadata (maybe that the icon should not be a pen in this case but something else (an eye?) and the delete for these GeoObject types should not be visible) 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
The same actually applies to hierarchies as well. I was able to modify the information (without saving it) and to delete a hierarchy created by another organization

**Comment by SteeveEbener** [comment]
...and I just discovered that Organization B can actually upload a spreadsheet against a GeoObject type created by Organization A

**Comment by SteeveEbener** [comment]
The RA from organization A now can't delete or edit GeoObject types and hierarchies from other organization but he also can't see the metadata associated to both of these items which is what is captured under point 3 of the ticket:

3. Any organization should be able to see the GeoObject types created by the other organizations and the list and have access to its metadata (maybe that the icon should not be a pen in this case but something else (an eye?) and the delete for these GeoObject types should not be visible)

This issue is linked to ticket #275 

This ticket should remain open and included in sprint 9 together with ticket #275

**Comment by rrowlands** [comment]
Do we want to allow them to view the metadata for the attributes defined on the GeoObjectType? Or simply the list of attributes (only displaying their labels)?

**Comment by SteeveEbener** [comment]
Good question. Ideally, they should also be able to consult the metadata for the attributes but of course not edit it.

If this is possible, it would be good if this could be done from the list of attributes, meaning without having to enter the attribute manager. Maybe through some kind of "view" button next to each attribute in the list?
 
This would not only be useful to all the users, including those from the organization having the curation mandate over the GeoObject type in question but also to remove the "manage attribute" button for the users that only have the right to look at the GeoObject type metadata.

**Comment by rrowlands** [comment]
Created a new ticket for for your suggestion #327.
