### ISSUE TITLE
Organization appearing in a dropdown field when creating a new GeoObject Type or Hierarchy

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#207]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
In the GeoObjects and Hierarchies module,  the organization to which the GeoObject or Hierarchy he is attached to is appearing in a dropdown field instead of being directly attribute to the organization to which the RA or RM is attached to

**To Reproduce**
Log in as a RA or a RM
1. Go to the GeoObjects and Hierarchies module
2. Click on the "Create" button either to add a new GeoObject type or create a new hierarchy
3. See error: the organization is appearing in a dropdown field

**Expected behavior (clear and concise)**
The organization is appearing in a field that is not giving the impression that an option needs to be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/80853880-91451d00-8c66-11ea-8823-b5e75069fff8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Just tested and it is still the same, the organization is still appearing in a dropdown instead of the field being automatically filled

![image](https://user-images.githubusercontent.com/12602163/89120757-5cf22e80-d4eb-11ea-9294-56a1e0e49967.png)

**Comment by rrowlands** [comment]
This code has not yet been deployed and thus is not yet testable.

**Comment by SteeveEbener** [comment]
The dropdown is gone but it's the organization "code" and not its name which is appearing as per the original ticket=> can we please adjust this as not all the implementation will use "codes" matching the organization acronym and if they do not all the users would know what these acronyms stand for.

**Comment by justinlewis** [comment]
Moved from sprint 11 to sprint 12 so we can set the value to the label rather than the code as Steeve is asking in the last comment.

**Comment by rrowlands** [comment]
This issue did not pass my testing and as such cannot be released as part of 0.12.0.

**Comment by rrowlands** [comment]
The fix for this issue has been deployed to the staging server. It is passing my tests.

**Comment by SteeveEbener** [comment]
The dropdown is gone but it's the organization "code" and not its name which is appearing as per the original ticket=> can we please adjust this as not all the implementation will use "codes" matching the organization acronym and if they do not all the users would know what these acronyms stand for. Thanks

**Comment by SteeveEbener** [comment]
Tested on staging and it is working. I am closing this ticket
