### ISSUE TITLE
RM not able to import data on which it has the role while the RA can

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#210]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
A user having the RM role on a given GeoObject type can't import data for that object

**To Reproduce**
As a RA:
1. Create a RM account and attach it to a specific GeoObject type
2. Log out as the RA

As a RM
1. Log in
2. Go to the import module 
3. Try to import the list against the GeoObject type in question
4. See the message error (screenshot below) => the data does not import

**Expected behavior (clear and concise)**
The RM who has the right over the GeoObject type can import data against it

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/80897444-3c1f0f00-8d2b-11ea-849f-97c394112447.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
It looks like there is no clear error being reported?  Instead just a loading spinner that never closes?

**Comment by SteeveEbener** [comment]
Yes, indeed

**Comment by SteeveEbener** [comment]
I just tested this ticket and the RM can't even see the list of GeoObject types on which he has the role in the dropdown of the import window (the dropdown is empty

![image](https://user-images.githubusercontent.com/12602163/85087867-3e70f600-b211-11ea-884e-6bc387f74db6.png)

**Comment by jsmethie** [comment]
@SteeveEbener I cannot reproduce this error locally.  Are you testing this on the staging server? If so can you tell me what user you are testing with and what hierarchy you are trying to import against?  Thanks.

**Comment by SteeveEbener** [comment]
@jsmethie : Yes. I just tried again and I am getting the same blank dropdown.

This problem occurs before specifying any hierarchy as this is the first field in window that appears after you have selected the "import from my computer" option.

When you do the same step as the RA you get the list of oganization specific GeoObject type as per the following screenshot:
![image](https://user-images.githubusercontent.com/12602163/85803059-ef7b1180-b778-11ea-8bb7-746f6fb93a00.png)

The RM should get the same

**Comment by SteeveEbener** [comment]
I don;t know if this can help but the same problem happens with the RC when trying to submit a change request for GeoObject types over he has the RC role => the dropdown for the GeoObject type is also empty (tried with the MOH RM)

**Comment by SteeveEbener** [comment]
This is now working. I am closing this ticket
