### ISSUE TITLE
Latitude and longitude fields appearing when uploading a spreadsheet against a polygon or multipolygon format GoeObject type

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#211]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
Latitude and longitude fields appearing when uploading a spreadsheet against a polygon or multipolygon format GoeObject type

**To Reproduce**
As a RA (and I would guess RM)
1. Create  a polygon or multipolygon format GeoObject type
2. Go to the import module
3. Enter the GeoObject type, import startegy (any), start date and choose a file
4. Click the submit button
4. See error: the next page contains the possibility to indicate  a field from the spreadsheet containing latitudes and longitudes (see screenshot below) 

**Expected behavior (clear and concise)**
The longitude and latitude fields are not appearing when you are uploading a spreadsheet for a GeoObject type presenting the polygon or multipolygon format

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/80897802-5bb83680-8d2f-11ea-9a74-438e385b84eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
We need to check if the code to only show those fields if the GeoObjectType geometry is set to point. It looks like this is not working correctly.

**Comment by SteeveEbener** [comment]
Tested and this is working. I am closing this ticket
