### ISSUE TITLE
Scheduled jobs initiated by organization A visible to Organization B

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#215]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The scheduled jobs initiated by organization A are visible to Organization B

**To Reproduce**
As the RA/RM of organization A
1. Perform some tasks that will result as a job being captured in the "scheduled jobs" window (import data for example)
2. Log out

As RA/RM of organization B
1. Log in
2. go to the "scheduled job" window
3. See error: jobs initiated by organization A are listed 

**Expected behavior (clear and concise)**
Scheduled jobs are organization, and maybe even job specific + we should discuss which roles can access to the scheduled jobs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by rrowlands** [comment]
Is this a duplicate of #412 and #382 ?

**Comment by SteeveEbener** [comment]
Indeed. Good catch.

I am closing this one as the other two tickets are more detailed
