### ISSUE TITLE
Term type attribute: Can't use the same "code" as already used for another GeoObject type  

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#217]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
When using a term type attribute, I can't re-use a class (code) that has already been used for another GeoObject type while the information being captured is the same (e.g.: geographic coordinate accuracy level, health facility type,...)

When I do that I get the following error message (see screenshot below): An instance of [Classifier] already exists with [net.geoprism.registry.ST1] as the value for Key Name - please choose a different value.

**To Reproduce**
As a RA/RM
1. Go to the GeoObjects and Hierarchies module  
2.  Click the edit pen for a first GeoObject type
3. Add a term type attribute to this GeoObject type
4. Create a set of classes using for example 1, 2, 3, 4 for the code and any given label
5. Submit the change
6. Click the edit pen for another GeoObject type
7. Add a term type attribute to this GeoObject type
8. Use the same codes than those used under step 4 for the first GeoObject type
9. See the error message (Sceenshot)

**Expected behavior (clear and concise)**
I foresee two options with a preference for the first one:
1. We can access classifications tables created for other GeoObject Types (the way described in the original guidance document
2. The classification is GeoObject type specific but, in this case, we take the risk of having differences between classification tables due to typos for example 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81022153-7c9f9980-8e9f-11ea-9532-34ffd1f8a525.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**
See section 5.2.4 in the CGR guidance document for more details about classification tables

**Comment by SteeveEbener** [comment]
Doing some more test I just found out that the issue reported here above does also appear when trying to use the same class (code) for a GeoObject type handled by another organization

**Comment by SteeveEbener** [comment]
I have created the following schema to illustrate the expected process: https://docs.google.com/presentation/d/1BMDPKqrnrM5g6MpkqdEtksU_2lCcbucC-ilOdTpt7oU/edit?usp=sharing

**Comment by SteeveEbener** [comment]
Can I please know what has been implemented in other to test the change?

**Comment by SteeveEbener** [comment]
Based on the discussion I had with Nate and Justin on August 4 (Manial time) , the second option I have proposed in the original ticket (possibility to use the same code for two different GeoObject types) should have been implemented .

I just tested this and it is not working. I am getting the following message when doing this: "Cannot add an attribute named [Test_Type] to class [Health Centre (MOH)] because that class already defines an attribute with that name."

=> This ticket is not completed

**Comment by jsmethie** [comment]
I am glad you are testing it but this ticket as been marked for sprint 0.11.0 which we haven't released yet.

**Comment by justinlewis** [comment]
Option #2 was implemented with ticket #384 

Option #1 was not done as part of this. This functionality will need to be considered in the future.

**Comment by SteeveEbener** [comment]
Thanks for the clarification. I guess you mean that option 2 has been implement at the same time as #384 and not that option 2 has been addressed through #384. To be continued once version 0.11.0 has been released :) Thanks

**Comment by SteeveEbener** [comment]
Tested and working. I am closing this ticket.
