### ISSUE TITLE
Button to create a GeoObject type or a Hierachy and delete them accessible to the RM role + edit pen confusing

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#219]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RM has access to the "Create" button and delete icon for GeoObject types and Hierarchies while only the RA has the right to do these operations.

The Edit pen is also confusing as the RM does not have the right to edit => we should change the icon to something looking more like a metadata.

**To Reproduce**
As a RM
1. Go to the GeoObjects and Hierarchies module 
2. See error: create button and the delete icon for both the GeoObject Types and Hierarchies are there

**Expected behavior (clear and concise)**
1. These buttons should be removed for the RM role as, per the user role management epic, only the RA should be authorized to create and delete a GeoObject type or a Hierarchy
2. The edit pen icon should be replaced by a metadata look

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81027017-ad3aff80-8eae-11ea-8ed5-f896da349239.png)

**Desktop (please complete the following information):**
 - OS: WIindows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**
User role management epic google doc: https://docs.google.com/document/d/19LcXKsgGTvDd6lqPYrEVY4d1FtTwGcGSl7n0LBrN3gs/edit?usp=sharing

**Comment by justinlewis** [comment]
#1 in expected behavior has been addressed. 

#2 in expected behavior should be pulled out into a separate ticket. The pen is used as a standard symbol to modify elements of the app. To change the pen icon here means we need to determine an appropriate icon, create it if it doesn't exist, and ensure that the change doesn't break consistency. Because of all this and that these two requests likely have different priority levels we need a separate ticket.

**Comment by SteeveEbener** [comment]
I have capture the second issue (edit pen icon) in issue #275

**Comment by SteeveEbener** [comment]
The create and delete button have been removed but the RM can't access the metadata as this should be the case as per the rights by role google spreadsheet.

**Comment by SteeveEbener** [comment]
The RM can now access the metadata but only the GeoObject types and hierarchies created by his own organization are appearing in the module while all of them should be visible as per the rights by role  google spreadsheet.

**Comment by CarlyNel** [comment]
Hi @justinlewis, could you please provide an update on the above?

**Comment by justinlewis** [comment]
I created a new ticket to address @steevebener's common on June 17: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/351
