### ISSUE TITLE
Spreadsheet import: Can't link a GeoObject type to its parents which are under the mandate of another organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#220]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
I have not been able to import the parents of the Universities as per the hierarchy reported in the first screenshot below. 

The error message I got at the import is as follow: You do not have permissions to view a GeoObject of type [Shire (MOHA)] in the organization [Ministry of Home Affairs].

This actually applies to all the administrative divisions part of the hierarchy in question when trying to resolve the problems.

**To Reproduce**
As the RA of the Ministry of Home Affairs  
1. Create the administrative divisions GeoObject types (Region, Province, County, Shire)
2. Create the administrative divisions hierarchy
3 Import the spreadsheets containing the lists for the administrative divisions
4. Create master list for each of the administrative divisions
5. Log out

As the RA of the Ministry of Education
1. Create the University GeoObject type
2. Create the hierarchy as reported in the screenshot below
3. Import the spreadsheet containing the master list of Universities matching the parents as per the hierarchy
4. Go to the scheduled jobs
5. Click on resolve problems
6. See the error message reported here above and in the second screenshot below

**Expected behavior (clear and concise)**
Any given organization can implement hierarchies containing GeoObject types under the mandate of another organization as long as the list for the GeoObject types in question is public

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81037774-78db3980-8ed6-11ea-8c7f-5707398ce9ec.png)

![image](https://user-images.githubusercontent.com/12602163/81043011-fe191b00-8ee3-11ea-82ed-4058cb527ebb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**
We need to look into the question of the public vs private status.

For the moment, such status is only attached to a list (and maybe a geospatial data?) but we might have to actually attach it to GeoObject type to avoid for an organization to use a GeoObject type in one of its hierarchy while the content of the list is not public.

We will also certainly have to add something like a "restricted" status in order to give access to the given GeoObject type to a given number of organizations.

**Comment by rrowlands** [comment]
Related ticket: #266.

**Comment by justinlewis** [comment]
The implementation of this ticket will not include addressing concerns around this section in the description:

> Additional context (if any)
We need to look into the question of the public vs private status.

For the moment, such status is only attached to a list (and maybe a geospatial data?) but we might have to actually attach it to GeoObject type to avoid for an organization to use a GeoObject type in one of its hierarchy while the content of the list is not public.

We will also certainly have to add something like a "restricted" status in order to give access to the given GeoObject type to a given number of organizations.


This topic is has a lot of considerations and is being discussed as a larger conversation.

**Comment by SteeveEbener** [comment]
I just tried, as the RA of the MOE, to re-import the Universities master list (spreadsheet) into the staging instance.

No error message this time and the import was completed but only the information for the Shire level (code and name) got imported in the graph, not the code and name for the county, province and region.

This might be linked to the discussion I had with Nate on Wednesday regarding the fact that, for the moment, the MOE does not inherit the complete MOHA hierarchy on top of the Shire level when creating the hierarchy as presented in the original ticket.

**Comment by rrowlands** [comment]
I'm not exactly sure of the priority of the issue you just described, and it doesn't seem to be in the original scope of this ticket. If you would like this issue to be addressed, please create a new ticket.
