### ISSUE TITLE
Can't import a shape file for a polygon format GeoObject type 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#221]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
I get the following error message when trying to upload a shape file for a GeoObject type which does already have a list in the graph: The provided geometry is invalid. Check to ensure that the geometry is well formed and/or that it is in 4326 projection.

I checked the shape file and the projection system is correct

**To Reproduce**
As a RA (RM import not working for the moment, see issue #210 )
1. Create the GeoObject type
2. Create the hierarchy
3. Import the content of the list in the graph
4. try to import the shape file corresponding to the list which is in the graph 
3. See error message mentioned here above

**Expected behavior (clear and concise)**
As a RA, or RM, I can import a shape file corresponding to the content of the list already in the graph.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
This was caused by the geometry of the Shapefile having invalid geometries. Specifically the bad validity was that the geometry had a self intersecting ring. To fix this you can run a buffer tool in a GIS progroam (Qgis, PostGIS, etc...) with a buffer distance set to 0.

**Comment by SteeveEbener** [comment]
For reference, here is the process to follow in QGIS to address the problem countered with the shapefiles in question: https://gis.stackexchange.com/questions/265661/fixing-polygon-self-intersection-in-qgis
