### ISSUE TITLE
Can't cancel a scheduled job linked to a spreadsheet import  that needs to be resolved (no button) 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#223]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
As A RA/RM I can't delete a scheduled job linked to spreadsheet import the same way I can do that when importing a shapefile 

**To Reproduce**
As a RM/RA
1. Go to the import module 
2. Import a spreadsheet that will need resolution (wrong parent code for example)
3. Import a shapefile that will need resolution (invalid geometry for example)
3. Go to the sheduled job page and see the error (screenshot below): there is a cancel import button for the shapefile import but not for the spreadsheet one 

**Expected behavior (clear and concise)**
There is a cancel button attached to a spreadsheet import that needs to be resolved

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81366942-72d79980-911e-11ea-889e-f24c260bf6dc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
I actually just found out that, in some cases uploading from a shapefile (uploading a shape file against  a GeoObjct type for which there was already information in the graph) does not make the "Cancel import" button appear as shown here when a resolution is needed:

![image](https://user-images.githubusercontent.com/12602163/81486924-18a81700-928b-11ea-9712-0ed2d5c8986b.png)

**Comment by rrowlands** [comment]
This was happening because an import cannot be "canceled" once it has passed validation and reached the data import stage. We have added a button for this scenario titled "Ignore all errors" which will achieve a similar effect.

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/90f525fa-c97e-4afe-a9bd-d3b10a0d8931)

I have also updated the confirmation modal to make this more clear

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/d743fd55-dd06-408a-b41c-df179195c9de)

**Comment by SteeveEbener** [comment]
Thanks for the clarification. 

If I understand correctly, that means by clicking on the "complete import" button everything not presenting an issue that needs to be resolved will be imported, right?

What if you finally realize through the list to be fixed that you actually screw up (selected the wrong file for example) and want to cancel the whole import?

**Comment by SteeveEbener** [comment]
I need an answer to the questions listed in my last message to not only make sure that the CGR does what I think it should do but also test it. Thanks

**Comment by CarlyNel** [comment]
@justinlewis Could you please get back to Steeve on his above questions so that he can move forward with testing this ticket? Thanks.

**Comment by justinlewis** [comment]
@SteeveEbener Yes to your first question. By the time you hit "complete import" all the data that could be imported was already imported. Regarding the second question the ability to roll back an entire import is not supported at this phase.

**Comment by SteeveEbener** [comment]
Thanks for the clarification. Why is the resolution of issues then not taking place before the complete import?





1. The user experience  might need to be improved because when seeing "Database import" in red in the progress bar and that something need to be resolved my thinking was that the import did not take place as issues needs to be resolved

**Comment by justinlewis** [comment]
@steeveebener - Because these are validation issues that the database is inforcing so we would have to replicate database functionality in the app layer to detect these earlier. This could be done in the future.

**Comment by SteeveEbener** [comment]
@justinlewis Thanks for the clarification Justin. Let's then at least improve the user experience by including the message and changing the colors for the progress bar. Proposition:

- Fully passed: green
- Partially passed: orange (case of the partial import)
- Not passed at all: red

**Comment by SteeveEbener** [comment]
Message and change in coloring not yet implemented

**Comment by justinlewis** [comment]
@steeveebener We need to take these UI/UX improvements to a new ticket because they are not about the presence or absence of the cancel button. This is a good suggestion but it's a little more effort than it may seem to change that and diverges from the functionality that was released that specifically addresses the ability to "cancel" the job (as opposed to making the status more clear).

**Comment by SteeveEbener** [comment]
Ok. Make sense => I have created ticket #414 for that and I am therefore closing this one. Thanks
