### ISSUE TITLE
Import module> Shapefile import:  New shape file imported in the graph only if the GeoObject unique ID and name matches but no error message

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#224]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The new shape file I created to update the existing one does not get imported in the graph if both the unique ID (Code) and the name (display label) are not matching the information already in the graph.

The import does nevertheless go through
 
**To Reproduce**
As a RA/RM:
1. Include a typo in the name for one of the GeoObject in the new shape file
2. Zip the new shape file
3. Go to the import module
4. Go to the Shapefile import section
5. Import the shape file containing the typo (using the update only option for the import strategy)
6. Go to the schedule job to observe that the process went through
7. Go to the list manager
8. Open the list for the GeoObject type in question
9. Click the edit button for the GeoObject that you have modified
10. Open the geometry window
11. See error: the new geometry has not been imported

**Expected behavior (clear and concise)**
The shape file should be updated in the graph despite the typo in the name if the unique ID (Code)  is correct.

=> Question though:  while the shape file import does not change the information included in the list but only adjust the geometry (which is good), I am wondering if we should not include an additional field under the import strategy to capture two options?:
 1. match based only on the code
 2. match based on the code and label

If yes, the attempt of import presented here above would have resulted in the import of the new shape file when using option 1 but no import when using option 2

The answer to this question will depend on which information is being included in the attribute table of the shape file exported from the graph: the one visible in the list or the one included in the attribute table of the shape file that has been imported. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**
- Issue linked to the geospatial data manager module

**Comment by jsmethie** [comment]
I cannot recreate this problem. Can you re-test it or give me more information? This could also be an issue with the shapefiles.  Can you send me the original shapefile as well as the modified one?

**Comment by SteeveEbener** [comment]
I just tried again on staging (ve 0.12.2) logged in as the Moha RA and with the shapefile you will find in this drobox folder (I also included the one without the change): https://www.dropbox.com/sh/4arjclia2bmzltl/AACwGxQP_Cf5czd-1PQWX6w5a?dl=0

This is Province level data and the change I have included in the "error" file is the name of the Andustar Province passing to Andustarala on 2007-04-20.

The import of the "error" shape file went through and the change appears in the list from 2007-04-20 as per the first screenshot below but there is no geometry in the graph (click on the edit pen button and then open the geometry tab => empty as per the second screenshot below)

![image](https://user-images.githubusercontent.com/12602163/102425421-3b33b700-4048-11eb-887d-7644cca014e9.png)

![image](https://user-images.githubusercontent.com/12602163/102425523-77ffae00-4048-11eb-9c52-1cdd41fc7b8f.png)

**Comment by jsmethie** [comment]
When I try to open the IMPORT_ERRORS.zip in QGIS it gives the following error:
"Layer is not valid: The layer DSME/IMPORT/IMPORT_ERRORS.zip/COR_TOLKIEN_PRO_2007_2018_ERROR.shp is not a valid layer and can not be added to the map. Reason:"

Unfortunately it doesn't give a reason why the layer is not valid, but my guess is one of the geometries in the layer is invalid.

**Comment by SteeveEbener** [comment]
For wathever reason the files got corrupted once zipped => I replaced the zip file and tested its content before importing it again.

This time the import worked as expected for both the name in the list and in the spatial data => anyway this could be identified during the import and the user informed about it?

**Comment by justinlewis** [comment]
@steeveebener It doesn't seem like we have a good way to detect this issue right now. We use GeoTools to handle the shapefiles which implements the simple features specification but has very little validation. The comment by jsmethie above suggests that Qgis also doesn't have a great way to handle this since it doesn't give a reason.

**Comment by justinlewis** [comment]
@steeveebener The issue is that our current tools aren't able to detect an issue. Qgis has additional functionality to detect that there is an issue (although they don't report the reason). To address this issue we'll need to do further investigation to determine what a solution might be.

**Comment by SteeveEbener** [comment]
This did not happen since the last message here => closing this ticket
