### ISSUE TITLE
Change in attribute label not appearing after submitting the change unless you refresh the browser

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#228]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The change I made in the attribute label (DefaultLocale) appears neither in the "Manage attributes" nor "Manage Geo Object type" window unless I refresh the page in the browser

**To Reproduce**
As a RA:
1. Go to the GeoObect types and hierarchies module
2. Click on the edit pen button of a GeoObject type on which you have the mandate
3. Click on the Manage attributes button
4. Click on the edit pen for one of the attribute
5. Change the label (DefaultLocale) for this attribute
6. Click Submit
7. See error 1: the label is not changed in the "Manage attributes" window
8. Click the Back button
9. See error 2: the label is not changed in the "Manage Geo Object Type" window
10. Click the submit button
11. Refresh the browser
12. Go back to the "Manage Geo Object Type" window and observe that the change is now visible for that attribute

**Expected behavior (clear and concise)**
The change in label is appearing as soon as you hit the back button on the "Edit attribute" window

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
I think the ticket description doesn't fit the roles matrix. The RM shouldn't be able to modify attributes in a GeoObjectType. @steevebener - can you edit the description so it's only the RA?

**Comment by SteeveEbener** [comment]
Good catch! I modified the description

**Comment by SteeveEbener** [comment]
Tested and implemented. I am closing this ticket

**Comment by SteeveEbener** [comment]
Tested and implemented. I am closing this ticket
