### ISSUE TITLE
When creating a new account, the RA from organization A can link a user to a RM, RC or AP role attached to a GeoObject type under the curation mandate of organization B

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#230]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The list of GeoObject types under the curation mandate of organization B, together with the role associated to them, is appearing when organization A creates a new user and organization A can attribute these role to the user it is creating

**To Reproduce**
As a RA of organization A :
1. Click to setting in the burger menu
2. Under "User Accounts", click the "Manage Accounts" button
3. Click the "+" to add a new user account
4. Scroll down the "Account" page to see the error: GeoObject types and role associated to other organizations are appearing

**Expected behavior (clear and concise)**
The RA can only create RC, RM and AP roles for GeoObject types under the mandate of its own organization

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81515875-955cf300-9368-11ea-9703-e34748e87399.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**
 - linked to issue #201 and #218

**Comment by justinlewis** [comment]
With these changes an RA will only have options to assign a new user to roles inside the organization they are an RA for.

**Comment by SteeveEbener** [comment]
Checked and implemented. I am closing this issue
