### ISSUE TITLE
Explore location pin enabled for a GeoObject without geographic coordinates

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#231]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The pin button is enabled for a GeoObject not presenting any geographic coordinates

**To Reproduce**
As a RA, RM or RC:
1. Open a list for which there is at least 1 GeoObjects without geographic coordinates (point format GeoObject type) 
3. See error: the explore location pin is enabled and clicking on it open a separated tab in the broswer

**Expected behavior (clear and concise)**
The explore location pin is only enabled for point type format when geographic coordinates are available 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81518519-e7097b80-9370-11ea-937f-215e4aade408.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
Marked as needs prioritization because this functionality may be impacted by the design of the upcoming location manager.

**Comment by vrajasekaran18** [comment]
@justinlewis is this valid anymore given the location pin is not something a user can click from a list?

**Comment by SteeveEbener** [comment]
@vrajasekaran18 . This is indeed not valid anymore. I am closing this ticket
