### ISSUE TITLE
RC can't access the exploratory section for GeoObject types over which he has the RC role

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#232]
**List the CGR version information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
A RC can't access the exploratory section in the lists module for GeoObject types over which he has the RC role 

**To Reproduce**
As a RC: 
1. Go to the lists module
2. Among the lists under the mandate of the organization to which the RC is attached, click the view button for a GeoObject type over which the RC has the RC role
3. See error: the RC don't have access to exploratory section

**Expected behavior (clear and concise)**
The RC can access the exploratory section as well as extract and consult exploratory instances of the lists for the GeoObject type on which he has the RC role

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/87847414-a434c880-c90a-11ea-9a7f-d88b1b3540f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
I just checked this in the demo instance (version 0.10.0) and the exploratory section is still not accessible to the RC for the GeoObject on which he has the RC role.

**Comment by jsmethie** [comment]
I am glad you are testing it but this ticket as been marked for sprint 0.11.0 which we haven't released yet.

**Comment by SteeveEbener** [comment]
The RC can now access the exploratory section but still can't generate an exploratory instance of the list on which he has the curation mandate

**Comment by SteeveEbener** [comment]
The RC can access the section but still can't extract and consult exploratory instances of the lists for the GeoObject type on which he has the RC role

**Comment by SteeveEbener** [comment]
Tested this again on ve 0.12.2 in staging and the situation remains the same as report on Nov 20, 2020

**Comment by SteeveEbener** [comment]
Tested under ve 0.13.0 and working. I am closing this ticket.
