### ISSUE TITLE
Edit term option - Change of label attached to a class (code) not working

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#236]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The label associated to a class (code) can't be changed

**To Reproduce**
As a RA (should also be the case for a RM) :
1. Go to the GeoObject and Hierarchies module
2. Click the edit pen for a GeoObject type containing a term 
2. Click the edit pen for the attribute in question
3. Click the "Manage Term Options" button
4. Click the edit pen for one of the classes (code)
5. Modify the label associated to the code
6. See error 1: the "Submit" button is not active
7. Click the cancel button
8. See that the label has anyway been changed in the attribute window
9. Refresh the browser and go back to the edit attribute and manage term, options windows.  See error 2: the label is back to its previous version 

=> the change did not take place

**Expected behavior (clear and concise)**
The submit button is working and the change of label is implemented in the system

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
@steeveebener - Are you trying to change the value for the "code" field?

**Comment by SteeveEbener** [comment]
No, the label attached to an existing"term"

**Comment by SteeveEbener** [comment]
Just tested this. The submit button is now active but:
   - there is no need to click it for the change to be appear as implemented in the Manage Term Options window.
   - Refreshing the browser and going back to the edit attribute and manage term, options windows shows that the change has actually not been implemented.

Clicking on the submit button on the other hand:
   - implements the change in the manage term options  window but not in the Edit attribute window unless you click on the submit button in this window as well as the one on the manage Geo Object Type window

=> This ticket is not yet implemented

**Comment by jsmethie** [comment]
I am glad you are testing it but this ticket as been marked for sprint 0.11.0 which we haven't released yet.

**Comment by SteeveEbener** [comment]
Checked and working. I am closing this ticket.
