### ISSUE TITLE
Can't create two lists based on the same GeoObject type

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#237]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
I got the error message reported in the screenshot below when trying to create a second list based on the same GeoObject type

**To Reproduce**
As a RA (should be the same for the RM)
1. Create a first master list based on a given GeoObject type
2. Create a second master list based on the same GeoObject type  
3. See error message reported in the screenshot below

**Expected behavior (clear and concise)**
The RA/RM can create more than 1 list based on the same GeoObject type

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81786034-b6247480-9531-11ea-8386-a5a79deb90aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
To clarrify, my understanding is that we should be able to create multiple non-master lists for the same type but there should be only one 'master list' for the type. Is this what you're asking for?

**Comment by SteeveEbener** [comment]
Tested and working on staging. I am closing this ticket
