### ISSUE TITLE
Can't import the missing parent for a given GeoObject from a complete spreadsheet

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#239]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
- I imported a spreadsheet with missing parents for a given GeoObject
- I wanted to fill the missing information by uploading a complete spreadsheet but this did not work and got the message reported in the screenshot below in the job details

**To Reproduce**
As a RA (and should be a RM):
1.  Go to the import module
2. Import a spreadsheet that contains some GeoObjects with missing parents
3. Go to the lists module to check the import with the missing parents
4. Go back to the import
5. Import the complete spreadsheet against the same GeoObject and specifying:
   - update only as the import strategy
   - fill  the mandatory fields in the attribute mapping window (red border) including the hierarchy for which there were some missing parents
   -  Indicate the field containing the missing parent(s) in the "optionally specify parent" window
6. Go to the schedule job page 
7. See that the job needs to be resolved
8. Click the "resolve problems" button for that job 
9. See error message reported in the screenshot

**Expected behavior (clear and concise)**
The import of the complete spreadsheet fills the missing parents in the graph 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81801493-1c67c200-9547-11ea-89f5-28eb07e446b4.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Google Chrome
 - Version:  81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
I can't recreate this issue, and I think that it is no longer valid because the implementation has changed with the migration to the graph database.

**Comment by SteeveEbener** [comment]
The problem might still be there or be different.

Here are the steps to follow to see the issue in staging:
- Log in as the MOH RM
- Go to the health center master list and open the list for 2020-07-06
- Look at the record for health facility with code HF0171 => the fields for the Shire (MOHA) under the Health Geography hierarchy (MOH)  are empty
- click the edit pen for that record and check the parent tab => there is actually a parent that is being specified under that hierarchy

If you the n try to re-import the content for that list (https://bit.ly/3qHqpnZ) using the "update only" or "New and upate" option nothing is changing.

I hope this helps.

**Comment by jsmethie** [comment]
Hmm, the fact that it shows up in the edit modal says the parent was actually assigned.  There must be something specific to the publish mechanism of the list which is causing it to not show up in the list.  Although I have no idea what that would be at this time.

**Comment by jsmethie** [comment]
Ok, whats going on with the list is that you have assigned the health center to the shire TLK0102038.  TLK0102038 has been marked as inactive after 2007-04-20 an as such the for the list of 2020-07-06 the parent assignment is ignored because the parent is no longer an active geo object.

**Comment by justinlewis** [comment]
@steeveebener This sounds like what we're seeing is behavior where parents are not shown in a list if the parents are inactive. What behavior would you expect in this situation?

**Comment by SteeveEbener** [comment]
Good catch by @jsmethie !  I forgot that I inactivated that Shire in the dataset

This is an excellent illustration of the importance of the curation module. The fact that this Shire does not exist anymore since 2007-04-20 should have been flagged to the RA/RM having the curation mandate over the master list of health centers.

This apart, there are few things that should be happening list module
 1. The field containing the parent should be empty in both the list view, the Parent management modal and the manage values over time windows (not the case right now as shown in the first two screenshots below)
 2. The inactivated Shire should not appear in the list of options you can assign for an instance valid after 2007-04-20 (you can right now as per the third screenshot below)
 3. Ideally, the end date for the first instance should automatically be set to 2007-04-20 and a new empty instance starting from this date automatically added to the view


![image](https://user-images.githubusercontent.com/12602163/102421165-c314c380-403e-11eb-8b05-9eaf0baf2b85.png)

![image](https://user-images.githubusercontent.com/12602163/102421231-e5a6dc80-403e-11eb-9bd3-81746b19a30c.png)

![image](https://user-images.githubusercontent.com/12602163/102421443-606ff780-403f-11eb-806e-c888ae33a980.png)

**Comment by justinlewis** [comment]
@steevebener If you last message has any action items can you create a ticket for them?  We want to close this ticket because the original intent of the ticket creation has been met.

**Comment by SteeveEbener** [comment]
Thanks Justin. I have created ticket #495 to capture this bug.

I can close the ticket here.
