### ISSUE TITLE
Upload manager (all concerned roles): general issues (Enhancement, priority 1)

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#24]
Several issues with this module, including:

- How do we make the distinction between importing the content of the attribute of a shape file to populate a master list from importing a shape file that contains the boundaries for a specific GeoObject type without affecting the content of the corresponding master list?

- The system does currently not allow to store a metadata for the shapefile associated to a specific GeoObject type presenting the polygon format. This is something that should be fixed and such metadata being attached to the shape file when exported
- Duplication of the export function already included in the master list manager

=> these functionalities should be clarified, the module removed from the list and replaced by functionalities directly integrated in the "Master lists manager" and the "Geospatial Data Manager" modules

**Comment by SteeveEbener** [comment]
Mockup to complement the issue posted here: https://www.dropbox.com/s/mn9u6w0nn0b2vwf/Mockup_import_module_230220.pptx?dl=0

The distinction between a "correction" or an "update" is is made as follow:
- correction: overwrite data for a given validity period (need a start and end date)
- update: overwrite data from a given date until the present (only need a start date)

**Comment by SteeveEbener** [comment]
The distinction between a correction and an update has been implemented in version 0.7.0.

What remains from the original ticket are:

- How do we make the distinction between importing the content of the attribute of a shape file to populate a master list from importing a shape file that contains the boundaries for a specific GeoObject type without affecting the content of the corresponding master list? 

- The system does currently not allow to store a metadata for the shapefile associated to a specific GeoObject type presenting the polygon format. This is something that should be fixed and such metadata being attached to the shape file when exported

What has then also been included in the mock up mentioned in the Feb 23 message (https://www.dropbox.com/s/mn9u6w0nn0b2vwf/Mockup_import_module_230220.pptx?dl=0)  is the need to have both a start and end date field to specify a specific validity period when importing data (only having the start data can create unwanted data overwrite)

Finally, we should be able to select the worksheet from which we import the content of a spreadsheet

**Comment by CarlyNel** [comment]
This ticket has been split into multiple sub-tickets as the initial request is too large.

- Validity period: start and end dates [#424](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/424)
- Metadata for shapefiles: [#425](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/425)
- Ability to select the worksheet from which we import the content of a spreadsheet:  [#426](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/426 )

**Comment by SteeveEbener** [comment]
Thanks Carly. I have captured the need to improve the UI when importing shapefile content in ticket #427.

I am closing this ticket as all the initial issues have captured in separated ones.

**Comment by CarlyNel** [comment]
Thanks Steeve, however, I understand that your first point above "_How do we make the distinction between importing the content of the attribute of a shape file to populate a master list from importing a shape file that contains the boundaries for a specific GeoObject type without affecting the content of the corresponding master list?_" has not yet been addressed. This request will remain the focus of this ticket and this work has been assigned 5 story points so this ticket will be reopened. (please correct us if this has been misunderstood as this was the understanding as of yesterday). You are correct that all other requests within your original ticket have been captured individually on separate tickets. Many thanks.
