### ISSUE TITLE
The tab to modify, or provide, the parent(s) information is missing from the submit section of the change request module

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#240]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The tab to modify, or provide, the parent(s) information is missing from the submit section of the change request module

**To Reproduce**
As a RA, RM or RC:
1. Go to the change request module
2. Try to submit a change request for any GeoObject type and GeoObject
3. See that :
    - a set of fields appear between the "Geo Object" and "Reason" field instead of opening a window similar to the editing window you get from the lists module
    - the possibility to change the parent(s) is present 

**Expected behavior (clear and concise)**
The window to submit a change request for a given GeoObject  from the the change request module looks the same as the window that opens when you edit a GeoObject from the list and this including the tab to provide or modify the parent(s) information

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81804322-7ec2c180-954b-11ea-8735-0a48c4637a1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
Closing because the standalone change request submission form has been removed to consolidate the UX and code base as the new more map centric design.
