### ISSUE TITLE
Can't import a polygon format GeoObject type when in the hierarchy it is linked to a point format one 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#242]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
In the hierarchy I have created, a polygon format GeoObject type (Catchment area) is linked to point format GeoObject type (Health post).

No problem linking the two when creating the hierarchy in the  GeoObject type and hierarchy module but I can't upload the polygon format shape file against the hierarchy in question.

When doing this, the import does not go through and the problem to be resolved present the error message reported in the screenshot (You cannot add a geo object with a geometry of type [MultiPolygon]. As geometry of type [POLYGON] is expected).

**To Reproduce**
As a RA (should also work for a RM)
1. Create a hierarchy that link a polygon format GeoObject type to a point format one 
2. Import the spreadsheet containing the information for both GeoObject types and the hierarchy 
3. Import the shape file containing the polygon format GeoObject type
4. Go to the scheduled job window
5. Open the window to resolve the problem
3. See error messsage reported in the screenshot

**Expected behavior (clear and concise)**
It is possible to link a polygon format GeoObject type to a point format one 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81944224-05040400-962f-11ea-96b9-30499b68e023.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
I think this is because you're trying to upload a MultiPolygon geometry type to a GeoObjectType that is set as Polygon. I don't think it relates to the parent Health Post GeoObjectType. This is a validation check to enforce the geometry type.

**Comment by SteeveEbener** [comment]
Good catch! I misunderstood the error message.

Two new issues then:
1. I can't modify the geometry type without deleting and recreating the GeoObject type
2. This links to a more larger issue that I documented under #93

**Comment by SteeveEbener** [comment]
On the original issue, I have now been able to upload the catchment areas shape file after deleting and re-creating the GeoObject type using the multipolygon geometry type.

I am closing this issue and will capture the observation here above under issue #93.
