### ISSUE TITLE
Can't import a shape file against the newly created validity period

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#245]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
In the continuity of issues #243 :

Now that I have added my new Province from 20 Apr 2007 I wanted to import the shape file containing all the Provinces for this new period of validity. This did not work and got the "Unable to complete" error message included in the screenshot below. I then need to refresh the browser to be able to continue using the CGR.

**To Reproduce**
As a RA (should also work for a RM)
1. Once the new GeoBject has been added (see issue #243)
2. Go to the import module
3. Select the import shapefile section
4. fill the fields in the first window (the error appears with any import strategy) 
5. Click the submit button
3. See the error message

**Expected behavior (clear and concise)**
as a RA/RM I can upload the shape file containing the geometries matching the new period of validity that I have created

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/81999017-88047900-9686-11ea-90bd-3cbbb6e5af48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
As MOHA RA, I just tried to import the shape file for the new validity period (20 Apr 2007-present) and it did not work. 

I am getting the following message after clicking the submit button on the import shape file window:

![image](https://user-images.githubusercontent.com/12602163/85189888-86f9e380-b2e5-11ea-95e9-7e6affacdf18.png)

**Comment by jsmethie** [comment]
@SteeveEbener I cannot reproduce this problem locally.  Can you provide me with the shapefile you are importing, the hierarchy, and the geo object type?

**Comment by SteeveEbener** [comment]
Hi @jsmethie . Sure, the shape file is in this dropbox folder: https://www.dropbox.com/sh/qub8c9xe91ptirx/AAAJfvaZziZQYa4hb-RtUodka?dl=0

The GeoObject type is "Province (MOHA), the hierarchy is the "Administrative structure hierarchy" and the new Province is the Province of Orrostar which is already implemented in the graph with start date 20.04.2007.

Please don't hesitate to let me know in case you need anything else

**Comment by jsmethie** [comment]
@SteeveEbener The cause of the problem is that the shapefile you are uploading is invalid.  It is missing the file COR_TOLKIEN_REG_2000_2018.shp.  I will update the system to give a better error message in this situation but you will need to fix the zip to go further.

**Comment by SteeveEbener** [comment]
@jsmethie : Arrg, I managed to select the wrong set of files when creating the zip file! Thanks indeed for adjusting the error message.

Shall I already close the issue or only do that once the error message has been changed?

**Comment by jsmethie** [comment]
Leave it open until you have validated the new error message.

**Comment by SteeveEbener** [comment]
The error message is much more explicit now. I am closing this ticket
