### ISSUE TITLE
RA should not be able to change the local (only SRA) + English not appearing in the list of language while it used by the CGR and can be exported

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#247]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RA can add or export a language while only the SRA should be able to do so and English is not appearing in the list of language while it is being used and can be exported

**To Reproduce**
As a RA:
1. Go to the burger menu and choose  Settings
2. See Error 1: the RA can access the localization setting 
3. See error 2: English is not appearing in the list

**Expected behavior (clear and concise)**
Only the SRA can change the local and English is appearing in the list by default and should not be deleted 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/82385839-96c3a500-9a65-11ea-97e1-fafc3ef0b348.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by dtreatman** [comment]
Linked to https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/197 - suggest these be addressed together

**Comment by justinlewis** [comment]
The ability to access localization as an RA has been removed.

**Comment by SteeveEbener** [comment]
The issue of the RA being able to change the local has been addressed and I have created ticket #296 to address the question of the English local not appearing in the localization table.

I am therefore closing this issue
