### ISSUE TITLE
RM can't create a list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#249]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RM can't create a list for the GeoObject types on which he has this role.

**To Reproduce**
As a RM:
1. Go to the Lists module 
2. See error: the create button is not there

**Expected behavior (clear and concise)**
The RM can create lists (master and non-master) for the GeoObject types on which he has this role.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 0.7.0
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**
- Link to the User Role Management Epic

**Comment by justinlewis** [comment]
@steeveebener - RM's are assiged to GeoObjectTypes not organizations. Do you mean an RM should be able to publish lists for GeoObjectTypes they are RMs for?

**Comment by SteeveEbener** [comment]
Yes, the description in the ticket was not well written, my apologies for that. I have adjusted the text to make it more clear.
