### ISSUE TITLE
DHIS2 User Interface

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#25]
**What is this:**
[A.2.2] Utilize support for OAuth and a link navigation system so that users from within DHIS2 can directly navigate to the corresponding screen in the common geo-registry for the governance workflow.

**Why is this important:**
For example, a program manager who uses DHIS2 for their routine reporting and management system who wants to make an update to a node in the DHIS2 hierarchy should not need to log in to the CGR separately to do so. The program manager need only click on the appropriate link to edit the details of the hierarchy node within DHIS2 to be redirected to the appropriate CGR interface that displays the details of that particular GeoObject and provides the program manager with the ability to edit the GeoObject or submit a change request, depending on the program manager's role in the CGR for that GeoObject type.

**Comment by dtreatman** [comment]
Questions:
- How and where should a user click in DHIS2 to be redirected to the CGR? Would this be a custom DHIS2 attribute?
- Where should the user be redirected to in the CGR when they click on a node of the DHIS2 hierarchy or tracked entity instance? Should they arrive in the Navigator? Or a filtered view of the master list?

**Comment by steesdale** [comment]
Merged with DHIS2 Integration epic
