### ISSUE TITLE
RM and RC not having access to the GeoObject types and hierarchies module

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#250]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
RM and RC not having access to the GeoObject types and hierarchies module

**To Reproduce**
As a RM or RC
1. Login 
2. See error: the GeoObject types and Hierarchies module is not there 

**Expected behavior (clear and concise)**
The RM should be able to have access to theGeoObjects and Hierarchies module to be able to consult the metadata associated to both and understand the hierarchies implemented in the lists he is looking at 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Both the RM and RC can now have access to the GeoObject types and hierarchies module but still can't have access to the metadata for all of them as per the information reported in the rights by role google spreadsheet (linked to epic ticket #285)

**Comment by justinlewis** [comment]
Related: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/219

**Comment by SteeveEbener** [comment]
This ticket has been addressed and the remaining issues captured in other tickets. I am closing this one
