### ISSUE TITLE
Title of the "Create list" window remaining the same when viewing the list metadata

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#251]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The change of  title for the "create list" window (issue #185) resulted in the same title to appear when we open the metadata

**To Reproduce**
As a RA (Should also be the case for the RM and RC)
1. Go to the lists module
2. Click on the metadata button for one of the lists
3. See error: the title of the window that opens is "Create list"

**Expected behavior (clear and concise)**
Two options:

1. It is possible for the title to be different between the moment you create the list and view/edit the metadata

2. The title has to remain the same independently from when we access it (create vs consult for example). In this case we should use a title that would apply to both cases.

I am in favor for the second option and suggest that we title this window "GeoObject Type list Metadata" (for Example "Health facilities list Metadata")

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**
Continuity of issue #185

**Comment by rrowlands** [comment]
The requested title in this ticket cannot be implemented as requested. This is because it includes the GeoObjectType display label, which is unknown when the dialog is displayed for the "create new" usecase. For this reason I have implemented #1.

**Comment by rrowlands** [comment]
![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/dae35ca9-e42c-49c7-9d8c-001bb270e4ca)

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/68e4473e-093b-4484-a268-8b0eee6463e0)

**Comment by SteeveEbener** [comment]
This ticket has been checked and is correctly implemented. I am closing this issue.
