### ISSUE TITLE
Add organization button accessible to the RA role

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#252]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The RA can access the add organization button in the settings while it should not even be there

**To Reproduce**
1. As a RA
2. Go to the Settings 
3. See error: the Add organization button ("+") is accessible

**Expected behavior (clear and concise)**
The add organization button is not accessible to the RA role.

The RA should only have the possibility to:

- view or edit its own organization information
- view the information for he other organizations in order to be able to contact them if needed

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/82712913-d5529d00-9cbb-11ea-99ad-545863b241f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
The "Add" button has been removed but the RA cant see the other organizations.

To simplify, I have created a new ticket to capture the second issue not yet implemented (#301)

P.S.: When it comes to the RA being able to modify the information of his organization I finally think that it is good that this goes through the SRA => I have not included this functionality in the new ticket.

I am closing this issue in view of the above

**Comment by CarlyNel** [comment]
Hi @SteeveEbener, I'm going to close this issue as per your above comment (looks like you might have forgotten but please flag if otherwise).

**Comment by SteeveEbener** [comment]
Ho, I thought I clicked on the Comment and close button. Thanks Carly
