### ISSUE TITLE
Support of polygons in spreadsheet import

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#254]
In December of 2019, Vital Wave shared with TerraFrame a spreadsheet containing jurisdiction data for Thailand. This file contained data for multiple location types, including provinces, districts, and villages. Since the CGR can only import data for one location type at a time, that file had to be broken up into separate files manually. Additionally, the file contained geometries and the CGR can only import lat and long coordinates from spreadsheets. The geometries had to be manually converted into shapefiles and then were imported into the CGR.

Support will be added for importing polygons from spreadsheets. This will eliminate the need to produce shapefiles in order to import geometries. Files will still need to contain data for only one location type at a time. Once imported, all of the CGR data validation and curation use cases will apply.

Note: the CGR spreadsheet importer requires that all locations within a spreadsheet are of a given type, such as provinces, districts, villages, and structures. This will remain true for this effort and support for a single spreadsheet with multiple location types will not be supported.

**Modify spreadsheet importer screen**

When a spreadsheet is imported into the CGR, the user is presented with a screen to map the columns in the spreadsheet to attributes on a GeoObject Type that has been defined in the CGR. The first row of the spreadsheet must be a column header with labels for each column. The user matches these labels to the corresponding attribute on the GeoObject Type. Since the current screen assumes there is a single column to store latitude and a single column to store longitude, the user will need to be presented with the option to specify if the spreadsheet has lat long coordinates or contains a column specifying a geometry. The spreadsheet examples that TerraFrame were provided contained the Geometry Type in a separate column instead of in the same column as the geometry itself. It needs to be discussed with Akros, Ona, and Vital Wave if this is desired, as typically a geometry column containing a GeoJSON geometry definition contains both the geometry type and the coordinates together. Example:

"geometry": {
"type": "MultiPolygon",
"coordinates": [
[
[
[
98.66642938917731,
15.761668960697268
],
[
98.66633709272412,
15.761664428365012
],
[
98.66633408341482,
15.761721887754845
],
[
98.66642638082739,
15.761726420090286
],
[
98.66642938917731,
15.761668960697268
]
]
]
]
},

**Comment by nmceachen** [comment]
In December of 2019, Vital Wave shared with TerraFrame a spreadsheet containing jurisdiction data for Thailand. This file contained data for multiple location types, including provinces, districts, and villages. Since the CGR can only import data for one location type at a time, that file had to be broken up into separate files manually. Additionally, the file contained geometries and the CGR can only import lat and long coordinates from spreadsheets. The geometries had to be manually converted into shapefiles and then were imported into the CGR.

Support will be added for importing polygons from spreadsheets. This will eliminate the need to produce shapefiles in order to import geometries. Files will still need to contain data for only one location type at a time. Once imported, all of the CGR data validation and curation use cases will apply. 

Note: the CGR spreadsheet importer requires that all locations within a spreadsheet are of a given type, such as provinces, districts, villages, and structures. This will remain true for this effort and support for a single spreadsheet with multiple location types will not be supported.

**Modify spreadsheet importer screen**

When a spreadsheet is imported into the CGR, the user is presented with a screen to map the columns in the spreadsheet to attributes on a GeoObject Type that has been defined in the CGR. The first row of the spreadsheet must be a column header with labels for each column. The user matches these labels to the corresponding attribute on the GeoObject Type. Since the current screen assumes there is a single column to store latitude and a single column to store longitude, the user will need to be presented with the option to specify if the spreadsheet has lat long coordinates or contains a column specifying a geometry. The spreadsheet examples that TerraFrame were provided contained the Geometry Type in a separate column instead of in the same column as the geometry itself. It needs to be discussed with Akros, Ona, and Vital Wave if this is desired, as typically a geometry column containing a GeoJSON geometry definition contains both the geometry type and the coordinates together. Example:

"geometry": {
            "type": "MultiPolygon",
            "coordinates": [
                [
                    [
                        [
                            98.66642938917731,
                            15.761668960697268
                        ],
                        [
                            98.66633709272412,
                            15.761664428365012
                        ],
                        [
                            98.66633408341482,
                            15.761721887754845
                        ],
                        [
                            98.66642638082739,
                            15.761726420090286
                        ],
                        [
                            98.66642938917731,
                            15.761668960697268
                        ]
                    ]
                ]
            ]
        },

**Comment by rrowlands** [comment]
This ticket was implemented, but not as it was described in the ticket. It was hardcoded to the reveal usecase and was implemented to expect that 1) coordinate columns are always at the end of the spreadsheet and 2) the geometryType column is always immediately 1 column behind that coordinates column. Additionally, the polygon import option only appears when importing to a reveal external system.
