### ISSUE TITLE
Export Data in the Reveal Format

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#256]
Users will have the ability to export the curated location data as text files in the Reveal JSON format. 

**Add the GeoJSON format to the Geospatial Data Manager**
Users have the ability in the master list management module to export published lists as shapefiles. Support for exporting as GeoJSON will be added.

**Add hierarchy levels to the GeoJSON format**
The Reveal GeoJSON format has an attribute that specifies the level of a given object within a hierarchy. In the CGR, hierarchy information in stored as relationships and as attributes. A level attribute should be added to the exported GeoJSON format at runtime. Since the Reveal data will only have one hierarchy, there only needs to be one level field.

**Comment by nmceachen** [comment]
![Screen Shot 2020-05-30 at 12.09.18 AM.png](https://images.zenhubusercontent.com/5df86e5855438f1d74c8021e/9eb6cf77-c73f-4f5e-8af3-ed3ed39f62b0)

Add a button or a link that gives people the ability to export in the Reveal GeoJSON format.

**Comment by nmceachen** [comment]
Here is an example of the Reveal format:

{
        "type": "Feature",
        "id": "3d4e6ece-bd19-48c8-91fd-ee6918ae44ee",
        "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
                [
                    [
                        [
                            98.66642938917731,
                            15.761668960697268
                        ],
                        [
                            98.66633709272412,
                            15.761664428365012
                        ],
                        [
                            98.66633408341482,
                            15.761721887754845
                        ],
                        [
                            98.66642638082739,
                            15.761726420090286
                        ],
                        [
                            98.66642938917731,
                            15.761668960697268
                        ]
                    ]
                ]
            ]
        },
        "properties": {
            "status": "Active",
            "parentId": "64b43168-1c78-4215-9ddd-4d6d65cfdd38",
            "geographicLevel": 6,
            "version": 0,
            "externalId": "3d4e6ece-bd19-48c8-91fd-ee6918ae44ee"
        },
        "serverVersion": 1571225816014
    }

**Comment by nmceachen** [comment]
As an interim deliverable to Akros, write code that can export instances of GeoObject Types from a Master List  (not directly from the graph). Since as of the week of June 1st, we do not have support for external system IDs implemented, generate GeoJSON with the following:

{
    “type”: “Feature”,
    “id”: “fd49ddbc-a15c-4b10-bbb4-29af4d746340", **<- use the CGR ID for now**
    “geometry”: { **<- use the Geometry for the GeoObject**
...
    “properties”: {.   
        “status”: “Active”,    **<- For now, export the GeoObject status field**
        “parentId”: “5f801f45-c8e5-4aad-9a93-e98961e6a9fa”,  **<- for now, include a GeoObject ID of a parent. Just pick a parent regardless of hierarchy, as Reveal will only have one.**
        “name”: ” ทุ่งนาห้วยน้ำนัก (6307010404)“, **<- populate this if there is a locale defined**
        “geographicLevel”: 5, **<- populate this with the level in the hierarchy**
        “version”: 0, **<- just put 0 here for now**
        “OpenMRS_Id”: “ba63b443-7413-4548-b89d-7d63ac9c04c9", **<- just put 0 here for now**
        “externalId”: “6307010404", **<- populate this with the code field**
        “name_en”: “THUNG NA HUAI NAM NAK (6307010404)” **<- this is the default locale**
    },
    “serverVersion”: 1584615428560
}

**Comment by rrowlands** [comment]
Shall I put 0 in for "serverVersion"? Also is serverVersion supposed to be inside the "properties" json object? (I assume this is supposed to be valid geoJSON?)

**Comment by rrowlands** [comment]
The following:

> Add the GeoJSON format to the Geospatial Data Manager
> Users have the ability in the master list management module to export published lists as shapefiles. Support for exporting as GeoJSON will be added.

Has not been implemented because we decided to not write an exporter that works on masterlists.

**Comment by craigappl** [comment]
I want to confirm that we can drop the serverVerion.

**Comment by nmceachen** [comment]
@craigappl Yes, dropping the server version is not a problem.
