### ISSUE TITLE
Enhance RESTful API to allow Reveal to query for GeoObjects

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#257]
The CGR Restful API will be enhanced to allow Reveal to query for objects of a given type for a given hierarchy that have been modified on or after a given date. Reveal can authenticate itself with the CGR using the RESTful API. Alternatively, the GeoObject Types can be queried without authentication if they are made readable to the CGR anonymous user.

**Implement query parameters for RESTful API**
The following parameters will be implemented to give the Ona team what it needs to query the CGR and retrieve location information

•	The Hierarchy Type
•	The GeoObject Type – If null or empty string is provided then include all GeoObject Types for the given hierarchy.
•	A flag indicating whether to include the Level attribute in the GeoJSON format that indicates what level the object is in the hierarchy
•	A timestamp – return objects that have been updated since the given date 

The API returns either the total number of pages or indicates there are additional pages to return if there are more than 1000 results.

**Comment by nmceachen** [comment]
Draft API here:

https://docs.google.com/document/d/1qVjue6NB2l3ZBDOGXsBvjElhAfijuBajgI8i1Zu2cy0/

**Comment by CarlyNel** [comment]
@nmceachen @justinlewis Could you please advise if you are waiting on external feedback on this ticket? Justin this is one of the tickets that I mentioned in our call last week that is purely technical in nature and I asked whether in a case like this, TF will review and close these tickets.

Could you please confirm? Thanks!
