### ISSUE TITLE
Use of the back button when viewing a list from the "Published"  section brings you to the "Exploratory" one

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#258]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
The browser back button brings you to the "Exploratory" section when clicking it while viewing a list from the  "Published" section. 

**To Reproduce**
As a RA, RM or RC:
1. Go to the lists module
2. Click the view button for a list under the curation mandate of the RA/RM
3. Go to the published section
4. Click the view button for one of the lists
2. Click the back browser back button
3. See error: you end up in the Exploratory  section

**Expected behavior (clear and concise)**
Clicking on the browser back button from a lists opened in the published section brings you back to the published  section

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**
Need to make sure that clicking the back button from a list in the exploratory section still brings you back to the exploratory section main page as this is currently the case

**Comment by justinlewis** [comment]
Marking as invalid because the new list design being released in 0.18 doesn't have the exploratory section tabs this refers to.
