### ISSUE TITLE
Adding a GeoObject require to precise the parents across all the hierarchies, including those created by other organizations

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#259]
**List the CGR version information**
- CGR version: 0.7.0

**Describe the bug (clear and concise)**
When adding a new GeoObject (hitoric change) for a GeoObject type under the curation mandate of organization A, the RA (should also be the RM) has to precise the parent across all the hierarchies including those created by organization B (see screenshot below) while organization A does not have the authority over the GeoObject types and hierarchies managed by organization B.

**To Reproduce**
As a RA (should also be for the RM) of organization A
1. Go to the lists module
2. Open the list for which you want to add a new GeoObject (this has to be  for a GeoObject type that has parents across different hierarchies, including some managed by organization B)
3. Add a GeoObject
4. Go to the parents tab
5. See the error: The hierarchies created by other organizations are appearing.

**Expected behavior (clear and concise)**
The RA/RM of the organization having the curation mandate over the GeoObject type should only have to change the parents for the hierarchies over which it has the mandate.

The need to change the parents in relation to hierarchies created by other organizations should be handled by the organizations in question.

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/82889037-bcc4da00-9f7c-11ea-98e0-e2cd04551dc9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by rrowlands** [comment]
It may also make sense to only display hierarchies for which the GeoObjectType participates in.

**Comment by SteeveEbener** [comment]
Indeed but it seems to already be the case from what I have seen, no? The main problem is that the list shows the hierarchies created by other organizations

**Comment by rrowlands** [comment]
It would only be a problem if a particular user were an RA of many different hierarchies, however this particular GeoObjectType only participates in a single hierarchy. In this scenario, no, we're not currently filtering these out properly for this widget.

**Comment by SteeveEbener** [comment]
We will certainly have the case where the RA has the curation of more than one hierarchy within its own organization. Would that be an issue?

**Comment by rrowlands** [comment]
Yeah, the widget doesn't currently handle that scenario very well.

**Comment by rrowlands** [comment]
I have created a new ticket #292 where we can address the additional issue discovered in the comments.

**Comment by SteeveEbener** [comment]
I just tested the issue reported in this ticket and this is still not working. All the hierarchies in which the GoeObject type is involved are still appearing in the window (same screen shot as in the original issue)

**Comment by rrowlands** [comment]
I am sorry about that Steve. This issue was clearly more complicated than I had originally realized. I have created a new ticket #292 and we can add fixing the usecase described in this ticket as part of the  requirements of that ticket.

**Comment by CarlyNel** [comment]
Hi @rrowlands,

I am unable to find ticket 292. Could you please confirm if that's the correct ticket number?

@SteeveEbener, once you've reviewed the new ticket, if you're happy that your above mentioned error has been accurately captured in the new ticket, could you please go ahead and close this ticket?

Many thanks!

**Comment by SteeveEbener** [comment]
@justinlewis I can't find issue #292 neither and the issue reported in the initial ticket remains

**Comment by CarlyNel** [comment]
Hi @justinlewis @rrowlands Could one of you please respond on the above? When Steeve last tested this work, the original issue remained and neither of us are able to find the subsequent ticket #292 to which you refer.

**Comment by justinlewis** [comment]
I'm sorry I didn't see these comments earlier. I deleted that ticket because @steeveebener said the new ticket was not relevant to the this one.There was some confusion about what the objective was for this ticket. This ticket is still open. I'll put this out of 'in review' so we can get it on our radar again.

**Comment by rrowlands** [comment]
As far as I can tell, this issue has been resolved and the code has been pushed to staging. If this is not the case, please let us know.

**Comment by CarlyNel** [comment]
Thanks @rrowlands and @justinlewis. @SteeveEbener could you please test this ticket again and confirm/close this ticket if you are happy with the results? Thanks everyone.

**Comment by SteeveEbener** [comment]
@rrowlands : in which version has this been resolved? If it is in 0.10.0, I will have to wait until it is pushed in the demo instance to be able testing it

**Comment by SteeveEbener** [comment]
Tested and working in version 0.10.0. I am closing this ticket.

**Comment by SteeveEbener** [comment]
I unfortunately need to re-open this ticket because the error in back in ve 0.12.1 as per the following screenshot (AnneTest and AL Test Hierarchy are hierarchies from another organization):
![image](https://user-images.githubusercontent.com/12602163/100238828-a0c1e580-2f6b-11eb-84fc-0e8f1dd2799e.png)

**Comment by rrowlands** [comment]
I can confirm that this is unfortunately still an issue on the latest release.

**Comment by SteeveEbener** [comment]
Still a problem in 0.13.1 (staging). To see that:
1. Log as the Moha RA
2. Go to the list of villages
3. Click the Add GeoObject button
4. Scroll down the items on the left
5. See that the health care referral hierarchy (MOH) is accessible to MOHA and editable:
![image](https://user-images.githubusercontent.com/12602163/104421366-35cd7c00-55b6-11eb-934e-1f19c74c9ac4.png)

**Comment by rrowlands** [comment]
Good catch Steeve. This will be fixed in 0.13.2. Apologies for any inconvenience.

**Comment by SteeveEbener** [comment]
Tested under 0.13.2 and working. I am closing this ticket
