### ISSUE TITLE
Basemap Imagery Service

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#26]
The CGR currently uses a satellite base map imagery service from Mapbox. The GIS Server component of the CGR makes geometries for GeoObjects available as a WMTS service. The GIS Server can also be used to host satellite imagery base maps to in-country to avoid dependence on a single vendor.

Epic documentation and user stories: [Shared Google Doc](https://docs.google.com/document/d/1mVB3BElj6PgFIRo5FwjhWFmuhuNHTC5pXzj8VNbyt9M/edit#heading=h.uwq12f2tqkul)

**Comment by dtreatman** [comment]
Questions:
- Should RAs be able to store basemaps on the CGR server itself? Or do we expect them to always point the CGR to another server or web-hosted source of basemaps?

**Comment by nmceachen** [comment]
This was scoped to point the CGR to public WMS services.

**Comment by CarlyNel** [comment]
Anne confirmed that this ticket should remain in the icebox.
