### ISSUE TITLE
Banner image not updating after uploading a new one

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#260]
**List the CGR version information**
- CGR version: 0.7.1

**Describe the bug (clear and concise)**
Banner image not updating after uploading a new one.

**To Reproduce**
1. As an SRA go to the settings page
2. Click on banner edit button
3. Upload a new image
4. Refresh the browser (while clearing your cache)
5. Note the ico image in the browser tab not changing

**Expected behavior (clear and concise)**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by justinlewis** [comment]
This functionality is designed for an onlder UI that is not relevant anymore. This functionality should be removed.

**Comment by SteeveEbener** [comment]
Do you mean that we should remove or replace the possibility for the SRA to customize the CGR banner?

**Comment by justinlewis** [comment]
@steeveebener - I mean we need to remove it because we don't have a mechanism in the UI to place the banner in the page.

**Comment by SteeveEbener** [comment]
To be decided by CHAI then

**Comment by SteeveEbener** [comment]
What has been CHAI decision then?

**Comment by justinlewis** [comment]
This was functionality that has had no place in the UI for a long time and so there is nothing to discuss. The only branding configuration that is supported is changing the logo.
