### ISSUE TITLE
Invitation emails that are more informative

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#261]
## User stories
1. When I am invited as being a user of the CGR I would like to know for which organization, role and GeoObject type this is the case

## Problems this relates to
1. Generic emails included in the localization file

## Proposed solution
1. Include a set of template emails that are role specific (RA, RM, RC) and which could ideally also specify for which organization and GeoObject types this is the case 

## Considered alternatives
1. None for the moment

**Comment by justinlewis** [comment]
Would this just be a different paragraph (and only one paragraph ever) of text or would we want a different structure for each template (e.g. different HTML)?

**Comment by SteeveEbener** [comment]
These emails will only concern the RA, RM and RC roles, right?

I could work on a template for each of them to be able to answer your question if this is the case.,

**Comment by justinlewis** [comment]
Don't spend time on the templates yet please. I ask because we will likely not be ablet to support different templates in this round of effort.  Changing the text for each is feasible.

**Comment by SteeveEbener** [comment]
Having a different text for each email is what I meant. Just let me know when you want me to work on such text.

**Comment by justinlewis** [comment]
@steeveebener - Gotcha. We'll estimate for just changing the text. You can hold off for now please.

**Comment by justinlewis** [comment]
@steeveebener You asked for this:

> Congratulations!
> 
> You have been invited to create an account as Common Geo-Registry Administrator for the Ministry of Health Organization.
> 
> To do so, click the link below: LINK
> 
> The above link will stop working in 168 hours.
> If you did not request this, you can safely ignore this email. 

But right now we are only able to change this to:

> Congratulations!
> 
> You have been invited to create an account with the Common Geo-Registry.
> 
> To do so, click the link below: [LINK]
> 
> The above link will stop working in 168 hours.
> If you did not request this, you can safely ignore this email. 


So this doesn't include the roles information. There are some technical reasons why we don't have access to that information when this email is sent. This can be improved in the future but in the mean time I'm wondering if adding the roles to the page the user is routed to from the email would satisfy the need for a user to see what roles and organization they are being invited to?

For reference this is what that form looks like now:
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/05cfe3d0-4ce6-4bed-a9c1-6ac726bc2f2e)

**Comment by SteeveEbener** [comment]
@Justin. Too bad that we can't change anything in the email. I hope this won't make some users hesitate to click on the link thinking this might be a spam.

In the meantime, it would then indeed be good if the following text could for example be added on top of the form (text in italic between [] to be replaced by the corresponding information and English to be checked):

You have been invited by the [_Organization_] to create an account as Common Geo-Registry [_role_] over the following Geo-Object types:

- [_Geo-Object type 1_]
- [_Geo-Object type 2_]
- ....

Please fill the form below (mandatory fields indicated by a red border) and click the submit button if you indeed requested for the above.

**Comment by CarlyNel** [comment]
Hey @justinlewis Just adding a reference here to ticket [#335](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/335) as it also relates to the invitation email. Was a minor recommendation regarding the validity (days vs hours) of the invite. Thanks.

**Comment by rrowlands** [comment]
The requested behaviour, while do-able, is not able to fit within the timeline of the 0.13.1 release. I have determined that the requested email feature can be included within the 0.13.2 release as requested, due to the fact that it can be completed with a similar amount of effort as what is requested for including the roles on the "create your account" page.

What is unknown to me at this time, however, is whether or not a user will ever be invited with permissions to multiple organizations. If this is the case, then the invite text must take this into account in a way that makes sense. Sentences such as "You have been invited by the [Organization] to create an account as Common Geo-Registry" cannot be implemented as requested since they do not take the multiple organizations use-case into account.

**Comment by justinlewis** [comment]
The only cross organisation role we plan to support in the funded road-map is the System Administrator so you can rely on an assumption for this ticket that a RA, RM, and RC will only be a part of one organisation.

**Comment by rrowlands** [comment]
And do I just leave the part about the organization out of the message if they're invited as a sys admin?

**Comment by justinlewis** [comment]
Yes as long as we still indicate that they are being invited as a System Admin.

**Comment by rrowlands** [comment]
The requested changes to the email invites have been made. If you would like any additional changes please let us know (they should be pretty straightforward from here on out).

**Comment by SteeveEbener** [comment]
The email works well but if you mix the roles (example: RM for Provinces and RC for County) the email makes only reference to the role attached to the geo-object type on top of the list in the "invite  a User" window => How can we address this?

**Comment by rrowlands** [comment]
I can change the text to include multiple roles, however it's not clear the best way to do this. It was also unclear to me that a particular user might be an RA for one org and an RC for a different org. Finally, it's also conceivable that a user could be an RM for 10 different GeoObjectTypes, in which case even if we were to display many different roles it conceivably could get very wordy very quickly. If you would like a change to be made to this text I will need a template and a suggestion as to how to solve this problem.

**Comment by rrowlands** [comment]
A potential solution here is to list the roles and the organizations as a list with zero duplicates. So, for instance, if the user is an RM of 3 different GeoObjectTypes for Organization Apple, and RA for Organization Banana, and an RC for Organization Carrot, we could show it as:

`You have been invited to create an account as Common Geo-Registry Registry Maintainer, Registry Administrator, Registry Contributor for the Apple, Banana, Carrot Organization(s).`

**Comment by SteeveEbener** [comment]
Thanks @rrowlands. The RA can't actually invite someone to have different role across multiple organization (and it should remain like this) but he can invite someone to have a different roles (RM, RC or API, not RA) for different geo-object types

=> The email could read as follow to make it simple:

"You have been invited to create an account as Common Geo-Registry Registry Maintainer and Registry Contributor over specific geo-object types for the Central Government Organization."

**Comment by rrowlands** [comment]
I can implement this however I recommend omitting the "over specific geo-object types" text since it is not relevant for RA's and SRA's.

**Comment by rrowlands** [comment]
My latest code just produced this output:


> Congratulations!
> 
> You have been invited to create an account as Common Geo-Registry Registry Contributor, Registry Maintainer, API Consumer for the Central Government organization.
> 
> To do so, click the link below:
> https://localhost:8443/georegistry/cgr/manage#/admin/invite-complete/7d867c9a-ce95-387e-956f-70b6f4b25653b5b2298c-b068-3435-b458-fb6958415a62
> 
> The above link will stop working in 7 days.

**Comment by SteeveEbener** [comment]
Looks good. Closing this ticket
