### ISSUE TITLE
Support external IDs in the importer - back end

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#263]
Read this requirements doc for additional context:

https://docs.google.com/document/d/1-jW953CL1UyxFHmko1SCRHNikbzdb1O9yvxZxXpVp_k/

Implement support for associating an external ID from a given external system with a GeoObject. This will give the CGR the ability to export to and to synchronize with external systems. When importing data from an external system, we will need the ability to specify that, for a dataset, a column/attribute represents an external ID. The external ID would be stored as an attribute on a relationship between the GeoObject and the node representing the external system from which the data is from.

By importing a spreadsheet of health facilities that contains a column with the DHIS2 org unit ID, then this functionality can be used to establish a mapping between the objects in the CGR and the corresponding objects in DHIS2.

**Back end**
A new MdEdge class, Has External ID, will be created that will be used to store the IDs of GeoObjects in external systems.

There will be a separate relationship for each external system that the CGR is synchronizing with for a GeoObject.

Regardless whether data are being imported from a GeoJSON file, a Spreadsheet, a Shapefile, or a direct data feed (not yet supported). The CGR importer requires that fields from the source datatype need to be mapped to fields defined on GeoObject types. The current field mapping screen for importing files will eventually be repurposed for mapping fields on data pulled programmatically from an external system. This mapping data model between source and target fields will need to be extended to register fields as external ids. 

There are two types of external IDs:
Object ID:  An identifier for the current record in an external system. This can be used to match an imported record with the corresponding GeoObject in the CGR.
Parent ID: An identifier of a parent reference in an external system. This can be used to identify a parent reference.

There can be only one external ID on a dataset that is an object ID. There can be zero, one, or multiple external IDs on a dataset that are Parent IDs. If a field is an Object ID and the importer is attempting to update GeoObjects, then identify the GeoObject by matching the External_ID of the Has_External_ID relationship for the given external system.

**Comment by SteeveEbener** [comment]
For info, the possibility for the CGR to serve as key correspondence table between IDs used by different systems, or programs in the first phase of deployment and while waiting for all the systems/programs to use the same unique ID, is an important feature of the CGR

This links to the possibility to create other fields containing uniqe IDs as described to some extent in issue #209

**Comment by rrowlands** [comment]
Summary of a discussion @jsmethie and I had:

We think it makes sense that when the importer cannot find either a parent with the externalId in the spreadsheet, or a parent with a code specfied in the spreadsheet (and matchStrategy == CODE), then we handle it at validation stage as a RowValidationError (and a error message specific to the scenario which clearly describes the problem). This behavior would force the user to reimport their spreadsheet to fix the problem. We agreed that in the future it might make sense to solve these with some sort of "local synonym" (specific to this import) or some additional importer resolutions mechanisms that don't currently exist. Given that this code must be soon, we don't have time for any of that and a RowValidationError is the easiest to implement given the time crunch.

**Comment by SteeveEbener** [comment]
What about having this being captured as "unknown" and then being managed through the curation module?

**Comment by rrowlands** [comment]
This sort of behavior can be discussed further at a later date as it hints towards a larger discussion revolving around data curation. Additionally it brings up a discussion about scope.
