### ISSUE TITLE
RA/RM should be able to specify the date from which the publishing of a list takes place 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#265]
## User stories
1. As a RA/RM I want to be able to decide the date from which a given list is being shared with users outside of my organization and this for the following reason:

- The updating mechanism might not necessarily end up in the list being updated by the end of a given year (e.g. might only be released by June 1st of each year)
- I might have data in the graph from a given date (e.g. January 2000) but might only want to share the lists from January 2010 with other organizations because older data is not ready for sharing.

## Problems this relates to
1. issue #186 

## Proposed solution
1. In the list specific metadata window, add a field to capture the date from which lists will be published based on the defined frequency. This field could for example be labelled "Publishing start date" 
2. At the same time, change the label of of the "frequency" field into "publishing frequency"
3. The instance of the list that are being published should be for the date specified in the "publishing start date" field and not the day before that.

## Considered alternatives
1. None

**Comment by SteeveEbener** [comment]
Just tested this ticket and the "publishing start date" field is still not appearing in the list specific metadata => this ticket is still not implemented as expected.

![image](https://user-images.githubusercontent.com/12602163/99493188-be121500-29a9-11eb-830c-ba165bd8bd98.png)

**Comment by SteeveEbener** [comment]
Just tested under ve 13  in staging and this is still not working as expected.

I have entered the 15-Mar-2010 as the publishing start date on an annual frequency:

1. When there are already published list(s) in the window (see example with the referral hospital master list (MOH)):
- The lists that were already in the window remained while they should have been removed
- The starting date actually implemented is 31-Dec and not 15-Mar

2. When there were no published lists at all in the window (see example of the community health worker master list (MOH)
- The lists that are published start from 2010
- The starting date actually implemented is 31-Dec and not 15-Mar

Here is what is expected when you enter 15-Mar-2010 as the publishing start date on an annual frequency:
![image](https://user-images.githubusercontent.com/12602163/103333075-8a95d080-4aa7-11eb-97e1-7ad014589b85.png)

The problem of the lists being published in the future remains (ticket #404)

**Comment by justinlewis** [comment]
I had a discussion with CHAI that had some relationship to this and so I'm moving this to Sprint 14 so that there is time to discuss further.

**Comment by justinlewis** [comment]
@steeveebener 

For #1 of your last comment I don't think what you're seeing will be an issue because this is migration issue where there is a reference to the older lists that where created before this change. Since you're rebuilding the Demo data and Laos is starting fresh there is no production data that would have this reference. There isn't a need to add functionality to delete old lists becuause this should never happen again unless we add the ability to edit list definitions. 

For #2 it seems like you're asking more for the ability to set a date range representing the frequency periods. For example, rather than the hard coded assumption we currently have (annual Valid On date being Dec 30) someone would specify annual where the annual range is 15-mar to 30-dec (or any date later than 15-mar but sooner than 366 days from 15-mar)?

**Comment by SteeveEbener** [comment]
As discussed with Nate we are talking about two different ways to generate a series:
1. Based on a given frequency (annual, quarterly,...) starting from a given date => Valid on
2. Based on iuntervals that would be manualy set by the RA/RM => Valid for

The present ticket refers to the 1st option only => we should not be talking about intervals. In this regards, the problems that remains are as follow:
a. The date for which the lists are generated are still not corresponding to the publishing start date (we will actually have to change thisw terminology once we move to the new design). If you specify  January 1st, 2010 as the publishing start date you still get lists valid on December 31
b. Once you published a series, you can go back to the metadata and edit the publishing frequency and publishing starting date (I put it to 15 March 2010 for example) + submit it => no message appearing saying that there was an issue. If you then go to the published section for that list and click "Publish lists" the process run but you still get the same series all published for December 31st of each year

=> what needs to be fixed here is:
1. The date for which the list is published corresponds to the publishing starting date, not the day before that
2. There is no lists being included for a date in the future in the series
3. We have the possibility to delete all the lists part of a given series with a unique button instead of one by one
4. Either we can't change the publishing frequency and publishing start date in the metdata once it has been fixed or we can still change it but this then result either in: a. replacing the current series based on previous information; b. adding the new instances to the one already in the series

**Comment by rrowlands** [comment]
> 1. The date for which the list is published corresponds to the publishing starting date, not the day before that

Is this issue still happening? If so, what time zone is it occurring in?

**Comment by SteeveEbener** [comment]
@rrowlands . There might have been a misunderstanding at some point because this is not the expected behavior.

We are not talking about a period here as many changes might have happened between each instance of list (especially on a yearly frequency) but about a specific date => What the user is specifying is the date for which the instances are being created.

If I enter 01.01.2000 on a yearly frequency I want to have the first instance to be for 01.01.2000, the next one will be for 01.01.2001,.... and not the day before.

If someone wants to have a list being published for each 31st December then it should enter that date in the metadata.

=> This has to be modified

Thanks

**Comment by SteeveEbener** [comment]
Just tested under 0.18.0 and the problem is still there. 

The instances are created for the day before the frequency start date

**Comment by jsmethie** [comment]
No longer valid with new list design

**Comment by justinlewis** [comment]
Reopened to serve as the ask to change the logic for how frequency start dates are handled. See this comment: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/788#issuecomment-1171731645

**Comment by SteeveEbener** [comment]
This ticket can now be closed as #788 has been addressed
