### ISSUE TITLE
Importer : Including context of parents in a different hierarchy

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#266]
Consider the hierarchy from:

#220 

as:

Administrative Divisions (Ministry of Home Affairs):
1. Region (MOHA)
2. Province (MOHA)
3. County (MOHA)
4. Shire (MOHA)

Ministry of Education (Ministry of Education):
1. Region (MOHA)
2. Province (MOHA)
3. County (MOHA)
4. Shire (MOHA)
5. University (MOE)

If you import a spreadsheet into University as a RA of Ministry of Education, and you also provide context columns for Region, Province, County and Shire, then the import will fail saying that it cannot find the parent context columns (even though the labels should match just fine). This happens because the importer is trying to find the parent as part of the Ministry of Education hierarchy, however the relationships only exist in the Administrative Divisions hierarchy and the importer does not know that.[https://app.zenhub.com/files/142912671/52b3ebfc-3ed9-46e1-b6e2-370645b89e8c/download](https://app.zenhub.com/files/142912671/52b3ebfc-3ed9-46e1-b6e2-370645b89e8c/download)

**Comment by rrowlands** [comment]
[https://app.zenhub.com/files/142912671/dd42a235-ef08-48b5-9abb-7bee67301655/download](https://app.zenhub.com/files/142912671/dd42a235-ef08-48b5-9abb-7bee67301655/download)

**Comment by rrowlands** [comment]
Also discussed during the phone call:

1. Implement the ability in Master lists to display parents of parents transitively from other hierarchies.
2. Hierarchy management -> Visually show the transitive parents from other hierarchies when defining your hierarchy.

**Comment by rrowlands** [comment]
Worth additional consideration:

1.The system allows you to import into University in this scenario, however the system could easily check to see if there is data at the Region / Province / County / Shire levels and in theory we could bark at the user and tell them that they're doing the import in reverse (i.e. you should start at importing data with the Region first, and then Province, etc.).

2. The usecase for allowing people to only create relationships between (for example) Region and Province (when Region and Province are in a different hierarchy) is confusing when using the spreadsheet importer. This is because you're importing instance level data for creating objects, however the only purpose for the import is to create just the relationships.

**Comment by jsmethie** [comment]
This doesn't seem relevant anymore with support for inherited hierarchies

**Comment by rrowlands** [comment]
I am not convinced that this ticket is no longer relevant.

Using the current data on the demo instance, with the following MOE hierarchy as:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/9ec7d447-dbb9-4852-ad59-e5e4b599d5cf)

I am attempting to import the following spreadsheet:

[https://app.zenhub.com/files/142912671/434edf40-21b4-4555-8079-684fa97a869d/download](https://app.zenhub.com/files/142912671/434edf40-21b4-4555-8079-684fa97a869d/download)

Which produces the following error:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/d235e6af-695a-44d3-9e5a-53e54f28c433)

The problem here is that the importer is not finding that object, not because it does not exist, but simply because it is searching in the wrong hierarchy.

**Comment by SteeveEbener** [comment]
I have just experienced the same thing during another import. When a situation like this happens we should indeed have a message guiding the user towards starting the import from the higher node in the hierarchy

**Comment by rrowlands** [comment]
There were quite a few additional concerns and considerations which were added to this ticket during various meetings / calls. Most of the concerns were made obsolete due to other changes that were made in the system since this ticket was created. The concerns that were not obsolete were added to the Inherited Hierarchy Additions #542 epic.

**Comment by rrowlands** [comment]
If this ticket is implemented, #541 should also be considered.
