### ISSUE TITLE
User Role Management

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#27]
Administrators can define registry maintainer (RM) and registry contributor (RC) roles for GeoObject Types. 

Epic documentation and user stories: [Shared Google Doc](https://docs.google.com/document/d/19LcXKsgGTvDd6lqPYrEVY4d1FtTwGcGSl7n0LBrN3gs/edit#)

Sketches can be found [here](https://www.lucidchart.com/documents/edit/c70be9eb-80e3-4d44-ac61-9aca8d70fc89/0_0#)

**Comment by dtreatman** [comment]
Question: should user roles be able to be designated to a subset of GeoObjects for a single GeoObject type? For example, should an RA be able to allocate the RM role for ONLY the Bokeo province for GeoObject type "Province" to a provincial officer for Bokeo, and have the officer's role be limited to RC or AU?
