### ISSUE TITLE
GeoObjectEditor : Setting the parent of the root node

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#274]
The GeoObjectEditor widget allows you to set the parent of the root node in a hierarchy. You are allowed to create a new relationship and give it a time period, however the value selection is empty. When this is submitted and then viewed later via edit, any time periods that you may have created are not displayed, which may indicate that they were not saved in the database.

Do we want to hide the parent tab all together when a GeoObject is the root in it's hierarchy?

**Comment by SteeveEbener** [comment]
I am guessing that the GeoObjectEditor is the window that opens when you edit a geobject in a given list and that the root node is the highest node of the hierarchy, right?

If this is the case, the RA or the RM should indeed not be able to add a new parent to that root node (like it is currently the case in the GeoObject &Hiearchies module) and the parent tab should ideally be hidden.

**Comment by rrowlands** [comment]
> I am guessing that the GeoObjectEditor is the window that opens when you edit a geobject in a given list and that the root node is the highest node of the hierarchy, right?

Yes, this is correct.

**Comment by rrowlands** [comment]
This ticket was implemented as part of the Change Request work.

The solution can be seen in this screenshot:
![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/adbabc54-e36c-44de-b8d6-677107b2e595)

**Comment by SteeveEbener** [comment]
For information, I initiated a user feedback to change the message appearing in this case.

Suggestion: "This geo-object is at the top of this hierarchy. Parent selection is not necessary"

**Comment by justinlewis** [comment]
@rrowlands I updated this localization XML It will be in the next release.
