### ISSUE TITLE
Edit vs metadata/view icon

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#275]
## User stories
1. When I see the edit icon (pen) as a user (independently from my role) I am expected to be able to make modifications in the window that will open while, sometime, I am only authorized to view the information in the window in question

## Problems this relates to
1. Difference of rights between roles

## Proposed solution
Two options:
1. Use a different icon than the pen when the information in the window that is being opened can only be viewed (this would require for the icon to be different depending on the role. Example: RM can edit => pen; RC can't edit => other icon)
2. Use a "metadata" or "view" look button (see example in the additional context section) instead of the pen one, the capability to edit what is in the window that opens would then be based on the role. 

## Considered alternatives
1. See previous section

## Additional context
![image](https://user-images.githubusercontent.com/12602163/83698043-05425e80-a633-11ea-91d3-22ea41684632.png)

**Comment by SteeveEbener** [comment]
Implemented in the GeoObjects & Hierarchies module but not in the lists one

**Comment by justinlewis** [comment]
There's a different ticket for the list page:
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/302

**Comment by justinlewis** [comment]
There's a different ticket for the list page:
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/302

**Comment by SteeveEbener** [comment]
#302 does only cover the RC role and was not talking about changing the "edit pen" icon into the  "view" one in this case. Would you like me to change #302 to cover the issue for the all lists module?? I am asking because it is attached to sprint 10

**Comment by CarlyNel** [comment]
@SteeveEbener @justinlewis Are we still waiting for confirmation on Steeve's last comment above or are you both happy with the details provided in ticket [#302](https://github.com/terraframe/geoprism-registry/issues/302) in which case this ticket can be closed?

**Comment by justinlewis** [comment]
@steevebener No need to edit this ticket. We can use the other ticket to address the lists behavior.

**Comment by SteeveEbener** [comment]
I have adjusted #302 to address my question and we can therefore close this ticket
