### ISSUE TITLE
External systems configurations - front end

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#279]
See this document for additional context:

https://docs.google.com/document/d/1-jW953CL1UyxFHmko1SCRHNikbzdb1O9yvxZxXpVp_k/

The CGR will have an abstraction for representing external systems with which the CGR will integrate. This abstraction can be extended to add support for additional systems.

These classes will be defined as MdVertex classes, as instance data in the graph will need to reference them. The root abstract class will store the login credentials for the external system. Abstract methods will be implemented with the platform specific behavior, such as establishing a connection with a DHIS2 instance. A connect() method is listed in the UML class model above, but that is just a suggestion. The methods communicating with an external system will need to be defined and will most likely change through iterative development.

**Front end**
Create a user interface that will allow a user to create, read, update, and delete External System records. It is yet to be determined whether this will be a function of the SRA or RA role. Place a link to this functionality in the appropriate place on the settings screen.

**Comment by CarlyNel** [comment]
Hi @nmceachen,

In chatting with Derek, he feels that this should be the function of the RA given that the individual responsible for other external systems would typically be the RA for a given organization and not the SRA. @SteeveEbener would you agree with the above?

@justinlewis was this clarification the blocker on this ticket?

**Comment by SteeveEbener** [comment]
Agreed regarding the need for the API to be managed at the RA as it will be linked to GeoObject types managed by a given, or a set of organizations

**Comment by CarlyNel** [comment]
Thanks Steeve.
