### ISSUE TITLE
Can't remove GeoObjectType from hierarchy if data is associated with it 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#284]
**List the CGR version information**
- CGR version: 0.6.2

**Describe the bug (clear and concise)**
This error is thrown:
- "Cannot modify the GeoObjectType [Zambia] because it has associated data."
When trying to remove a node from a hierarchy even if no relationships have been built against it in this hierarchy.

**To Reproduce**
1. As a an SRA go to the hierarchy management page.
2. Create a new hierarchy
3. Build a new basic hierarchy (country -> province -> district -> commune) using existing GeoObjectTypes in the system which have had data uploaded to them in the past.
4. DON'T upload any data to your new hierarchy.
5. Try to remove a node from the hierarchy.

**Expected behavior (clear and concise)**
For it to be removed because I've not uploaded data to it or built any relationships (parent / child) using other mechanisms (e.g. change requests). 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version:

**Additional context (if any)**
This was done on production.

**Comment by SteeveEbener** [comment]
@justinlewis in: the SRA should not be able to create, edit or delete a GeoObject Type or a hierarchy => Are you referring to the RA role?
