### ISSUE TITLE
Status does not display properly in GeoObjectEditor widget

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#286]
When creating a new GeoObject, the status field does not correctly populate the dropdown once selected. This is purely a graphical bug however, because the internal elements are correctly populated and the value is correctly sent and retrieved from the server.

To reproduce: create a new GeoObject and select a value for the status field.

**Comment by CarlyNel** [comment]
Hi @rrowlands Please forgive me if I'm doing this incorrectly (I'm still learning), but I've tried to test this and have followed these steps:

1. Logged into Staging as MOH-RA
2. Navigated to the Referral Hospital Master List - Exploratory tab
3. Clicked "view" on the first list
4. Clicked "AddGeoObject"
5. Filled in a GeoObject Unique ID
6. Scrolled down to status and clicked "edit"
7. Clicked "+ new version"
8. Selected a start date of 10 June (after which the panel turned green) and left the status as "active"
9. Selected "ok"
-> The AddGeoObject window is still showing a blank bar for the status (see below)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/60e517c5-9cd1-47eb-b37b-5ba50731f6f4) Could you please confirm whether this is what is supposed to populate in the below window?

**Comment by SteeveEbener** [comment]
@Carly: I don't know if this will help but the RA from MOHA should not be able to edit a GeoObject type under the curation mandate of the Ministry of Health (MOH) like Referral hospitals => the add GeoObject type button should not have appeared in this case (a bug to be reported). This does also related to ticket #302 I submitted few days back.

What is happening when you are trying to do the same thing with a GeoObject type under the curation of MOHA?

**Comment by rrowlands** [comment]
@CarlyNel Do you know what the "for date" was selected as at the bottom of the widget? I ask because if your "for date" is set as before the data which you had entered (in this case, June 10) then the expected behavior is that the data would not be displayed in the widget (even though you just entered it). You would be able to see your newly entered data if your "for date" is either at or after the date at which you entered data.

I'm going to close this ticket for now (as this ticket was about a different bug), but we can reopen it if my assumption about date filtering was incorrect.
