### ISSUE TITLE
Terminology consistency when adding a new attribute to a GeoObject type

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#298]
## User stories
1. As a RA it would be nice if the terminology used to add a new attribute to a GeoObject type would be consistent across windows.

Right now, when I add a new attribute:
- In the “Manage Attributes” window the button specifies ”+Add”
- The table in the next window is then labelled “Create attribute” 
- The title on top of the attribute types is itself labeled “Define a new attribute”

## Problems this relates to
1. Terminology consistency across the CGR 

## Proposed solution
1. Use "Add" across all the above mentioned windows

## Considered alternatives
1. None

## Additional context
None

**Comment by justinlewis** [comment]
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/04f63eaf-6035-4c74-bc27-81db8407b9cd)

**Comment by SteeveEbener** [comment]
Tested under 0.15.2 and implemented. I am closing this ticket
