### ISSUE TITLE
A RA should see the other organizations in the settings

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#301]
**List the CGR information**
- CGR version: 0.8.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The RA of organization A can't see the information about the other organizations

**To Reproduce**
As the RA
1. Go to settings 
2. See error: the other organizations are not visible to the RA

**Expected behavior (clear and concise)**
The RA of organization A can see the other organizations as per the rights by role google spreadsheet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context (if any)**
- Extracted from issue #252 
- link to epic ticket #285

**Comment by justinlewis** [comment]
This was done in the last release when a dev used the matrix to tighten up some work on the roles matrix.

**Comment by SteeveEbener** [comment]
The RA can indeed see the other organization now but does not have access to all the information that would allow him to contact such organizations => shall we capture this in a separated ticket as this is actually linked to the SRA role?

**Comment by justinlewis** [comment]
@steeveebener Yes that would be great if we create a new ticket for it.

**Comment by justinlewis** [comment]
@steevebener That would be great. Can you please create that?

**Comment by SteeveEbener** [comment]
Captured in ticket #466. I am closing this ticket
