### ISSUE TITLE
Edit column header and pen icon should be replaced by another icon for  organization and roles not having editing rights on a list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#302]
**List the CGR information**
- CGR version: 0.13.1
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The RA, RM and RC can see "edit" as the column label  and the edit pen next to GeoObjects in lists for which they do not have the editing rights

**To Reproduce**
As the RA,RM, RC for organization A
1. Go to the list module 
2. View the list for a GeoObject type from another organization
3. See error: the "edit" column and pen is appearing in the list (see screenshot below)

**Expected behavior (clear and concise)**
The header of the column does not read "edit" and the edit pen appearing next to the GeoObjects is replaced with another icon for lists over which the user does not have the editing right

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/105171437-3091a380-5b59-11eb-8b03-9c389793dd99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Checked and working. I am closing this ticket.

**Comment by SteeveEbener** [comment]
I am re-opening this ticket as the edit mention and edit pen is back in lists over which the user does not have the curation mandate as per the following example (list curated by the MOE when viewed by a MOHA user):
![image](https://user-images.githubusercontent.com/12602163/103402978-87731100-4b89-11eb-9b88-3647a7b155a1.png)

**Comment by justinlewis** [comment]
Admin view
![Screenshot from 2021-02-16 22-00-52.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/00f3e8ac-493b-44e3-986c-8ee95f11bdf9)

RC view
![Screenshot from 2021-02-16 22-00-16.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/405837bb-759e-4bc6-b2d3-c8be1b35442d)

**Comment by SteeveEbener** [comment]
Thanks @justinlewis 

Remains the question of the column header that still reads "Edit" in both cases. What about replacing this by "Action" which would also work when adding the icon for deleting a complete record?

**Comment by justinlewis** [comment]
@SteeveEbener good catch. I just changed it to Action

**Comment by SteeveEbener** [comment]
Tested under 0.14.0 and working. Closing this ticket
