### ISSUE TITLE
Submit button activating despite required reason field not filled out

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#303]
The submit button becomes active while the "Reason" field has not been filled while mandatory. This is when submitting a change request from the standalone change request form.

**Comment by CarlyNel** [comment]
I'm logged in as an MOH-RA and can confirm that the Submit button only activates after I have typed something in the mandatory "reason" field. Closing this ticket.

**Comment by SteeveEbener** [comment]
What about the RM (even if this functionality should normally be removed to him (see rights by role google spreadsheet) and the RC role?

**Comment by CarlyNel** [comment]
I can confirm that it works correctly for both the RM and RC role too.

**Comment by SteeveEbener** [comment]
Thanks Carly

**Comment by SteeveEbener** [comment]
This ticket needs to be re-opened as per what has been reported in ticket #506
