### ISSUE TITLE
Frequency and Start Frequency dates to be visible

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#305]
Request from Steeve:

This is within the context of [ticket #81](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/81) around changing labels within the Master List Manager.

"The problem is that the CGR is not currently creating all the instances of the published list based on the publishing frequency being specified when you create the master list. Once this has been corrected...... it would be useful if the Frequency and Start Frequency date would appear on this page to inform the user."

## User stories
1. 

## Problems this relates to
1. 

## Proposed solution
1. 

## Considered alternatives
1.

**Comment by CarlyNel** [comment]
@SteeveEbener could you please flesh the details of this ticket out for TF? Thank you.

**Comment by SteeveEbener** [comment]
@Carly. This issue is already capture in ticket #265

**Comment by CarlyNel** [comment]
That's great! Thanks Steeve. I'll go ahead and remove this ticket.
