### ISSUE TITLE
Changes to the ShapeFile Buttons in the List Modules

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#306]
Request from @SteeveEbener

This request came off the back of [ticket #81](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/81) about labels in the Master List Manager.

"I remain very disturbed by the presence of the “publish shapefile”  and “download shapefile” button in this view and this for the following reasons:
o  If ever this should remain in the list module (still not convinced about this, at least not for polygons format GeoObject types) this should be available once you see the list and not before that
o  Having the possibility to download the shape file will depend on the redistribution rights attached to the lat/long fields in the case of points format GeoObject types and to the shape file in the case of polygon format GeoObject types
o  This option is not available from the exploratory section"

**Comment by CarlyNel** [comment]
@SteeveEbener @justinlewis @dtreatman I've created this ticket for further discussion/clarification/agreement before work on this can continue.

**Comment by justinlewis** [comment]
Closing as this is out of date and will not be relevant with the planned changes to lists and spatial data.
