### ISSUE TITLE
As an RA I need to see who the SRA is for a CGR instance

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#307]
One option proposed by @steeveebener is to put the SRA information as a new section under setting (before "Organizations").

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.

**Comment by SteeveEbener** [comment]
This ticket remains applicable for the system admin role => included as feedback 78 in the google spreadsheet
