### ISSUE TITLE
Display label (Name) and Status field not mandatory when adding a new GeoObject

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#311]
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When adding a new GeoObject to a list:
- The "Default locale" and "Status" field are not mandatory (see screenshots below)
- The "Status" field is set to inactive by default which is not necessary what the user wants

**To Reproduce**
As a RA/RM:
1. Go to the lists module
2. Click on a list for a Geo-Object type on which you have the curation module 
3. Click "Add Geo-Object"
4. See errors in the modal: the Default local and status fields are not mandatory (the only mandatory field is the Geo-object unique ID

**Expected behavior (clear and concise)**
The default local and status fields appear as mandatory and have to be field before being able to add a new geo-object

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/103403769-492b2100-4b8c-11eb-9158-1313529833bc.png)

![image](https://user-images.githubusercontent.com/12602163/103403789-5f38e180-4b8c-11eb-9710-6f86fcaf7a81.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context (if any)**
None

**Comment by justinlewis** [comment]
I think there is some confusion:

`There is no data entry field for adding the GeoObject Name (label), just the edit button (see first screenshot below)`
- The edit button opens up the change over time modal to enter one or more labels by time. So this is how you add a name.

`The "Status" field is not mandatory (see first screenshot below). The submit button becomes active while not filling it but then the error message reported in the second screenshot appears (A problem occurred and your operation could not be completed. [Display Label] requires a value. [Status] requires a value.)`
- The error you listed here says there are two required values. The [Display Label] error is correct if you didn't add a version of the label (see my comment above). However the [Status] error is a bug where we need to show it as required in the frontend.

`You loose all what you have entered after clicking the "Close" button of the error message`
- This seems like a bug.

**Comment by SteeveEbener** [comment]
The information provided on the first issue wasn't clear, sorry for that. 

What I meant is that it is confusing not to have an empty field appearing in the space for the  "GeoObject Name (label)" attribute while such empty field appears for any of the other fields that also require to go through the change over time modal.

Object name field:
![image](https://user-images.githubusercontent.com/12602163/90197459-4ad49200-de01-11ea-9754-428c441dc314.png)


Other fields:
![image](https://user-images.githubusercontent.com/12602163/90197488-5e7ff880-de01-11ea-97b6-a7b49d518c57.png)

I hope it is clearer this time. My apologies once again.

**Comment by SteeveEbener** [comment]
I have updated this ticket to match the new geo-object modal

**Comment by SteeveEbener** [comment]
Going through this ticket again, I realize that this is part of a bigger issue which is to have the possibility to capture which fields should be mandatory when adding a new geo-object => ticket #299. I am closing this ticket
