### ISSUE TITLE
Administrative divisions options not appearing and empty windows opening when trying to define the parents of a new GeoObject

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#312]
**List the CGR information**
- CGR version: 0.8.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
When adding a new GeoObject in the list of Universities, I needed to specify the parents according to a hierarchy that connect such University to the Administrative divisions managed by MOHA but:
- While the Region, Province, County and Shire fields are appearing under "value" there are no options attached to them (no dropdown appearing when clicking on the field) - First screenshot below
- I could enter dummy text in each fields and click the submit button. After doing this I go a window with empty fields and no text (second screenshot)
- I could nevertheless click the submit button which led me to an empty version of the "Manage Values over time" window - third screenshot below. I could then click ok but nothing happened

**To Reproduce**
As the RA/RM of an organization managing infrastructures like schools/health facilities
1. Go to the lists module
2. Open the list for one of the GeoObject type on which you have the curation rights
3. Click on the "Add GeoObject" button
4. go to the "Parents" tab
5. Clik the edit button for the hierarchy linking the infrastructure with the administrative divisions
6. Click the "+New version" button
7. Click in the Region Field => first error: no dropdwn appearing 
8. Enter some dummy values in each field and click Ok
9. Other errors: the empty windows mentioned in the bug description are appearing

**Expected behavior (clear and concise)**
You can link the New GeoObject to the the GeoObject managed by another organization as per the hierarchy you have defined

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/85100887-c962e800-b233-11ea-9d6c-f323e4dfabbf.png)

![image](https://user-images.githubusercontent.com/12602163/85100947-ebf50100-b233-11ea-84e2-bfcf078c9006.png)

![image](https://user-images.githubusercontent.com/12602163/85101054-1a72dc00-b234-11ea-84e0-fbfe0e5386d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context (if any)**
- this issue relates to the possibility to create hierarchies containing GeoObject types managed by different organizations and the dynamically link that should remain between these objects as illustrated in the following slide: https://docs.google.com/presentation/d/1Xw2_rspUmFzEB2JWNqph2a_6MvC4WA_RM2N21USuqlA/edit?usp=sharing 
- Linked to tickets #220 and #259

**Comment by justinlewis** [comment]
In step 7 above the field is a search input. Can you try typing some text to see if the search is returning results that you know should show up?

**Comment by SteeveEbener** [comment]
I did that and nothing is appearing.

This issue is somehow also linked to the comment I have just included in ticket #341 as the use of a search instead of a dropdown is really not practical (see reason in that ticket)

**Comment by justinlewis** [comment]
@steeveebener Are you able to try this again? A lot has changed since you last tested this.

**Comment by SteeveEbener** [comment]
We can indeed close this one. Doing that now
