### ISSUE TITLE
Missing the possibility to manually type or edit the geographic coordinates in the Lat/Long fields

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#317]
## User stories
1. As a RA, RM or RC I would like to be able to manually enter or edit the geographic coordinates associated to a point type GeoObject in the geometry window without having to do that using the map.

This would also allow the user to see these coordinates directly in this window

## Problems this relates to
1. None

## Proposed solution
1. Add the possibility to manually type/edit geographic coordinates as per the screenshot below

## Considered alternatives
1. None

## Additional context
![image](https://user-images.githubusercontent.com/12602163/85188751-95db9880-b2db-11ea-944d-4678639aa911.png)

**Comment by vrajasekaran18** [comment]
@justinlewis Just to check the scope of this ticket:
1. Will this include the ability to validate the coordinates entered?
2. Once coordinates have been manually entered, will the map update to show the point on a map (probably only for RM/RA edits)?

**Comment by SteeveEbener** [comment]
Hi @vrajasekaran18 Varshana. If I may:
1. What do you mean by validate?
2. The point should indeed appear on the map and this even for the RC during the submission of a change request

**Comment by vrajasekaran18** [comment]
@SteeveEbener sure!
1. I'm going to butcher the GIS terminology, but I guess we would want to validate that the coordinates entered is valid? E.g. Is there enough number of characters? So where if something should be an email address, you can validate it has the @ sign? 
2. Agreed so they can at least see what it looks like!

**Comment by SteeveEbener** [comment]
Hi @vrajasekaran18.

No worry with the butchering :) 

Thanks for your feedback.

When it comes to geographic coordinates, the only thing you could check is if the latitude is between -90 and +90 decimal degrees and the longitude between -180 and +180 decimal degrees.  

We should maybe discuss if we were to enforce tests on other attributes like the email address for example

**Comment by SteeveEbener** [comment]
Tested under 0.15.2. It is indeed now possible to to manually change geographic coordinates for point type geo-objects. I am just wondering why we need to click the "show" button to see the coordinates

**Comment by justinlewis** [comment]
It follows the same behavior as the geometry in the map. Clicking show displays the geometry in map form and coordinate form.

**Comment by SteeveEbener** [comment]
I saw that. My question is why do you need to click one more button to see this information? I thought we are trying to reduce the number of clicks the users have to do to reach an information

**Comment by rrowlands** [comment]
This is because there can be many different geometries for many different time ranges. If we were to render all of them at once it could potentially be very confusing and overwhelming.

**Comment by SteeveEbener** [comment]
Hi Richard. I was only referring to the instance of the information corresponding to the date for which the list has been generated.

It would indeed not be practical for all the instances to be visible once you reach the editing modal. Cheers.

**Comment by SteeveEbener** [comment]
Just tested under 0.17.2 and you still need to click the "show" button for the lat/long field to appear in the modal.

In addition to that, the lat/long fields are disappearing when you click on another period in the history bar. 

=> I still maintain that the lat/long fields should appear automatically for the instance you are looking at

**Comment by SteeveEbener** [comment]
Tested under 0.18.1 and the issue remains

**Comment by rfromthecastle** [comment]
Tested on v0.19.3 and this works for me.

**Comment by justinlewis** [comment]
@steeveebener Regarding this

> Just tested under 0.17.2 and you still need to click the "show" button for the lat/long field to appear in the modal.

Are you saying that if we show it in an un-editable mode that this would be more efficient to understand the point location?

I say un-editable because to edit any geometry you need to click the show button. So iditing the geometry on the map and the lat/long directly would follow the same user behavior for being able to change the data. 

In regards to this 

> In addition to that, the lat/long fields are disappearing when you click on another period in the history bar.

That's because currently they display when in edit mode (after clicking show). When you change the display via the history bar we close that edit session.

**Comment by SteeveEbener** [comment]
@justinlewis 

Yes to "Are you saying that if we show it in an un-editable mode that this would be more efficient to understand the point location?"

This would also allow the user to directly copy/paste the lat/long without having to put the geo-object in the edit mode. This is particularly needed when the user is looking at a geo-object under the curation of another organization for which the spatial data is public.

Right now the suer can't see the left tab with the detailed information (don't understand why), only the pop up and it does not contain the lat/long

![image](https://user-images.githubusercontent.com/12602163/175180005-e3f7f743-e501-49f4-b34d-6dc2df2b49f0.png)

**Comment by justinlewis** [comment]
All this makes sense. We can show the lat/long for all points even when not in edit mode. 

> Yes to "Are you saying that if we show it in an un-editable mode that this would be more efficient to understand the point location?"

> This would also allow the user to directly copy/paste the lat/long without having to put the geo-object in the edit mode. This is particularly needed when the user is looking at a geo-object under the curation of another organization for which the spatial data is public.

For this:
> Right now the suer can't see the left tab with the detailed information (don't understand why), only the pop up and it does not contain the lat/long

to show the left tab you need to push edit on the popup but I don't see the edit button so you may be looking at a geometry you don't have edit rights to?

**Comment by SteeveEbener** [comment]
**All this makes sense. We can show the lat/long for all points even when not in edit mode.**

=> Great. Thanks in advance for that

**to show the left tab you need to push edit on the popup but I don't see the edit button so you may be looking at a geometry you don't have edit rights to?**

=> Correct, that was the point I am trying to make. You can't see the coordinates unless you have the editing right while the data might be public, meaning that you should be able to see it.

**Comment by justinlewis** [comment]
@steeveebener I think this is resolved with the new list design. Note the screenshot here that includes the lat/long.

![Screenshot from 2022-12-15 14-09-24.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/83f104f4-faf4-4099-b356-de121b8c24fc)

**Comment by rrowlands** [comment]
Agree with @justinlewis however I can also see the utility of not requiring being in edit mode to see lat/long. Lat / long should now be visible when not in edit mode as be8d05c669174dc94ef64def0c262bfc23be8cf4.

**Comment by SteeveEbener** [comment]
Tested in stagging and working. Closing this ticket. Thanks
