### ISSUE TITLE
Organization dropdown in external system registration showing organizations the RA doesn't have authority over

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#318]
**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
Organization dropdown in external system registration showing organizations the RA doesn't have authority over. An RA only has mandate over one organization so any external system they register can only be accessible to that organization. 

**To Reproduce**
1. As an RA go to the Settings page
2. Click on the button to register a new system
3. Open the dropdown for organization. 
3. The bug:  Organizations that you are not an RA for show up as options. 

**Expected behavior (clear and concise)**
Only a single option which would be the organization the RA is part of. Better yet the RA should not need to select the option at all. Rather we can just set it.

**Screenshots**
![Screenshot from 2020-06-19 21-31-01.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/b54916da-a1d9-4ee4-806d-f22b2bef9e94)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by CarlyNel** [comment]
Hi @justinlewis I've just tested this and it appears to be working.

I'm an RA for MOHA only:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/c763664e-7e58-48b3-ac35-adf3232fa812)

When setting up a new external system, I am only able to see MOHA as an option in the organization:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/6196f9eb-9f48-4043-b682-28f70d407eac)

Marking this ticket as done.
