### ISSUE TITLE
Change the terminology in the import module

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#319]
Here is the list of terms and sentences which I think we should modify across the import module:

1. map/mapping into match/matching (map/mapping should only be in relation to geographic mapping a platform dealing with geography, geospatial data and/or geospatial technology)
=> example: “Match the GeoObject Type attributes to the imported file columns”

2. “Source file” into “imported file” 

3. Find an alternative to “parents” because we will have a growing issue with the “mother” concept in the COT context. In relation to that:

- (4) “Optionally specify parent” into “Hierarchy matching (optional)”

- (5) “Map the source file columns to the parents location” into “Match the different levels in the hierarchy to the imported file columns” (also reversing the sentence to homogenize with the previous windows)

6. In the currently labelled "Optionally specify Parents" window: change "Source" with "Imported file column"

**Comment by justinlewis** [comment]
List of items from the description
- [ ]  #1
- [ ]  #2
- [ ]  #3
- [ ]  #4
- [ ]  #5
- [ ]  #6

**Comment by justinlewis** [comment]
Regarding “Source file” into “imported file” - The file is not fully imported yet. The matching steps we're talking about here are configuring the system to do the import.

**Comment by SteeveEbener** [comment]
@justinlewis . I just realized that 4 and 5 were not clearly appearing as sub-bullet point from 3, my bad => I have adjusted that. 

Regarding #2 and #6, I think that we should indeed use "Imported file" if we use it for #1 and #5 and, but I might be reaching the limit of my English here, when I read "source" I think "reference" and therefore CGR => is it really not correct to use "imported file" even if it still not being imported? needing the help of native English speakers here :)

**Comment by justinlewis** [comment]
Ok. So it sounds like by addressing 4 and 5 it also addresses3?

Source is commonly used to describe the origin of a thing. For example, "the source of the problem is..." or "what's the source of this data?". So saying "source file" makes sense in this case because we're saying "the source file column maps to the destination column".  Also notice I used "maps". This is common as well. I think 'matches works with your suggested changes but it's more common (in my experience) to use 'mapping' for phrases like my last example.
--- I ain't no language specialist though ya hear.

**Comment by SteeveEbener** [comment]
Yes, 4 and 5 are sub-bullet points of 3.

I hope for other people's inputs regarding the other point. For me, I keep having to think few seconds when using the import module to figure out if "source" refers to the content in the filer being imported or what serves as the reference for the matching, meaning the information stored in the CGR

**Comment by justinlewis** [comment]
I just got Pedro's opinion. Sounds like we'll go with "source" and change if users are confused.

**Comment by SteeveEbener** [comment]
Sorry to insist but I am a confused user and "demoer" :) 

I guess that this comes from the fact that we are very rightly presenting the CGR as being the "source of truth" => The source is for me what is already in the CGR.  When you import data you are importing it in the source of truth.

If you anyway decide to use "source file" what is then happening with bullet point #1 and #5?

Please also think about the translation in other languages....

**Comment by justinlewis** [comment]
For this release this is what I landed on based off of feedback from HGLC and Chai. Remember all labels can be changed through localization process. If any user of the system needs terminology like this changed to fit their cultural or linguistic expectations they can. 
- Match the different levels in the hierarchy to the source file columns.
- Match the Geo Object Type attributes to the source file columns
- Source file parent column
- Match Strategy
- Attribute Matching

![Screenshot from 2020-07-01 16-54-17.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/a4cf765c-ec5e-404d-871a-e3f690bc9088)

![Screenshot from 2020-07-01 16-56-30.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/21bea917-c9c3-492c-be81-db8b6b7d372c)

**Comment by SteeveEbener** [comment]
The second one should refer to "GeoObject" and not "Geo Object" (with space) to be consistent rest of the platform

P.S.: this actually needs to be adjusted in other windows as well

**Comment by justinlewis** [comment]
I created a ticket for this since you mentioned it's an issue in other places. Let me know what places those are and I'll update the description of that ticket:
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/373

**Comment by CarlyNel** [comment]
Hi @SteeveEbener, given that a new ticket has been created for the "GeoObject" spelling consistency which I see you have started adding to, are you happy to go ahead and close this ticket?

**Comment by SteeveEbener** [comment]
@Carly. Thanks for the message. I can indeed close this ticket
