### ISSUE TITLE
Exploratory section appearing for lists curated by another organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#322]
**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
A user from organization B has access to the exploratory section when viewing a list generated by organization A

**To Reproduce**
As any user from organization B
1. Go to list module 
2. Click on the "view" button for a list under the curation mandate of another organization
3. See error: the "exploratory" section is accessible to organization B while only the "published" version should be accessible.

**Expected behavior (clear and concise)**
As a user from organization B I should only see the "published" section viewing lists created by organization A 

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Additional context (if any)**
This is a rule stated in the rights by role google spreadsheet

**Comment by SteeveEbener** [comment]
Tested for the RA, RM and RC roles. The exploratory section is not appearing anymore for lists curated by other organizations. I am closing this ticket.

**Comment by SteeveEbener** [comment]
I have to re-open this issue as the exploratory section is again appearing for lists curated by another organization in v2 0.12.2 (staging)

![image](https://user-images.githubusercontent.com/12602163/101113834-3409b380-361b-11eb-8a30-d5000ccf1f86.png)

**Comment by justinlewis** [comment]
@SteeveEbener We'll try to get this in the next release.

**Comment by justinlewis** [comment]
Moving to Sprint 0.14 to track becasue this may be invalid with the planned changes to move toward the dataset centric UI.

**Comment by SteeveEbener** [comment]
The possibility to have access to exploratory lists should remain under the dataset centric UI

**Comment by SteeveEbener** [comment]
Just tested under 0.14.3 and the issue is still there. 

=> could we please fix this as it will still take some time for the new lists/spatial data module to be implemented?

Thanks

**Comment by jsmethie** [comment]
No longer valid
