### ISSUE TITLE
Home Page Icon Font Case

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#336]
Instance: 
- Staging - Firefox
- 0.8.0 on 19 June 2020

As any user, the icon names on my home page are in different font cases and not aligned.

I expected the icon naming convention to be consistent eg: all upper case or all lower case with a capital letter, and I expected all icons to be aligned/equal in size.

**Low Priority**

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/64028a20-0138-4447-ac8b-976eafe7ee38)

**Comment by justinlewis** [comment]
This is fixed with the most recent release

![Screenshot from 2020-07-15 21-18-15.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/bac6ca5a-a9e5-47ae-b571-98bca612b305)
