### ISSUE TITLE
Adding children to hierarchy

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#338]
Instance: 
Staging - Firefox
0.8.1 on 22 June 2020

1. As a MOH-RA I created a new hierarchy. 
2. I then wanted to add children.
3. I successfully added one but then could not figure out how to add more. I clicked on the “Province (MOHA)” (see screenshot) but nothing happened and I couldn’t find any other button which would enable me to add more.
4. I accidentally right clicked and saw the menu of options.

I expected to see a button informing me that I could “add child” or “remove” what I had just added.

Medium Priority

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/46738fc3-a258-435c-b653-846b88df4d3a)

**Comment by justinlewis** [comment]
Marking as invalid because you define the structure of the hierarchy (including adding children in the column to the right of this. Alsco because we're redesigning this page.
