### ISSUE TITLE
Space missing between "Manage" and the name of the hierarchy 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#344]
In the GeoObject types and Hierarchies module, a space is missing between "Manage" and the name of the hierarchy in the title of the widget on the right

**Comment by CarlyNel** [comment]
The spacing is now correct. Steeve, as this is such a minor change and I've included a screenshot for you to see, I'm going to close this ticket.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/c6de80b3-796e-4f3a-a914-78ff71af3754)
