### ISSUE TITLE
Inactive user account should be more clearly separated from the active ones

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#346]
## User stories
1. As the RA I want to clearly separate which user accounts are inactive from those that are active 
2. As the RM or RC I want to only see the active accounts for my organization 

## Problems this relates to
1. User account management

## Proposed solution
1. Have two separated tables: one for the active user account and one for the inactive ones
2. Don't show the table of inactive user account to the RM or RC 

## Considered alternatives
1. More clearly separate the two in the same table (change of color of the cells + put the inactive at the end)
2. Remove the inactive user accounts from the table

## Additional context
None

**Comment by SteeveEbener** [comment]
The inactivation is more obvious now but I would change the label and content of the column capturing this information as misleading.

Suggestions:
- Column label: "Status" instead of "disabled" (latter does not match the terminology used in the user account window anyway)
- Content: "Active" instead of "False"  and "Inactive" instead of "True"

**Comment by justinlewis** [comment]
I changed those labels described in the last comment but they won't be available till the next release.

**Comment by SteeveEbener** [comment]
Thanks Justin

**Comment by SteeveEbener** [comment]
Checked and implemented. I am closing this ticket.
