### ISSUE TITLE
Support for CSV import

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#350]
## User stories
1.  Support import of CSV file type 

## Problems this relates to
1.  Import of an XLS is currently supported, but XLS cells are limited to a number of characters. If a long list of vertices for a polygon is included in a cell (e.g., from a Reveal export), this list will be truncated. 

## Proposed solution
1.  Allow user to import CSV files

## Considered alternatives
1.  Current workarounds: upload shapefile instead, delimit the CSV files by comma to blow out the points by column and then save as XLS 
2. Develop support for upload of GeoJSON file

**Comment by justinlewis** [comment]
Closing since it's a duplicate
