### ISSUE TITLE
GeoObjectTypes and Hierarchies from other organizations not visible to RM

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#351]
**List the CGR information**
- CGR version: 0.8.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The RM can access the metadata but only the GeoObject types and hierarchies created by his own organization are appearing in the module while all of them should be visible as per the rights by role google spreadsheet.

**To Reproduce**
1. As an RM: Go to the hierarchy page
2. See error: see GeoObjectTypes that are part of other other organizations

**Expected behavior (clear and concise)**
RM, RC, and RA should see all GeoObjectTypes and Hierarchies but only the RA should be able to edit those that they have mandate over. They should only be able to view the metadata for any that are part of other organizations.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Might be good to change the title of the ticket to also include the RC role

**Comment by SteeveEbener** [comment]
I checked this ticket and it is implemented. It can be closed.
