### ISSUE TITLE
Error message on the Manage tab under Change Requests module

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#354]
**List the CGR information**
- CGR version: 0.9.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
I'm logged in as MOH-RA and clicked on the "Change Request" module. Whenever I'm on the "manage" tab within this module, the below technical-looking error pops up. I am however able to click on the "submit" tab without any issues, but then if I click on the "manage" tab again, the same error window pops up.

**To Reproduce**
1. As an MOH-RA  
2. Click on the Change Request Manage
3. See the error window pop up shortly after the page loads and whilst the page is showing info for the "manage" tab.
4. Click on the "submit" tab - see no error
5. Click on the "manage" tab again - see the error message again.

**Expected behavior (clear and concise)**
I should be able to click on the manage tab and not receive an error messages popping up.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/90f379ab-cb23-4441-988e-fa422e1927c5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 77.0.1 (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
@CarlyNel can you try to see if this is still an issue?  I'm guessing we won't be able to reproduce it after clearing the database recently. I think this was caused by some condition that left data in a bad state and the polling request that attempts to update the page every couple seconds is repeatedly failing.

**Comment by CarlyNel** [comment]
Hi @justinlewis I can confirm that this error is no longer popping up when I click on either the "manage" or "submit" tabs under the change request module. Feel free to close this ticket if you feel that this has subsequently been resolved.
