### ISSUE TITLE
User table does not reflect changes after an edit until the page is refreshed

### ISSUE THREAD

**Issue by jsmethie** [terraframe/geoprism-registry#355]
See title

**Comment by CarlyNel** [comment]
Hi @jsmethie Is this referring to the "user accounts" section? If so, I've just tested this -> edited a user, added a contact number and saved and the new number appeared straight away. No refreshing was needed so I can confirm that this is working correctly.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/824e73b4-3579-407d-8892-f9186ac557f7)
