### ISSUE TITLE
Pointer not automatically passing from the month to the year part of a date field

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#357]
As a user I would like for the pointer to automatically pass from the month to the year part of a date field like it is currently the case once you have entered the day (it automatically passes to the month)

**Comment by justinlewis** [comment]
Do you mean that the after you've entered all the required digits for month the cursor should automatiecally go to the next part of the date setting?

If so, the handling of date fields is entirely handled by the browser and any customization of that is significant for the value we will get out of it.  This should be very low priority or taken off the board to avoid impacting more critical functionality.

**Comment by SteeveEbener** [comment]
Yes to your question.

I thought this was an easy thing to fix as this is already the case when you have enter the day part (it automatically jumps to the month one).

Could this be linked to the date format used in the CGR or is it only linked to the browser?

I am asking this because of the issue captured in ticket #225  => would the issue be solved if the date was always captured as dd-mm-yyyy instead of dd-mmm-yyyy?

**Comment by justinlewis** [comment]
This is controlled entirely by your browser so the date format wouldn't affect it.

**Comment by SteeveEbener** [comment]
Ok. Something that we can't fix then. I am closing this ticket
