### ISSUE TITLE
Need for the top of a hierarchy to be another hierarchy 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#360]
## User stories
1.  As a RA I want to be able to link a specific GeoObject type to another hierarchy in order to 

## Problems this relates to
1. Master list
2. Import
3. Curation
4. Explorer

## Proposed solution
1. To allow for hierarchy A to serve as the top of hierarchy B

## Considered alternatives
1. 

## Additional context
   - I am creating this ticket to start the discussion on this topic which was touched upon during the CGR partner call on June 24th
   - The following schema  describes what is expected to happen at the import once this enhancement has been implemented: https://docs.google.com/presentation/d/1Xw2_rspUmFzEB2JWNqph2a_6MvC4WA_RM2N21USuqlA/edit?usp=sharing

**Comment by justinlewis** [comment]
This functionality will be part of [a larger ticket.](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/417)
