### ISSUE TITLE
Need the possibility to specify the status of the information when importing a spreadsheet in the CGR (active or inactive)

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#364]
## User stories
1. As a MOHA RA/RM I want to be able to easily inactivate a large number of administrative divisions from a given date because they have all been transferred to another parent and their unique ID is therefore changing (see example for the Tolkien Region in the  screenshot below)

## Problems this relates to
1.  Spreadsheet import

## Proposed solution
1. Add a field in the  Attribute matching window (import module) for the RA/RM to capture the status of the information that is being imported

Without this field, the inactivation has to be done manually one division at a time from the lists module

## Considered alternatives
1. None

## Additional context

In this example, the cells highlighted in blue shows Shire which are being transferred from one county to another on April 20, 2007 => change of their unique ID:

![image](https://user-images.githubusercontent.com/12602163/86505966-3ada9300-bdfd-11ea-8303-8ef58961f194.png)

**Comment by SteeveEbener** [comment]
This seems to be working. May I just know what the NEW, or PENDING status options are referring to before closing this ticket?

These options appeared when importing the excel file without following the correct spelling for the status information as per the following screenshot:

![image](https://user-images.githubusercontent.com/12602163/91266499-fee00080-e7a3-11ea-85ae-3f0bbd955ded.png)

Thanks

**Comment by justinlewis** [comment]
@steeveebener NEW and PENDING where added to support use cases where an object was not yet verified as active or inactive. These where defined with input from the wider DSME community in the first year of requirements gathering.

**Comment by SteeveEbener** [comment]
Thanks for the clarification. Closing this ticket
