### ISSUE TITLE
Need more than just the GeoObject name when managing parents over time

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#365]
## User stories
Changes in the administrative structure of a country requires to transfer infrastructures like health facilities from one instance of a given administrative divisions to another. 

In many cases, the administrative division that has been transferred keeps the same name but its code has changed.

=> There is a need for the unique ID attached to the concerned parents to also appear when changing the parents for the concerned infrastructure .

## Problems this relates to
1. COT

## Proposed solution
1. Add the unique ID of the parent in addition to its name "Manage values over time" window

## Considered alternatives
1. None

**Comment by SteeveEbener** [comment]
I can't figure out how to also access the GeoObject ID when specifying the parents => can someone please provide some indication on how it is supposed to appear? Thanks

**Comment by CarlyNel** [comment]
Hi @justinlewis and @jsmethie. Just flagging Steeve's above question as I'm sure you've come back to quite a few emails etc after your Thanksgiving break.

**Comment by justinlewis** [comment]
You can see the ID's attached to the labels in the input fields (example: Namibia : f45b9380-c970-4dd1-8533-9e95ab12f128)

![Screenshot from 2020-12-01 13-33-10.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/67b420f2-4fbc-485b-917c-2892df91fa32)

![Screenshot from 2020-12-01 13-31-46.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/55e8160c-6e3e-4385-9fd8-2ad5a008d6fe)

**Comment by justinlewis** [comment]
@steeebener - I'm going to put some thought into how to improve this for the designs we'll be discussing shortly.

**Comment by SteeveEbener** [comment]
Thanks Justin. Just one thing, the screenshots you have included in your previous message are referring to the fields attached to the Geo-Object itself and not the parents of that given Geo-Object.

**Comment by justinlewis** [comment]
Maybe we didn't understand the issue. Are you saying that in the top screenshot I posted that Namibia, Namibia District, and Namibia Region should also have the parents for each displayed?

Like:

Namibia: 99999

Namibial: 99999  (parent of Namibia District)
-- Namibia District: 99999

Namibia District: 99999 (parent of Namibia Region)
-- Namibia Region: 99999

**Comment by SteeveEbener** [comment]
All good now. I misunderstood your previous message and the screenshots, my bad. 

The only thing that is missing now is the possibility to also search according to the unique ID => reported in ticket #443 

I can close this ticket
