### ISSUE TITLE
Can't inactivate a GeoObject for a given period

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#366]
**List the CGR information**
- CGR version: 0.9.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
As a RA/RM I can't inactive a GeoObject for a given period

**To Reproduce**
As a RA/RM:
1. Go to the lists module
2. View a list on which the RA/RM has the mandate
3. Click the edit pen button for one of the GeoObject
4. Click the Edit button for the status field
5. Click the "+New version"
6. Create a new period over which the status would be "inactive" 
7. Click Ok and the submit
8. See the error message reported in the screenshot below

**Expected behavior (clear and concise)**
The RA/RM can inactive a GeoObject for a given period

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/86513918-95491300-be40-11ea-918f-103e49eff000.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:  83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
I can not recreate this problem.  Can you give me more details about the actions you took before hand?  Was this a list you published and then tried to edit before logging out and logging back in?

**Comment by SteeveEbener** [comment]
Hi @jsmethie .

I just redid the process in the demo instance and the problem is indeed not appearing anymore but two new one did... => I am closing this ticket and will create new ones...
