### ISSUE TITLE
Can't access a GeoObject that has been "fully" inactivated

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#367]
**List the CGR information**
- CGR version: 0.9.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
I created a GeoObject that was wrong and wanted to delete it but this is not possible (which might make sense)

I then "fully" inactivated it (meaning over its complete period of existence) but then realized that it is not accessible anymore (would be useful in some case for tracking purpose)

**To Reproduce**
As a RA/RM
1. Go to the lists module
2. View a list on which the RA/RM has the mandate
3. Add a dummy GeoObject
4. Click the edit pen for the dummy GeoObject
5. Change the status of the GeoObject from active to inactive
6. See error2: the GeoObject disappear and can't be accessed anymore

**Expected behavior (clear and concise)**
1. It is possible for the RA/RM to access the inactivated GeoObjects. 

A reason field should be added when inactivating a record. As an example, in the case of the DOH (Philippines) health facility registry, the possible reason for inactivation we implemented were: duplicate, not a... (_health facility for example_), does not exist, closed. This list of options will have to be expanded in the case of the CGR as we can also inactivate a GeoObject over a limited period of time (temporarily closed for example) + these reasons might be different depending on the GeoObject type (for example for administrative divisions we could have: split, merge, move

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 
 - Version:  83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**
Linked to tickets #87, #364, #366

**Comment by justinlewis** [comment]
Expected behavior #1 --> A larger discussion needs to be had around the lifecycle of inactivated objects and how they are presented in the UI.

**Comment by SteeveEbener** [comment]
=> I have added this as a topic for the CGR design meetings discussion

**Comment by justinlewis** [comment]
Estimated as an 8 if we simply show inactivated GeoObjects in the Lists with an indicator that they are inactive.

**Comment by CarlyNel** [comment]
Anne confirmed - no new interface needed.

**Comment by SteeveEbener** [comment]
Showing the record as inactivated is a first step. What will then need to be captured is the reason for inactivation which is an important information from a record management perspective.

**Comment by justinlewis** [comment]
This ticket implements the ability to see inactivated GeoObjects in Lists but does not add the reason field to the process of inactivating the GeoObject. A new ticket has been created for that functionality.
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/428

**Comment by SteeveEbener** [comment]
Just tested and the GeoObject that I have created and then fully inactivated is not accessible to the RA or RM => this is still not working as expected

**Comment by justinlewis** [comment]
@steeveebener - This is because status is defined as a "term type" in the backend which is a generic data type of key/value pairs (e.g. option sets). They're actually a little more unique than key/value pairs because there will be a value for every locale that is installed in the system because they are localized. So CGR:Status-Active is a key and Active is the localized value. If there where more locales there would be more columns. This means that any term type created, including custom attributes, would show in this way so the user can see the mapping. To change this for the default status field would require us to hardcode the condition which is doable. If we want to do that we should add it to the prioritization process.

**Comment by SteeveEbener** [comment]
Thanks Justin. The only difference here though is that we can't manage the "status" term type and therefore convert what is appearing in the "Status" field into options (e.g. code) like it is the case for other term type fields.

This is linked to ticket #146 => I will close the present ticket and include the above issue in 146
