### ISSUE TITLE
RM can access the edit buttons in a change request submitted by the RC

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#368]
**List the CGR information**
- CGR version: 0.9.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**

When clicking on the DETAILS button in a change request submitted by a RC, the RM has access to the edit buttons for all the fields associated to the concerned GeoObject.

While the changes that the RM could include in the different fields does not get captured when clicking on the "Ok" button the fact that he can do such changes is confusing

**To Reproduce**
As a RC:
1. Go to the change request module
2. Submit a change request for a given GeoObject
3. Log out

As the RM having the mandate on the GeoObject type: 
1. Open the change requests module 
2. Open the pending request submitted by the RC
3. Click on the DETAILS button
4. See error: all the edit buttons are appearing and the RM can change the values in the different fields (see screenshot below)

**Expected behavior (clear and concise)**
The RM can't edit the content of the fields in the DETAILS window

**Screenshots**

![image](https://user-images.githubusercontent.com/12602163/86523583-2bad2100-bea1-11ea-8de4-87ee37b9e903.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
The ability to edit a request as an RM in this way is supported. If I understand correctly it seems like there is actually a bug where the changes an RM makes to a request is not being saved. Rather than disabling the ability to edit the edits should be persisted with the request.

**Comment by SteeveEbener** [comment]
The RM should NOT be able to edit a request that has been submitted by the RC. This is a simple question of transparency.

If something needs to be modified in the request that has been submitted then this should be done by the RC himself.

This links to  ticket #84 (possibility for the RC to manage the tickets he has submitted and possibility for the RM to see the contact information of the RC in order to be able to contact her/him (rights by role matrix)

**Comment by SteeveEbener** [comment]
The edit button is still there and the RA and RM can still edit the "For Date" and "Contributor Notes" fields as per the screenshot below:

![image](https://user-images.githubusercontent.com/12602163/103252862-8d19fc80-49b9-11eb-9e50-36d0f6406903.png)

![image](https://user-images.githubusercontent.com/12602163/103252863-8f7c5680-49b9-11eb-9d01-3bf6485fdef1.png)

The only field that the RA or RM should be able to edit is the "Maintainer Notes" one.

**Comment by justinlewis** [comment]
I disabled the ability to edit contributor notes. In the screenshot you can see it's grey (disabled). I'm logged in as RM.

![Screenshot from 2021-01-15 16-59-33.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/dfddeffa-d8fb-43f5-8393-b3ae8b9a42f2)

The for date is just for viewing the Geo-Object over time. It doesn't impact the data that's being submitted. The basic use case is to see the history of an object beyond just the last state and proposed state.

**Comment by SteeveEbener** [comment]
Thanks for the adjusting the first issue.

The date field has actually no place when looking at a change request because it has been submitted for a specific temporal validity  (period) => The RM should not be able to use the change request ticket itself to go navigate the information for that particular geo-object => this field should actually be removed from that vindow

**Comment by justinlewis** [comment]
@steeveebener The main issue with removing the date field is that if a request is sent where one or more attributes have changes across time periods there would be no way to see the changes that aren't the most current. For example, if the old health facility name was changed and a new name was also added they would only be able to see the new label. To remove the date picker we would need to redesign the way we see changes of a Geo-Object which is beyond the scope of this ticket.

**Comment by SteeveEbener** [comment]
@Justin. Thanks for the clarification via slack.

As mentioned, there is no way that the RM will know that the RC has submitted more than one instance for a given geo-object => What has been implemented here does not make sense and need to be adjusted.

If the RC is submitting more than one instance for a given geo-object, then these need to be captured in separated requests (making the date field obsolete at the same time).

This is another case similar to what is captured in ticket #349

**Comment by justinlewis** [comment]
@steeveebener  Doing what you are asking would require changing the way that change requests are created and/or displayed after creation which is a significant change. This is beyond the scope of this ticket and should be discussed outside this ticket. For the time being we can't remove the date field because it's the only way to see those changes. We'll leave the date field until this workflow is adjusted to better support transparency of each change of a Geo-Object.

**Comment by SteeveEbener** [comment]
@Justin. I have included the date issue in ticket #547 

Apart from that, the edit button is still accessible to the RA/RM under 0.13.3 and it seems that this is only to be able to enter information in the "Maintainer notes" field => why is this field actually appearing in the DETAILS window while he can be field on the main window together with the "Additional Decision Makers" field?

=> my suggestion: Remove both the "Maintainer notes" field and the "Edit" button from the DETAILS window

**Comment by justinlewis** [comment]
@steeveebener I agree. Changes made:

From the main page
![Screenshot from 2021-03-01 14-41-31.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/81eb9425-af50-4b1b-b770-a50773bc2ec2)

In the details modal:
![Screenshot from 2021-03-01 14-41-47.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/d4bd9604-aa14-411b-9a08-c0898ddffb62)

**Comment by SteeveEbener** [comment]
Tested under o.14.0 and it is working. Closing this ticket
