### ISSUE TITLE
Change instances of "Geo Object" or GeoObject to Geo-Object

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#373]
- [ ] attribute matching modal page

**Comment by SteeveEbener** [comment]
[ ] Import module: 
      - first window, first field
      - Second window (attribute matching), window subtitle

 [ ] GeoObject type & Hierarchies module:
     - Manage Geo Object Type window , window title

[ ]  Lists module
     - Create list, second field (Geo Object Type)

I will keep adding if I find other ones. Thanks

**Comment by CarlyNel** [comment]
Hey @justinlewis I could be mistaken but wasn't it agreed that we were going to change the spelling to Geo-Object?

**Comment by justinlewis** [comment]
You're correct. I changed the title

**Comment by CarlyNel** [comment]
Cool thanks Justin. I assume that this will automatically include all instances of Geo-Object Types as well but flagging here just in case.

**Comment by SteeveEbener** [comment]
The following has not been changed in ve 13 (staging):

1 Import module:
- Second window (attribute matching), window subtitle (still reads Geo Object)

**Comment by justinlewis** [comment]
@steevebener I just updated it to say:
- Match the Geo-Object Type attributes to the source file columns
