### ISSUE TITLE
SRA having access to the exploratory section and able to publish lists

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#376]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The SRA can access the exploratory section when looking at a list

**To Reproduce**
As a SRA:
1. Go to the lists module 
2. Click on the view button for any list
3. See error 1: the exploratory section is accessible to the SRA (see screenshot below)
4. See error 2: the "Publish list" button is accessible to the SRA

**Expected behavior (clear and concise)**
1. Only the published section is accessible to the SRA
2. the SRA does not have access to the publish list button
3. The jobs section does not need to appear for the SRA

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/87503801-b6f39700-c697-11ea-8894-231ff3fb78ff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
The SRA  does only access the published section and does not have access to the publish list button but the job section is still appearing in the window.

**Comment by SteeveEbener** [comment]
Just checked, the list of jobs is not appearing anymore but the exploratory section back to being accessible to the SRA:

![image](https://user-images.githubusercontent.com/12602163/91168701-a60f5a00-e708-11ea-8001-03be6e2cbaff.png)

**Comment by SteeveEbener** [comment]
Just checked in version 0.12.2 and the exploratory section is still accessible to the SRA

![image](https://user-images.githubusercontent.com/12602163/100327901-d7007300-3006-11eb-930e-a417bae002cd.png)

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.
