### ISSUE TITLE
SRA can't see the metadata associated to the lists in the CGR

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#377]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The SRA can't see the metadata associated to the lists in the CGR (public or private)

**To Reproduce**
As a SRA
1. Go to lists module 
2. See error: the metadata button is not there for any of the lists

**Expected behavior (clear and concise)**
The SRA can consult the metadata associated to any list in the CGR (public/private) as per the rights by role spreadsheet

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/87509819-f2489280-c6a4-11ea-9303-e5c7dccc8d93.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
Currently the "metadata" button opens a modal that enables editing. This is due to a previous ticket that asked to change "edit" to "metadata".  To support an SRA viewing metadata, who should not be able to edit lists, we will need to add view only support to this modal. The estimate includes adding this support.

**Comment by SteeveEbener** [comment]
This issue does not only apply to the SRA but also any other roles looking at lists created by other organizations (see ticket #214)

In other words, the metadata for all the list should be viewable by any organization and roles but only editable by the RA/RM of the organization that generated it.

The issue reported in ticket #381 might also need to be addressed at the same time

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.
