### ISSUE TITLE
Jobs section should not appear when looking at a the lists published by another organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#378]
## User stories
1. It is difficult to understand what the "jobs" section is about when looking at the lists published by another organization

## Problems this relates to
1. 

## Proposed solution
1. Hide the "jobs" section for lists published by other organizations

## Considered alternatives
1. None

## Additional context
![image](https://user-images.githubusercontent.com/12602163/87517146-127e4e80-c6b1-11ea-8860-60f5ff0b7eb8.png)

**Comment by jsmethie** [comment]
No longer valid
