### ISSUE TITLE
RM can see and resolve job processing for GeoObject types over which he does not have the RM role

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#382]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The RM can see and resolve job processing for GeoObject types over which he does not have the RM role

**To Reproduce**
As a RM
1. Go to the job processing module
2. See the error: the RM can see and resolve jobs submitted for GeoObject types on which he does not have the RM role
3. See error

**Expected behavior (clear and concise)**
The RM can only see and resolve jobs processing fro GeoObject types on which he has the RM role

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/87787308-fe338080-c86d-11ea-97f2-78a5c4229dfe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome 
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by apliu02** [comment]
@justinlewis is this not similar to 412 (which is 8 story points?)

**Comment by justinlewis** [comment]
@apliu02 It's similar but the difference is that #412 is a check on organizations while this needs to check organizations and geoobject types. But you're right that 21 is a bit high. I changed it to 13.

**Comment by SteeveEbener** [comment]
Tested under ve 13 and working. I am closing this ticket
