### ISSUE TITLE
Make sure terms are not globally namespaced

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#384]
1. Make sure the key name won't get too long and throw an error

**Comment by CarlyNel** [comment]
Hi @rrowlands Is this something that you need me to test or is this back-end code related? If you'd like me to test something here, could you please provide a little more context so that I understand what I'm supposed to be testing. Thanks.

**Comment by justinlewis** [comment]
It's largely backend. There is no need for you to test here. Thanks!

**Comment by CarlyNel** [comment]
Ok great thanks @justinlewis . I'll leave this for you to test and close then.
