### ISSUE TITLE
No warning message when deleting a published instance of a list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#385]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
There is no warning message appearing when deleting a published instance of a list 

**To Reproduce**
As a RM:
1. go to the lists module
2. view a list over which the RM has the mandate
3. Publish the lists if needed
4. Click on the delete button for one of the published instances'
5. See Error: no warning message is appearing

**Expected behavior (clear and concise)**
A warning message like the one appearing when you delete an exploratory instance of a list is appearing when you click on the delete button for a published list (see screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/88130137-5a9af500-cc0c-11ea-812b-86966fbf49a6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
The buttons to delete a published or exploratory instance of a list not appearing anymore to the RA/RM => I can't check this ticket and I have created ticket #409 to report this problem.

**Comment by SteeveEbener** [comment]
Can't test in ve 0.12.2 as clicking on the "publish lists" button in the "Published" section does not generate any lists.

**Comment by justinlewis** [comment]
@steeveebener I just created a list from the Namibia Districts Geo-Object Type and was able to publish. The warning message did appear. It sounds like if the list your trying to publish isn't working there is a different issue.

**Comment by SteeveEbener** [comment]
@justinlewis : Did you create a published or a exploratory list? I can create an exploratory list but not a published one and the current ticket refers to the latter

**Comment by justinlewis** [comment]
@steeveebener I just double checked and I can create published lists. It sounds like there's something unique about the data or list you're trying to publish.

**Comment by SteeveEbener** [comment]
I have just rechecked this under staging (0.12.2) and I have now been able to publish lists as a RA or RM => I can confirm that the present ticket has been address and I can therefore close it.
