### ISSUE TITLE
Can't create a new GeoObject without the GeoObject type being part of a hierarchy

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#386]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
You can't add a GeoObject to a list for a GeoObject type that is not part of a hierarchy

The only way to handle this is to create a dummy hierarchy and put the GeoObject type in question on top of it

**To Reproduce**
As a RA/RM:
1. Create a new GeoObject  type but don't attach it to a hierarchy
2. Go to the lists module and create a list for that GeoObject 
3. Click on the Add GeoObject button
4. See the error: the "Parents must be assigned" message in red appears on top of the Parents tab and does not allow me to submit the creation of the new GeoObject while there are no parents to be specified as the GeoObject type is not part of a give hierarchy

**Expected behavior (clear and concise)**
A list can be created and filled without the GeoObject type it contains needing to be part of a hierarchy

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/88349887-f0a55b80-cd83-11ea-8f20-0706ab49f20a.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context (if any)**
Might be connected to ticket #310

**Comment by rrowlands** [comment]
That check exists to prevent Geo-Objects floating around without parents. Do we wish to disable the check entirely or only if the type is not part of a hierarchy?

**Comment by SteeveEbener** [comment]
Only if the geo-object type is not part of a hierarchy

**Comment by rrowlands** [comment]
This appears to be working on the latest release.

**Comment by justinlewis** [comment]
@SteeveEbener Please see last comment

**Comment by SteeveEbener** [comment]
Tested and indeed working. Closing this ticket
