### ISSUE TITLE
We should specify the validity period only once when creating a new GeoObject

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#388]
## User stories
1. As a RA or RM I would like to avoid having to enter the start date of the validity period for all the fields I have to complete and just mentioned it once at the beginning of the process

## Problems this relates to
1. Create new geoObject

## Proposed solution
1. Get the user to first specify the validity period and then automatically apply this to all the fields, including parents

## Considered alternatives
1. None

## Additional context 
Only applicable when creating a new GeoObject, not when editing an existing one

**Comment by vrajasekaran18** [comment]
@justinlewis with the new exist/validity periods - this has now kind of worked on?

**Comment by SteeveEbener** [comment]
@Varshana. I just checked this under 0.17.2 and this is indeed the case now. I am closing this ticket
