### ISSUE TITLE
Incomplete list of error codes

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#389]
**List the CGR information**
- CGR version: 0.9.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**

As an MOHA-RM I was testing the uploading of duplicate data. 
- I followed the CGR test scripts and uploaded file 1 with new data (new data import)
- I then uploaded a second file with 30 entries - 20 of which were near duplicates (new data import).
- The CGR said that 9 of the 30 entries had been uploaded (I was expecting 10 to upload since 10 were new and 20 were duplicates). 
- Of the 21 entries that the CGR said were not uploaded, it only gave a (correct) error report for the 20 duplicates. I don’t know what happened to the 21st entry that was not uploaded.

**Expected behavior (clear and concise)**
I expected: 
1) 10 of the entries to upload and 
2) to receive an error report for all entries that failed the upload

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/f70a777a-775c-4237-9abf-3968489209e1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2 (64-bit)

**Comment by CarlyNel** [comment]
Update: This has just happened again now.

I'm logged in as an RA, uploaded a file with 400 entries. Only 394 entries were uploaded but:
1) No error report was generated for the missing 6 entries
2) The file upload was reported as being successful under the "completed jobs" section. Previously, if any records weren't uploaded successfully, the upload status would remain under the "in progress" section. 

Screenshots included below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/fee82985-d43c-440d-b941-a38e1de485ea)

Status of file upload is SUCCESS.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/adc943d0-cdb1-421f-aa96-93f990ba0bc0)

**Comment by rrowlands** [comment]
Can you please upload your spreadsheets to this ticket so that we may reproduce the issue?

**Comment by CarlyNel** [comment]
Hi @rrowlands. I've having issues uploading the files so I'll include the links to the google sheets instead and you should be able to download from there.

File from my original ticket: https://docs.google.com/spreadsheets/d/135cgOQeY-1ARDUyEzOeIo9I_UxudzxGG6jvYgrtfMFw/edit?usp=sharing

Latest file from today's upload: https://drive.google.com/file/d/18RpnkGWZ75Uutb_Yk0kSayueGbeTb-Zm/view?usp=sharing

Let me know if you need anything additional.

**Comment by justinlewis** [comment]
I think this was fixed with this ticket:  https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/421

We need to validate with the next release testing.

**Comment by rrowlands** [comment]
@justinlewis These are separate issues.

**Comment by rrowlands** [comment]
This ticket will be part of release 0.12.1.

**Comment by rrowlands** [comment]
The fix for this issue has been deployed to the staging server. @CarlyNel Now is a great time to test this to make sure it's fixed.

**Comment by CarlyNel** [comment]
Just tested this by uploading the same file as previously but with a single new line. Of the 30 entries, 29 were duplicates and 1 was new. All 29 error reports showed correctly under the job details. I then tried uploading the same file again, and the CGR correctly showed all 30 error codes as all 30 entries were already in the CGR.
