### ISSUE TITLE
Unexpected filter behaviour within Lists

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#390]
I'm not sure how the filter within Lists is supposed to work so I'm logging this ticket in case this is a bug, but perhaps it's working as intended, in which case this would be a feature request.

Instance: 
Staging - v 0.9.1

As an RM, I wanted to view a filtered subset of data within a master list but came across two potential issues:

1. I opened a master list to view all GeoObjects. I then tried to filter on 3 specific codes but was only able to filter one by one. 
2. Secondly, I wanted to view information for all GeoObjects within the Pakngum district. The filter recognises each instance of Pakngum (all spelt the same way) as different filters and seems unable to filter based on all instances of this district. 

I expected 
1) to be able to filter on/view the details of more than one GeoObject at a time and
2) all instances of the same name to be recognised as a single filter

Screenshots:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/ebc6c5e8-1c5b-4179-aede-8b336c15a9b1)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/4ef2bdda-5f51-4dae-a50f-d61c2a047b15)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/d3db3ee6-5a43-47eb-8aec-eb8cd8f1da4f)

Desktop (please complete the following information):

    OS: Windows 10
    Browser: Firefox
    Version: 78.0.2 (64-bit)

**Comment by CarlyNel** [comment]
From Rica in CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915): _"It would be nice to have checkboxes next to the options provided in the filter dropdown, so that multiple values can be selected to be filtered_"

**Comment by rrowlands** [comment]
Gonna add to this ticket:

The filter autocomplete dropdown is being cut off ever since we added scrollbars

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/31fa36af-1386-468c-bacb-97a2f3938fb9)

**Comment by rrowlands** [comment]
I have added the ability to filter based on multiple codes to the 0.16.1 release, as well as the style issue I outlined in the previous comment.
