### ISSUE TITLE
Accepted Change on Non Master List not Reflecting

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#391]
Instance: 
Staging v 0.9.1 

**As an RM, I**

- Wanted to accept a change request submitted by an RC to a GeoObject in a non-master list.
- I went to the change request module and both accepted and implemented the decision.
- When I viewed the non-master list again, the change to the GeoObject name was not reflecting.
- It was however showing when I clicked the edit pen to view details of the GeoObject that was supposedly amended.

**I expected** to see the updated GeoObject name reflect in the list after implementing the change.

**Screenshots**:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/61502735-ff8b-48a6-bfaa-ed1548f0f823)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/a82f9017-bcbb-4ad2-818f-440f1eda7c1e)

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/29c0a5a0-81e3-40cf-96f4-dec46f879809)

Desktop (please complete the following information):

    OS: Windows 10
    Browser: Firefox
    Version: 78.0.2 (64-bit)

**Comment by justinlewis** [comment]
@CarlyNel I think this is just because you didn't refresh the lists?  

If that's the case can you mark this as invalid and close it?

**Comment by CarlyNel** [comment]
Hi @justinlewis Thanks for pointing this out and I think you're right. I just viewed a more recently published list of what I had previously submitted a change request for, and the change is reflecting. Apologies! I'll mark this ticket as invalid and close it.
