### ISSUE TITLE
The SRA can access the curation module through the burger menu

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#396]
**List the CGR information**
- CGR version: 0.10.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The SRA can access the curation module through the burger menu while it should not be the case as per the rights by role google spreadsheet

**To Reproduce**
As a SRA
1. Open the burger menu
2. See error: the curation module appears in the menu and you can access it

**Expected behavior (clear and concise)**
The SRA can't access the curation module from the burger menu

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/89121328-8eb9c400-d4f0-11ea-90c6-08e769fe5fe1.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.105 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
What's the justification for not showing this to the SRA?  Right now we generate tasks for the SRA such as create an organization.  That SRA should only be able to see tasks relevant to them.

**Comment by SteeveEbener** [comment]
Who or what can generate tasks for the SRA to accomplish while he has the highest level of authority in the platform? There might also be a need to clarify what is the role of the curation module vs the concept of tasks.

The curation module corresponds to case 3 described in the Epic google doc: https://docs.google.com/document/d/1TxgLTf9pD02sn5-J6mibAqKO93ruvhIoAIApuMea6A8/edit#.

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.
