### ISSUE TITLE
RC requested to provide the unique ID of the GeoObject when submitting a "Add GeoObject" change request

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#401]
**List the CGR information**
- CGR version: 0.10.0
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The "GeoObject Unique ID" field is mandatory when the RC is submitting a change request to add a new GeoObject while the coding responsibility is most likely to reside at the RA/RM level.

**To Reproduce**
As a RC:
1. go to the lists module
2 View  a list on which you have the RC role
3. Click the "Add GeoObject" button
4. See error: the "GeOobject Unique ID" field is visible and mandatory 

**Expected behavior (clear and concise)**
The RC does not have to provide a unique ID when submitting a "Add GeoObject" type change request.

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/90197070-24622700-de00-11ea-9eb9-2136c1f001df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.125 (Official Build) (64-bit)

**Additional context (if any)**
Linked to ticket #431

**Comment by CarlyNel** [comment]
In country validation required: A change request cannot be accepted until a UID has been set. Who (RA/RC) in the workflow would know the new code/UID?

**Comment by SteeveEbener** [comment]
The attribution of the unique ID needs to be centralized and this for the following reasons:
1. The request to add a GeoObject has to be validated before using any UID from the stack of available UIDs. It can for example be that the RC suggested to add a GeoObject that is already in the list
2. To avoid for different RCs to attribute the same UID to different GeoObjects. You could put a rule on this one but it might be complex because this will have to not only check against already valid records but also the other change requests that are still pending
3. to ensure that the coding scheme is respected as once attributed the UID can't be changed . This involves, but is not limited to: avoiding typos in the UID but also respecting the structure of the UID as well as the making sure that the next available code is being used and not any random code
4. Some of the RCs might not be part of the organization having the curation mandate over the coding scheme

=> The RA/RM are the guardians of the coding scheme and this is the practice that the CGR should promote. This is the practice I have seen implemented in countries. When this is not the case, meaning that the RC can create the UID, then they rapidly run into issues with their list.

**Comment by SteeveEbener** [comment]
Checked under 0.18.1 and still not implemented

**Comment by rfromthecastle** [comment]
I agree this is an issue. Initially the Lao MOH wanted to have Provincial Health Office (RC) staff submit new health facilities using the Add New Geo-Object button, however, determining the code of the Geo-Object lies with the RM. The current workaround is that only RMs can add new Geo-Objects.

**Comment by rrowlands** [comment]
Committed as e8cd8957668ae4bf8965bf3af1213fb18c1905d0

**Comment by rrowlands** [comment]
This feature is now available for testing on the staging server.

**Comment by SteeveEbener** [comment]
Tested on staging and working. The RA/RM is now the one who needs to enter the unique ID for the change request to be accepted. Closing this ticket
