### ISSUE TITLE
SRA can't see private lists created by any organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#410]
**List the CGR information**
- CGR version: 0.11.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The SRA can's see private lists created by any organization in the lists module

**To Reproduce**
As a RA/RM
1. Set one of the list over which you have the curation as private

As SRA
1. Go to the lists module
2. See error: the list set as private can't be seen by the SRA

**Expected behavior (clear and concise)**
The SRA can see private in the list module and consult its metadata but not create, edit, delete, consult,... such list as per the rights by role matrix.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 84.0.4147.135 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
Marking as invalid and closing because SRA has been depricated in favor of System Admin while the need and organizational implementation for SRA is evaluated.
