### ISSUE TITLE
RA/RM can generate more than one instance of exploratory list for the same date 

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#413]
**List the CGR information**
- CGR version: 0.11.1
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The RA/RM can generate more than one instance of exploratory list for the same date

**To Reproduce**
As a RA/RM: 
1. Go to the lists module
2. Click on the View button for a list on which the RM has the RM role
3. Generate an exploratory list for the same date as one of the already generated list (See the "List Valid For" column)  
3. See error: it is possible to generate more than one instance of exploratory list for the same date (see screenshot below)

**Expected behavior (clear and concise)**
The RA/RM, and also RC, can't create more than one instance of the exploratory list for a given date to avoid duplicates in the table of generated lists (a message could be provided indicating that an exploratory list has already been generated for that given date)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/91439222-3384b280-e89f-11ea-82f6-839542de76a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
No longer valid
