### ISSUE TITLE
Create primary hierarchy widget

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#417]
This includes the primary functionality of hierarchy management. 

See the [design mockups](https://docs.google.com/drawings/d/1HUg7i6xufoScSSynSjYO6bz7LxLshgpyh35ims0dTO8/edit) and [requirements doc](https://docs.google.com/document/d/1JO50-6oaoZmopYzDrhtPXxk3ygKYXIFHykwpAwTSkIo/edit#) for more details.

**Comment by CarlyNel** [comment]
Hi team, not sure if this is something that I am able to test or if this is back-end? If you'd like me to test this, please tell me how I can go about doing so. Thanks.
