### ISSUE TITLE
Hierarchies created by organization A visible and parents editable by organization B when editing a geo-object

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#419]
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
When editing a Geo-Object for a Geo-Object type under  the curation mandate of organization A, the RA/RM of organization B can see and change/specify the patents for hierarchies created by organization A that contain the Geo-Object type in question 

**To Reproduce**
As the MOHA RA/RM (Tolkien data)
1. Go to the lists menu
2. View the Village master list 
3. Click on the edit pen for one of the Villages 
4. Scroll down to the section used to edit hierarchies
5. See error 1: The health care referral hierarchy created by the MOH containing the Village Geo-Object is visible to the MOHA RA/RM (first screenshot below)
6. Click the Edit button
7. See error 2: the MOHA RA can edit the parents in the health care referral hierarchy (second screenshot below)

**Expected behavior (clear and concise)**
Two possible options:
1. Only the hierarchies created by organization B are visible and can be edited
2. All the hierarchies containing the Geo-Object type in question are visible but only those under the curation mandate of organization B can be edited

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/103392540-5ed32300-4b59-11eb-9241-f5a3d5601000.png)

![image](https://user-images.githubusercontent.com/12602163/103392562-7ca08800-4b59-11eb-942f-e1bfcb1c153b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Just tested this in ve 0.13.0 (staging) and the problem does not only remain but it is now possible for the RA/RM of organization A to edit the information for a hierarchy under the curation mandate of organization B => I have edited the title and content of this ticket accordingly

**Comment by vrajasekaran18** [comment]
@justinlewis FYI Anne's categorised this as high priority so updating the status for the ticket

**Comment by rrowlands** [comment]
As far as I can tell and am aware, this issue has been fixed in #259. If the "reproduce" section of this ticket is followed on the staging server, the CGR no longer displays the health care referral hierarchy.

Please let me know if I am missing something.

**Comment by SteeveEbener** [comment]
Good catch Richard. Closing this ticket
