### ISSUE TITLE
Do not allow editing in the Explorer

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#429]
Taken from ticket [#420](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/420).

This relates to issues around the slowness of the Explorer and it not always working as expected (eg: showing the incorrect GeoObject level). Suggestion from Steeve: Use a non-editable version of the editing geometry modale to visualize the geography of a given GeoObject from the lists module. 

This ticket would remove editing from the CGR and have the Explorer be a view only.

**Comment by SteeveEbener** [comment]
This ticket does not correctly reflect the suggestion reported in ticket #420 and should be closed (focuses on visualization and not editing). 

In any case, the editing functionality should NOT be removed from the CGR.
