### ISSUE TITLE
Deleting a GeoObject type corrupts the CGR

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#436]
**List the CGR information**
- CGR version: 0.11.1
- CGR instance (e.g. a URL): Demo, Production

**Describe the bug (clear and concise)**
Both Pedro and I needed to remove the data associated to specific GeoObject types from the graph (data not needed anymore, needed to change the unique IDs associated to the GeoObjects). 

After deleting the lists created for these GeoObjects, we went to delete the hierarchy linking these types but the CGR did not allow us to do this mentioning that some data was still associated to it => we tried to directly delete the GeoObject types => the platform started the process but then displayed the error message captured in the screenshots below and corrupting the content of the CGR (GeoObject types and hierarchy window becoming empty and not possible to do some actions like creating a new list

**To Reproduce**
As a RA/RM: 
1. In the lists module: delete the lists associated to the GeoObject types for which you want to remove the content from the graph
2. In the GeoObject and Hierarchies module, try to delete the hierarchy linking the GeoObjet types in question (message saying this is not possible)
3. Delete the first GeoObject type for which you  want to remove the content from the graph
4. See the first error message that appear in the GeoObject and Hierarchies module (first screenshot below), and that the module content is gone when you close that message (second screenshot
5. Go to the list module and click on the create button or open the metadata of a list
6. See the second error message at the top of the window (third screenshot below

**Expected behavior (clear and concise)**
It is possible to delete the content associated to a GeoObject type in the graph following a specific process. For example:

1. Delete the list for that GeoObject type as well as the list in which this type is used as part of a hierarchy
2. Remove the GeoObject type from the hierarchy(ies) in which he is used
2. Delete the GeoObject type

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/94204938-cfccc400-fef4-11ea-9133-51ccf3f22141.png)

![image](https://user-images.githubusercontent.com/12602163/94204943-d22f1e00-fef4-11ea-9afa-07143501727a.png)

![image](https://user-images.githubusercontent.com/12602163/94204953-d5c2a500-fef4-11ea-800b-afbb72726ecf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Just tested that in staging and:
- deleting the list: OK
- removing the GeoObject type from the hierarchies: Ok
- Deleting the GeoObject type: Ok

But  when trying to directly deleting the GeoObject type I get the following message while I could not find any hierarchies containing the GeoObject type in question (Village (NMCP) under the MOH in this case):
![image](https://user-images.githubusercontent.com/12602163/99542346-e96a2380-29ec-11eb-82e7-39a4360f1efe.png)

=> Could there be an error in the message, meaning that it should make reference to the fact that GeoObject Type is being used in at least one list?   (the error message making reference to the hierarchy should maybe also make reference to "at least one hierarchy")

**Comment by justinlewis** [comment]
@steeveebener - We're having a hard time reproducing and debugging this. I created a ticket to target fixing this in Sprint 23. 
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/476

Can you take a look at that ticket and add the steps to reproduce?

**Comment by SteeveEbener** [comment]
Ok (hopefully you are referring to sprint 13 and not 23 :) )

I am closing this ticket and will continue on the new one
