### ISSUE TITLE
Confluence user documentation to be updated

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#446]
Given the continuous development on the CGR, the original [user documentation](https://terraframe.atlassian.net/wiki/spaces/GGR/pages/901808172/User+Documentation) has now become outdated which was highlighted in CHAI's [recent testing](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915) of the CGR. Updates need to be made across most of the sections.

**Comment by justinlewis** [comment]
Addressed:
- Row 1
- Row 8
- Row 15

**Comment by CarlyNel** [comment]
Hi Justin, I've just looked through all of this and feedback as follows:

Row 1 - The table of user roles appears to be incomplete. Has the SRA role been changed to Administrator? What is the Data Manager role? and should it also include anonymous users or not until this option exists?

Row 8 - Looks good

Row 15 - There is a typo under the modify an existing users settings section - see screenshot:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/a639cef4-d323-4fe7-a2de-429318a52578)

Row 20 - If this FAQ section is going to be fleshed out in the future then great, it' worth keeping. If not, then I would recommend rather including the questions on the associated tabs (eg: on the uploading spreadsheet tab). Either way, I would include a link to this FAQ section on the tabs to which the questions relate so that as the person is going through for example, uploading a spreadsheet, they can navigate straight to the FAQ section to view questions related to the action they're currently trying to perform. (hopefully this makes sense)

Row 21 - Re the "uploading a spreadsheet" page and "uploading a shapefile" page: I think these different options (in screenshot below) should be referred to as tabs not pages.
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/c8d316fe-ab62-4ab9-89fd-9a6d87bbc53f)


I think this should be referring to a spreadsheet and not shapefile since we're under the spreadsheet section.
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/c69ae57d-3223-41bb-ae98-b3a5867a81fd)

The content under the publishing and updating lists tabs looks good.

Row 22 - So far so good
Row 23 - So far so good
Row 24 - So far so good
Row 25 - Looks good
Row 26 - Looks good
Row 30 - Looks good

Row 32 - The update is not reflecting on my side. It's still showing old information and the old screenshot is confusing because the items in the hamburger menu are very different since you were logged in as an admin.

Row 35 - There is no information on how to submit a change request specifically via the change request module. The current info only appears to cover submitting a change request via a List.

Row 37 - Looks good

Row 39 - All screenshots load for me. A suggestion would be to maybe expand on what "implement decisions" actually does because if the user has already accepted a change request, it seems a bit strange that they then have to (in a way) accept it again by clicking this button.
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/7a368d1c-f751-4d9c-a357-8ef4401bf4d2)


More feedback to follow in a new comment.

**Comment by CarlyNel** [comment]
**Final things to consider:**

- The spelling of Geo-Object will need to be updated across all documentation (from GeoObject)
- Is Geo-Object type supposed to be two words? And does 'type' have a capital letter?
- On the System Access page (under Getting Started), all steps are labeled as #1.
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/157c28ab-3f0f-4672-ae49-591e2f076835)

- Under System Email Management: Who do you have to be logged in as in order to see the "Email Settings" in the hamburger menu? The screenshot just says Admin as the user. (same for adding a new logo)

- Under Configuring a new hierarchy, there's a typo
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/1c4513ea-7e92-46a9-b2f0-fcfcd35290b9)

**Comment by CarlyNel** [comment]
Just found another typo in the word _inherit_ under the hierarchies tab. See screenshot below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/1ceb3d9a-71bf-43d1-ac8e-54cf584c48f7)

**Comment by CarlyNel** [comment]
I've also just realised that there isn't any section in the user documentation that explains how grouping within a hierarchy works or how to set up a group. The only reference to grouping is that it can be added to a hierarchy like a Geo-Object type (see below). Perhaps we need a step before this explaining how to create a group.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/1ce11ee3-86f0-4b1d-95ea-1f6d145145b5)

**Comment by justinlewis** [comment]
Re-opening because I didn't see these additional comments before. I'll be working on documentation changes on Monday which will cover a lot of changes because this release had an impact nearly everywhere in the app.

**Comment by justinlewis** [comment]
@CarlyNel I've gone through all your feedback here and made corresponding changes.

**Comment by CarlyNel** [comment]
Thanks @justinlewis. I just went through all of my above feedback and the changes all look good. I'll go ahead and close this ticket.
