### ISSUE TITLE
Appropriateness of user roles when inviting a new user to the CGR

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#448]
**List the CGR information**
- CGR version: 11?
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
From Rica: "I might be understanding the roles incorrectly, but why is an MOH RA (i.e. I’m signed in as Moh_guest_RA) currently able to assign roles for MOE and MOHA GeoObjects? How I’m understanding the roles is that only an SRA could assign roles for GeoObjects managed by different ministries. This option appears when inviting users to create an account."

**Expected behavior (clear and concise)**
An MOH-RA should only be able to assign roles for the MOH and not for any other organization.

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915)

**Comment by SteeveEbener** [comment]
It would be good to have more information regarding what is reported here because I can't reproduce it.

I checked all the user accounts accessible from Moh_guest_RA and only MOH GeoObject types are accessible from the Settings>User account page. Example:
![image](https://user-images.githubusercontent.com/12602163/97077998-25db7700-161b-11eb-8f3c-f358b8f98f11.png)

**Comment by jsmethie** [comment]
Same. I have been unable to replicate this problem

**Comment by CarlyNel** [comment]
I reached out to Marcus some time ago and asked him for screenshots in relation to this ticket but have never received them.

**Comment by jsmethie** [comment]
I believe I have recreated the issue

**Comment by CarlyNel** [comment]
@jsmethie What steps did you follow to recreate Rica's original error?

I logged in as an Moh_RA and navigated to the 'invite new user' section under the settings tab and saw the same as what Steeve reported above -> everything pertaining only to the MOH. Where did you see the reported error?

**Comment by jsmethie** [comment]
The problem was on the invite user modal.  It was showing all organizations.  The normal create user modal was restricting it to just the correct organization.  The invite user modal has been fixed to only show the current users organization roles.

**Comment by CarlyNel** [comment]
Ah right! Thanks for clarifying @jsmethie. I have now checked the invite user modal too and everything appears to be under the MOH which is the organization that I'm currently logged in under.
