### ISSUE TITLE
Differentiating a new instance of an attribute from the original instance

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#454]
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915). Line 38.

From Rica: "_When adding a new instance of an attribute using the widget to manage values over time, it would be nice to see what instance we added (this could be with some colored text below the original attribute value, as is done when modifying an existing attribute value) in the GeoObject edit modal. Right now, we only see the original instance_."

Screenshot from Rica:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/47535492-8f98-4740-b8bd-c9880be18402)

**Comment by justinlewis** [comment]
Closing and marking as invalid because this widget has been depricated.
