### ISSUE TITLE
Unspecified error when trying to configure an external system synchronization

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#455]
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915). Line 44.

From Rica: _"I get an unspecified error when trying to configure a synchronization using the external system I previously registered_."

Screenshot from Rica:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/fa1be781-2668-4317-a833-dd2329df7550)

**Comment by jsmethie** [comment]
I strongly suspect that this is caused when the user has entered bad DHIS2 connection information or the DHIS2 server is down.  I will add a better error message, but the server is always going to return an error if it can't communicate with DHIS2
