### ISSUE TITLE
Explorer: Problems with zoom function, scroll function and cut off names

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#456]
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915): Line 45.

From Marcus: "_When clicking on the geo-location of an object in the master list - and I am sent to the Explorer view page - this is the view I get (see below screenshot). You will notice the region names are cut off in the left panel. When I try to scroll up on this panel it does not allow it; same with the Zoom option on the top right of the map window. Though the interface allows me to scroll in and out using my track pad."_

Screenshot provided:
![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/0ec4330b-de71-44a4-9291-cf11700dcdd4)

**Comment by SteeveEbener** [comment]
Linked to ticket #420

**Comment by justinlewis** [comment]
I believe this is a result of an error we fixed already where permissions to objects outside of the users organization aren't being caught very well. This should be fixed with the 0.13.0 release.

**Comment by CarlyNel** [comment]
The new Explorer has addressed Marcus's original issue with content in the left pane being cut off and not scrollable.
Steeve has already provided feedback on possible improvements to the zoom function in ticket [#420](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/420).

All info is visible in the left pane as below:

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/01996c44-de2a-4522-8363-66ccbb3b67cb)
