### ISSUE TITLE
Inconsistent date formats

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#457]
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915): Line 46

From Rica: "_It would be nice to have all the date formats be the same across the CGR platform (and configurable in the settings, if possible). Right now I see dates in US format, with dashes or slashes, year first, etc., which is a little bit confusing_."

Justin confirmed that correcting the date formats is a high priority. However, dates will not be configurable.

Similar issue raised in ticket [225](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/225).

**Comment by jsmethie** [comment]
The date input fields are determined by your browser and locale.  We have no control over that format.  However, we can change the format of how dates are displayed outside of the input fields.

**Comment by SteeveEbener** [comment]
The need to homogenize how dates are being displayed in the front end is captured in ticket #225.

This ticket does nevertheless capture the need to also adjust the format of the validity date displayed when looking at instances of a list (yyyy-mm-dd)

**Comment by justinlewis** [comment]
We're going to target setting all formats to yyyy-mm-dd because it fits the w3c spec:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by justinlewis** [comment]
There's a conversation in ticket [#225](https://github.com/terraframe/geoprism-registry/issues/225) that explains the solutions and why it was chosen.
