### ISSUE TITLE
List frequency to include 6 months

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#458]
Taken from CHAI's recent testing [feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=1752608915): Line 28

From Rica: "_For list frequency: adding in a 6-month frequency may be useful. I don’t yet have a specific example from Lao PDR where such an update frequency is needed, but based on previous experience in working with UK Ordnance Survey datasets, some of their national vector and raster datasets were updated every 6 months_"

**Comment by CarlyNel** [comment]
Justin confirmed relatively easy to implement.

**Comment by CarlyNel** [comment]
Hi @SteeveEbener Tagging you on this ticket in case you have any additional context to add re list frequency. Thanks!

**Comment by CarlyNel** [comment]
@justinlewis @jsmethie I've just checked this but am not seeing a semi-annual list frequency option in the drop down menu. See below screenshot. I'm only seeing monthly, quarterly (which would be every 3 months) and annual. Could you please advise?

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/3a0b2b52-1e44-4e66-a9b4-beddecc5c4c1)

**Comment by CarlyNel** [comment]
@jsmethie @justinlewis Apologies, please ignore my previous comment. I see that this ticket is under sprint 13 so the fix won't yet be in staging.

**Comment by SteeveEbener** [comment]
Biannual does not mean every 6 months. The options could be as follow to be consistent:
- Annually
- Half-yearly
- Quarterly
- Monthly

**Comment by jsmethie** [comment]
Biannual means "occurring twice a year" in the same way that annual means "occurring once a year"

**Comment by SteeveEbener** [comment]
The joy of the English language :) 

Occurring once or twice a year does not necessary mean that this would always be at the same date. In addition to that, it seems that biannual can mean two things: occurring once every two years or occurring twice per year (https://www.dictionary.com/browse/biannual#:~:text=Biannual%20can%20mean%20two%20things,years%20or%20twice%20per%20year)

=> Yearly might actually be better than annually
=> Half-yearly or biyearly seems to be the correct term based on the definitions find on the internet

Remains to check how all of this can translate in other languages :)

We might end up having to go for:
- once every 12 months
- once every 6 months
- once every 4 months
- once every month

To be continued....
