### ISSUE TITLE
Incorporate feedback from hierarchy v1

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#461]
- [x] Make related hierarchies context menu look better / more consistent with rest of CGR
- [x] Make GeoObject Type nodes in sidebar match main hierarchy.
- [x] Font sizes are different across different elements making it confusing
- [x] UI: When I tried to remove the bottom level from my hierarchy, I clicked and dragged “CN Test MOHA District” into the left side pane but when doing so, it didn’t look like anything was happening (the item I was moving looked like it was moving behind the pane) until such time as I released my cursor. I appreciate that this is minor but because I expected to see, for example, an empty dotted block in the left pane where my GeoObject Type was going to go as I dragged it over, I initially thought that something was wrong.
- [x] Functionality: After dragging my GeoObject Type out of my hierarchy, the below pop up appeared which made me a bit uncertain. I was not trying to delete the GeoObjectType completely. I was simply trying to remove it from my current hierarchy, but the below made me think that if I clicked “submit”, that the GeoObjectType would be completely deleted from the CGR. What is the intended action? Will it be deleted or will it simply be removed from the hierarchy I’m working on and returned to the side pane? Perhaps this should be rephrased to something like “are you sure you’d like to remove [XXX] from the current hierarchy?”
- [x] It appeared that I was able to delete from a hierarchy over which I am supposed to only have viewing rights.  Only after clicking “submit”, did the window pop up telling me that I didn’t have permission to make the change. My recommendation would be to show the error page (about permissions) immediately after I try to move a GeoObject Type out of a hierarchy over which I have no mandate.
- [x] UI: The unusually large font for the related hierarchies is a bit distracting so I would:   a) recommend reducing it to at max, the same size at the font used in the hierarchy.

**Comment by CarlyNel** [comment]
Hi @justinlewis.

Feedback on this ticket below:

#1: I'm unsure where to find this
#2: Looks good.
#3: Re font sizes: If I'm honest, to the naked eye, the fonts still appear to be a bit different in terms of size, actual font, bold/not bold, colour (grey vs black). Also, the related hierarchy menu that appears when you click on the link icon in a hierarchy is still a much larger font than what I feel it should be - perhaps it's just the really big headings that makes it so distracting ("Related hierarchies" and "Actions"). Given that this is a menu of additional information, my expectation was that the font would be smaller than that in the hierarchy.

#4: Re dragging Geo-Object Types out of my hierarchy:  Nothing appears to have changed (I'm probably missing something here). When I drag an object out of my hierarchy and back into the left hand pane, it kind of disappears behind the pane so doesn't look like any action is going to happen when I release my cursor. **NOTE: I'm not sure what's going on but I just let go of my cursor and am unable to remove any Geo-Object type from my hierarchy. I'm logged in at MOHA-RA. I'm viewing my hierarchy/hierarchies but am unable to remove any Geo-Objects from any of them**. No errors are thrown. Nothing happens. The Geo-Object type that I'm trying to remove just shoots straight back into the hierarchy. How do I remove items from my hierarchy? Did something change or am I having a really blonde moment here? :-) 

#5: Re editing another organization's hierarchy: The same happened as the above. It wasn't clear that I actually couldn't edit anything. I was still able to click and drag Geo-Objects, except they popped back into the hierarchy so no message explaining why I couldn't edit anything. A suggestion could be to either a) Have the cursor change to a no entry sign whenever I navigate over someone else's hierarchy that I only have viewing rights over or b) if I click and drag anything, for a message to pop up saying that I don't have editing rights etc

#6: Re font of related hierarchies - addressed in comment #3 above.

**Comment by CarlyNel** [comment]
Apologies, I clicked the wrong button by mistake so reopened this ticket.

**Comment by CarlyNel** [comment]
Re #4 above... I've just seen that the option to remove an item from my hierarchy is now available via the chain link icon/menu.

**Comment by justinlewis** [comment]
> # 1: I'm unsure where to find this

This is the context menu after clicking on the chain link icon. This was mostly driven by me rather than CHAI feedback.

> # 3: Re font sizes: If I'm honest, to the naked eye, the fonts still appear to be a bit different in terms of size, actual font, bold/not bold, colour (grey vs black). Also, the related hierarchy menu that appears when you click on the link icon in a hierarchy is still a much larger font than what I feel it should be - perhaps it's just the really big headings that makes it so distracting ("Related hierarchies" and "Actions"). Given that this is a menu of additional information, my expectation was that the font would be smaller than that in the hierarchy.

Can you post a screenshot so I can compare mine?  I will tweak this a little for the next release.

> # 5: Re editing another organization's hierarchy: The same happened as the above. It wasn't clear that I actually couldn't edit anything. I was still able to click and drag Geo-Objects, except they popped back into the hierarchy so no message explaining why I couldn't edit anything. A suggestion could be to either a) Have the cursor change to a no entry sign whenever I navigate over someone else's hierarchy that I only have viewing rights over or b) if I click and drag anything, for a message to pop up saying that I don't have editing rights etc

If I understand correctly this is when you have a hierarchy from another org selected and then try to drag Geo-Obejct Types from your org onto the other orgs hierarchy?  I get an error message saying I'm not allowed to add children when I try. However I'll look into restricting the ability to drag when a hierarchy from another org is selected.

**Comment by CarlyNel** [comment]
Hi Justin, regarding the font, it's certainly not the worst looking but it does look like different fonts have been used across the various items in the below screenshot (or perhaps it's the different size of the font that is making it seem like a different font altogether). Here you can also see the different colours - header is grey vs hierarchy which is black. Are the organization names in a different font to that used for the "Geo-Object Types" and "Hierarchies" tabs?

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/d548e25b-ef73-49ba-b30e-5a7d1df00e92)

Regarding the point on editing another organization's hierarchy... perhaps given that the delete function has changed from dragging an item out of a hierarchy to clicking on the chain icon, my previous feedback is less relevant. I've included a screenshot below though to show what I mean. I'm viewing a different org's hierarchy and it appears like I can click on and drag items out of the hierarchy. (nothing happens now but it gives the impression that editing is possible). No biggie. Just flagging none the less.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/e8e3e7df-7b05-4f0b-b061-4b242e6b9577)

**Comment by justinlewis** [comment]
Adding a couple items from additional feedback:

- [ ] Disable dragging of nodes on the hierarchy manager to avoid somone thinking that move functionality exists.
- [ ] Add ability to unshow a related hierarchy.
- [ ] Add ability to un-inherit without showing the inherited hierarchy. Currently you have to show the inherited hierarchy to see the button.
- [ ] Replace chain with a cog icon (https://fontawesome.com/v4.7.0/icon/cog)
- [ ] Add org name to all nodes rather than just inherited nodes.
- [ ] Deleting a hierarchy while that hierarchy is selected needs to move to another hierarchy or no selected hierarchy.

**Comment by CarlyNel** [comment]
Hey Justin,

This is looking really good and I like your above additional changes.

One very minor piece of feedback in relation to "Add hierarchy name to all nodes rather than just inherited nodes"...
Some of the names are cut off at the very end (see below screenshot), so a suggestion might be to centralize or left align the hierarchy names on the nodes if possible. Hopefully that will resolve the issue. That being said, what would happen if the names was even longer? Will the text 'wrap" onto a new line like the setting in excel/google sheets?

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/cf336c7d-a976-4917-87f6-8aba8f50ff6f)

**Comment by justinlewis** [comment]
I created a ticket for that issue the other day that we'll be working on this week:
- https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/498

**Comment by CarlyNel** [comment]
Great! Thanks Justin. I'll go ahead and close this ticket then.
