### ISSUE TITLE
Drilling into hierarchies throws privilege error for Geo-Object Type data outside of the users org

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#465]
Justin talked with Chai about this and decided to patch 0.11.1 with:

1. keep the privilege checsks as is so that no one can see data outside of their org while in the Explorer
2. add messages letting them know why they can't access them.

The error message should say:
- "The data for the selected Geo-Object Type is managed by [MOHA] and set as private to their organization."

**Comment by SteeveEbener** [comment]
This might finally be implemented differently based on the discussion which took place just after the above message has been posted. Further information to follow

**Comment by justinlewis** [comment]
The description above mentions a patch but this was also released to the main codebase.
