### ISSUE TITLE
Need to extend the contact information section attached to an organization

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#466]
## User stories
1. As the RA of my organization, I would like to be able to contact the RAs of other organizations

## Problems this relates to
1. Communication and data exchange between organization 

## Proposed solution
1. Replace the "Contact information" field attached to an organization with the following set of fields and make them visible to the RAs of other organizations under settings:
- Contact first name
- Contact last name
- Contact first name (local)
- Contact last name (local)
- Contact position/function
- Contact email address
- Contact phone number

## Considered alternatives
1. None 

## Additional context
None

**Comment by rrowlands** [comment]
For ease of process and development, can we merge this ticket with #288?

**Comment by SteeveEbener** [comment]
We can. Closing this one and keeping #288
