### ISSUE TITLE
Show name and contact info of RC for a change request

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#481]
When accepting changes, RAs and RMs should see the name of the person and contact details of the RC to follow up in the request.

**Comment by justinlewis** [comment]
![Screenshot from 2020-12-07 21-27-41.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/5b53d0b2-ca1b-4e3c-a0b1-213a9de31488)

**Comment by SteeveEbener** [comment]
The name of the contributor is not appearing in the request, only its username => this ticket needs to be re-opened
