### ISSUE TITLE
Published instances of a private list not appearing in the window for the RA,RM having the curation mandate

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#484]
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The publishing of the instances of a private lists are not appearing in the window while the process bar indicate that the process has been successful (see screenshot below)

While such lists should indeed not be visible to other organizations, the RA and RM of the organization having the curation mandate over the list should be able to generate and consult them

**To Reproduce**
As the RA/RM:
1. Go to the list module
2. Set one of the list to be private
3. Open the list
4. Go to the published section
5. Click the "publish lists" button 
6. See error: The jobs is indicated as successful but there is no instances of the list in the window
    
**Expected behavior (clear and concise)**

The published instance of the private list are being generated and are visible to the RA, RM and RC of the organization having the curation mandate while not visible to the other organizations 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/101128092-dfc1fc00-3639-11eb-98c6-13af55449f83.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 86.0.4240.198 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
New tests performed on December 6th shows that actually it is not only for the private lists that the published instances are not appearing but also for the public ones. Try with National hospitals and catchment areas under staging

**Comment by rrowlands** [comment]
This issue was addressed in a different ticket according to @jsmethie

**Comment by SteeveEbener** [comment]
@rrowlands: Do you mean documented? If yes, could you please give me the ticket number to close this one or link it to the other one if needed? Thanks

**Comment by rrowlands** [comment]
According to @jsmethie this ticket was fixed in ticket #265 (https://github.com/terraframe/geoprism-registry/issues/265).

If it makes sense for testing purposes on your end then we can keep this ticket open.

(Additional related ticket is #403, https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/403)

**Comment by SteeveEbener** [comment]
Do you mean that the bug reported in the present ticket is supposed to be solved through the release of ve 13?

If that's the case, then we should anyway keep it open for the sake of making sure that this is working in that release

**Comment by justinlewis** [comment]
@steeveebener Yes we'll leave this "In Review" so it can be tested with Release 13

**Comment by SteeveEbener** [comment]
Tested under ve 0.13.0 and working => closing this ticket
