### ISSUE TITLE
Fields defined at the group level not appearing among the attributes of the Sub Geo-Object types

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#488]
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): Development

**Describe the bug (clear and concise)**
I created a health facility group and attached the different types of health facilities to it.

The "Manage attributes" button being not active for any of the sub geo-object types I created these fields at the group level (see first screenshot below).

These attributes should then appear for each sub geo-object types but this is not the case when opening their metadata but this is not the case (see second screenshot below). Same when you import data against the sub geo-object type in question

**To Reproduce**
As a RA:
1. Create a group
2. Attached Geo-Object types to this group
3. Create new attributes at the group level
4. Open the metadata profile for one of the Sub geo-object types
5. See error: the fields created at the group level are not in the list
6. Import data against the sub geo-object type in question
7. In the attribute matching window, see that these fields are not there neither

**Expected behavior (clear and concise)**
The attributes created at the group level are applied to each sub geo-object types

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/101274346-644a8100-37d8-11eb-83b8-b3c901df748b.png)

![image](https://user-images.githubusercontent.com/12602163/101274348-68769e80-37d8-11eb-844e-408c81ed13eb.png)

![image](https://user-images.githubusercontent.com/12602163/101274353-6c0a2580-37d8-11eb-912b-b3e39ede3648.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
@steeveebener We determined this was an issue where we where not updating the cache of the group members (only the group object). We're implementing a fix for the sprint 13 release but until then the workaround is to define all of the attributes on the group before adding group members to the group.

**Comment by SteeveEbener** [comment]
Just tested this under ve 0.13.0 and it worked => closing this ticket
