### ISSUE TITLE
DHIS2 OAuth

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#489]
Allow users to log into the CGR using logins provided via OAuth from a remote DHIS2 server.

The following documentation has been produced to support this usecase:
https://terraframe.atlassian.net/wiki/spaces/GGR/pages/1825701889/DHIS2+Oauth+Integration

**Comment by rrowlands** [comment]
Discussed on an internal conference call:

- Editing exiting user which has DHIS2 oauth integration is not pulling up existing information
- Multiple DHIS2 external systems is not well tested. Do we want to support this?
    @nmceachen says Yes
- Do we want to support allowing users to login via Oauth and also standard password or is it one or the other?
    @nmceachen says to disable standard password login if Oauth is enabled on the user
- What do we want the login UI to look like when logging in via DHIS2?
    @justinlewis is thinking something like this:

![image (3).png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/f61e068f-461f-4c4c-a8d2-292b18e012ac)
