### ISSUE TITLE
Status fields not appearing in the exploratory lists while appearing in the published ones

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#492]
**List the CGR information**
- CGR version: 0.12.2
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The status field is not appearing in the exploratory lists while it does in the published ones

**To Reproduce**
1. As any role
2. Go to list module 
3. Go to the view window for one of the lists (own organization or other)
4. Open the list under the published section and see that the status fields is there (first screenshot below)
5. Open the list under the exploratory section and see that the fields are not there

**Expected behavior (clear and concise)**
The status fields are appearing in both the exploratory and published lists

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/102334430-9ecacf80-3fc9-11eb-8ce8-e575457d75ce.png)

![image](https://user-images.githubusercontent.com/12602163/102334602-d6397c00-3fc9-11eb-86ad-3c0fde1cb546.png)

Note: I cropped the images to facilitate the visualization of the issue

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Google Chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
The cause of this isn't if the list is published or exploratory but rather when the list was first created.  If it was created before the requirement to include the status fields in the list was added to the system, then the list will not include those status fields. Delete that version of the list and recreate it if you want the new status fields.

**Comment by SteeveEbener** [comment]
Got it, thanks.

Closing this ticket
