### ISSUE TITLE
Allow for the upload of official documentation approving a change request

### ISSUE THREAD

**Issue by CarlyNel** [terraframe/geoprism-registry#494]
Taken from recent [Laos feedback](https://docs.google.com/spreadsheets/d/1VD9sTHAx5CukHyjTEH9--9GjVM-oLpJmpbw1AOmFTHw/edit#gid=876136817). For context, see the User Feedback Laos tab, row 8. 
We need to allow for the upload of approval documents, viewing and downloading thereof.

**Comment by CarlyNel** [comment]
Rica confirmed with the DPC: "they confirmed that they just want to upload the final letter. It’s not a per-requisite for approval and can be uploaded after (basically after all paperwork is signed off uploading that final document)"

**Comment by justinlewis** [comment]
Details:
- Both maintainers and the original RC who submitted the request can manage documents. 
- Documents can be uploaded, downloaded, and deleted.
- There is no limit to what kind of files can be uploaded.
- There is no limit to how many files can be uploaded.
- The presence or absence of a file does NOT prevent the ability to approve or reject the change request. 

![Screenshot from 2021-03-12 14-42-28.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/1213a339-6096-46be-bac6-feb4a425188a)
