### ISSUE TITLE
Deleting a hierarchy needs to change selected hierarchy

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#496]
Deleting a hierarchy while that hierarchy is selected needs to move to another hierarchy or no selected hierarchy.

**Comment by rrowlands** [comment]
As far as I can tell this is already working as expected. Which version / server was this issue detected on?

**Comment by justinlewis** [comment]
@nmceachen experienced this on Staging for v 0.13.0.  He deleted a hierarchy that was currently the selected hierarchy and it didn't shift to another hierarchy. I'm not sure exactly what happened.

**Comment by nmceachen** [comment]
The hierarchy I deleted was visible on the right after I had deleted it.

**Comment by rrowlands** [comment]
I will need more specific steps on how to reproduce this if we want to proceed with this ticket.

**Comment by jsmethie** [comment]
This was something I noticed and fixed without creating a ticket.  The source code now is:
`  public removeHierarchyType(code: string): void {
    this.hierarchyService.deleteHierarchyType(code).then(response => {

      let pos = this.getHierarchyTypePosition(code);
      this.hierarchies.splice(pos, 1);
      this.updateViewDatastructures();

      if (this.hierarchies.length > 0) {
        this.setCurrentHierarchy(this.hierarchies[0]);
      }
      else {
        this.currentHierarchy = null;
      }

      this.renderTree();

    }).catch((err: HttpErrorResponse) => {
      this.error(err);
    });
  }`

You can see its selecting a new hierarchy on delete
