### ISSUE TITLE
Rename SRA to System Administrator

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#499]
The SRA role was converted into a System Administrator in Release 0.13.0 but the name of the role wasn't changed. The role needs to be called System Administrator.

**Comment by CarlyNel** [comment]
Hi Justin, just calling out here that there is still a reference to the old SRA role in our user documentation. See below screenshot.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/264e67e5-b10b-4e48-a9cb-ac5070a8b4e8)

**Comment by CarlyNel** [comment]
Ok coming back to my above comment, I see that this ticket request is to change the name to _"The role needs to be called System Administrator"_. So is the above confluence reference to SRA incorrect? Where else in the CGR is reference made to this role?

**Comment by justinlewis** [comment]
@CarlyNel Thanks. I'm still working on the documentation but took a note to address this.

**Comment by CarlyNel** [comment]
Hi @justinlewis. I'm busy editing my system admin profile and have just noticed a reference to the old SRA role under "system roles"- screenshot below.

![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/fcfb77bc-7c99-4a67-a05e-71dda7042fb8)

**Comment by rrowlands** [comment]
Hi @CarlyNel 

This ticket is part of release 0.13.1, which has not yet been released to the staging server. Therefore you will not be able to test this ticket yet.

**Comment by CarlyNel** [comment]
My bad. Sorry @rrowlands. I didn't see the minor release number.
