### ISSUE TITLE
List Geo-Object Type label is being displayed in the code field after saving

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#501]
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
List Geo-Object Type label is being displayed in the code field after saving

**To Reproduce**
1. As an RA create a list.
2. After the list is created open the edit form.
3. Error: the Geo-Object Type label is in the code field when it should actually be the code of the list.

**Expected behavior (clear and concise)**
The value in the code field should actually be the code of the list.

**Screenshots**
Before:
![Screenshot from 2020-12-30 10-43-56.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/119bc1d3-b402-46f0-8104-22a796cbcf16)

After:
![Screenshot from 2020-12-30 10-44-29.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/8b4dad7e-2214-4dbd-97fe-22353c8f1703)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Tested under 0.13.1 and working. This ticket can be closed
