### ISSUE TITLE
As RC, can't add a new Geo-Object from the new geo-object modal (error message)

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#502]
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
When trying to add a new geo-object as an RC I got the following error message and the request has not been submitted:  "An unspecified error has occurred. Please try your operation again. If the problem continues, alert your technical support staff."

**To Reproduce**
As a RC
1. Go to the lists module
2. Open a list for a geo-object type on which the RC has the curation mandate 
3. Click the Add Geo-Object type button 
4. Fill as many fields as you want including the unique ID (still mandatory) and click the submit button
5. See error message: An unspecified error has occurred. Please try your operation again. If the problem continues, alert your technical support staff.

**Expected behavior (clear and concise)**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Just tested that under 14.7.  under demo. The error message does not appear anymore but seems there is still a serious problem because:
1. The Add new geo-object window remains open after clicking the submit button with no message saying that the request has been submitted + Unique ID and comment fields with the red border
2. I tried it twice and the ticket that got generated and is accessible to the RM (Request ID 70785504-3ae2-4ed0-a623-9de0740005cd) contains two parts, each part related to one of the attempt I made (see geo-object unique ID):
![image](https://user-images.githubusercontent.com/12602163/121802186-d01d1300-cc6d-11eb-8a0c-738bff617da7.png)

**Comment by justinlewis** [comment]
@steeveebener The change request functionality was mostly rewritten in Release 0.15.0 which may make what you posted your last comment invalid. Since the primary issue in this ticket is addressed I'll close this ticket but if the other issue (in your last comment) comes up with the new change request design please create a ticket. However, I don't see how that could be the case because the design is very different now.
