### ISSUE TITLE
"Reason" field not available anymore to the RC when submitting a change request or adding a new geo-object through the new geo-object modal

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#504]
**List the CGR information**
- CGR version: 0.13.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The "Reason" field, which is mandatory, is not included in the new geo-object modal when submitting a change request or adding a new geo-object (see screenshot below)

**To Reproduce**
As the RC:
1. Go to the lists module
2. View a list over which the RC has the curation mandate
3. Open the geo-object modal for one of the geo-object or add a new geo-object
4. Click the edit button
5. See the error: the "reason" field is not accessible

**Expected behavior (clear and concise)**
The "Reason" field is accessible and mandatory from the geo-object modal

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/103406683-7f6d9e00-4b96-11eb-81be-2b95a5232ff6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by rrowlands** [comment]
I also discovered and fixed a bug (unspecified error) when creating a new Geo-Object via change request.

**Comment by SteeveEbener** [comment]
Tested under 0.13.1 (staging). Result: field appearing with red border but can submit the request without entering anything in the field => Still not fully fixed

**Comment by justinlewis** [comment]
![Screenshot from 2021-01-14 18-50-52.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/46a5492a-55c7-48aa-8cbb-ad8fc24a6cd5)

![Screenshot from 2021-01-14 18-51-09.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/abb02484-51d9-4ec3-bd9b-434ae7c7c69c)

https://github.com/terraframe/geoprism-registry/commit/b12cd1b15f068fd9614e500058e7bafdf535535f

**Comment by SteeveEbener** [comment]
Tested under 0.13.2 and working. I am closing this ticket
