### ISSUE TITLE
Cannot create new GeoObject as change request

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#506]
Creating a change request to create a new GeoObject using the navigator as a registry contributor throws an unspecified error when submitting the form.

**Comment by rrowlands** [comment]
Better test coverage for this issue is recommended.

**Comment by SteeveEbener** [comment]
I guess you mean in the geo-object modal. If yes, tested in ve 0.13.1 in staging: no error message but you can submit the request without filling the reason field while it appears with the red contour
