### ISSUE TITLE
Hierarchy Manager: Deleting a hierarchy causes error when viewing related hierarchies

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#507]
To reproduce:
1. Start with a hierarchy (Administrative Divisions) which contains a GeoObjectType (TestGot)
2. Create a new hierarchy called TestHier
3. Add TestGot to TestHier
4. Delete the hierarchy TestHier
5. Open the Administrative Divisions hierarchy. View the related hierarchies for TestGot

The related hierarchies menu does not appear because an error occurs while displaying it.

**Comment by SteeveEbener** [comment]
Another example why directly deleting a hierarchy without taking into account the impact this has on the rest of the graph is not a good idea

**Comment by SteeveEbener** [comment]
What has then been implemented to address this issue?

**Comment by justinlewis** [comment]
@SteeveEbener Nothing has been implemented yet. The ticket is still open which means it wasn't released. I just removed the 0.13.1 release tag so it's less confusing.

**Comment by rrowlands** [comment]
The bug which was occuring in the front-end which was preventing the related hierarchies menu from displaying is now fixed. If the related hierarchy menu appears after performing the above steps, then this ticket is fixed.
