### ISSUE TITLE
Submitting a request for the creation of a new Geo-Object add an unrelated request to it

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#512]
**List the CGR information**
- CGR version: 0.13.1
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
Testing ticket #506 as the RC I added a geo-object for which I only entered the name and the unique ID for that Geo-object. I did not specify anything else, not even the parents.

When opening the request as the RM, there was actually two parts to that request:
1. One concerning the creation of the new geo-object (name and code)
2. One to set the parents of the geo-object while I did not enter that information in the initial request

**To Reproduce**
As the RC: 
1. Go to the list module
2. Open a list on which the RC has the curation mandate
3. Click the "Add geo-object" button
4. Enter the name and unique ID of the geo-object
5. Click the submit button (the reason field is not mandatory while the border line is red)
6. Log out as RC and log in as RM 
7. go to the change request module
8. Open the pending request submitted by the RC
9. See the two parts of the request (see screenshot below)

**Expected behavior (clear and concise)**
Only what has been submitted by the RC is converted into requests

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/104453115-e51e4900-55de-11eb-8eb5-d0f0dc9973c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by justinlewis** [comment]
Duplicate of part of this ticket:  https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/349

**Comment by SteeveEbener** [comment]
Good catch...starting not to remember what I already submitted...time for me to eat more fish I guess. Closing this ticket
