### ISSUE TITLE
Deleting a Geo-Object Type throws error

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#515]
When trying to delete a GeoObject on the left side menu, an error message appears: "The requested [Metadata Element] was not found. Please verify that all information was correctly entered in your request and try again." The data I am trying to delete still persists.

Reported by Marcus from CHAI.

[Sameen] I am also experiencing this error, even for geo-object types that are not part of any hierarchy/have any data associated with them
[Varshana] Also viewing this problem
[Rica] Experiencing this too

**Comment by rrowlands** [comment]
I am unable to reproduce this issue. Please include the following information:

1. A list of steps which, when followed, should produce the specified error
2. The specific role for which the steps should be performed as
2. The server on which the error occurs
3. The version of the software of which this was tested (can be found in the "settings" module).
