### ISSUE TITLE
Improve error message for bad hierarchy codes

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#517]
While creating a new hierarchy with the code "Health_Facilities", I received the following error message that could be rephrased to make it easy for the user to understand the problem:
"A instance of [Type Meta Data] already exists with values [net.geoprism.registry.graph], [Health_Facilities] for attributes [Package Name], [Type Name] - please choose different values."

Reported by Nafissatou at CHAI

**Comment by rrowlands** [comment]
The error message for duplicate GeoObjectType code is also similarly cryptic. I will address both in this ticket.

**Comment by rrowlands** [comment]
The new error message:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/6e21c251-5425-45b8-911e-86651397c273)
