### ISSUE TITLE
Geo-Object appearing in a list for a date when it still does not exist

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#519]
**List the CGR information**
- CGR version: 0.13.1
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
The Province of Orrostar in the Tolkien dataset has been established on April 20, 2007 => It has been added as a new geo-object starting from that date with the code TLK05

When you extract a list for a date before April 20, 2007 a record presenting the code TLK05 appears in the list as inactive while it should not even be there as the Province was not existing before that date (see screenshot below)

**To Reproduce**
As the Moha RA/RM:
1 Go to the lists module 
2. open the Province master list
3. extract an exploratory list for any date before April 20, 2007
4. See error: the TLK05 record appears on the list while the first instance for that Province starts on April 20, 2007

**Expected behavior (clear and concise)**
There is no record in the graph before the start date of the first instance of a geo-object because this geo-object does not exist before that date

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/105179993-f7f7c700-5b64-11eb-965b-2c08b02ab7db.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Google Chrome
 - Version: 87.0.4280.141 (Official Build) (64-bit)

**Additional context (if any)**
Linked to the management of inactivated records

**Comment by SteeveEbener** [comment]
The ticket has actually been addressed under 0.13.3. I just tested it under that version and it is working. I am closing this ticket

**Comment by rrowlands** [comment]
I have addressed a corner-case for this issue which caused it to occur again on staging.

**Comment by SteeveEbener** [comment]
Thanks. Is this included in release 14?

**Comment by SteeveEbener** [comment]
Is this actually implemented in release 14?

**Comment by justinlewis** [comment]
@steeveebener Yes what Rich was referring to in his last comment is in Release 0.14.0

**Comment by SteeveEbener** [comment]
Just tested under 0.14.0 and it is working. Closing this ticket
