### ISSUE TITLE
Issues with specifying parents in a hierarchy when using the new geo-object modal (editing an existing or adding a new geo-object)

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#525]
**List the CGR information**
- CGR version: 0.13.1
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
The following issues are experienced when specifying parents in a hierarchy when using the new geo-object modal (editing an existing or adding a new geo-object):
1. The name and code of the options are appearing twice (first screenshot below)
2. After selecting an option, the field is filled with the text [object Object] for a while before the selected option finally appears (Second screenshot below
3. Below a certain level the options are not consistent with the upper level (Shire level options part of Province TLK03 while the county and Province options selected before that where for Province TLK01 - See third screenshot below
4. The list of option is incomplete and the text for the last one at the bottom of the dropdown is cut (third screenshot below)

**To Reproduce**
As the Moha RA:
1. Go to the lists module
2. Open the Village list 
3. Click the edit button for one of the geo-object
4. Either click the edit button for that geo-object or add a new one
5. move down to the Administrative structure hierarchy (MOHA) and put it in the edit mode
6. Select the admin unit as per the screenshots below and see the errors mentioned here above

**Expected behavior (clear and concise)**
1. The name and codes of each option are only appearing once
2. The [object Object]  text should not appear in the field after selecting the option
3. The options presented are consistent with the upper levels in the hierarchy
4. All the options are available and the text is not cut 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/105296440-d34b3000-5bf4-11eb-9fff-aeb9a845915a.png)

![image](https://user-images.githubusercontent.com/12602163/105297906-2c1ac880-5bf5-11eb-9330-626664f7704f.png)

![image](https://user-images.githubusercontent.com/12602163/105298302-43f24c80-5bf5-11eb-94fa-add676e941d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest one

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Tested under 0.13.2:

Working as expected:
1. The name and code of the options are appearing twice
2. After selecting an option, the field is filled with the text [object Object] for a while before the selected option finally appears (Second screenshot below
4. The list of option is incomplete and the text for the last one at the bottom of the dropdown is cut (third screenshot below)

Not working as expected: 
3. Below a certain level the options are not consistent with the upper level (Shire level options part of Province TLK03 while the county and Province options selected before that where for Province TLK01. This is still happening as per the following screenshot:
![image](https://user-images.githubusercontent.com/12602163/106375386-7dca0c80-63c6-11eb-8c3d-9f9ed5404d2e.png)

You need to click twice in the field for the correct list of options to then appear as follow:
![image](https://user-images.githubusercontent.com/12602163/106375404-a7833380-63c6-11eb-9803-ed104cf02cbc.png)

**Comment by rrowlands** [comment]
I am unable to reproduce the behaviour you are describing for point number 3. Is there some different way to how you're selecting Hyarrostar in the autocomplete dropdown? Once I select my province, all I have to do is click once into the County field and it displays the correct results.

**Comment by SteeveEbener** [comment]
@rrowlands, my apologies for the late reply on this one.

I just tried again and get the same problem . What I am doing is just to click with the left click of the mouse in the county field and the dropdown that appears contains all of them, not only those from the Hyarrostar Province:
![image](https://user-images.githubusercontent.com/12602163/108819034-42051a00-75f5-11eb-9ef9-77595a49faa7.png)

It is only if I click on another field and then come back to the County one that the correct list appears:
![image](https://user-images.githubusercontent.com/12602163/108819139-68c35080-75f5-11eb-9610-02fc8431c91e.png)

I am also using Chrome, Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by rrowlands** [comment]
You are logged in as MOHARA I assume. The only other thing I can think is to test this on a Windows OS.

**Comment by SteeveEbener** [comment]
Yes, I am logged in as MOHA RA. Happy to let you access my computer if this can help

**Comment by rrowlands** [comment]
I just tested this on Windows OS, Chrome browser, still was not able to reproduce. I agree we'll have to either do a screenshare call or remote access to resolve this.

**Comment by SteeveEbener** [comment]
Let me know when you would like to do that

**Comment by rrowlands** [comment]
Does 9am March 9 or 8:30am any other day this week (MST) work for you?

**Comment by rrowlands** [comment]
Summary from meeting:

Our current working theory is that this issue happens if the user is moving faster than the system is able to make + receive requests to/from the server. It appears that after an object is selected a request is made to the server. If a lower-down dropdown is selected before that request returns, it appears to not have registered that the higher object has been selected.

**Comment by SteeveEbener** [comment]
I just tested the above under 0.14.0 and it is working. I am closing this ticket
