### ISSUE TITLE
Add Geo-Object Type label to top of sidebar in type focused explorer (Geo-Object modal)

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#527]
"It would be good to add the Geo-Object type on top of the new geo-object modal for the user to know on which type he is working"

Reported by @steeveebener

**Comment by justinlewis** [comment]
This is addressed in v 0.14.0

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/a2e2cb0e-2505-4c1e-a6e2-26655e4b9884)

**Comment by SteeveEbener** [comment]
Tested in 0.14.0 and working. This ticket can be closed
