### ISSUE TITLE
Collapse 'Context layer' menu by list type, as it is currently very long when you have several years

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#535]
As an RA or RM:
1. Go to List
2. Open a list with data, such as Community Health Workers
3. Click on View
4. Click on the Edit pencil icon next to any data item
5. Go to Hamburger icon on the map and click on Add Context Layers
6. Scroll through list

Reported by Sameen at CHAI

**Comment by SteeveEbener** [comment]
Only the contextual layers presenting a temporal validity close to the one of the list currently been looked at should appear in the list in question

**Comment by vrajasekaran18** [comment]
@justinlewis this might be addressed as part of the existing Explorer re-design?
