### ISSUE TITLE
Creation of synonyms for inherited hierarchies

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#541]
Our importer has the ability to create synonyms when a parent reference cannot be resolved. These synonyms are global and affect the way data is importer from that point forward. If a parent reference is specified for a parent in an inherited hierarchy, this synonym mechanism will not work as expected. Additionally, it could be argued that this mechanism is not desire-able as it may allow a user to modify the way data is imported for data that they do not own or manage.

This ticket is only relevant if #266 is also implemented, as the usecase of specifying parent context columns for inherited hierarchies currently does not work anyway.

**Comment by rrowlands** [comment]
The estimate of this ticket can vary wildly depending upon the implementation. If we want to solve this simply by disabling the ability to create synonyms for inherited hierarchies, then the estimate might be more in the range of 6. If we want to do some larger synonym refactor whereby we reduce the scope of synonyms to be specific to an organization or a hierarchy then the estimate is likely closer to 21.

**Comment by SteeveEbener** [comment]
This is an issue that should be discussed during a design session due to the impact such implementation could have
