### ISSUE TITLE
Disable ability for RC to drag nodes in hierarchy management widget

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#543]
Reported by Rica at CHAI

"It would be best to disable the functionality to drag Geo-Object types into existing hierarchies for RCs. Right now, an RC can try to drag a Geo-Object type into a hierarchy, and will be presented with a permissions error."

**Comment by justinlewis** [comment]
This was partially implemented. You are prevented from dragging types that are part of your organization but are still able to drag types from other orgs. 

- Tested on the 0.14.0 release

**Comment by rrowlands** [comment]
I also added logic which hides actions in the context menu which they do not have permissions (i.e. removing a GOT from a hierarchy, inheriting a hierarchy, etc.).
