### ISSUE TITLE
Allow RA to see who the System Admins are 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#545]
Reported by @steeveebener

As an RA I need to see who the System admnin is for a CGR instance

As the RA for an organization:
1. go to the settings module
2. See that the contact information of the system admin is not accessible

Expectation:  Put the system admin information as a new section under setting (before "Organizations").

**Comment by SteeveEbener** [comment]
Tested under 0.14.6. Working for the RA to see the SRA(s).

This being said, the RMs and RCs can now also see who the SRA is and I am wondering if this is appropriate. Any thoughts on this?

**Comment by justinlewis** [comment]
@steeveebener - To me it seems important for any role to know who the System Admin is so they can know who to ask for help if there is a system issue.

**Comment by SteeveEbener** [comment]
Fair point. This being said, I don't think it would necessarily be appropriate for a RC or even an RM to directly contact the System Admin. I think they should pass through the RA for any issue they encounter.

**Comment by justinlewis** [comment]
That sounds like an operational policy to me that a team could adopt if they choose that chain of command.

**Comment by SteeveEbener** [comment]
Fair enough. We can close the ticket then
