### ISSUE TITLE
All the change requests are appearing in the view after clicking the implementing a decisions button

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#548]
**List the CGR information**
- CGR version: 0.13.3
- CGR instance (e.g. a URL): Stagging

**Describe the bug (clear and concise)**
Once you click the "Implement decisions" button after having accepted/rejected a pending request from the "Pending" window all the requests (pending, rejected, accepted) are appearing in the window.

**To Reproduce**
As the RA/RM (for the MOH in Staging):
1. Go to the change requests module
2. Click the "Pending" tab (First screenshot below)
3. Open one of the "Pending" requests (Second screenshot below)
4. Accept or reject the request
5. Click on the "Implement decisions" button
6. See the error: all the requests are appearing in the window (under the pending tab) (third screenshot below)

**Expected behavior (clear and concise)**
When you implement the decision (accept or reject) on a pending request:
1. The request is directly moved to the corresponding tab (Accepted or Rejected)
2. What appears in the window are only the remaining pending request

Caveats: the possible integration of a button allowing for the RA/RM to perform some edit on the geo-object concerned by the change request before closing it might request for this action to happen before the request is being moved to the corresponding tab. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/108974246-3c283b00-76c0-11eb-8082-ec294da32d5d.png)

![image](https://user-images.githubusercontent.com/12602163/108974268-40ecef00-76c0-11eb-8647-d3e0019275dd.png)

![image](https://user-images.githubusercontent.com/12602163/108974396-65e16200-76c0-11eb-863c-b1440168ae3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 88.0.4324.190 (Official Build) (64-bit)

**Additional context (if any)**

**Comment by jsmethie** [comment]
Please retest this as I believe it was fixed when the change requests were redesigned.

**Comment by SteeveEbener** [comment]
Tested under 0.16.1 in staging and indeed working. I am closing this ticket
