### ISSUE TITLE
Error thrown when selecting second level of synchronisation config to DHIS2

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#551]
**List the CGR information**
- CGR version: 0.13.3
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
Selecting the Geo-Object Type for the second level of a synchronisation config throws 500 error.

**To Reproduce**
1. As an System Admin: Go to the synchronisation page
2. Click on the button to create a new synchronization config
3. Select Ministry of Health for the org
4. Select DHIS2 Hierarchy for the hierarchy
5. Select HMIS for the external system
6. Configure Level 1 as Geo-Object Type = country...
7. For Level 2 select Provincial Health Department for the Geo-Object Type
8. Look at the console for the error (see image below)

**Expected behavior (clear and concise)**

**Screenshots**
![Screenshot from 2021-03-01 19-11-17.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/65c09509-edf2-4075-b7e9-d49a6121c214)

![Screenshot from 2021-03-01 19-12-21.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/ba3ac5d2-5f3d-483a-b788-9a42b3978726)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version:

**Additional context (if any)**

Reported by Pedro from CHAI

**Comment by rrowlands** [comment]
This issue arose because this is the first time we have tested against a DHIS2 instance which has zero attributes. This ticket will be included in the next release, if you need a quick hack in the meantime, you can avoid this error by creating an attriubte (any attribute) in your DHIS2 server.
