### ISSUE TITLE
Add ability to modify a Geo-Object that's associated with a Change Request

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#553]
From @vrajasekaran18 -  "Following the approval/rejection of a change request, RMs are able to edit that geo-object - solution we discussed on improving navigation makes sense and we can see how users respond to it during the pilot. "

**Comment by SteeveEbener** [comment]
Is it possible to point to the solution that has been discussed? Is it the one proposed by the CHAI Team in Laos and which I described during one of our last design calls?

**Comment by vrajasekaran18** [comment]
@SteeveEbener yup it's the solution you recommended from one of the last design calls:

- RM's have to accept/reject and implement a change request
- There's a button/pop-up/some UI asking if the RM would like to make edits to that geo-object
- If the RM clicks yes the RM is redirected to the geo-object editing window where they can edit the geo-object directly
	
Disclaimers:

- This solution is different to bringing back the edit functionality that was removed in Sprint 13
- We won't have visibility of edits the RM makes (this should be fine as we don't anyway at the moment, as an RM can make changes directly in the geo-object window)

**Comment by SteeveEbener** [comment]
Thanks Varshana

**Comment by justinlewis** [comment]
This is where I'm at with this. Reading Varshana's notes above I didn't realize you talked about a modal popping up.  Either way I'm assuming that quick access to edit the Geo-Object is useful for approved actions after (days, weeks, months) the initial approval so I put a link on the approved action itself. See the link in the bottom right:

![Screenshot from 2021-03-03 15-39-39.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/fdc7325a-983e-4f2d-b4c5-dfdde7da9953)

Clicking this link will bring you to the Explorer with the Geo-Object selected and the ability to edit. 

![Screenshot from 2021-03-03 16-06-01.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/27d026cb-f72c-4ce0-82e2-924eb6ce7d15)

@steeveebener and @vrajasekaran18 Does this align with what you are expecting?

**Comment by justinlewis** [comment]
#555

**Comment by SteeveEbener** [comment]
@justinlewis. Thanks for that.

Some feedback:
1. This is not only meant to be implemented for approved but also rejected requests
2. Ideally, the possibility to edit the geo-Object in question would not be given once the request has been moved to the approved or rejected section but while you are still in the pending request'
3. Here is a potential flow:
    a. The RA/RM accept or reject the request
    b. When he click on the "Implement decisions" button, the decision(s) are being implemented and a window with the following message appears: "Do you want to make any further edits on this particular geo-object?" with two buttons "Yes" and "No"
      - If the RA/RM clicks on yes then the geo-object editing modal appears and he can perform the edits. He he brought back to the change requests module main window once done
      - If the RA/RM clicks on No then the message windows close and he is back to the change requests main window 

Don't hesitate to let me know if this is not clear.

**Comment by justinlewis** [comment]
This implementation in v 0.14.0 follows @steeveebeners suggested flow.
