### ISSUE TITLE
It should be possible for different geo-objects to have the same unique ID as long as they are of different types

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#558]
## User stories
1. It is very likely that different sectors will be using the same coding scheme for different geo-object types
2. There is a need to be able to upgrade a geo-object from one type to the other 

## Problems this relates to
1. The management of an increasing number of geo-object types as the CGR is being used across sectors
2. The management of changes through time

## Proposed solution
1. Allowed for the same unique ID to be used by different geo-objects as long as they are from different geo-object types

## Considered alternatives
1. None

## Additional context
Extracted from ticket #509

**Comment by SteeveEbener** [comment]
Just tested under 0.17.2 (demo) and it is not working for geo-objects that are part of a group: I tried to create a health center with unique ID HF0003 (ID used by a health post) and got the following error message: "An instance of [] already exists with [HF0003] as the value for Code - please choose a different value."

When using that same unique ID for a geo-object type not part of the group (CHW for example) then the new geo-object is being created 

=> It seems the problem is present for geo-object types part of the same group which is the use case for which we need to be able to use the same unique ID when there is an upgrade for example

**Comment by justinlewis** [comment]
@SteeveEbener We believe this was an issue with the data patch we had. A fix was rolled out with release 0.18.0 so please re-test.

**Comment by SteeveEbener** [comment]
Tested under 0.18.0 and you can indeed now create a geo-object presenting the same unique identifier than another geo-object of a different type.

I am closing this ticket
