### ISSUE TITLE
Unable to update localization file in the CGR

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#559]
**List the CGR information**
- CGR version: v0.13.3
- CGR instance (e.g. a URL): Laos instance

**Describe the bug (clear and concise)**
If a user tries to update the localization file in CGR by uploading a new version, the new translations are not viewable in the CGR. A user does not get an error message if the upload has failed or if it's successful. As such we're unclear if it's the upload that's failed or a bug with the translations appearing in the CGR. We're guessing it's the former.

**To Reproduce**
1. Download the existing localization file
2. Edit the file
3. Try and upload the new file
4. Translations are not viewable

The localization file the team have tried uploading is attached. [https://app.zenhub.com/files/142912671/61aba108-bfa3-4b57-8509-157600ffc1a4/download](https://app.zenhub.com/files/142912671/61aba108-bfa3-4b57-8509-157600ffc1a4/download)

The team tried uploading the localization file on Monday (1st March)

**Expected behavior (clear and concise)**
The user is able to upload updated localization files with the changes reflected in the CGR

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 91

**Additional context (if any)**

**Comment by rrowlands** [comment]
From what I can tell, the localization spreadsheet that you uploaded did indeed work. When I switch to Laos locale and view a user in the user management screen, I can see that the "Registry Administrator" role's label has changed. I took this screenshot on the Laos server:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/d28268ec-d5d1-4050-a1eb-a0336f1b0cec)

I took a look at the spreadsheet you uploaded here and I noticed that only the last tab in the spreadsheet (Registry Metadata) has been filled out. A lot of the labels on the Registry Metadata tab are used in a somewhat limited capacity, i.e. various exceptions or labels for very specific roles. If you start with localizing the "UI Text" tab first you will notice a lot more difference after importing.

If the import is not successful it will tell you. You can see that here:
![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/3c040699-d97f-4589-9c1c-dfb1b92f0456)

And lastly, it might be necessary for some of these changes to display to log out and then log back in again.

**Comment by justinlewis** [comment]
Blocked by me because I need to do an inventory of any localization keys that might not be used in the CGR so we can filter them out of the exported localization spreadsheet.

**Comment by justinlewis** [comment]
I went through the localization strings that are exported from a v 0.14.0 CGR instance and identified about 500 which we can remove because they refer to components of GeoPrism that the CGR doesn't use. Next we'll work on filtering those out.

**Comment by rrowlands** [comment]
I have created a related issue, #585, which will also be included in this release which should hopefully help with the importing.

**Comment by vrajasekaran18** [comment]
@justinlewis I've tried uploading a new excel spreadsheet (attached below) and am getting the following error message: ![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/d219cec2-5537-472b-be22-660777634292)

[https://app.zenhub.com/files/142912671/64b15d13-6338-46a2-b2b3-ef06175e7729/download](https://app.zenhub.com/files/142912671/64b15d13-6338-46a2-b2b3-ef06175e7729/download)

**Comment by justinlewis** [comment]
@vrajasekaran18 This is fixed in release 0.14.1 with [ticket #585](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/585).

**Comment by vrajasekaran18** [comment]
@justinlewis Thanks for the update - could you test on stage that it's working and the files uploading okay? I've just tried with my SA privileges and realise I'm not SRA. Just want to make sure that localization is working as expected :)
