### ISSUE TITLE
Inconsistencies in UI/UX for change request forms (between master list manager and change request manager)

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#56]
**Describe the bug**
Change request forms are not consistent

From "Master List Manager" module: 
- The “Reason” field is missing and should be shown

From “Change Request Management” module:
- Form should show tabs across top for Attributes, Parents, and Geometry, as shown in the other two modules
- Geometry widget should be in the Geometry tab, not shown in-line in the form
- Change over time edit UI via Change Request Manager only shows the default locale labels (does not show other locale labels)

Across both master list manager and change request manager
- Consider labeling submit button as “Submit as Change Request” instead of “Submit”, to clarify that this will be submitted as a change request that must be approved

**To Reproduce**
1. Create a change request via the "Change Request Manager"
2. Create a change request by clicking on the edit icon for an item in a master list via the "Master List Manager"
3. Compare the UI for both

**Expected behavior**
Both change request forms should be identical in UI/UX

**Screenshots**
See screenshots captured in test case doc here: https://docs.google.com/document/d/1APKCc85nlDt9xwKrbZHyq5UJ0bqJ2QU7XsUWyPDhya0

**Desktop (please complete the following information):**
Device Make and Model/Browser: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
Operating System and Version: Windows 10

**Additional context**

**Comment by justinlewis** [comment]
Related: https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/81

**Comment by justinlewis** [comment]
Closing because this module has changed significantly since this ticket was created and Sprint 15 will include a significant overhaul of this functionality with the inclusion of many of these suggestions.
