### ISSUE TITLE
Start and End date not appearing correctly in the scheduled job module when importing data

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#560]
**List the CGR information**
- CGR version: 0.13.4 
- CGR instance (e.g. a URL): Production

**Describe the bug (clear and concise)**
The start and end date information appearing in the scheduled job module correspond to the import date and not the start and end dates specified at the moment of the import (see screenshot below)

**To Reproduce**
As a RA/RM:
1. Go to the import module
2. Import the data for one of the geo-object type remembering the start and end dates you specified
2. Open the scheduled job module
3. See error: the start and end date corresponds to the import date (day), not the start and end dates specified at the moment of the import

**Expected behavior (clear and concise)**
The start and end dates appearing in the scheduled job corresponds to the information entered at the moment of the import and not the day when the import was performed

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/110232253-ab6f1c00-7f57-11eb-8990-aa319bf14785.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest version

**Additional context (if any)**

**Comment by justinlewis** [comment]
We might need to change thsee labels. They aren't the start/end dates for the uploaded data. They are the dates for when the processing started and when the job completed.

**Comment by SteeveEbener** [comment]
@justinlewis . Thanks for the information. I would then argue that having the start and end date specified for the temporal validity of the information being uploaded would be much more useful than the dates for when the processing started and when the job completed (could it really take more than 24 hours?).

**Comment by justinlewis** [comment]
I changed these labels to 
- Job Start Date
- Job End Date

We need these so the user and anyone supporting them can have some idea of how long the job is taking. When working with datasets of 500,000 rows or more the job does take quite long. We've done some performance improvements so most jobs would be less than 14 hours but it's possible to upload a much larger dataset.

**Comment by SteeveEbener** [comment]
This then mean that the start and end date would be the same in the case you are describing (less than 24 hours), right?

I honestly continue not to see what is the value of this information compare to knowing the temporal validty of the information that has been uploaded.

**Comment by justinlewis** [comment]
This is a separate need from temporal validity of the data. This is to show the overall period of time it took to process the data. For example look at this screenshot of staging. Here you can see that the job at the top was started (the import was started) on October 2020 but it wasn't completed until March of 2021. That might be because there where issues that needed to be resolved. A job that runs with no issue will likely complete in less than a day but if there are issues and exteranal conversation is needed this can extend beyond a day. 

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/bb84688e-9949-48a9-b6c7-8bd7c0992f61)

**Comment by SteeveEbener** [comment]
Ok, closing this ticket then
