### ISSUE TITLE
RM can't inactivate a geo-object over a given period of time

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#561]
**List the CGR information**
- CGR version: 0.13.4-SNAPSHOT
- CGR instance (e.g. a URL): Production

**Describe the bug (clear and concise)**
I tried to inactivate a geo-object as the MOHA RM but got the error message reported in the second screenshot below when trying to do this.

There is no problem when doing the same thing as the MOHA RA

**To Reproduce**
As a MOHA RM:
1. Go to lists module 
2. Open a list over which the RM has the curation mandate
3. Select one of the geo-object and create a new inactive instance for a recent period
4. Click the submit button  
5. See the first issue: the information is reported like if it was a change request (first screenshot below)
6. Click the submit button
7. See the error message (second screenshot below)

**Expected behavior (clear and concise)**
The RM can inactive a geo-object from a given date

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/110235916-d2d0e380-7f6d-11eb-8c7e-e232c1ce2880.png)

![image](https://user-images.githubusercontent.com/12602163/110235709-833de800-7f6c-11eb-8611-28a2a612cd8e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google chrome
 - Version: The most recent one

**Additional context (if any)**

**Comment by rrowlands** [comment]
The issue described at step 5 will require a larger conversation.

Which GeoObject and GeoObjectType is this happening on?

**Comment by SteeveEbener** [comment]
It was with the Province of Andustar but the error message does not appear anymore this morning and this either with this geo-object or any other ones and this across types 

Regarding step 5, the mention of the change is now appearing across all the roles (don't know what happened yesterday)

=> I will close this ticket and re-open it in case it happens again
