### ISSUE TITLE
Strip out white space when adding code to new Geo-Objects

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#566]
This was discovered in [Ticket #509](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/509) by @steeveebener

**Comment by rrowlands** [comment]
Are there any other characters we would like to prevent ?

**Comment by justinlewis** [comment]
The server prevents certain characters based on a Java/PostgreSQL standard already. Spaces and dashes are the two that seem to come up the most as surprising people in testing. If the Jave/PostgreSQL characters are clearly documented from those environments we could consider replicating those in the frontend but only if we have long term confidence in maintaining the rules on the frontend to match those backend standards. I believe UTF-8 is also handled by the backend but I could be wrong.

**Comment by SteeveEbener** [comment]
Space is indeed the most expected case as it is the one which is visualy difficult to identify

**Comment by SteeveEbener** [comment]
Tested under 0.14.6 and working. This ticket can be closed
