### ISSUE TITLE
Add sort and filter functionality to Master List Manager to be able to sort and filter master list versions by date or date range

### ISSUE THREAD

**Issue by dtreatman** [terraframe/geoprism-registry#57]
## Problems this relates to
**Is your feature request related to a problem? Please describe.**
The list of master lists over time is not sorted by date which makes it difficult to find the master list for a specific date

## Proposed solution
**Describe the solution you'd like**
Automatically sort the list of master lists by "For Date" column and ideally have the ability to manually sort or filter the list of master lists by all viewable columns (For Date, Published Date), similar to the sort and filter functionality available within a single master list version

## Considered alternatives
**Describe alternatives you've considered**
At minimum, having the list of master lists sorted by "For Date" (even if no manual sort or filter functionality) would be helpful

**Comment by jsmethie** [comment]
No longer valid
