### ISSUE TITLE
Submitting a CR as an RC if you have an RM role somewhere else

### ISSUE THREAD

**Issue by rrowlands** [terraframe/geoprism-registry#570]
If you have an RM role on Geo-Object A, and an RC role on Geo-Object B, the system allows you to submit edits to Geo-Object B. This user should only be allowed to submit change requests (not edit).

**Comment by SteeveEbener** [comment]
Is this ticket close because the issue has been addressed? If yes, in which version will the fix be available for me to test it? Thanks

**Comment by justinlewis** [comment]
@SteeveEbener - Yes it was closed because it was released and tested. You can tell which release it's in under the Releases section of the sidebar on the right.

**Comment by SteeveEbener** [comment]
Thanks :)
