### ISSUE TITLE
Add warning to attribute version widget when there is a gap in the time ranges

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#571]

**Comment by justinlewis** [comment]
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/985dc535-692a-40f3-add3-dbd9e968dc7a)

**Comment by SteeveEbener** [comment]
Tested under 0.14.6 for both the RA/RM creating new attribute instances in the lists module or for the RC to submit a change request from the list or the change requests module. This ticket can be closed according to me.
