### ISSUE TITLE
RC unable to view attribute details when adding a new geo-object

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#574]
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
1. As an RC go to the list module
2. Click add a new geo-object
3. Fill out information on default locale
4. As you fill information for each attribute, you can't view the information submitted (in the screenshot below I've completed the defaultLocale, Geo-Object unique ID and staff gender)
5. Once the geo-object has been submitted, the information still does not appear in the window (The RM is able to see all attribute details apart from status field when reviewing a change request)

**Expected behavior (clear and concise)**
As the RC completes attribute details, the RC is able to view the information inputted.
When reviewing a change request, the status field information is displayed (whether the RC or RM is reviewing their submitted change request)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/92297b71-0051-4a79-8606-565e71f4d685)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version:

**Additional context (if any)**
* This only happens when the RC is adding a new geo-object

**Comment by justinlewis** [comment]
I think what you're seeing is a mis-match between when the list data you're looking at when creating the object. 

1. What time period did you set for the attributes? 

Looking at your screenshot it appears the list data you're looking at is valid on 01/02/2010 meaning the list and corresponding map view will only show data that exists on that day. If the attributes you are creating do not have data for on or before that date the map view you're looking at is filtering it out. This is like when you're looking at the details of a change request and you adjust the date picker behond or before any values in the attributes exist. The Geo-Object form goes blank in that situation. This is essentially what I think is happening with you. Try doing this again but set the date range of your attribute to 01/01/2000 - current. 

Please let me know if this is or isn't the issue.

Either way I can see how this is confusing. I'm going to think about a way to make this more clear and am more than happy to hear if you have any ideas.

**Comment by vrajasekaran18** [comment]
@justinlewis Thanks I created a new attribute that covered the time period of the list and the information was shown. Agree this will be confusing and one for us to determine how to make it clearer for users down the line.

**Comment by justinlewis** [comment]
@vrajasekaran18 - Moving back to backlog so we can investigate a simple solution for this. I'm thinking we can adjust the date picker to a date that is valid for at least one of the attribute values.

**Comment by justinlewis** [comment]
@vrajasekaran18 I marked this as invalid because the new design of the map sidebar in release 0.15.0 shows all the attribute versions so this isn't an issue anymore. Let me know if I'm incorrect at all.
