### ISSUE TITLE
RC is able to add maintainer notes in a pending change request

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#575]
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
RC is able to edit the maintainer notes section in the change request module

**To Reproduce**
1. As a RC go to the Change Request module
2. Click any change request in pending state
3. RC is able to add maintainer notes

**Expected behavior (clear and concise)**
RC is unable to add maintainer notes to a change request

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/f70c0f58-7eaa-4bf8-af21-45e1832f23bb)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser: Google Chrome
 - Version:

**Additional context (if any)**

**Comment by rrowlands** [comment]
I'm guessing we also want RC's to be able to change their own contributor notes on CR's they've authored? What about after it has been accepted?

**Comment by vrajasekaran18** [comment]
@rrowlands Once a change request has been accepted or rejected the RC should not be able to edit their own contributor notes. 

You've raised a good point and I've just checked on an accepted change request, when the RC opens up the details the edit button is visible and they are able to submit changes to an accepted change request. The expected behaviour should be once a change request is accepted/rejected the RC is not able to edit that change request (i.e. they are only able to edit the change request when it's in pending state).

**Comment by SteeveEbener** [comment]
I agree with Richard

**Comment by rrowlands** [comment]
I have thoroughly audited and improved permissions across the entire change request stack. Please do rigorous testing for this ticket to ensure that required features still work as expected.
