### ISSUE TITLE
When RC edits a pending change request the only option is to cancel

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#576]
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When an RC tries to edit an attribute in a pending change request, the only option they have is to cancel the action

**To Reproduce**
1. As a RC go to the change request module
2. Click on a pending change request
3. Click details of the geo-object
4. Click edit
5. Click on an attribute (e.g. status)
6. The only option a user has is to click cancel (if a user makes a change and clicks cancel, the change persists)

**Expected behavior (clear and concise)**
It is clear to the user what changes are getting saved vs. getting canceled. We use cancel to help the user return to the previous screen which may be confusing as the user may interpret cancel as the edit has been cancelled.
Elsewhere in the CGR the user has to click save for a change/edit to be enforced, we should keep consistency here - save to save the change and return to previous screen, cancel to cancel the change and return to previous screen.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/aeec5426-849c-412a-9490-07c87f1180a7)

**Desktop (please complete the following information):**
 - OS: Microsoft 10
 - Browser: Chrome
 - Version:

**Additional context (if any)**

**Comment by justinlewis** [comment]
Changed the "Cancel" to "Close". While looking at this issue I noticed that the "New instance" and "Submit" button also where not showing and so fixed that. 

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/e0215031-9133-4ffd-85e6-7e20e351dff5)

Regarding save I don't recall anywhere we are using save (definately could be wrong). We use "Submit" a lot. But honestly save does make more sense in this case.

**Comment by justinlewis** [comment]
After thinking about this more I remembered the reason we standardised on "submit" is because in this case "save" might give the impression it's saving those versions to the database but that doesn't happen until the submit the actual request.  We could say "Set Configuration" but I'm not sure that makes it much more clear.

**Comment by vrajasekaran18** [comment]
Do we use "Set Configuration" elsewhere? If we haven't perhaps we keep to submit for now but then have a think about standardising the different action buttons across the CGR so as not to confuse the users?

**Comment by SteeveEbener** [comment]
Set configuration is not clear neither. Submit makes sense for any actions initiated by the RC.  

According to me the confusion comes when we use "submit" for action that are actually resulting in a direct change in the graph => See feedback No 23 in the user feedback google spreadsheet.

**Comment by justinlewis** [comment]
I talked with Varshana about this and we agreed to keep it as submit for now to keep it consistent with the rest of the app.

**Comment by SteeveEbener** [comment]
I am all for consistency but the issue here is one of clarity and Varshana actually agreed with that as you can see in cell Q24 of the "Partner Feedback" sheet of the User Feedback google spreadsheet => This issue should not have been closed
