### ISSUE TITLE
If an RC reverses any changes to a change request while in pending state, the change request is not deleted

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#577]
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
An RC has submitted a change request to change a geo-object status from active to inactive. While the request is pending review, the RC edits the change request and reverses the change (i.e. deleting the inactive change), the change request is not deleted and is shown to the RM for review.

**To Reproduce**
1. As a RC Go to the change request module
2. Click on a pending change request > details > edit
3. Reverse any changes made > save
4. See error: the change request remains there in pending state (log-in as RM and see that the change request is still there)

**Expected behavior (clear and concise)**
If an RC has reversed all changes in a change request, the change request is deleted as no further action is required OR make it possible for an RC to delete a pending change request they have submitted.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:

**Additional context (if any)**

**Comment by justinlewis** [comment]
Shouldn't they explicitly delete the request vs try to revert their changes? Automatically deleting a request in this situation could be very risky. When it comes to managing data I'd much prefer to lean on the side of being very explicit when deleting data. One approach that might address this is to detect when all the changes have been reverted and then put a message on the UI saying something like:

"There are no changes to save. All the proposed changes in all the actions for this change request have been reverted to the original state of the Geo-Object when this change request was submitted. Please delete or reject this change request."

**Comment by vrajasekaran18** [comment]
RC is able to delete an accepted/rejected change request. RC should only be able to delete a pending change request

**Comment by SteeveEbener** [comment]
Reverting all the changes that the RC would have included in the request is equivalent to not submiting a request in the first place, right? => This is equivalent to deleting the request and this is what should be taught to the RCs

If the RC in question has not received the training, or forgot, having a message indicating to the RC that this is the equivalent of a delete and suggest to proceed with such a delete is a good idea. There is just no need to specify "reject" as this applies only to a RA or RM.

**Comment by vrajasekaran18** [comment]
Hey Steeve, this is definitely my bad as a user - I didn't see the delete button in the change request module and ended up reverting changes to see what happens! I agree with you and Justin that we'll train users to delete a pending change request rather then revert the changes. The one thing we realised this morning is that the RC has the option to delete the change request once it's been accepted/rejected (which shouldn't be the case).

**Comment by justinlewis** [comment]
Based on conversation in this thread and outside of this ticket I'm marking as invalid.
