### ISSUE TITLE
Add support for Google Analytics tracking

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#578]

**Comment by SteeveEbener** [comment]
Any chance someone could describe what this is about? thanks

**Comment by justinlewis** [comment]
It's a standard analytics tool for tracking website visitors so you know if anyone's on the site at a given time (useful if planning an update), how many people visit the site, and what pages of the site people click through. This Google Analytics account that tracks the data is configurable in the CGR so each instance can use different Google accounts or opt out entirely.

**Comment by SteeveEbener** [comment]
Great. Thanks Justin
