### ISSUE TITLE
Non CGR specific roles 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#58]
**Describe the bug**
There are two roles that are appearing in the list (administrator and Data manager) that do not correspond to a CGR role.

Desired functionality: remove these two roles from the list of user roles.

**To Reproduce**
1. Go to the manage users page
2. Click on edit for a users
3. View the available roles.

**Expected behavior**
A list of roles based on the CGR spec

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dtreatman** [comment]
Agree on prioritizing this fix. And also, please add the new role "Super Registry Administrator"

**Comment by SteeveEbener** [comment]
The SRA is created and managed at the GeoPrism level 

=> The SRA role can't be managed by an RA or an RM and should therefore not appear in the list of the options for the account manager

This being said, the SRA might appear to all the RAs/RMs  in the list of accounts in order for all of them to contact the SRA if needed.

**Comment by justinlewis** [comment]
Adding or modifying of roles for the upcoming sprint is managed in other tickets.  This ticket should focus specifically on removing non CGR roles.

**Comment by justinlewis** [comment]
I believe Data Manager has been removed in release 0.7.0.  I'll to verify.

**Comment by justinlewis** [comment]
This has been fixed in the 0.7.0 release.

**Comment by SteeveEbener** [comment]
This ticket has been implemented and can be closed
