### ISSUE TITLE
When editing a geo-object, valid on is mis-spelt as vallid on

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#580]
**List the CGR information**
- CGR version: v0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
Spelling mistake: valid on is mis-spelt as vallid on when editing a geo-object from list view

**To Reproduce**
1. As a RM Go to a list
2. Select a geo-object for editing
3. See error: valid on is mis-spelt as vallid on

**Expected behavior (clear and concise)**
Correct spelling of valid on

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/fb9acc02-0bb9-41ba-b8ea-ecdfa17d1b1a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:

**Additional context (if any)**

**Comment by justinlewis** [comment]
Good catch

![Screenshot from 2021-03-19 11-10-41.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/6036caf6-d3a3-4728-8320-db0651fcd23a)
