### ISSUE TITLE
Parent specification does not take changes through time into account when adding a new geo-object or modifying one

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#581]
**List the CGR information**
- CGR version: 0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When you add a new Geo-Object, or want to modify the parents of an existing Geo-Object, the start and end date you specify does not take into account the changes that occured in that hierarchy over that period of time. 

**To Reproduce**
As a RA/RM for MOHA
1. Go to the list module
2. View the village list
3. Click the "Add Geo-Object" button
4. Click the edit button for the Administrative structure hierarchy (MOHA)
5. Create a new instance
6. Specify 01.01.2000 as start date and 01.01.2007 as end date. 
7. Click in the Region (MOHA) field and choose the Tolkien Region
8. Click in the Province (MOHA) field and choose the Andustar one (TLK01)
9. Click in the County (MOHA) field and choose the Eldalonde one (TLK0102)
10. Click int he Shire (MOHA) field and look at the scroll down list that appears (Screenshot below)
11. See the error: several of the Shire active over the 01.01.2000 - 01.01.2007 period are not appearing in the list (TLK0102002, TLK1002004, TLK1002006, ...) 

Redo the same as the above until point 5 and then:
6. Specify 01.01.2008 as start date and present as end date. 
7. Click in the Region (MOHA) field and choose the Tolkien Region
8. Click in the Province (MOHA) field and choose the Andustar one (TLK01)
9. Click in the County (MOHA) field and choose the Eldalonde one (TLK0102)
10. Click int he Shire (MOHA) field and look at the scroll down list that appears (Same screenshot below)
11. See the error: Some of the Shire that are appearing in the list (TLK0102003, TLK1002005, TLK1002009, ...) are not active over the 01.01.2008 to present period

**Expected behavior (clear and concise)**
The parents that are apperaring at each level are those being active over the period that has been specified

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/112154367-2b1b0d00-8c1f-11eb-99c0-380087f619d5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version: the latest one

**Additional context (if any)**

**Comment by jsmethie** [comment]
Try typing in Bagsa, Banao, or Busacio.  They appear as options.  As far as I can tell the list of options is not sorted at all.

**Comment by jsmethie** [comment]
Create a new ticket for the date issue

**Comment by SteeveEbener** [comment]
Just tested on 0.19.0 with Nate and here is the conclusion for the record:
1. There is now a logic in the dropdown (first 10 options in alphabetical order)
2. The selection of parents is based on the existence of such parent for the validity period that has been specified.

This ticket could indeed be closed

P.S.: new issue identified: The dropdown is not appearing for the geo-object type at the top of the hierarchy, even when typing some characters
