### ISSUE TITLE
Geo-object inactive from a given date appearing in the list, on the map and in the exported list or shapefile after that date

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#583]
**List the CGR information**
- CGR version: 0.14.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)** 

Geo-objects inactive from a given date are appearing in the list, are appearing on the map below the other active polygons in the geo-object editing modal and are included in the exported list or shape file (unless you first filter the records by status and keep only the active ones)

**To Reproduce**
As the RA/RM Moha in staging
1. Go to the lists module 
2. View the exploratory Shire list for 20/04/2007 (this is a the list after from the day changes have been implemented)
3. See error 1: the Shires inactive starting from 20/04/2007 are appearing in the list
4. Click the edit pen for any of the inactive geo-object (Gumabao for example)
5. Zoom out on the map
6. See error 2: the active and inactive records for that date are overlayed on top of each other (less transpratent area, see screenshot below)
7. Go back to the list and export it in shapefile format
8. Open the shape file in a GIS software (QGIS, ArcGIS)
9. Open the attribute table of the shape file and see that the inactive records are there (overlaping polygonson the map)

**Expected behavior (clear and concise)**
The geo-object that are inactive from a given date are by default not appearing in the list, on the map in the geo-object editing modal or included in the exported spreadsheet or shapefile 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/112268537-18054d00-8cb2-11eb-8e2d-e85247e3f2d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest one

**Additional context (if any)**
- This issue is partly documented in ticket #495 but I think important to have it documented separately as well as the case is a bit different and this is important from a demo perspective
- this issue is independent from the new design for the lists/Spatial data module
- the overlap on the map in the geomodal and the exported shapefile only happens if you have:
   - a first geometry that you upload for the 01/01/2000 - present period
   - You inactivate the Shires that should be inactivated from 20/06/2007
   - Then you update the geometry for the 20/04/2007-present period
- The overlap on the map in the geomal does not happen, and the polygons are not in the shape file, if each separated shapefile for each period is uploaded with the start-end date for each of these periods. This being said, the inactive records remains in the list and are included in the attribute table of the exported shapefile

-

**Comment by SteeveEbener** [comment]
The ticket in question was #367 

In this case the issue was that the geo-obejct was fully inactivated, meaning over the entire time period covered by the data in the graph. This case corresponds to a record inactivation amd the need to have these records stored in a separated table (see slide 1 of the following google slides: https://bit.ly/2Wkb1zR . 

The case here correspond to what I am referring to as a "geo-object instance inactivation" in that same slide deck and would not be an issue as it would always be accessible over the time period(s) during which it has been active. 

This is key in the case of geo-object types like administrative divisions because once inactivated they are not being re-activated again and should therefore not appear at all in the list since the date of inactivation.

Two approaches can be considered in the case of geo-object that can be "temporarily closed" (health facility that still exists but which is currently closed by lack of staff for example):
1. The same approach as above is applied but then it is not possible for the RA/RM to see that there is a health facility that could re-open (would generally apply to the current date and not a past date). This being said he would most probably know about this facility, be able to find it through the active instance of the record and then see that the reason for inactivation is "temporarily closed"
2. the "temporarily closed" is captured as part of the status information attached to an active record in the way that is described on slide 3 for other cases like planned, under construction,...

I hope this clarifies. Don't hesitate to let me know if this is not the case

**Comment by SteeveEbener** [comment]
A complement to my previous comment: Inactive geo-objects are also appearing as options in the dropdown menu aiming at selecting a parent for the period over which they are actually inactive. An example:

The Everholt village (TLK0101013001) changed Shire on 14.09.2012 => is inactive after that date and its unique then becomes TLK0101003002 but when I want to select this village as parent for the period 15.09.2012 to present both options (TLK0101013001 and TLK0101003002) are appearing in the dropdown as shown in this screenshot: 

![image](https://user-images.githubusercontent.com/12602163/113376566-99409c00-93a4-11eb-868e-b375bddafd65.png)

In this case there is not even an indication of the status of both records => one more example and case illustrating why inactive records should not appear in the list, or dropdowns, over their period(s) of inactivity

**Comment by SteeveEbener** [comment]
Please look at my comment dated May 1, 2021 in ticket #613 regarding how I think this issue should be addressed => requires a change in the handling of the "Status" attribute

**Comment by rrowlands** [comment]
This ticket is now superseded by #633. In an effort to reduce operational burden on our team I am closing this ticket.

**Comment by SteeveEbener** [comment]
The issue in this ticket was not be considered as being superseded by #633 until testing that the issue was indeed solved under the E/NE functionality. I just did the test under staging and it is indeed working. The ticket I submitted could indeed be closed
