### ISSUE TITLE
Add ability to map CGR core attributes to DHIS2 attributes

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#590]
Reported by Pedro at CHAI

Currently custom attributes can be configured between the CGR and DHIS2 through an external synchronization configuration. This only is available for custom attributes. CGR core attributes are hard coded to DHIS2 core attributes. Adding the ability to explicit configure the core attribute matching will help add flexibility to synchronization with DHIS2. 

TODO: Define user stories and requirements

**Comment by PedroPagalday** [comment]
@justinlewis this would the attributes that will need mapping in DHIS2: Name, Short Name, Code, Description, Opening Date, Closed date (?), Comment, URL, Contact Person, Address, Email , Phone Number + Custom Attributes

Those are DHIS2 core attributes, the DHIS2 ID should never be edited. And the above should be optional to do a mapping between DHIS2 and the CGR attributes.

Let me know if this answers your question

**Comment by rrowlands** [comment]
The software changes for this ticket were completed, however they were never merged back into the main branch.

https://github.com/terraframe/geoprism-registry/pull/626
