### ISSUE TITLE
RM can't access geo-object types part of a group over which he has the curation mandate

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#591]
**List the CGR information**
- CGR version: 0.14.2
- CGR instance (e.g. a URL): Production

**Describe the bug (clear and concise)**
When specifying the role for the RM over geo-object types part of a group, the RA can only define the role at the group level (see first screenhot below, health facility (MOH) is the group)

When loged in as the RM, the geo-object types part of this group are not appearing when trying to import data (see second screenshot below) or creating a new master list (third screenshot below). The folloing health facility types are part of this group and should have appeared: National Hospital (MOH), Referral Hospital (MOH), health Centre (MOH)  and Health Post (MOH). 

**To Reproduce**
As a Moh RA: 
1. Go to Geo-object types and hierarchies module and see the health facilities type part of the Health facility (MOH) group 
2. the settings module
2. Open the user management window for the MOH RM or MOH RC and see that the role attribution is done at the group level

Log out and log in as the MOH RM
1. Go to the import module
2. click on the Geo-Object bar
3. See Error 1: the geo-object types parts of the group are not appearing in the dropdown (2nd screenshot below)
4. Go to the lists module
5. Click the create button
6.  click in the Geo-object type file
7. See Error 2: Only the Health facility (MOH) group appears in the dropdown menu, not each separated health facility type

**Expected behavior (clear and concise)**
Each separated geo-object type part of a group appears in all the dropdown menus where the RM or RC has to precise this information starting with the import module and the creation of a new list (there might be others).

Clarification added 06.04.2021: The group itself should remain among the options, together with the individual geo-object types when creating a list

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/113267092-8a0c1080-9308-11eb-8a16-d558c9257fec.png)

![image](https://user-images.githubusercontent.com/12602163/113267171-9e500d80-9308-11eb-856d-987e416c6f99.png)

![image](https://user-images.githubusercontent.com/12602163/113268009-86c55480-9309-11eb-8812-6ff2bda3ba0d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The lastest one

**Additional context (if any)**
Interestingly, it seems that the issue does not apply to the RC role, at least not when submitting a change request:
![image](https://user-images.githubusercontent.com/12602163/113268847-6c3fab00-930a-11eb-974b-440a76af81ec.png)

I am just wondering if the group (Health facility (MOH)) should appear in the dropdown in that case

**Comment by SteeveEbener** [comment]
Just tested tis ticket under Version: 0.14.3 (2021-04-06T02:08:06Z)

All the geo-object types part of a group are now appearing in the concerned dropdown for the RM and RC but the group itself has disapeared from the dropdown when the RM is creating a list while in this case it should have remained:

![image](https://user-images.githubusercontent.com/12602163/113656333-3ca7ee80-96ce-11eb-9353-b34aa671eb9b.png)

**Comment by jsmethie** [comment]
Unless I am missing something, I see "Health facility (MOH)" in your dropdown on the screenshot.

**Comment by SteeveEbener** [comment]
Ho my. Looks like it might be time for me to change my glasses...or to get some more rest :) 

We are all good then => I am closing this ticket.

Thanks guys
