### ISSUE TITLE
RC/RM are unable to submit a change request in the Laos instance (account details)

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#592]
**List the CGR information**
- CGR version: v14.2
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/cgr/manage

**Describe the bug (clear and concise)**
RC/RM are unable to submit a change request for a geo-object or edit a geo-object. They receive an error "You do not have permission to perform this action. If this action is associated with an Organization or Geo-ObjectType, check to make sure that you have the relevant permissions". We checked the user permissions and the roles for RC/RM were set-up correctly.

We were unable to recreate this in the staging environment and might be something specific with user permissions in Laos?

**To Reproduce**
1. As a RC go to the HFML
2. Click on edit a geo-object
3. Edit an attribute and save changes
4. Try and submit a change request
5. See error: 'You do not have permission to perform this action. If this action is associated with an Organization or Geo-ObjectType, check to make sure that you have the relevant permissions'

1. As a RM go to the HFML
2. Click on edit a geo-object
3. Edit an attribute and save changes
4. See error: the RM is shown the submit a change request flow and asked to submit registry contributor notes
5. Try and submit a change request
6. See error: 'You do not have permission to perform this action. If this action is associated with an Organization or Geo-ObjectType, check to make sure that you have the relevant permissions'

**Expected behavior (clear and concise)**
* RC is able to submit a change request for a geo-object within the geo-object type of a geo-object group they have an RC role over
* RM is able to submit an edit for a geo-object within the geo-object type of a geo-object group they have an RM role over

**Screenshots**
![image (9).png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/b989d3d2-dca2-4c5f-b247-5efa52697927)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Google Chrome
 - Version: Latest version

**Additional context (if any)**

**Comment by justinlewis** [comment]
@vrajasekaran18 Does this happen on every (or many) Geo-Object Types or is it unique to the HFML you have in the description above?

**Comment by vrajasekaran18** [comment]
@justinlewis I've just tried with the Laos instance currently on v13.3 and I can't seem to reproduce it. When we found it it was just the HFML we were looking at (as that's the list we had during training). In the future in the event we see this, what troubleshooting steps would you like us to - check user settings, Check other lists?

**Comment by justinlewis** [comment]
Because this worked on other instances/versions we where wondering if this was an issue with the data in the Laos instance that we didn't predict in development. That must not be the case given it now works. However, it is very strange that the CGR caught a permission issue in the screenshot above but now doesn't. Are you sure you re-tested with the same user?

**Comment by vrajasekaran18** [comment]
@justinlewis We wiped the instance in between trainings so it's all new users at this point

**Comment by vrajasekaran18** [comment]
User creation steps:
1. Set-up organizations
2. Set-up geo-objects types
3. Create users (able to add users and assign to type)
