### ISSUE TITLE
As an Sys Admin I am unable to create a new locale to import a localization

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#594]
**List the CGR information**
- CGR version: v13.3
- CGR instance (e.g. a URL): Laos

**Describe the bug (clear and concise)**
Sys Admin is unable to create the Laos locale in the CGR

**To Reproduce**
1. As a Sys Admin: Go to the settings
2. Click on create new locale (+ button)
3. Complete information and try to save
4. See error: An unspecified error has occurred

**Expected behavior (clear and concise)**
A sys admin is able to create a new locale in the CGR

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by justinlewis** [comment]
@vrajasekaran18 I'm able to install a new locale on Staging. What are the settings in the modal when you're trying to install a locale?

**Comment by vrajasekaran18** [comment]
@justinlewis If you log-in to the Laos instance as the SRA (sharing details over slack) you will find the error. Is it user settings? The adminDPC has the sys admin role.

**Comment by justinlewis** [comment]
I was able to log in as this user you shared with me and install the Laos language with no issue. We will need to try again from your environment to further troubleshoot.

**Comment by vrajasekaran18** [comment]
@justinlewis We found the bug when you inputted a variant. What's the thinking in terms of either hiding the variant or improving the error handling?

**Comment by justinlewis** [comment]
We removed the varient option because it is a rare case where it's needed.
