### ISSUE TITLE
End date not being set

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#596]
Reported by @vrajasekaran18 

If I've imported data for a geo-object type with an end date of 2 April 2021, published a list at quarterly frequency. If I then I re-upload the same data but now with an end date set to present, create an exploratory list for today, the geo-objects within that geo-object type still do not appear.

**Comment by SteeveEbener** [comment]
Not sure to understand what the issue is here...some information seems to be missing

**Comment by justinlewis** [comment]
@SteeveEbener This was a bug that occurs when uploading (to updated existing data) where the original start date and the incoming start date are the same but the incoming end date is different the import end date was being ignored.

**Comment by SteeveEbener** [comment]
Got it. Thanks

**Comment by justinlewis** [comment]
@vrajasekaran18 can you re-test this? We did on our end but want to give you a chance to verify.

**Comment by justinlewis** [comment]
Closing because of a lack of activity
