### ISSUE TITLE
Change request asking to delete the existing instance for a given attribute generates an empty ticket on the RM side

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#597]
**List the CGR information**
- CGR version: 0.14.3 (2021-04-06T20:56:24Z)
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**

- The RC can submit a change request in which he suggests to delete the only existing instance for a given attribute  (HF name for example).
- When the RM opens the request in question he obtains the blanck ticket reported in the screenshot below (sometime the information appears during a fraction of second and then disapears)

**To Reproduce**
As a MOH RC:
1. Go to the lists module, open the list ofr one of the geo-object type over which he has the curation mandate (Referral hospital for example) 
2. Open the editing modale for one of the geo-object, put it in the edit mode and click the edit button for the health facility name
3. If more than one instance for that field, delete one of them, if only one delete the instance in question
4. Click the submit button

Log out as the MOH RC and log ina s the MOH RM
1. Go to the change request module and open the request submitted by the RC (8ca8434b-59a1-4d66-8c8a-84916a0005cd under staging)
2. See the error: the ticket is empty, even the label on the buttons is gone (screenshot below)
3. Clcik on the Details button => redirect to an empty window

**Expected behavior (clear and concise)**
The change request iniated by the RC results in a ticket that is not empty and can therefore be handled by the RM 

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/114143430-bb0ec580-9946-11eb-9f7a-3c310d95336c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest version

**Additional context (if any)**

**Comment by rrowlands** [comment]
I am unfortunately unable to reproduce the issue in this ticket on version 0.14.5 of our software (currently on staging). Additionally, the change request data you had originally submitted for this ticket was deleted on April 17th so I can't pull that up either and investigate.

Please re-test this issue on staging and let me know if you continue to have issues.

**Comment by rrowlands** [comment]
I just reproduced the original issue in the ticket.

It happens on some attributes and not others. Deleting the geometry attribute or the display label attribute seemed to do it.

**Comment by rrowlands** [comment]
I also noticed some scenarios where a "diff" change was not being displayed (especially when removing attributes). These should be fixed as well.

**Comment by SteeveEbener** [comment]
Tested under 0.14.6. The ticket is not empty anymore when the RC suggest to delete an instance but it is impossible for the RM to understand that he is actually deleting an instance for a given period.

**Comment by rrowlands** [comment]
Correct me if I'm wrong, but what you're talking about is a larger issue with change requests where it's hard to find changes which occur on dates other than the current date you're viewing. Unless I'm misunderstanding you, that should be handled within a different (and much larger scope) ticket.

**Comment by SteeveEbener** [comment]
Fair point. I have added a comment to ticket #547 to get this covered there.

I am closing this ticket
