### ISSUE TITLE
RM unable to select a column to match an attribute set to integer against

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#598]
**List the CGR information**
- CGR version: v0.14.2
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When importing data from a spreadsheet, if a custom attribute is set to integer format and the corresponding column is set to a number, during matching, there are no drop-down options for columns in the spreadsheet for matching the attribute in the CGR against.

**To Reproduce**
1. As a RM Go to the import module
2. Click on import army hospitals and attach the spreadsheet below
3. On the matching page, find the Health Facility Phone Number attribute and try and map a column in the spreadsheet against it
5. See error: no options to map the attribute against

**Expected behavior (clear and concise)**
RM is able to view columns in the spreadsheet that are set as integers to map an integer-based attribute against

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/69aa8c43-f20a-4f1a-a57c-968d49c23f62)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Latest

**Additional context (if any)**
* File for upload

[https://app.zenhub.com/files/142912671/898f978a-db6b-4e9f-bd37-c1e3bb5d9ae9/download](https://app.zenhub.com/files/142912671/898f978a-db6b-4e9f-bd37-c1e3bb5d9ae9/download)

**Comment by justinlewis** [comment]
@vrajasekaran18 Can you test this? We believe we've fixed it.

**Comment by justinlewis** [comment]
Closing because of a lack of activity
