### ISSUE TITLE
It is possible to create contradictory hierarchies

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#599]
**List the CGR information**
- CGR version: 0.14.3 (2021-04-06T20:56:24Z)
- CGR instance (e.g. a URL): Stagging

**Describe the bug (clear and concise)**
After implementing the administrative structure hierarchy (first screenshot below) I have been able to create a new hierarchy that organises the same geo-object types exactly in the contrary order (second screenshit below).

I did not even try to upload data against the new hierarchy by fear it would corrupt the graph but creating such a contradictory hierarchy should not even be possible in the first place

**To Reproduce**
As a MOHA RA : 
1. Go to the geo-object types and hierarchies module
2. Look a the Administrative structure hierarchy (MOHA) hierarchy (first screenshot below)
3. Create a second hierarchy that organises the same geo-object types in the opposite order (second screenshot below, test hierarcvy)
4. See error: it is possible to create such a contradictory hierarchy

**Expected behavior (clear and concise)**
It is not possible to create contradictory hierarchies (if geo-object type A is the parent of geo-object type B in a given hierarchy it is not possible for geo-object type B to be the parent of geo-object type A in another hierarchy)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/114660837-917be280-9d28-11eb-9c68-777e84612923.png)

![image](https://user-images.githubusercontent.com/12602163/114660857-96d92d00-9d28-11eb-9ad2-2acdeb5bb446.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest version available

**Additional context (if any)**

**Comment by nmceachen** [comment]
I don't think this is a problem. The edge types are different for each hierarchy and thus these two hierarchies are orthogonal. Populating one hierarchy does not impact the other. I suggest we close this ticket.

**Comment by SteeveEbener** [comment]
Thanks Nate, the explanation given during our call today confirmed that we can indeed close this ticket as each hierarchy is managed independently from each other
