### ISSUE TITLE
Date picker for change over time allows invalid dates

### ISSUE THREAD

**Issue by nmceachen** [terraframe/geoprism-registry#6]
Pierre from VitalWave has reported that the data picker for specifying a date when versioning an attribute, parent relationships, or geometries.

From Pierre:
"it’s when one uses the up and down arrows for the day field in the date control
this always goes up to 31"

**Comment by jsmethie** [comment]
We are leveraging the html 5 date input type.  So this is a browser specific error that we have no control over.
