### ISSUE TITLE
RM unable to view jobs in progress/completed jobs in staging

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#602]
**List the CGR information**
- CGR version: v0.14.2
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
RM is unable to view jobs in progress or completed jobs in staging. If there's a job in progress that requires validation the RM is unable to view it

**To Reproduce**
1. As a RA: Go to Scheduled Jobs
2. Click on View Completed Jobs
3. Log-in as a RM: Go to Scheduled Jobs
4. Click on View Completed Jobs
5. See error: RM does not have any completed jobs since 17 March

**Expected behavior (clear and concise)**
RM is able to view jobs currently in progress (for example for further validation) and all completed jobs as per the roles by rights matrix

**Screenshots**

RA view of completed jobs
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/44fd8520-1786-49ac-a496-74d4858bfda3)

RM view of completed jobs
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/4c907f99-c94a-4933-b444-6af03cc9c8c7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
What exactly do your user's permissions look like? Specifically, which organization are you an RM of? Which GeoObjectTypes do you have permissions over? You will only be able to see imports for GeoObjectTypes over which you have explicit permission.

When I create an RM of all GeoObjectTypes in MOH organization, as follows:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/5f88ddd5-9bdb-4864-93e7-e48ac84ae8b0)

I am able to see the following import history:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/5413eeab-7510-4fef-bc99-459df845fe7b)

Which, after peeking at the history records in the database, is exactly what I would expect to see given my permissions.

**Comment by vrajasekaran18** [comment]
@rrowlands I'm using Moh_RM that has RM permissions for Health Facility, when I look at scheduled jobs I'm seeing below
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/abb677f6-1890-4ff6-b6fe-88295bd77885)


When I log-in as Moh_RA I can see health centre imports (that are geo-object types within Health Facility)

![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/54fdb8a7-4c3f-485f-ad34-69ee76d77f14)

Why can't the RM view imports for geo-object types within the geo-object group they have RM permissions for?

**Comment by rrowlands** [comment]
This issue occurs when data is imported against a subtype and the user has permission to the super (group) type.
