### ISSUE TITLE
When importing data for a geo-object type that is the ultimate parent of a hierarchy, the hierarchy is not an option during import

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#606]
**List the CGR information**
- CGR version: v14.2
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
If you are importing data for a geo-object type that is the ultimate parent of a hierarchy, that hierarchy is not an option in the drop-down for assign a hierarchy. For example in Laos, we have the Capital Health Office as the ultimate parent of a management hierarchy, when importing data for the Capital Health Office, the management hierarchy is not an option when assigning a hierarchy.

**To Reproduce**
1. As a RM: Go to the import module
2. Select health post as a geo-object type, fill out other columns and attach a sample xlsx file
3. Click Next and under attribute matching, select hierarchy
4. See error: the CHW Health post hierarchy is not an option in the hierarchy dropdown even thought Health Post is a member of the hierarchy. Health post is the ultimate parent and may be why the hierarchy does not appear

**Expected behavior (clear and concise)**
User is able to view all hierarchies a geo-object type is part of regardless on where it sits in that hierarchy.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/3bb16f66-0689-4686-8bd9-2c3b22c71911)

![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/bb0265ef-b78c-40b8-b780-8a65cbf26e7b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Same problem with the Tolkien data when loged in as the MOH RM. I can't see the Health geography hierarchy (MOH) when importing data for the national hospital:
![image](https://user-images.githubusercontent.com/12602163/115942129-3fcb1900-a4db-11eb-89e9-22c750a4beab.png)

...and the national hospital is at the top of the hierarchy:
![image](https://user-images.githubusercontent.com/12602163/115942147-58d3ca00-a4db-11eb-886d-b025dce13db4.png)

**Comment by SteeveEbener** [comment]
One more thing related to this ticket is that it is possible to actually create an instance of parents for hierarchies in which the geo-objects in question is at the top and that does not make sense. Example: as the Moh RM/RA go to the list of national hospital and put one of the geo-objects in editing mode. You will see the "Health care referral hierarchy (MOH)" appearing among the "attributes" and you have the possibility to create an instance for which you actually don't specify a parent:
![image](https://user-images.githubusercontent.com/12602163/116957983-cf3aae00-accb-11eb-9630-d93dd5cd19bb.png)

**Comment by SteeveEbener** [comment]
Tested under 0.14.10 and:
- When logged in as the MOH RM or RA, I can now see the Health geography hierarchy (MOH) when importing data for the national hospital
- The issue reported here above on May 4 has itself not been fixed. It is still possible to create an instance of parents for hierarchies in which the geo-objects in question is at the top and that does not make sense. Example: as the Moh RM/RA go to the list of national hospital and put one of the geo-objects in editing mode. You will see the "Health care referral hierarchy (MOH)" appearing among the "attributes" and you have the possibility to create an instance for which you actually don't specify a parent:

**Comment by justinlewis** [comment]
@steeveebener Regarding your comment from May 4 can you test that again?  I believe the rewrite of this functionality in release 0.15.0 may have fixed this.
