### ISSUE TITLE
Add or expose unique ID to Change Requests

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#61]
A unique ID should be attributed to each request to facilitate tracking

**Comment by justinlewis** [comment]
@Steeve - Can you explain what you mean by tracking? It would also help if you described the problem we're trying to solve by doing this.

**Comment by SteeveEbener** [comment]
By tracking I mean the same kind of operation you do when you track a letter you sent through the US postal service => a unique ID you can use to search and identify a specific change request

=> having such a unique ID would simplify for both the contributor and the RM to identify which request they are referring to if they have to discuss it over the phone for example.

**Comment by dtreatman** [comment]
Agree, all change requests should have a unique ID for ease of reference, e.g., "Jane, can you please tell me the status of my change request, number 1456?"

**Comment by justinlewis** [comment]
![Screenshot from 2020-12-07 22-21-44.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/bb37db94-2a1d-490e-becb-cbe7a030d14d)

**Comment by SteeveEbener** [comment]
This should be an ID that someone can refer to, meaning human readable not a GUID. The objective here is for a RM to for example call the RC and say "I am calling you regarding request DA12536 that you submitted on June 6, 2020"

**Comment by justinlewis** [comment]
@SteeveEbener So it sounds like this is an ID that the RC needs to manually add when submitting the request?

**Comment by SteeveEbener** [comment]
@justinlewis : It should be machine generated anyway to ensure their consistency and that there are no duplicates, at least at the organization level.

**Comment by justinlewis** [comment]
This was discussed outside of this ticket but given limitations with offline mobile combatibility and a lack of available attributes to build a human readable ID I am:
1. Releasing in Release 0.13.0 the version that exposes the UUID from the request that is less human readable than hoped. 
2. Moving this ticket to Sprint 0.14. so we can discuss this issue further. 

This exposes a unique ID that can be used now while giving us some time to determine if a better solution exists.

**Comment by justinlewis** [comment]
There was some discussion around developing an algorithm that would make a more human readable ID with the best idea being a combination of username and date (by @steeveebener):
> combining the username (Example: Moh_RA) with the date (Example: 2020-12-06) and time (Example: 13:05:10) at which the request is submitted? => Moh_RA20201206130510.

While this seems like it would be an improvement it's still not easy to read especially because agreement on date formats/localization is not agreed on at this moment which could result in the date in the ID not matching with a users expected format. In addition because a Change Request can have more than one action we should consider if actions need an ID exposed as well. 

I created [this Epic](https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/584) to serve as a roadmap item to improve Change Requests as a whole. I would like to close this ticket in favor of looking at improving this ID when we're looking at how to improve searchability and clarrity as a whole.
