### ISSUE TITLE
RM unable to select a geo-object type for import or when creating new lists

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#612]
**List the CGR information**
- CGR version: 14.5
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
RM is unable to select a geo-object type for importing or when creating new lists even though they have RM privileges

**To Reproduce**
1. As a RM: Go to the import module
2. Click on Geo-Object Type
3. See error: No geo-object types appear for import

Update: Error also there when an RM is trying to select a geo-object type for creating a new list

**Expected behavior (clear and concise)**
All geo-object types the RM has RM access to should be displayed in the dropdown list

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/51e1a09d-cbab-40b0-a7d1-3da440cb5c8f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Seems the RM role has been screwed in different places. This is what you get when you log as the Moha RM:

![image](https://user-images.githubusercontent.com/12602163/116638463-f9713080-a998-11eb-8553-94cc1b349e6e.png)

Can someone please check what has been damaged against the rights by role matrix?

**Comment by jsmethie** [comment]
Despite its name it looks like Moha_RM isn't actually assigned as an RM to any type.  So it doesn't have permissions for anything.

**Comment by nmceachen** [comment]
Looks like we need a message that says something to the effect of: You have not been assigned permissions on any data in the system

**Comment by SteeveEbener** [comment]
Interesting. I missed that one. Should it actually be possible to create a user without any role?

**Comment by SteeveEbener** [comment]
Thanks for the message appearing in the home page.

There might actually have been something else happening as I don't remember deleting any geo-object types in the Tolkien data without this being part of a complete reset + going through all the user account yesterday in Demo I found that the Moha_RC user was not associated to any role (still the case in the production instance. 

This being said I can't remember what happened in the first place => will document here in case this happens again.
