### ISSUE TITLE
You can specify a start date that is later than the end date in the import module

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#614]
**List the CGR information**
- CGR version: 0.14.6
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
It is possible for the RA/RM to specify a start date that is later than the end date in the import module

**To Reproduce**
As the RA/RM:
1. Go to the import module
2. Select a geo-object type and import strategy
3. Specify an end data that is older than the start date
3. See error: it is possible to have an end date that is older than the start one (see screenshot below)

**Expected behavior (clear and concise)**
The end date can only be equal or older to the start date

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/116952382-1c635380-acbd-11eb-8aae-2eb6ac814585.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The most recent one

**Additional context (if any)**

**Comment by justinlewis** [comment]
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/6b193bfc-5a74-4767-9727-c14608ea76fe)

**Comment by SteeveEbener** [comment]
@justinlewis . Looks good. Will test and close the ticket once 0.15 has been released

**Comment by SteeveEbener** [comment]
Tested under 0.14.10 and it is working. I am closing this ticket
