### ISSUE TITLE
RM is unable to implement a change request

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#615]
**List the CGR information**
- CGR version: 14.6
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
RM is unable to implement a change request for a geo-object type they have RM permissions over

**To Reproduce**
1. As a RM (Moh_RM): Go to the change request module
2. Click on a pending change request
3. Accept the change request
4. Click implement changes
5. See error: User MOH does not have permission to modify attribute

**Expected behavior (clear and concise)**
RM is able to implement the change

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/ab15b671-d483-4380-9737-7aab531056c5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
I am unable to reproduce this issue. As Moh_RM on the staging instance I was able to accept and implement 6 different change requests (and they are now all accepted).

When creating a new GeoObjectType attribute the error you described can occur if you have not logged out and then logged back in again. Perhaps this is what happened?

**Comment by vrajasekaran18** [comment]
@rrowlands yeap sorry I should have closed this. It was something only I could produce once and since then it's been unreproducable!
