### ISSUE TITLE
RM is unable to view a geo-object in explorer/map view after implementing a change request

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#616]
**List the CGR information**
- CGR version: v14.6
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
After an RM has implemented a change request, when the navigation box appears, if the user clicks "Go to the map-editor" the user is re-directed to the change request page rather than the explorer/map view.

**To Reproduce**
1. As a RM: Go to the change request module
2. Accept/Reject a pending change request
3. Implement the change request
4. Click "Go to the map editor"
5. See error: RM is re-directed to the change request page rather than the explorer/map view

**Expected behavior (clear and concise)**
RM is directed to the explorer/map view when they click go to the map editor

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
Can someone please clarify what the "explorer/map view" and the "map-editor" are?

Please also have a look at the comments I posted on May 4th, in ticket #573 regarding the message and button that appear in the box in question as well as the window where the user is redirected

**Comment by justinlewis** [comment]
@vrajasekaran18 I just tested and believe this is fixed in release 0.15.0

**Comment by justinlewis** [comment]
For reference I just re-opened #573 because I noticed on testing that the new localization didn't take effect there despite it working on other servers.

**Comment by justinlewis** [comment]
Closing because of a lack of activity and because the explorer was rewritten.
