### ISSUE TITLE
Move 'add new geoobject' button from master lists to submit change request

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#62]
**Notes for the change request functionality:**

The user should:
   a. Select the geoObject type for which he wants to submit a request (already there)
   b. Specifiy if he wants to: 
      1. Add a GeoObject which he thingk is missing; 
      2. Report a correction of an information already in the master list (typo in a phone number for example); 
      3. Update an information that has changed; 
      4. Report the need to inactivate a GeoObject (duplicate, closed facility,....)
   c. see a window specific to the type of change that has been selecte under b appear
   d. Select the concerned Geoobject in case he choose option2, 3 or 4 and fill the option specific form

**Comment by SteeveEbener** [comment]
The "Add new GeoObject" button should remain accessible from the master list manager for the RM and RA roles

**Comment by dtreatman** [comment]
I may disagree with this and suggest we discuss it further. 

To the extent possible, the UI/UX should be identical, or nearly identical, regardless of user role (RC, RM, or RA), which will make training and support easier (especially as RCs eventually become RMs through their career progression). To explain:

- An RM in the Master Lists module should be able to click the "Add New GeoObject" button. For technical consistency, I proposed that this should actually generate a change request that is automatically approved, thus making it auditable in the list of accepted change requests.

- An RC in the Master Lists module should similarly be able to click the "Add New GeoObject" button. For UI/UX consistency, this button should be visible in the same place on the screen as for the RM. Similar to the RM scenario described above, submitting the addition generates a change request. The difference is the RC's change request must be reviewed and approved manually by an RM.

Keeping this button in the same place on the Master Lists module increases consistency in UI/UX. An alternative approach for RCs to add a new GeoObject is to go to the Change Request module.

**Comment by SteeveEbener** [comment]
Except that the RC will have the impression that he is directly adding something in the graph while this is not the case unless it is clear that he is going through a change request.

=> Compromise: when the RC hits the add GeoObject buttons in the master list he is redirected to the change request manager where he can submit a request for the considered GeoObject. That way it is clear what he is doing.

Something in the UI for the RM will certainly have to be different to ensure that he understand that his change is directly implemented.

The above should also apply to the edit  icon.

**Comment by justinlewis** [comment]
This sounds like the concern is about UX clarrity.  Before moving anything we will mock up something that maintains more consistency, avoids redirects, and makes it clear when a submission will be sent as a change request or directly persist.

**Comment by justinlewis** [comment]
Marking as invalid as of v 0.13.0 because the stand alone change request functionality was removed.
