### ISSUE TITLE
RC unable to refresh an exploratory list they have RC rights over

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#622]
**List the CGR information**
- CGR version: v14.8
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
RCs are unable to refresh an existing exploratory list for a geo-object type/group they have RC rights on

**To Reproduce**
1. As a RC_Moh Go to the list module
2. Click on a list that they have RC rights over (HFML)
3. Click on an existing exploratory list OR generate a new exploratory list
4. Click refresh
5. See error: "You do not have permission to create a List in the organization"

**Expected behavior (clear and concise)**
An RC is able to create exploratory lists and refresh existing lists for geo-object types/groups they have RC rights over.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/e655e7ee-1f2b-4661-871c-eeabcd76bc43)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
I can enable this ability, however we can talk about whether or not it makes sense for RC's to be able to refresh exploratory lists which they have not personally created (a so-called "ownership" over the exploratory list). Given that such an ownership concept does not exist (RC's are able to see exploratory lists that other RCs have created, and also the "owner" of the list is not visible anywhere), I will argue that RC's should either be allowed to refresh any exploratory list (for which they have GOT permissions) or no exploratory lists.
