### ISSUE TITLE
Searching for Geo-Objects from the Explorer doesn't work for the Laos locale

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#623]
**List the CGR information**
- CGR version: 0.14.8
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
Searching for Geo-Objects from the Explorer works for the Default Locale but not for the additional Laos locale. 

**To Reproduce**
1. As a an RA navigate to the Explorer
2. Look for a Geo-Object where you know a value exists for that period of time for both the Default and Laos locale
3. Search for the Default Locale value for that Geo-Object. This should work.
4. Search for the Laos value for that Geo-Object. The result is not found (error).

**Expected behavior (clear and concise)**
For searching with Laos characters on the Laos locale to return an accurate result.

**Screenshots**

![Screenshot from 2021-05-21 14-39-07.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/55316ed5-7035-4543-a173-14a67eed7af3)

![Screenshot from 2021-05-21 14-39-25.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/f287ec59-d880-49eb-b23d-511c4d9c2f4a)

![Screenshot from 2021-05-21 14-39-57.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/096dc778-3915-47ed-ad39-c1ef1c3a4917)

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Additional context (if any)**

**Comment by vrajasekaran18** [comment]
@justinlewis Searching for a geo-object in Laos in the change request does not work either

**Comment by rrowlands** [comment]
I have fixed searching for objects in other locales, however keep in mind that the search bars (specifically for that Change Request search bar and also the search bar when searching for setting a parents in the GeoObject editor) **will** take into account the user's current locale. If you are testing my fix and you find it's not working, make sure to check to make sure your locale is set to loas.

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/69a49b7a-6717-4dc2-a92b-bac0edf678ff)
