### ISSUE TITLE
Add column header mapping to metadata for Shapefile exports

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#628]
## User stories
1. As a user of CGR I need to know with certainty what the columns represent in a shapefile export.

## Problems this relates to
1. Shapefiles have a 12 character limit which often results in column headers being truncated because labels in Geo-Object Type attributes can be long. 

## Proposed solution
1. Use the code for all exported column headers because they are unique and tend to be shorter. Also enhance the metadata to include a mapping between codes in the CGR and the column header in the exported shapefile. 

## Considered alternatives
1.

**Comment by rrowlands** [comment]
Worded another way:

Add an attribute code column to the "Data Dictionary" tab of masterlist spreadsheet exports.

**Comment by rrowlands** [comment]
Unfortunately our open source library which we are using to write shapefiles does not support writing to shapefile metadata:

https://gis.stackexchange.com/questions/68863/writing-shapefile-metadata-with-geotools

**Comment by SteeveEbener** [comment]
What we discussed with Nate was for an XML file, or another type of file, to be generated separately from the shape file and included in the zip file being exported

**Comment by rrowlands** [comment]
As long as we're creating an XML exporter, would it make sense to create a file which in theory could at some point in the future (doesn't have to be now) be directly imported by the CGR to create a GeoObjectType?

I.e. something like this:

A file inside the shapefile zip with extension `.cgr` and format:

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <geoObjectType code="REG" id="29b92df0-1f9e-45a2-a797-b8320800066c" group="false" ... >
    <attributes>
      <attribute code="displayLabel" id="69a33gk0-149e-bla2-a759-gvl40800066c" defaultLocale="Region (MOHA)" lo_LA="ສາທາລະນະລັດ"></attribute>
      <attribute code="status" id="03daghk0-40de-la32-0d39-g0f30800066c"></attribute>
      ...
    </attributes>
  </geoObjectType>
</metadata>
```

**Comment by nmceachen** [comment]
Richard, interesting idea. Let's table that idea for now. I think our type creation XML syntax is too verbose for the purposes of communicating the metadata that is of interest here.

**Comment by rrowlands** [comment]
Just got off a call with the team. To summarize what we talked about:

1. We think it makes sense to put this ticket on ice until we have completed the additions to the list metadata (which may influence and shape what these metadata files ultimately look like
2. We like the idea of generating metadata into a spreadsheet and including that into the shapefile for a couple reasons:
  a. We already have to generate a spreadsheet for the excel format which already has to include the metadata. We can just take that tab and include it here
  b. Spreadsheets are much more human readable than XML or CSV

Interested to hear your thoughts @SteeveEbener

**Comment by SteeveEbener** [comment]
@rrowlands . Thanks for the update.

1. Which additions to the list metadata are you thinking about? This file is already "mature" according to me but the one for the shape file (which is meant to be a separated file + the information it will contain for the metadata part will be different than the information for the list) is still for discussion as it should only include the data dictionary and the metadata sheet
2. It should indeed be an Excel and not a CSV file (if not an XML one) and this simply to be able to store both the data dictionary and the metadata

This is something that needs to be solved as part of the conversion of the lists module into the lists and spatial data one

**Comment by rrowlands** [comment]
^ This question is best answered by @nmceachen

**Comment by nmceachen** [comment]
I would think an excel file would be the most convenient for a user.

**Comment by rrowlands** [comment]
Can we agree on a name for this file within the Shapefile? I was thinking 'metadata.xlsx' ?

**Comment by SteeveEbener** [comment]
Tested under 0.17.2.

The headers in the data dictionary are now matching those in the attribute table of the shape file but there is no way to relate them to the headers in the list or the attribute definition in the geo-object types and hierarchies module.

This is creating confusion and should be addressed in order for this ticket to be considered as implemented.

**Comment by jsmethie** [comment]
Create a new ticket for your last comment and mark it as an enchancement

**Comment by SteeveEbener** [comment]
Tested under 0.19.6 and the headers in the data dictionary are not matching anymore those used in the attribute table of the shape file => Submitting a new ticket for this.

Maybe that this is linked to the same problem as the one reported in ticket #819

**Comment by rrowlands** [comment]
Can you please link here the ticket you created which deals with the mismatch in columns between shapefile and metadata file? I am having trouble finding it.

**Comment by SteeveEbener** [comment]
Hi @rrowlands . I just created the ticker in question #869
