### ISSUE TITLE
Date published is shown for exploratory lists instead of date generated

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#631]
**List the CGR information**
- CGR version: v14.8
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When a user (RC/RM/RA) views an exploratory list it says date published rather than date generated

**To Reproduce**
1. As a RC: Go to an exploratory list
2. Click on view
3. See error: Published date is shown instead of date generated

**Expected behavior (clear and concise)**
Similar to the summary view of all exploratory lists present where date generated is used, the list view should say date generated rather than date published

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/4cf16cf5-b619-4da0-9856-656be6071c6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
The date itself is actually also different between the two views:
![image](https://user-images.githubusercontent.com/12602163/121176062-5d3b2300-c88e-11eb-9adf-87d8591762fa.png)

**Comment by justinlewis** [comment]
Updated the label

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/08dcd4a9-f79a-43e7-96f4-2327d8eace06)

**Comment by justinlewis** [comment]
@steeveebener I looked at Referral hospital master list on Staging and it looks like that's the only exploratory list where that happened. I can't seem to be able to re-create that locally. I'm not sure what happened there I looked through the code and can't see anything obvious that would have created that. I'll keep an eye on this. Please let me know if you see it again.

**Comment by SteeveEbener** [comment]
@justinlewis what is even more strange now is that published date appearing in the list view for that particular instance of the list has not changed to 2021-05-04...:
![image](https://user-images.githubusercontent.com/12602163/121878155-f7431580-cd3d-11eb-976c-1c6eb7a1e526.png)

Apart from that, I found the same issue with the following lists in staging (did not check all of them):
-  University master list (MOE) generated on 2021-03-27 (date appearing in the list view: 2021-05-20)
- College master list (MOE) generated on 2021-03-27 (date appearing in the list view: 2021-05-20)
- Region master list (MOHA) generated on 2021-04-19 (date appearing in the list view: none (blank))
- Province master list (MOHA) generated on 2021-03-09 (date appearing in the list view: 2021-03-15)

**Comment by vrajasekaran18** [comment]
@SteeveEbener good catch with the dates! @justinlewis Looks like a lot of this was during March/April where we had just changed the date picker and there were those bugs with dates being 1 day apart from the intended date? Could that be related?

**Comment by justinlewis** [comment]
It could be related. I think we should check if this exists on Laos. Staging has goon through a lot of testing and small releases. If it's happening on Laos we'll have a better idea if this is an artifact of dev iteration.

**Comment by SteeveEbener** [comment]
Just tested under 0.14.10 and the date being different between the two views remains for the following lists:

- University master list (MOE) generated on 2021-03-27 (date appearing in the list view: 2021-05-20)
- College master list (MOE) generated on 2021-03-27 (date appearing in the list view: 2021-05-20)
- Region master list (MOHA) generated on 2021-04-19 (date appearing in the list view: none (blank))
- Province master list (MOHA) generated on 2021-03-09 (date appearing in the list view: 2021-03-15)

**Comment by jsmethie** [comment]
No longer valid
