### ISSUE TITLE
Ability to have list metadata in the localized language

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#640]
## User stories
1. RM configures list metadata

## Problems this relates to
1. RM can only configure list metadata in English and not in a localized language

## Proposed solution
1. Each list descriptor should be available in any additional language the CGR is in (e.g. Lao)
2. In the exported list, the metadata tab should include any metadata in an additional language

## Considered alternatives
1. N/A

**Comment by SteeveEbener** [comment]
Hi @vrajasekaran18: Are you referring to:

1. The user being to switch between English and the local language for the field labels in the metadata 
2. The capability described under point 1 + the possibility to capture the information for each of the fields in both English and the local language (like we are for example doing now with the geo-object name) and therefore the ability to generate and export two separated metadata: 1. One fully in English (field labels + captured information); 2. One fully in the local language?

**Comment by justinlewis** [comment]
@steeveebener - I had a conversation with @vrajasekaran18 and the issue this relates to is that some people will need the metadata values in other languages and right now there is only an option to have one value for all the fields (other than the display label). So we will need to convert the other fields (e.g. description, access constraints, etc...) to localized attributes that would behave like the display label. 

@vrajasekaran18 correct me if I'm wrong.
