### ISSUE TITLE
Can submit new attribute with required fields still empty

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#65]
**Describe the bug**
Can submit new attribute in a GeoObjectType with required fields still empty.

**To Reproduce**
Steps to reproduce the beha  vior:
1. Go to a GeoObjectType
2. Click on manage attributes
3. Click add new attribute
4. enter a value for the default label
5. leave the additional locale empty

**Expected behavior**
Submit button shoul be disabled therefore preventing submission if required fields are not filled out.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser Chrome

**Additional context**
Non default locales may not be required however even if this field was set to required incorectly it still should prevent submission if a required field is empty.

**Comment by dtreatman** [comment]
Agree on prioritizing this fix

**Comment by SteeveEbener** [comment]
Tested across the different attributes type and it is working. This ticket can be closed according to me

**Comment by CarlyNel** [comment]
I've just tested the same and it's working for me too. I'll go ahead and close this ticket.
