### ISSUE TITLE
Geometry not appearing on the maps for the end date indicated during the import

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#654]
**List the CGR information**
- CGR version: 0.15.2
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
I imported a shape file containing polygons (Provinces) for the period 2000-01-01 to 2007-04-19 against the Province (MOH) geo-object type

I then create exploratory instances of the list for 2000-01-01, 2007-04-18 and 2007-04-19 (they are all in staging)

The polygons are appearing on the map for the 2000-01-01 and 2007-04-18 instance but not the 2007-04-19 instance. 

This being said, when you open the editing modale for any of the geo-object the map zoom to the place where the polygon should be and when you click the "Show" button the polygon appears in blue as per the screenshot below => the polygons are in the graph but not showing on the map.

**To Reproduce**
As the MOH RA or RM on Staging: 
1. Go to the lists module
2. View the Province (MOH) (Master) ( Public ) list
3. Open the 3 instances of lists you will find there and see that the polygons are not appearing for the 2007-04-19 instance

**Expected behavior (clear and concise)**
The polygons on the map are appearing n the map over the whole period for which they have been imported (might actually be the same with other geometry formats (points, lines)

**Screenshot**
![image](https://user-images.githubusercontent.com/12602163/131235357-3f5c8195-f8fc-49a1-93f2-d0a7ddfa06ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The most recent one

**Additional context (if any)**
If you want to try to re-import the shape file, you will find it here: https://bit.ly/3kw4Wff

**Comment by SteeveEbener** [comment]
I just did the process again under staging and now the  polygons are not appearing in any of the exploratory instances generated previous to uploading the shape file. They only appear if you create a new instance for a different date (see 2005-01-01 instance)

**Comment by justinlewis** [comment]
To clarrify. This is what I see when loading the map from the 2005-01-01 list. 
![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/3f67294a-6dbd-42dd-9394-38d8aedecb88)

But when I load the same feature from the 2007-04-19 list it looks like this:

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/720dabeb-376b-4a24-904f-a623de5b233f)

When I push the "show" button it shows the geometry like your screenshot above. 

And the issue is that the green and red polygons that show in my first screenshot aren't showing in the second screenshot?

**Comment by SteeveEbener** [comment]
Yes

**Comment by rrowlands** [comment]
From what I can tell, if the list is refreshed the geometries are then rendered just fine.

**Comment by rrowlands** [comment]
The vector tile cache is returning data for these tiles. I have no idea why that data isn't rendering.

**Comment by justinlewis** [comment]
@steeveebener This is going to take some more digging to determine the issue so we need to push this to the next sprint.

**Comment by justinlewis** [comment]
@steeveebener Have you seen this behavior on other datasets? We're trying to figure out if it's unique to this exact data.

**Comment by SteeveEbener** [comment]
@justinlewis : please see the last comment included in #674 . This might be another example of the same situation

**Comment by SteeveEbener** [comment]
Not valid anymore. Closing this ticket
