### ISSUE TITLE
Edit not automatically appearing in the list

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#655]
**List the CGR information**
- CGR version: 0.15.2
- CGR instance (e.g. a URL): Staging/Demo

**Describe the bug (clear and concise)*
An edit to a geo-object does not appear automatically in the list

**To Reproduce**
As a RA/RM
1. Go to any list on which they have the curation mandate
2. Submit a simple change for one of the geo-objects (change a character in the geo-object name for example) and submit
3. Go back to the list
4. See error: the change is not automatically appearing in the list
5. Click on the refresh button
6. the change is now appearing in the list

**Expected behavior (clear and concise)**
-  The change automatically appear in the list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: the latest one

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
@justinlewis > Is this going to be addressed as part of the redesigning of the list & spatial data module?

**Comment by justinlewis** [comment]
@steeveebener this won't be in release 0.18.0 or 0.18.1 however we're discussing a potential option. We'll reach out to you about this soon.

**Comment by SteeveEbener** [comment]
@justinlewis . I kind of remember we discussed something about this. If this is the case, is what we discussed captured somewhere? Thanks

**Comment by rrowlands** [comment]
Addressed as cf6a700e8bb7a6edce3ee32571bb76e3bc28d54c by @jsmethie.

**Comment by SteeveEbener** [comment]
@rrowlands: what has been addressed and in which version will this be released in order to be able to review the change? Thanks

**Comment by rrowlands** [comment]
@SteeveEbener This will be part of the 1.0.1 release. This fix is currently available for testing on the staging server.

**Comment by SteeveEbener** [comment]
Tested on staging and working for the working version of the list. I am closing this ticket
