### ISSUE TITLE
Users need to click into a change request to determine the geo-object the change request is for

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#663]
## User stories
1. RM searches for a specific change request

## Problems this relates to
Difficulty in navigating to a change request
1. To find a specific change request, a RM needs to click through each request until they find the correct one as the RM is only able to see the contributor and request ID
2. RMs are unable to filter or sort through a list of change requests by requester, priority or geo-object

## Proposed solution
1. In the current table of change requests, include additional columns:
* Geo-object name
* Geo-object type
* Geo-object code
2. Users can filter/sort by each column in the table (similar to list view)
3. If there is a new change request since the last time the RM has logged in, is there a way to have a notification dot on the change request module/and the specific change requests highlighted?

## Considered alternatives
1. 

## Additional context
* Proposed solution 1 and 2 are high priority, for 3 if it's a low lift and can be done easily that would be great.

**Comment by justinlewis** [comment]
A challenge with this is that there may be many RM's. We don't currently have a way for the RC to specify which RM should get the request so any display needs to account for many RM's.

**Comment by SteeveEbener** [comment]
@justinlewis : I am not sure to understand the issue you are describing. Request are geo-object type and not RM specific => any RM having the curation mandate over the geo-object type should see the requests in question.

If this relates to point 3 in the original ticket then is the functionality being described really needed once the table can be filtered as the contribution date is being provided?

I would more focus on the issues listed in ticket #630

**Comment by justinlewis** [comment]
- [ x ] Geo-object name
- [ x ] Geo-object type
- [ ] Geo-object code

**Comment by SteeveEbener** [comment]
Change request sorting implemented in 0.17.0 but not the filtering

**Comment by justinlewis** [comment]
@vrajasekaran18 and I agreed that because the level of effort for filtering is relatively high and the sorting allows for similar behavior that we won't implement filtering for this ticket.

**Comment by SteeveEbener** [comment]
The difference between the two functionalities become obvious once you have more than one page of change requests.

If there was not enough resources to implement both then this should have been discussed to decide which one of the two should be implemented. I would argue that in this particular case filtering would have been much more useful to help the user find a specific request (and this especially as the current grouping of requests is not very useful).

What about a general search function if the filtering currently used for a list can't easily be transferred to the change requests module?

**Comment by SteeveEbener** [comment]
@justinlewis : question in my last comment remaining to be answered.

At the same time, I would change "Geo-Object"  to "Geo-Object Name" as the header for the 3rd column in the list of requests
