### ISSUE TITLE
"Show" button appearing in the geo-object editing modal while it shouldn't

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#668]
**List the CGR information**
- CGR version: 0.15.4
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The "Show" button is appearing in the geo-object editing/viewing modal while:
- Case 1: you are adding a new instance for the geometry (first screenshot below)
- Case 2: there is no geometry in the graph (see second screenshot)
- Case 2: the geometry is already appearing on the map (instance corresponding to the temporal validity of the list I am looking at - third screenshot below)

**To Reproduce**
Case 1: As the RA/RM having the curation mandate over the geo-object type:
1. Go to the lists module
2. View the list for a geo-object type for which there is no geometry in the graph
3. Open the editing/viewing modal for one of the geo-object
4. add an instance for the geometry
5. See error: the "Show" button is appearing

Case 2: As the RA/RM/RC:
1. Go to the lists module
2. View the list for a geo-object type for which there is no geometry in the graph but for which an instance of geometry has been created
3. Open the editing/viewing modal for one of these geo-objects
5. See error: the "Show" button is appearing

Case 3: 
As the RA/RM/RC:
1. Go to the lists module
2. View the list for a geo-object type for which there is geometry in the graph
3. Open the editing/viewing modal for one of these geo-objects
5. See error: the "Show" button is appearing while the geo-object is already on the map

**Expected behavior (clear and concise)**
Case 1 and 2: The "Show" button is not appearing if there is no geometry in the graph
Case 3: The "Hide" button instead of the "Show" one is appearing in the modal for the instance corresponding to the temporal validity of the list I am currently lookin at (the "Hide" button switch of course to "Show" in case you click on it => the geometry disappear from the map)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/132945583-03b55ebc-b91b-4c3e-ba4c-47ccc513d4a4.png)

![image](https://user-images.githubusercontent.com/12602163/132945742-ffd8f915-cb43-462f-8cbc-b7424ae1cd2c.png)

![image](https://user-images.githubusercontent.com/12602163/132945590-b64a3799-954f-4257-b97a-7f6157b0fcc2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: the latest one

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
I have also just noticed that the "Edit Geometries" button (that should read "Edit Geometry") is appearing when you click the "Show" button while the geo-object is not in the editing mode => clicking on the "Show" button in this situation should not display the "Edit geometry" button

**Comment by justinlewis** [comment]
For clarrity, the show button shows the geometry from the graph. What you see in the map on page load (before pushing the show button) is a cached map layer of the list data with the specific Geo-Object styled differently (maroon). So, the basic workflow as it's implemented right now would be:
1. Load the map (by clicking edit from a list). This loads the list specific map. 
2. See the cached layer of all the geometries in the list with the selected Geo-Object styled in maroon. 
3. Click the show button to show the geometry from the graph. The edit button also appears. 
4. Click on the edit button to edit the geometry from the graph. 
5. Click stop editing to save. 

There are a couple ways I think we can make this more clear that also could work with @steeveebener's suggestions above:
1. Don't style the selected geometry in the cached layer (list data) differently from the rest. This seems to create confusion with the idea of showing the geometry from the graph. 
2. Don't show the cached layer by default. This is used for context but maybe explicitly turning it on would help understand that it's different from the data when editing. 
3. Change the label of the show button to "Show instance" or something similar.

**Comment by SteeveEbener** [comment]
Working on answer the comments to ticket #635 this morning I realized that the issue captured here is part of a larger issue captured in #635 => I have transferred the points that are relevant here to that ticket and I am closing this one.
