### ISSUE TITLE
Shire list on Demo has a start date of 0212-09-15 (see the year) which should be 2012 after release 0.15.0

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#669]
The database has 0212-09-15 as the start date. We need to determine if this was caused by the release (e.g. the migration script) or if this was how the data was before the release. One option is to restore the pre 015.0 release data to see what the value is.

Reported by @steeveebener

![image (44).png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/79604b35-7666-4650-bb98-32b8fa3189fe)

**Comment by justinlewis** [comment]
We pulled the data from an older version of the CGR and the date was bad there as well. I hate to say it but we so no reason this could be the software creating this. We think it was a typo when the data was created

**Comment by SteeveEbener** [comment]
I am correcting the Tolkien data and the start date was actually supposed to sometimes be 2000-01-01 and in other cases 2007-04-20....
