### ISSUE TITLE
Inactivating a GeoObject needs more configuration settings

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#67]
Inactivating a GeoObject should ask the date from which this inactivation is valid as well as the reason for such inactivation (duplicate, closed health facility,....), reason that should come from a pre-defined list

**Comment by justinlewis** [comment]
We need to define the list of options. I'll suggest:

- duplicate
- permanant closure
- temporary closure

**Comment by SteeveEbener** [comment]
For sure duplicate and permanent closure to which you can add:
- Does not exist
- Not a health facility

The temporary closure will depend on how the CGR can handle this "status" information through time.

In other words, can the GeoObject be inactive for a certain period of time and then active again and all of this being maintained in the CGR with start and end dates?

If not, then maybe that the "Temporary closure" option will have to be managed in a "Status" field.

**Comment by dtreatman** [comment]
Agree with prioritizing this enhancement, aligns well with Curation epic. 

Regarding "Not a health facility", if the list of reasons can be generated dynamically, then "Not a [GeoObject type]" where "[GeoObject type] is automatically replaced with whatever the GeoObject type is, that would be ideal.

Alternatively, suggest that "Not a health facility" be replaced with "Incorrect GeoObject type" (to be a generic reason for any GeoObject type).

**Comment by SteeveEbener** [comment]
The way inactivation is being treated starting from version 0.16.0 changes the original direction of this ticket but the need to capture the reason for inactivating a geo-object still remains (missing under 0.16.0)
