### ISSUE TITLE
Importing localization results in unspecified error

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#670]
From Rica at CHAI

Mag and I are trying to import a Lao localization file into v0.15.4 of the CGR on the Laos instance, however we receive an unspecified error. 

See attached localization file

[https://app.zenhub.com/files/142912671/421b0843-55aa-4423-a546-ac2cb1a2fac6/download](https://app.zenhub.com/files/142912671/421b0843-55aa-4423-a546-ac2cb1a2fac6/download)

**Comment by rfromthecastle** [comment]
Hi @justinlewis and @rrowlands, I tried importing the localization file again on Staging and it worked this time.
