### ISSUE TITLE
Exporting shapefiles with Laos characters result in imporoperly encoded Laos text

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#671]
Reported by Rica at CHAI. cc: @vrajasekaran18 

Having compared an exported shapefile with a shapefile that does have Lao characters properly encoded and displayed in an attribute table (I’ve attached an example), I noticed that the CGR exported shapefile has an encoding of windows-1252, as opposed to UTF-8 (which covers Lao characters).

I think what may resolve this issue is in the code that writes the shapefiles in the CGR, specifying that the file has UTF-8 encoding.

[sample data](https://app.zenhub.com/files/142912671/f8938e3b-43e9-45af-8365-ca3b38bb3972/download)

**Comment by justinlewis** [comment]
The shapefile standard doesn't support UTF-8 natively. Other vendors have used workarounds that might be seen as hacks. 

[See this post](https://gis.stackexchange.com/questions/3529/which-character-encoding-is-used-by-the-dbf-file-in-shapefiles#:~:text=The%20original%20DBF%20standard%20defines%20to%20use%20ISO8859-1%2C,to%20extend%20the%20standard%20to%20define%20the%20encoding)

We use the popular GeoTools for handling Shapefiles and have the encoding set to UTF-8

```
 ShapefileDataStore dataStore = (ShapefileDataStore) dataStoreFactory.createNewDataStore(params);
    dataStore.setCharset(Charset.forName("UTF-8"));
    dataStore.createSchema(featureType);
```
We need to verify that the exported shapefile is actually encoded as UTF-8 or something else. I'll look into that now.

**Comment by justinlewis** [comment]
We are having a hard time reproducing this issue. This is what the Shapefile and spreadsheet exports look like on my system. 

![Screenshot from 2021-09-16 15-52-23.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/b3485794-c630-4155-860d-d78dc4fe4f34)

![Screenshot from 2021-09-16 15-51-15.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/5fac4f2d-4627-428a-8429-d901315a565c)

**Comment by SteeveEbener** [comment]
@justinlewis : do you mean that the CGR does not support UTF-8 at the export?

**Comment by justinlewis** [comment]
@steeveebener We're looking into what specifically the issue is because as you can see in my comment above the characters render as expected. However, in truth the Shapefile spec does NOT support UTF-8. It seems that platforms like Qgis need to use tricks to support it. One of the shortcomings of the Shapefile.

**Comment by rfromthecastle** [comment]
Hi @justinlewis , wanted to provide some screenshots from my QGIS (in which I loaded a shapefile exported from the CGR) in case they may be of use:

![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/90e639ab-0c3b-42a2-b870-fe82ec96892f)

![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/557809e3-fd87-4b22-abd8-26ceaefb9f59)

**Comment by rfromthecastle** [comment]
Hi @justinlewis , when importing the shapefile into QGIS, I found an option to specify the encoding, which does render the Lao characters:

![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/94c838c0-c30a-4a15-8598-e39bfbdbf619)

![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/c9ca93c9-7ac8-4e28-b38b-c83e39bac97d)

There is a similar option in the layer properties where you can set the encoding, with UTF-8 as an option:

![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/1a5e2953-d3da-4921-b157-ef33e4c7d94c)

I'm still wondering though, for ease of use for the end users, if there is a way for this encoding to already be set during the export? The example shapefile I sent already has it set, but I'm not sure if this is easy to do in the GeoPrism code. Having this would not only have benefits for Lao script, but also a host of other scripts (e.g. Burmese, Welsh, Bengali...).

**Comment by justinlewis** [comment]
@rfromthecastle can you check if there's a file in the bundle of shapefile files with a .cpg extension. If so can you copy the contents here?  

If none exists can you try taking [this one](https://app.zenhub.com/files/142912671/d0fd5c42-d86b-42bf-a0ad-0dae84994504/download), unzip it, make sure it's in the same place as the other shapefile files, and try to add it to QGIS again. This is an optional file that some software uses to set the encoding. I'm trying to determine if this will set the default to UTF-8 for you.

**Comment by rfromthecastle** [comment]
Hi @justinlewis , the [districts shapefile bundle](https://app.zenhub.com/files/142912671/ac4372df-f72e-4d61-99e5-b0b3d37823c3/download](https://app.zenhub.com/files/142912671/ac4372df-f72e-4d61-99e5-b0b3d37823c3/download) which I sent in my initial email does contain a .cpg which contains "UTF-8". This bundle does automatically load with UTF-8 encoding in QGIS.

**Comment by justinlewis** [comment]
@rfromthecastle and I talked on Slack further. This was the key takeaway:

> 
> I shared screenshots of the HFML file (which does not have the .cpg file) to show that there is an option you can set in QGIS for it to interpret the file based on UTF-8 encoding. For the districts shapefile (which does have a .cpg file) had the .cpg file already included when I downloaded it from the Lao DECIDE Info platform. To answer your two questions:
> When I add a shapefile to QGIS that does have the .cpg file, the encoding is indeed correctly set to UTF-8.
> The issue indeed occurs when I add a shapefile without that .cpg file. I removed the .cpg file from the districts shapefile and imported it into QGIS, and the attribute values in Lao showed up as random symbols.

I think the solution is to manually add the .cpg file to Shapefile exports. The geospatial backen library we're using for format manipulation (GeoTools) doesn't support this (I believe) but we'll look for a workaround.
