### ISSUE TITLE
Show invalid geo-objects is confusing for users

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#677]
**List the CGR information**
- CGR version: v16.1
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
When a user clicks the show invalid geo-objects the list still shows valid geo-objects and invalid geo-objects are scattered through the list

**To Reproduce**
1. As a RM Go to the Health Facility Master List
2. Click on show invalid geo-objects
3. See error: The list shows both valid and invalid geo-objects with the invalid geo-objects scattered through the list

**Expected behavior (clear and concise)**
As a user, when clicking the show invalid geo-objects either: 1) Only the invalid geo-objects are shown OR 2) Update the label to read also show invalid geo-objects so invalid and valid geo-objects are shown with invalid geo-objects at the top

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
The label change and the filtering appears to have already been implemented on 1.0.0. Perhaps this ticket is out of date?

**Comment by SteeveEbener** [comment]
What needs to be solved is captured in #840 and #682 (ticket that has to be reopened).

The ticket here can indeed be closed
