### ISSUE TITLE
Make it more obvious/visible that the stability period bar needs to be fully selected to edit across time

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#679]
cc/ @vrajasekaran18 

High: When the user clicks edit, they are automatically taken to the top of the editing window
Option 1: Have two edit buttons (1. Edit all instances 2. Edit existing period)
Option 2: Have 1 edit button, auto-scrolling to the top of the window and prompting the user on view all button
Option 3: When a user clicks edit, they automatically see all instances
Option 4: Bring the edit button to the top (keep submit + cancel at the bottom)

**Comment by SteeveEbener** [comment]
What exactly has been addressed here as I see that several of the points included in the mockup mentioned in my comment dated Oct 29 have not been addressed?

**Comment by justinlewis** [comment]
@steeveebener - Option 2 was implemented.

**Comment by SteeveEbener** [comment]
@justinlewis: Thanks. Then the issue is not fully addressed as per my comment dated Oct 29th, 2021

**Comment by justinlewis** [comment]
Closing because this was already approved by the submitter (chai) and your slide deck covers more than the original ask to highlight that the whole stability bar needs to be selected. I looked at the app and we have incorporated some of that feedback on your deck but not all. You'll need to create another ticket if you don't have one for that feedback already.
