### ISSUE TITLE
GeoObject parent change needs time period setting 

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#68]
A change of parents should trigger for the RA/RM to specify for which validity period the change is valid.

The ability to set time period must be available for both the RC and RA/RM context.

**Comment by dtreatman** [comment]
Agree on prioritizing this fix

**Comment by justinlewis** [comment]
@steevebener - can you provide some more context?

**Comment by SteeveEbener** [comment]
Wow, that's an old one that must have been posted before the possibility to specify a validity period (start/end date) has been integrated. This issue can be closed
