### ISSUE TITLE
Historical Events module: User can choose a Geo-object type that his not under its curation mandate for the after type

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#688]
**List the CGR information**
- CGR version: 0.17.0
- CGR instance (e.g. a URL): Staging/Demo

**Describe the bug (clear and concise)**
The RA/RM can select geo-object types that are not under its curation mandate (i.e. from other organization) in the dropdown that appears for the "Geo-object type After" field.

**To Reproduce**
As the RA/RM (for Moha for example):
1. Go to the HE module
2. Click the create button
3. Enter an event date, description and choose one "before" geo-object type (no problem there)
4. Click the dropdown for the "Geo-Object type after" field
5. See error: all the geo-object types in the CGR are appearing in the dropdown (see screenshot below

**Expected behavior (clear and concise)**
Only the geo-object types under the curation mandate of the organization to which the user is attached to are appearing in the "Geo-Object type after" dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/141111025-aeb55006-61e6-44bc-8e23-3717406a4189.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**

**Comment by rrowlands** [comment]
We chose this implementation because we didn't want to restrict behavior more than necessary. I'm going to loop @justinlewis and @nmceachen in on this one because it might require a larger discussion.

**Comment by SteeveEbener** [comment]
This implementation is based on a misconception because historical events can only be between geo-object types under the curation of the same organization

**Comment by justinlewis** [comment]
Discussions with @steeveebener and @vrajasekaran18 have lead to the agreement that we will remove the ability to access Geo-Object Types outside of the organization of the user who is creating the historical event but will allow access to Geo-Object Types that are within the organization but under the mandate of another person.

**Comment by SteeveEbener** [comment]
Tested under 0.17.2 and it is working. I am closing this ticket
