### ISSUE TITLE
Historical Events module: No logic behind the list of geo-objects appearing in the dropdown

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#689]
**List the CGR information**
- CGR version: 0.17.0
- CGR instance (e.g. a URL): staging/demo

**Describe the bug (clear and concise)**
When creating an event, the list of geo-objects that are appearing in the dropdown when you click on the field does not present any logic (not listed by alphabetical order or according to their unique identifier)

**To Reproduce**
As a RA/RM (for Moha for example):
1. Go to Historical Events module
2. Create a new event at the shire level (merge or split)
3. click in the field for selecting the geo-object
3. See error: there is no logic in the list of options that are appearing(see screenshot below)

**Expected behavior (clear and concise)**
Either there is a logic in the list that appear or the dropdown does not appear until the user start typing a character

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/141112637-53141c63-b17e-40f5-a28c-dea8d20ff057.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context (if any)**
I remember having mentioned this same problem for the dropdown in another module but can't manage to find the concerned ticket

**Comment by rrowlands** [comment]
If we were to order that list alphabetically would that resolve this ticket?

**Comment by SteeveEbener** [comment]
That could indeed a solution if the dropdowns across the platform are kept

**Comment by SteeveEbener** [comment]
Tested under 0.17.2 and the geo-objects in the dropdown are now appearing in alphabetical order. I am closing this ticket
