### ISSUE TITLE
Data import fails for RM

### ISSUE THREAD

**Issue by vrajasekaran18** [terraframe/geoprism-registry#701]
**List the CGR information**
- CGR version: v17.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**
Importing of data fails for RM with a Java error thrown.

**To Reproduce**
1. As a RM Go to the import module
2. Import a spreadsheet for the geo-object type
3. Go to scheduled jobs and see the error

**Expected behavior (clear and concise)**
Spreadsheets/shapefiles successfully upload into the CGR

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2ac24ff6c267222d5f03cc/82e3d1c4-6cc9-4fe3-84c4-c587d4577012)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest[https://app.zenhub.com/files/142912671/0b8f9c6a-4df1-48dc-ad02-c7a61f8e06f1/download](https://app.zenhub.com/files/142912671/0b8f9c6a-4df1-48dc-ad02-c7a61f8e06f1/download)
**Additional context (if any)**

**Comment by rrowlands** [comment]
![cgr-701.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/d78a92e8-f2b5-43f2-962d-6a341faef301)
