### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#705]
- How Geo-Object Type public / private works
- How Geo-Object Type public / private affects lists
- Import hierarchy config
- historical events
- logic for task
- Logic for fixibility of geoobjecttypes in historical event widget
- behavior of empty values (e.g. null) when importing
- error resolution on imports (see https://app.zenhub.com/workspaces/geoprism-registry-5df81d4b734ff217d40b12a4/issues/terraframe/geoprism-registry/238#issuecomment-946846833)
- behavior for dhis2 sync when deleting geo objects
- configurability of the Explorer through georegistry.properties

**Comment by SteeveEbener** [comment]
We actually also need a more detailed documentation regarding the import process in general, especially when it comes to the impact of the different options that can be selected throughout the process. Thanks in advance for that
