### ISSUE TITLE
Automatically refresh row in list after editing a single Geo-Object

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#725]
Previous discussions about automatically refreshing Lists have resulted in development research that's determined the complexity of automatic refresh of an entire Working List is prohibitively resource intensive However, a solution has been identified that solves the problem of not seeing edits reflected in the current view (e.g. after editing a geometry in the Explorer). 

Solution:  When a Geo-Object is edited from the Explorer or a Change Request any corresponding working list that contains that Geo-Object will be updated for the row of that Geo-Object only. 

This solution does not address refreshing Working Lists when data is imported. Working lists would still need to be manually refreshed in this case.

**Comment by SteeveEbener** [comment]
Just tested under Version: 1.0.1 (2023-02-24T21:25:54Z) and submitting a change for a geo-object from the list (after clicking on the view eye icon) as a RA or RM does not lead to an automatic refresh in the list => You still have to click the refresh button
