### ISSUE TITLE
Creating a geoobject should not require a geometry

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#73]
You can't add a new GeoObject without creating its geometry. This should not be mandatory because in many case the geometry in question will be unknown. Adding the gemoetry for a point format GeoObject Type does actually not work (the submit button remains unaccessible)

**Comment by dtreatman** [comment]
Agree on prioritizing this fix - should be able to create a GeoObject without knowing its geometry (this should then come up in the Curation module, where RMs should be able to see GOs that are missing geometries and need to be located)

**Comment by justinlewis** [comment]
I have not been able to reproduce either of these issues.
