### ISSUE TITLE
List and date generated information empty when opening a list for the first time

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#732]
**List the CGR information**
- CGR version: 0.18.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
1. When you open the working version for one of the instances in a frequency- or period-based for the first time it is empty. You need to click the refresh button for the list to happen while you don't need to do that for a single date one
2. The "Date generated" field is empty

See screenshot below for both

**To Reproduce**
As a RA/RM:
1. Go to the lists (&Spatial data) module 
2. Create a single, frequency- or period-based set for one of the geographic object type over which the RA/RM has the curation 
3. Open one of the instances in the set
3. See error: empty list and empty "Date generated" field
4. Click the refresh button, the content of the list appears but note the "Date generated" information
5. Exit the list and re-enter it: The "Date generated" is now appearing

**Expected behavior (clear and concise)**
1. There is no need to click the "refresh" button for the list to appear when opening the list for the first time
2. The "Date generated" information is there when you open the list for the first time

This is the current behavior under  0.17.2

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/150089476-f6cc0adb-f2a5-49e4-8bc3-042dc6d7c58e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: The latest one

**Additional context (if any)**

**Comment by jsmethie** [comment]
No longer valid (old list module)
