### ISSUE TITLE
Glitch in the explorer module when looking at a geo-object presenting different geometries

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#736]
**List the CGR information**
- CGR version: 0.18.0
- CGR instance (e.g. a URL): staging

**Describe the bug (clear and concise)**

**To Reproduce**
As the MOHA RA:
1. Go to lists (& spatial data) module: 
2. Open the "Province (MOHA)" list for 2021-12-31) 
3. Click the edit pen for the Andustar province. You get this:
![image](https://user-images.githubusercontent.com/12602163/150917345-9dd467a5-13fb-4559-bcfc-4832422b4783.png)
4. Click the "Show" button, the Andustar province appears as expected:
![image](https://user-images.githubusercontent.com/12602163/150917466-4eb89ed2-22eb-48a1-bdba-c7d57271c58e.png)
5. Click "view all"  on top of the history bar: (first error: the the "Hide" button for the latest period turns back to "Show" while the geometry is still in the map):
![image](https://user-images.githubusercontent.com/12602163/150917551-e5564ec7-48b4-4e43-aab1-c892430b90de.png)
6. Click the "Show" button for the older period ("Hide" appears for the older period "Show" remains for the most recent one):
![image](https://user-images.githubusercontent.com/12602163/150917790-6a2919b2-d185-47b0-aac0-d883c80613d3.png)
7. Click "Show" for the most recent period (button turns to "Hide" without any change on the map):
![image](https://user-images.githubusercontent.com/12602163/150918082-b9231411-45bf-42c9-80ed-869e85d8d4a0.png)
8. Click view selected period (second error: the "Hide" button turns to "Show" while the geometry is still on the map)
![image](https://user-images.githubusercontent.com/12602163/150918359-eeef5957-972a-481d-8144-5d4ee1f41366.png)
9. Click the older period in the history tab (third error: the "Hide" button is back to "Show" while the geometry is on the map
![image](https://user-images.githubusercontent.com/12602163/150918580-8711ecd0-f204-4e3d-bf89-890b8d677365.png)

**Expected behavior (clear and concise)**

The content of the show/Hide button is not affected by operations made in the geo-object viewing/editing modal

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: latest

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
Tested on v0.19.3 and fix working.

**Comment by SteeveEbener** [comment]
Thanks Rica but, while one of the issues has been solved (the show and hide button is working correctly when it comes to showing the geometry from the graph), the problem mentioned under steps 5, 6 and 8 in the original ticket remains.

In other words, the instance of the geo-object for which you open the modal in the first place remains on the map all the time even if you select the older instance in the upper bar => this is misleading.

=> A possible solution to address this is reported in the comment dated October 12, 2021 for ticket #635 (description for a point type geo-object but this would be the same for polygons. 

=> not fully working for the moment

**Comment by justinlewis** [comment]
@steeveebener This functionality has changed since posting this. Right now the original geometry is part of a layer displayed in the layer panel. You can turn off that layer now where before you couldn't because there was no layer in the layer panel. 

I'm not sure what the issue is with the behavior on slide 6 above. Are you expecting the show/hide buttons to behave like radio buttons where you can only show one at a time?  If so that makes it more difficult to compare geometries. 

I believe the behavior in slide 8 above is not changing show to hide. I think it's removing the time periods that don't fit what you selected in the time bar. The one that fit the time period said show.

**Comment by SteeveEbener** [comment]
@justinlewis : The complete layer is indeed appearing in the layer panel on the right but the geo-object for which you open the modale is now highlighted in a different color while the button for that period is the "Show" one while it should be "Hide" as per the following screenshot: 
![image](https://user-images.githubusercontent.com/12602163/187120200-a3c67b8a-cb2b-49d9-a868-575ef508f5d3.png)

+ it remains highlighted all the time 

= > the UI is still confusing 

What I would be expecting is as follow:
1. When you reach the modale for a given date or period the geo-object is indeed highlighted but the button we see is "Hide".
![image](https://user-images.githubusercontent.com/12602163/187121051-7649b5c7-f00a-485b-93e6-c0a66fd593b4.png)
2. If you click on "Hide" the geo-object is not highlighted anymore and the button turns to "Show"
![image](https://user-images.githubusercontent.com/12602163/187121329-8f4bf3e6-7ea1-4624-9d22-ff7af6401a5f.png)
3. If I click on the other period in the history bar for that geo-object then I can get the map showing the geometry for that period and the  "show" button:
![image](https://user-images.githubusercontent.com/12602163/187121996-b6df37d8-09d5-4b7d-8acc-a0c06b3cb321.png)
4. If I click the "Show button" then the geometry for that period is highlighted and the button turn to "Hide":
![image](https://user-images.githubusercontent.com/12602163/187122436-0f471a56-b81e-4c10-b718-c32c991d63f5.png)
5. If I click on the "view all periods" option then I get this:
![image](https://user-images.githubusercontent.com/12602163/187123112-f240916c-5530-4518-8a91-7fe624c1f8fb.png)

I hope this makes sense and sorry for the different colors between screenshots, I had to restart the process different times to get all of them.

**Comment by rfromthecastle** [comment]
The UI isn't misleading/confusing to me. As for the layer showing all provinces, you can turn that off in the layer widget.

**Comment by SteeveEbener** [comment]
Just tested under Version: 1.0.1 (2023-02-24T21:25:54Z) and the UI is now working as anticipated

The change seems nevertheless to have created a new bug.

In staging, and as the MOHA RA/RM:
1. Click on the Province (MOHA) geo-object type
2. Open the Province master list and geospatial data set
3. Open the list for the working version for the 2007-04-20 - Present instance
4. Click on the viewing eye for the Andustar Province and then on the geometry tab. You get this:
![image](https://user-images.githubusercontent.com/12602163/221352033-bf250c7c-22df-4f88-8c04-11deb87b290d.png)

=> the two periods are appearing on the left bar (2000-01-01 to 2007-04-19 and 2007-04-20 to present) while you should only have the 2007-04-20 - Present one like this:
![image](https://user-images.githubusercontent.com/12602163/221352079-2405c063-5914-4a28-862f-bc6594362b33.png)

=> can this per chance be fixed before we close this ticket?

Thanks

**Comment by jsmethie** [comment]
Moved back to New to be re-evaluated for new functionality.

**Comment by SteeveEbener** [comment]
Just tested and working as expected now. Closing this ticket
