### ISSUE TITLE
Submit button activating despite required contributor notes field not filled out

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#75]
The submit button becomes active while the "Contributor notes" field has not been filled while mandatory. This is when submitting a change request from a List.

**Comment by dtreatman** [comment]
Agree on prioritizing this fix

**Comment by justinlewis** [comment]
![Screenshot from 2020-06-11 23-43-33.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/389496f6-3a13-41ed-9378-2e059033dc2b)

**Comment by SteeveEbener** [comment]
I just tested this from the MOHA RC account and could submit a change request without filling the reason field => this does not seem to work properly

**Comment by justinlewis** [comment]
I changed made changes to the change request form in the lists section which also had this issue. I'm going to modify the title and description to indicate that and create a new ticket for the other form that you're talking about.

**Comment by CarlyNel** [comment]
Hi @justinlewis If Steeve's comment/error has been captured in a new ticket, should this ticket be closed?
