### ISSUE TITLE
List&spatial data module - Clear filters button not working

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#750]
**List the CGR information**
- CGR version: 0.18.2 (2022-04-01T04:58:25Z)
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
- Clicking the clear filters button in a list does not clear the filters

**To Reproduce**
As any role
1. Go to the lists & spatial data module
3. Open one of the list
4. Filter the list according to one of the data elements
5. Click the "Clear filters" button
6. See the error: The filters are not cleared (the filtering value actually remain in the filtering field - see screenshot below)

**Expected behavior (clear and concise)**
The clear filters button clears the fielters

**Screenshots**

![image](https://user-images.githubusercontent.com/12602163/161458392-9d96c483-a9fb-4a43-a59d-fe1c05e89337.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**

**Comment by jsmethie** [comment]
The new table widget we are using doesn't support removing all filters through a button.  I will remove that button so the user doesn't expected something the happen when it won't

**Comment by rfromthecastle** [comment]
So in this fix, will the user then have to e.g. use the backspace to delete a text value in a text filter? In that case, would there be an option to have a small button next to each filter field (such as a small cross) so the user can easily cleared what they entered in the filter for one attribute?

**Comment by SteeveEbener** [comment]
Tested and the user indeed has to either use the back button or select the content of the filter field and click the delete key => I am closing this ticket
