### ISSUE TITLE
Classification Types module showing in hamburger menu

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#753]
**Instance details**
- CGR version: v0.19.0
- CGR instance (e.g. a URL): [https://staging-georegistry.geoprism.net/cgr/](https://staging-georegistry.geoprism.net/cgr/)

**Description**
A "Classification Types" module is listed in the hamburger menu for Registry Administrators, even though this module does not show on the homepage. When clicking on this module, I am taken to a blank page with a Create button.

**Steps to recreate**
1. As a Registry Administrator, expand the hamburger menu. 
2. A "Classification Types" option is displayed.

**Expected behavior**
Only the modules displayed on the homepage should be listed in the hamburger menu, plus the settings and localization options.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/1a1ba1a4-a2ad-4b10-bc4a-981199fc49a1)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 100.0.4896.75

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
Low priority for Laos

**Comment by rfromthecastle** [comment]
I think this can be closed? Didn't know when I was testing this that Classification Types was an actual module in the CGR mode of GeoPrism Registry.

**Comment by SteeveEbener** [comment]
This is not meant to be an actual module but a functionality linked to the possibility to re-use classification-based attribute.

While the present ticket could indeed be closed, the management of this type of attributes remains to be addressed as captured in ticket #805

**Comment by rfromthecastle** [comment]
Closing this ticket, with the management of classification type attributes to be handled in ticket https://github.com/terraframe/geoprism-registry/issues/805
