### ISSUE TITLE
When adding a second custom attribute to a newly created group, the group gets automatically duplicated

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#756]
**List the CGR information**
- CGR version: 0.19.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
When adding a second custom attribute to a newly created group, the group gets automatically duplicated

**To Reproduce**
1. As a Registry Administrator, open the Geo-Objects and Hierarchies module 
2. Add a new Geo-Object Type group.
3. Add a custom attribute of any type and submit until you return to the module's main page.
4. Edit the group again and add a new custom attribute.
5. Submit again until you return to the module's main page.
6. The group automatically gets listed twice in the left panel.

**Expected behavior (clear and concise)**
The group should only be listed once in the left panel.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/0e3f150f-f8f5-4e31-a559-67e0feb74d67)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 100.0.4896.75

**Additional context (if any)**

**Comment by jsmethie** [comment]
I can't recreate this problem.  Is there anymore information that you can give me?

**Comment by rfromthecastle** [comment]
Hi @jsmethie, I tried to recreate the bug myself but it didn't show up this time. I've tried this using a different Wi-fi network though, so previously my slow Internet at home may have been causing this issue in the GPR. I think this is no longer an issue.

**Comment by jsmethie** [comment]
Unable to reproduce
