### ISSUE TITLE
Clearer error message for non-existent users when logging in

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#759]
## User stories
As any user, when I log in using the credentials of an account that is inactivated, I am presented with a generic "login failed" error.

## Problems this relates to
Error messaging on login.

## Proposed solution
1. Clarify the messaging to something like "user does not exist" when someone tries to login with a username of an account that is inactive.

## Considered alternatives
N/A

## Additional context
N/A

**Comment by jsmethie** [comment]
In general we like to keep the message vague such that a bad actor can't derive information about the actual usernames/passwords in the system

**Comment by rfromthecastle** [comment]
Explanation clear, please close this ticket.
