### ISSUE TITLE
Master list name length too restrictive

### ISSUE THREAD

**Issue by justinlewis** [terraframe/geoprism-registry#76]
I got the following error message when try to create a master list for "provincial Health Department" as the text for the label: [Table Name] many not exceed a length of 31 characters. It seems this might be related to the lenght of the GeoObject Type name whiloe you don't have any limitation in the number of characters there

**Comment by dtreatman** [comment]
Agree on prioritizing this fix

**Comment by SteeveEbener** [comment]
I checked this ticket as it was coming from my initial feedback google spreadsheet.

This is working now and this ticket can therefore be closed.
