### ISSUE TITLE
Geo-Objects marked as invalid still visible in list

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#769]
**List the CGR information**
- CGR version: 0.19.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
I marked a Geo-Object as invalid and published a new version of the list, however the Geo-Object (e.g. Helheim Capital Health Office in Health Facility (LD)) still shows up in the list.

**To Reproduce**
1. As a Registry Maintainer, edit a Geo-Object to be invalid.
2. Republish a version of the list this Geo-Object is found in.
3. The Geo-Object still shows up even if the "Show Invalid Geo-Objects" is unchecked.

**Expected behavior (clear and concise)**
Invalid Geo-Objects don't show up in the list unless "Show Invalid Geo-Objects" is checked.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/6b2530d7-cfdd-4b2a-8815-946c8b1e10b7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 100.0.4896.75

**Additional context (if any)**
N/A

**Comment by jsmethie** [comment]
My mistake.  That is only relevant if the Show Invalid Geo-Objects button is checked
