### ISSUE TITLE
"Lists and spatial data" has lost the "spatial data"

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#773]
**List the CGR information**
- CGR version: 0.19.0
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**

The name of the "Lists and spatial data" module in the home page and burger menu is back to "Lists"

**To Reproduce**
As any role: 
1. Go to the home page or look at the burger menu
2. See error: the module is labelled "Lists" instead of "Lists and spatial data"

**Expected behavior (clear and concise)**
The module is referred to as "Lists and spatial data" across the platform

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/165643191-39dc9b13-7bd2-4c3e-9d29-5fdf9befde0c.png)

![image](https://user-images.githubusercontent.com/12602163/165643203-7a4c4b9a-3521-4098-9f70-14b04e4eecaa.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: The most recent one

**Additional context (if any)**

**Comment by jsmethie** [comment]
I have verified that the default label for the link is "Lists and spatial data".  It looks like someone uploaded a localization spreadsheet to staging which overwrote that label to a be just "Lists".
