### ISSUE TITLE
Geo-Object Type existence start and end dates not available to map onto DHIS2 organization unit opening and closing dates in synchronization configuration

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#776]
**List the CGR information**
- CGR version: 0.19.2
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/manage#/menu

**Describe the bug (clear and concise)**
When mapping attributes in a synchronization configuration, a Geo-Object Type's existence start and end dates are not available as options to map onto a DHIS2 organization unit's opening and closing dates, the former being a mandatory field to be mapped.

**To Reproduce**
1. As a Registry Administrator, create a DHIS2 synchronization profile.
2. Edit the attributes of a level.
3. View the Geo-Object Type attribute options when selecting the opening or closing date from the DHIS2 attributes to be mapped.

**Expected behavior (clear and concise)**
The existence start and end dates of the Geo-Object Type should be available as options to be mapped onto the opening and closing date attributes for the DHIS2 organization unit.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/ecce952a-0443-4a5c-a8f5-f2a19dc8d177)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Unknown

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
Reported by Southiny Phiahouaphanh, IT Staff, Department of Planning and Cooperation, Ministry of Health, Laos

**Comment by rfromthecastle** [comment]
Critical priority for Laos

**Comment by rrowlands** [comment]
Here is what that new UI looks like:

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/7e85e3b6-d290-467b-9bb9-962af75e41e6)

If you would prefer that "Mapping Strategy" header or "Period Start Date" and "Period End Date" be called something else just let me know.

**Comment by SteeveEbener** [comment]
@rrowlands : Thanks for the tag. I guess it depends on the type of date we are talking about.

From what I am reading, it seems we are talking about the existence of each "geo-object" and not of a "geo-object type".

With the caveats that the opening and closing date in DHIS2 might not correspond to the geo-object's existence but more separated attributes (especially the opening date) or the use of a "status" attribute, I would say that the last two fields should read "Start date" and "End date". 

I can't tell for the first one (labeled as Boolean for the moment) as I don't know what this corresponds to.

I hope this helps

**Comment by rrowlands** [comment]
The "Boolean" in this context is referring to a yes/no value as to whether or not the Geo-Object exists on the date of export. Now that I think about it though, do we even want to export Geo-Objects if they don't exist on the export date? If we don't want to export them, then this would always be "true", which wouldn't even be useful, which would tell me we wouldn't even want this as an option.

**Comment by rrowlands** [comment]
The "Boolean" in this context is referring to a yes/no value as to whether or not the Geo-Object exists on the date of export. Now that I think about it though, do we even want to export Geo-Objects if they don't exist on the export date? If we don't want to export them, then this would always be "true", which wouldn't even be useful, which would tell me we wouldn't even want this as an option.

**Comment by rfromthecastle** [comment]
Hi @SteeveEbener and @rrowlands, looking at the [DHIS2 documentation](https://docs.dhis2.org/en/use/user-guides/dhis-core-version-238/configuring-the-system/metadata.html#manage_organisation_unit), organization units have the optional "opening date" and "closing date" attribute. But from the description, it looks like these are existence start and end dates: "The opening dates control which organisation units that existed at a point in time, for example when analysing historical data.".

Given this, we may still want to synchronize Geo-Objects that no longer exist on the date of synchronization, as there may be historical programmatic data in DHIS2 attached to them. Let's say we'd like to make a correction for an organization unit from the past (e.g. spelling mistake in name or wrong existence period), we may still want to be able to synchronize this.

One thing I'm not sure though is how DHIS2 displays org units that no longer exist in the org unit hierarchy. I know right now the Lao MOH marks these with an X symbol and don't make use of the "opening"/"closing date" attributes. I'd guess they would still show up in the hierarchy but that the org unit wouldn't be selectable when entering programmatic data for it past its closing date.

**Comment by rrowlands** [comment]
@rfromthecastle If it is the case that they might want to sync Geo-Objects which do not exist, then I would think it best to add an option in the sync configuration "sync non-exist Geo-Objects" which would default to false. I bring this up because I see it as more of an edge case than a primary usecase.

Thoughts?

**Comment by rrowlands** [comment]
Here's how that UI looks

![image.png](https://images.zenhubusercontent.com/5df81ec613efba2c885c40e6/5ab14799-7e3f-4cda-90cc-5332ac59f1a8)

**Comment by nmceachen** [comment]
I do believe that it is common in DHIS2 instances to have Org Units in the tree that are no longer technically active for referential data integrity as Rica pointed out. I am not sure what the common practice is for managing that in DHIS2, though.

**Comment by rrowlands** [comment]
I'm also assuming that we don't want to export invalid Geo-Objects to DHIS2.
