### ISSUE TITLE
Need to refresh Lists and Spatial Data module after creating a new list configuration to be able to see the list

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#779]
**List the CGR information**
- CGR version: 0.19.2
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
When I create a new list configuration and submit it, when I'm taken back to the page with lists for a given Geo-Object Type, the newly created list does not show up. Only when I refresh the page does it show up.

**To Reproduce**
1. As a Registry Maintainer, go to the Lists and Spatial Data module.
2. Create a new list configuration and submit it.
3. The newly created list does not show on the page for the relevant Geo-Object Type.

**Expected behavior (clear and concise)**
The newly created list shows up on the page for the relevant Geo-Object Type immediately after its configuration has been submitted.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/c2188fba-3fd0-4461-91b7-f411893afc7c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 101.0.4951.64

**Additional context (if any)**
N/A

**Comment by justinlewis** [comment]
We just fixed this yesterday. It will be released when the graph-extensions branch is merged into the main branch. 

https://github.com/terraframe/geoprism-registry/commit/498df2ab019c7ac999bf9b83d45f7cd97ad8c3ee

**Comment by rfromthecastle** [comment]
Tested on v0.19.3 and working.
