### ISSUE TITLE
Change label of the "Master List Manager" button

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#78]
Replace "List" by "Lists" on this button as there is more than one list being managed by the CGR

**Comment by dtreatman** [comment]
OK with this suggestion. Please ensure that the change is made consistently everywhere the "Master List Manager" label exists (e.g., in hamburger menu)

**Comment by SteeveEbener** [comment]
Actually, due to the " Master"  vs " Non-master" discussion we might end up having to label this module as " Lists Manager"

**Comment by justinlewis** [comment]
Closing because this was moved to another ticket as was mentioned above.
