### ISSUE TITLE
Add Geo-Object button not working on working version page for lists

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#780]
**List the CGR information**
- CGR version: 0.19.2
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
When clicking on the Add Geo-Object button on the working version page of a list, nothing happens.

**To Reproduce**
1. As a Registry Maintainer, open the working version of a list in the Lists and Spatial Data module.
2. Click on the Add Geo-Object button.
3. Nothing happens.

**Expected behavior (clear and concise)**
The button either shows a dropdown to select a Geo-Object Type within the group, or directly takes you to the editor view.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 101.0.4951.64

**Additional context (if any)**
N/A

**Comment by rfromthecastle** [comment]
Tested on v0.19.3 and fix working.

**Comment by rfromthecastle** [comment]
High priority for deployment to Staging and Sandbox before training with Provincial Health Office staff on June 22.

**Comment by SteeveEbener** [comment]
Can this ticket be closed?
