### ISSUE TITLE
Geo-Object not showing in Explorer when opening from the Change Request module

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#785]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
When clicking on the Open in Geo-Object Editor button in the change request module, the Explorer module shows up as empty

**To Reproduce**
1. As a Registry Contributor, open the Change Request module
2. Search for a Geo-Object and click on Open in Geo-Object Editor
3. The Explorer module opens but is blank

**Expected behavior (clear and concise)**
The Geo-Object opens in the Explorer

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/c9e5d3f8-3289-4ea6-83b9-83fd56bc5e73)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 102.0.5005.115

**Additional context (if any)**
N/A

**Comment by rrowlands** [comment]
Addressed as commits fb555d0f096eab0b8c03e9d7f860b289af2180f7, fafdec76805dcc922b3ee011125813f3c7b956fa, and 2c434e0b42c92a1e93d408ea25945fe40a3d17df.

**Comment by rfromthecastle** [comment]
High priority for deployment to Staging and Sandbox before training with Provincial Health Office staff on June 22.

**Comment by SteeveEbener** [comment]
Tested under 0.19.3 and working
