### ISSUE TITLE
Subtypes hierarchies appearing in the configuration window for groups

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#789]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)** 

Hierarchies are appearing in the configuration window for sets created based on a group (e.g., health facilities in Tolkien data) while these hierarchies are not to appear in the corresponding lists or spatial data

These hierarchies are hierarchies that contains some of the geo-object types part of the group in question (e.g health centre, health post,... in the case of health facilities)

**To Reproduce**
As a RA/RM
1. Go to lists and spatial data module 
2. Click on the Health facility (MOH) geo-object type 
3. Open the configuration window for the "Health facility master list and geographic coordinates" set
4. See error: the hierarchies are appearing under the "??subtypeHierarchies??" field (screenshot below)

**Expected behavior (clear and concise)**
The subtypes hierarchies are not appearing in the configuration window for groups

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/174691999-3c5b67bc-6579-4a36-bef3-ecd4e71a6eb3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**

**Comment by justinlewis** [comment]
@steeveebener I believe this is fixed now

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/acc06558-e3e8-4f58-96be-a1157d65c0c1)

**Comment by SteeveEbener** [comment]
Checked and indeed working now. Closing this ticket
