### ISSUE TITLE
Geo-object not existing from a given date appearing in the list and on the map + avoiding for the shape file to be exported

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#790]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**

The geo-object not existing over a given period are appearing in the list (including the exported one, on the map in explorer, and produce the following error message when trying to export the set in a shape file: 

{"localizedMessage":"An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff.","developerMessage":"An unspecified error has occurred.  Please try your operation again.  If the problem continues, alert your technical support staff.","dto_type":"com.runwaysdk.RunwayExceptionDTO","wrappedException":"com.runwaysdk.RunwayExceptionDTO"}

**To Reproduce**
As a MOHA RA/RM
1. Go to the lists & spatial data module
2. Click on the Province (MOHA) geo-object type in the left tab 
3. Open the instance of the list for the 2000-01-01 to 2007-04-19 period
4. See the error: the code for the TLK05 Province appears in the list while only existing starting from 2007-04-20 (see first screenshot below) 
5. Click on the eye Icon to open the view/edit modale => the popup for TLK05 appears on the map (second screenshot below) 
6. Come back to the list (you have to hit the browser back button (you have to hit the button multiple time rapidly for that)
7. Click on the export button and export it the spatial data => see the error message mentioned here above

**Expected behavior (clear and concise)**
Only the geo-objects that exist for the concerned date are appearing in the list, on the map in the geo-object editing modal or included in the exported spreadsheet or shapefile

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/174694621-bfb0b032-9b82-4a04-9462-562acf79a62e.png)

![image](https://user-images.githubusercontent.com/12602163/174694804-5fe4aba9-e7fe-45e9-a63d-1264b1c2d621.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**
This problem was already encountered with version 0.14.0 as captured in ticket #583 (Geo-object inactive from a given date appearing in the list, on the map and in the exported list or shapefile after that date)

**Comment by rfromthecastle** [comment]
Bug still persists in v0.19.5 on Staging

**Comment by SteeveEbener** [comment]
@rfromthecastle : Even after hitting the refresh button?

**Comment by rfromthecastle** [comment]
Thanks @SteeveEbener, this is now working for me.

**Comment by rfromthecastle** [comment]
Thanks @SteeveEbener, this is now working for me.

**Comment by SteeveEbener** [comment]
Thanks Rica. Closing this ticket then
