### ISSUE TITLE
The user must refresh the browser to see that a set has been deleted

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#791]
**List the CGR information**
- CGR version:
- CGR instance (e.g. a URL):

**Describe the bug (clear and concise)**
When deleting a set in the list and spatial data module, the set does not disappear from the window unless you refresh the browser 

**To Reproduce**
As a RA/RM
1. Go to the lists and spatial data module 
2. Create a new set for any of the geo-object type under the curation mandate of the organization for which you logged in 
3. Wait until the set has been created
4. Click the Delete button
5. See the error: the set does not disappear
6. Refresh the browser: the set has now disappeared 

**Expected behavior (clear and concise)**
The deleted set disappear from the window without having to refresh the browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
Working in v0.19.5 on Staging.

**Comment by SteeveEbener** [comment]
Confirmed as working. Closing this ticket
