### ISSUE TITLE
The temporal validity for an instance of list part of a period-based set is a date instead of a period

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#794]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
The temporal validity for an instance of list part of a period-based set is a date instead of a period

**To Reproduce**
As the RA/RM/RC of any organisation
1. go to the lists & spatial data module
2. Open the list for one of the instance of a period based set (example: Province (MOHA)  for the 2007-04-20 to present period - first screenshot below)
3. See error: the temporal validity date appears as "List valid on: 2007-04-20" (2nd screenshot below) instead of "List valid for: 2007-04-20 - Present"

**Expected behavior (clear and concise)**
The temporal validity for an instance of list from a period based set is indicated as a period and not as a date

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/175186384-659b4214-36f7-403b-a9e3-fea6429c121f.png)

![image](https://user-images.githubusercontent.com/12602163/175186566-7ea57a32-3632-44d1-b3fe-be54906e9f97.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**

**Comment by SteeveEbener** [comment]
I would argue that this  is not an enhancement but a bug

**Comment by SteeveEbener** [comment]
Tested under 0.19.5. A period is now indeed appearing but the label before the period still says "Valid on" and not "valid for"  (Valid on is to be used when referring to a single date)

**Comment by SteeveEbener** [comment]
Tested under 0.19.6 and the label is still "Valid on" and not "valid for" => to be adjusted for me to be able to close this ticket

**Comment by SteeveEbener** [comment]
Closed by accident. My apologies for that

**Comment by rfromthecastle** [comment]
The text still reads 'valid on' for me too on Staging

**Comment by SteeveEbener** [comment]
Confirming what is reported by Rica and this in different place:

![image](https://user-images.githubusercontent.com/12602163/221351426-016a6d1f-0ffb-487f-8667-5b1c0bfbde0b.png)

**Comment by jsmethie** [comment]
When I look at the "List Valid On" and "Valid On" labels on staging they are updated. Please look at this again and close the ticket.

**Comment by justinlewis** [comment]
I pushed a fix for this in the last release so it sounds like you're seeing it's fixed

**Comment by SteeveEbener** [comment]
@justin: This has indeed changed but the problem now is that the sets that are only representative of a given date (single date or frequency based) are now also getting the mention "List Valid For" while it should have remained "Valid On". Example:

![image](https://user-images.githubusercontent.com/12602163/224852542-26206c41-139d-412b-8c84-699b43e32931.png)

The change should have only been implemented on the period-based sets

**Comment by SteeveEbener** [comment]
After reconsidering this, I think it is fine that we have "List valid for" in both cases. Closing this ticket
