### ISSUE TITLE
All roles> Navigator

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#80]
## Problems this relates to

The search field should not:
1.  automatically switch to another hierarchy in case the search does not give a result for the hierarchy selected in the dropdown.
2. Provide GeoObjects that are not included in the selected hierarchies as options

## Proposed solution

Desired functionality: If the term is not found in the selected hierarchy, an error message saying something like “Item not found in this hierarchy” should be displayed

**Comment by justinlewis** [comment]
We are going to redesign the Navigator and since this ticket refers to the current Navigator I'm setting to wontfix and closing. However, I added this input to a requirements doc for the new Explorer.
