### ISSUE TITLE
Ability to return to list after opening in editor mode

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#800]
## User stories
_Raised by Yongjoon Park (WHO Laos) on June 24, 2022_

As any user, after viewing a Geo-Object in editor mode, I'd like to return to the list by clicking on a button. Right now, the user has to reopen the Lists module and search again for the Geo-Object.

## Problems this relates to
1. User experience

## Proposed solution
Provide button in editor view to return to list view.

## Considered alternatives
None.

## Additional context
N/A

**Comment by SteeveEbener** [comment]
This ticket should be treated in proprity. This is a major limitation to the usability of the platform

**Comment by justinlewis** [comment]
Currently this can be done by clicking on the link in the name of the layer that shows in the layer panel on the right. This would take you back to the list that the Geo-Object was in when clicking edit for the Geo-Object. 

![image.png](https://images.zenhubusercontent.com/5df81cb2f5388bdc79385d22/36bb9421-9707-43eb-a891-2235b7e80aef)

**Comment by justinlewis** [comment]
This said, we agree that we should discuss a dedicated back button.

**Comment by SteeveEbener** [comment]
One thing I just noticed. If you it the browser back button rapidly multiple times from the explorer view you actually can manage to come back to a version of the lit view that allows to then come back to the lists & spatial data module main window => there might be a way to have a real "back" from the explorer view

**Comment by rfromthecastle** [comment]
High priority for Laos. Could even just move list link in list widget to its own back button

**Comment by rfromthecastle** [comment]
Closing this ticket as resolved by improved browser back button workflow.
