### ISSUE TITLE
The shapefile map projection is not checked at the import

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#813]
**List the CGR information**
- CGR version: 0.19.3
- CGR instance (e.g. a URL): Staging

**Describe the bug (clear and concise)**
It is possible to import a shapefile that is projected into the GPR (different from EPSG:4326) without getting any error message. 

Doing so can create instabilities in the backend and the crash of the platform

**To Reproduce**

I would not recommend trying it (this was experienced importing the Mozambique data into staging)
As a any role having the importing role:
1. Import a shape file that is projected
2. Create sets out of the imported shapefiles
3. Visualize the shapefiles in the explorer module, etc..

Not sure about what crashed staging from that step

**Expected behavior (clear and concise)**
The GPR check that the imported shapefile is unprojected (different from EPSG:4326). If not, the import does not take place and a message is given to the user

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
@SteeveEbener Do you have any unprojected shapefiles you could share with us that we could easily try out on the data currently in the Staging instance?

**Comment by SteeveEbener** [comment]
@rfromthecastle : you could always project any of the shape file currently in the GPR to have one. This being said, I just tried on my side with shape file for Tolkien that was projected (UTM 51 N) and did indeed get the following message:

![image](https://user-images.githubusercontent.com/12602163/181673275-ccf1db8e-db35-44a5-8adb-1c707fc86f88.png)

=> Working and I am therefore closing this ticket

P.S.: If you want to try by yourself the zip with the shape file is here (counties, Tolkien 2000 to 2007): https://bit.ly/3vqC7Hr

**Comment by rfromthecastle** [comment]
Thanks @SteeveEbener I can confirm this also works for me.
