### ISSUE TITLE
Cannot add a new period to an already configured period-based list series

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#818]
**List the CGR information**
- CGR version: 0.19.5
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/cgr/

**Describe the bug (clear and concise)**
A vague error message shows up when adding a new period to the configuration of an existing period-based list series.

**To Reproduce**
1. As a Registry Administrator, go to the Lists module.
2. Click on a Geo-Object Type with an existing period-based list series.
3. Click on Configuration.
4. Add a new period and click Submit.
5. The error message in the below screenshot shows up.

**Expected behavior (clear and concise)**
No error message shows up and the user can Submit the form with the newly added period.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/c4970978-58ea-4f3b-8a92-48be8527d525)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 103.0.5060.134

**Additional context (if any)**
N/A

**Comment by rrowlands** [comment]
This bug was fixed as part of the work done for ticket #569.

**Comment by rfromthecastle** [comment]
The error message no longer shows up on Staging following this fix.
