### ISSUE TITLE
Published versions of the master lists not accessible

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#82]
It is currently not possible for an RA/RM to have access to the published version of the master lists extracted from the graph based on the starting date and frequency of publishing defined by the RA/RM. 

As such it is also not possible to know when the published versions have been updated for the last time.

See slides 9 and 19 of the following mockup as potential options to address this: https://docs.google.com/presentation/d/1HlGY367LOLn-ZwsTx5OMJMFo9fmiBM319B5_qk_JQMg/edit?usp=sharing

**Comment by dtreatman** [comment]
This does not currently match the way that users see Master Lists and validity dates. They first select the master list, then the see the list of published versions for that GeoObject type. The user then sees the date that each version was "created" or "published" or "extracted" (whatever term we decide to use for this action).

So, I'm not sure I fully understand the issue. Flagging for discussion with Steeve.

**Comment by SteeveEbener** [comment]
The distinction between extracted and published is important here:
- Extracted refers to the lists the RM/RA has retrieved from the graph (can be any dates)
- Published refers to the lists the RC, AU, AC can see => They are extracted for specific dates that are defined by the publishing starting date and frequency they have defined

Right now, the RA/RM can only consult the " extracted" lists and not the " published" one. At least he can't make the distinction between the two in the table and could still delete a "published"  one

**Comment by SteeveEbener** [comment]
The RA/RM can now publish and see the published version of a list based on the frequency set in the metadata but some issues remain as indicated in issue #214 .

We can nevertheless close this one
