### ISSUE TITLE
Search functionality in the Explorer module display a layer for geo-objects that do not exist

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#826]
**List the CGR information**
- CGR version: 0.19.5
- CGR instance (e.g. a URL): stagging

**Describe the bug (clear and concise)**

When the name of the geo-object type you enter in the search bar does not exist (e.g kiujotysdhjko) a layer is anyway being displayed in the legend window on the right + there is no message telling you that the geo-object does actually not exist

**To Reproduce**
As any of the roles:
1 Go to explorer module
2. Enter a date and a name for the geo-object that does not exists
3. Hit the search icon
4. See error: a layer is being displayed in the legend on the right (screenshot below)

**Expected behavior (clear and concise)**
1. The search does not display a layer in the legend + gives a message to the user when the geo-object does not exist in the graph
2. The user has access to the same functionalities than those associated to the search functionality included in the change requests module (need to specify the geo-object type + display possible options as the user types the name of the geo-object)

**Screenshots**
![image](https://user-images.githubusercontent.com/12602163/182507906-987e95d0-2700-4299-a610-24e92570a626.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest one

**Additional context (if any)**
Another good illustration of the reason why we should remove the geo-object search bar from the explorer as long as it does not provide the same functionalities as the search functionality in the change request module

**Comment by rfromthecastle** [comment]
Fix working on Staging. The no search results message is a nice addition!

**Comment by SteeveEbener** [comment]
Tested as well under Version: 1.0.1 (2023-02-24T21:25:54Z) and indeed working => closing the ticket
