### ISSUE TITLE
Unspecified error occurs when trying to edit a Geo-Object as an RC from the list view

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#830]
**List the CGR information**
- CGR version: 0.19.5
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
When clicking on the Edit button in a Geo-Object's pop-up after opening it from the list view (working version), an unspecified error occurs.

**To Reproduce**
1. As an RC, open the Lists and Spatial Data module. 
2. Open the working version of a list from a given set (in this case, logged in as Moh-RC, opening working version of latest health facility master list).
3. Open a given Geo-Object from the list view (in this case, Baggins Referral Hospital).
4. Click on the Edit button in the pop-up.
5. An unspecified error occurs, with this message showing up twice (need to click Close twice). The RC is then unable to submit a change request.

**Expected behavior (clear and concise)**
The submit a change request panel on the left opens for the Geo-Object.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/dc2d9b88-f249-4f16-bda2-aff9c56e4957)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 104.0.5112.81

**Additional context (if any)**
Occurs for any Geo-Object opened for editing.

**Comment by rrowlands** [comment]
Fixed as [5e18119cef6b4e5e8b91b9fb2c562e8720c61f88](https://github.com/terraframe/geoprism-registry/commit/5e18119cef6b4e5e8b91b9fb2c562e8720c61f88)

**Comment by rfromthecastle** [comment]
Fix working on Staging
