### ISSUE TITLE
Duplicate event IDs possible

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#832]
**List the CGR information**
- CGR version: 0.19.5
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
Duplicate event IDs visible in the event history.

**To Reproduce**
1. As an RC, open the Historical Events module.
2. Search for Geo-Object Type 'Province (MOHA)', from 2000-01-01 to present.
3. Duplicate event IDs visible in returned list (two 1s).

**Expected behavior (clear and concise)**
Only unique IDs generated by GPR for historical events.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/5ad45d6d-00c2-4c0c-998b-c1126afb3c4e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 104.0.5112.81

**Additional context (if any)**
None

**Comment by SteeveEbener** [comment]
@rfromthecastle : this is because these two records are part of the same event => they have the same vent ID

**Comment by rfromthecastle** [comment]
Thanks for clarifying @SteeveEbener! In that case this can be closed.
