### ISSUE TITLE
RC: Access to the requests that she/he has submitted

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#84]
The registry contributor who submitted a request should be able to consult, and if needed manage (modify, delete), the requests she/he has submitted and see their status as well as who treated them 

=> The change request window for a RC Should have both a "Manage" and "Submit" Option

Ticket adjusted on August 8, 2020 to account for the new versions released since it posting

**Comment by CarlyNel** [comment]
Justin confirmed that the change would be implemented on [this](url) page. ![image.png](https://images.zenhubusercontent.com/5eda94a201596292f642f925/5865bfe0-f5b8-4e8c-b6a2-a2463180d536) 

Concern was raised that the RC can't see this page and that they are the target audience for this ticket.

Justin: I think that's part of the goal. A request has come up to let contributors see the requests they've made and edit them. So we would need to open this page up to contributors and then filter for just their tasks.

CHAI: Ideally they would only see their own tasks (or potentially any task within their organization? I can't imagine that would be an issue).

**Comment by SteeveEbener** [comment]
We should discuss if the RC should be allowed to:
1. Edit a request he has submit. I personally think that he should not
2. Delete a request he has submitted as long as it is still pending. I personally think he should
3. See the requests submitted by other roles within his organization. I personally think that he should not. If it is finally decided to do so then this should only be for the GeoObject types on which he has the RM role + should only be able to view them, not delete or edit them + there should be a way for the RC to easily filter his requests from the others

**Comment by CarlyNel** [comment]
Rica recently clarified/confirmed with the DPC: "they want RCs to be able to see the change request they made and some sort of status. What they’re trying to solve essentially is the issue of RCs calling them all the time to see what happened to their request"

**Comment by SteeveEbener** [comment]
My feedback:
- The "Submit" section is not appearing in the module anymore and this for any role. I  discussed this possibility with Nate but this was meant to go together with some adjustments in the geo-object modal for the RC to clearly understand he is not editing but submitting a request for change (e.g. changing the edit pen icon, not mentioning "edit" on the buttons but more something like "submit change"). If ever it has been decided to move forward with this then the "Manage" option on top of the window could be removed
- The possibility to edit a change request that is still pending has not yet been implemented (the edit button is there but the following error message appears when clicking it: "You do not have permission to update [2d9a518b-b7e4-44d6-a04e-0f20720005d1]"
- The possibility to delete a change request that is still pending has not yet been implemented (no button for that)
- The RC can't easily identify what the request is about without opening it. Linked not only to the question of the unique ID to be attached to each request (se ticket #61) but also the information that should

**Comment by justinlewis** [comment]
@steeveebener

Removing the stand alone change request was done inntentionally in Release 0.13.0. This topic should be discussed outside of this ticket.
- The "Submit" section is not appearing in the module anymore and this for any role. I discussed this possibility with Nate but this was meant to go together with some adjustments in the geo-object modal for the RC to clearly understand he is not editing but submitting a request for change (e.g. changing the edit pen icon, not mentioning "edit" on the buttons but more something like "submit change"). If ever it has been decided to move forward with this then the "Manage" option on top of the window could be removed

These are optomizations/additions that would need to be prioritized outside this ticket:
- The possibility to delete a change request that is still pending has not yet been implemented (no button for that)
- The RC can't easily identify what the request is about without opening it. Linked not only to the question of the unique ID to be attached to each request (se ticket #61) but also the information that should appear on the main page of the module to help any role to identify what each request is about

A new ticket should be created for this:
- The possibility to edit a change request that is still pending has not yet been implemented (the edit button is there but the following error message appears when clicking it: "You do not have permission to update [2d9a518b-b7e4-44d6-a04e-0f20720005d1]"

**Comment by SteeveEbener** [comment]
The following bullet point has been included in the user feedback google template:
- The RC can't easily identify what the request is about without opening it. Linked not only to the question of the unique ID to be attached to each request (se ticket #61) but also the information that should appear on the main page of the module to help any role to identify what each request is about

These ones have been included in a new ticket (ticket #536):
- The possibility to delete a change request that is still pending has not yet been implemented (no button for that) - Ticket #
- The possibility to edit a change request that is still pending has not yet been implemented (the edit button is there but the following error message appears when clicking it: "You do not have permission to update [2d9a518b-b7e4-44d6-a04e-0f20720005d1]"

I am closing this ticket
