### ISSUE TITLE
Error showing that parent of Geo-Object does not exists in a given time range even though it does

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#848]
**List the CGR information**
- CGR version: v1.0.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
An error shows up that a parent in a hierarchy doesn't exist in a time range even though it does.

**To Reproduce**
1. As a Registry Contributor, open a Geo-Object from the Change Request module (in this case Apad Health Post).
2. Set the existence to No from today's date (in this case October 7).
3. Adjust the end dates for the latest instances of each attribute.
4. In the hierarchy tab, an error persists saying that one of the parents does not exist in the given time range (in this case Guilopan Health Centre), even though it does exist then.
5. I am unable to submit the change request because of the error.

**Expected behavior (clear and concise)**
The end date of the parent can be updated without an error about it not existing in the given time range.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/e5ebcb10-4439-4f4b-8697-7b425e0daf6b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 106.0.5249.103

**Additional context (if any)**
None

**Comment by rfromthecastle** [comment]
Because this affects some of the core capabilities of the GPR, to manage multiple hierarchies and changes over time, I'd say this is a high priority bug to address. However, because I only saw this bug in this specific instance (see steps to reproduce), it may be an issue with the test data on Staging (which has been through lots of testing, changes, etc.) rather than the platform itself

**Comment by SteeveEbener** [comment]
@rfromthecastle : I just tested this in the demo instance and it is working correctly (Version: 0.19.6)

**Comment by rfromthecastle** [comment]
Hi @SteeveEbener, the latest v1.0.0 is the first time I saw this issue, so not sure if it's a bug from the latest release? This may also just be an issue with the data on Staging.

**Comment by rrowlands** [comment]
Hi @rfromthecastle, I'm sorry but I'm having trouble reproducing this issue on the staging server. I suspect that it might be related to time zones, as in it only happens at a specific time of day in a specific time zone. If you are able to reproduce it again can you please:

1. Go to this website
https://webbrowsertools.com/timezone/

And send me the information listed in the "Timezone info" section

2. Open the Explorer and search for and select the Geo-Object. Then, [open the developer console](https://developer.chrome.com/docs/devtools/open/) and then open the "Network" tab. Then, proceed to reproduce the issue described in this ticket. Immediately after you produce the "Parent does not exist at this time range" error, click the "Export HAR" button as shown in this screenshot

![image](https://user-images.githubusercontent.com/1326328/196556849-16989fc4-820b-4bca-9477-401a8f3c3383.png)

**Comment by rfromthecastle** [comment]
Hi @rrowlands, so sorry I didn't catch your message earlier! I've been testing the Change Request module in the latest v1 release on Staging and came across this same issue again. Please find the HAR file here,[https://app.zenhub.com/files/142912671/bee1addb-ca34-4b1d-8d19-916b495f6011/download](https://app.zenhub.com/files/142912671/bee1addb-ca34-4b1d-8d19-916b495f6011/download) , as well as my timezone: ![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/b605d440-c39d-4a50-a4f3-05f949e2368a)

**Comment by rrowlands** [comment]
Hi Rica,

Thank you so much for posting your HAR file. This file tells me that the non-existing parent was HF0002 (Guilopan Referral Hospital) and it did not exist on the time range [2000-01-01, 2022-11-22]. Looking at the test data on staging this is expected, since HF0002 exists on range [2000-01-01, 2022-10-06].

In my testing this appears to be confirmed. If you change the end date for Apad Health Post's parents to 2022-10-06 the "parent does not exist" error goes away.

**Comment by rfromthecastle** [comment]
Thanks @rrowlands! Your explanation makes sense. I tried going through the steps described above again and don't have the issue this time. I think this can be marked as closed.
