### ISSUE TITLE
Parent hierarchical information not automatically inheriting for newly added Geo-Objects

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#849]
**List the CGR information**
- CGR version: v1.0.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
For a newly added Geo-Object, when selecting a parent Geo-Object in a hierarchy, its parent in turn does not automatically get populated.

**To Reproduce**
1. As a Registry Maintainer, create a new Geo-Object for a given type (in this case, a new Referral Hospital named Rica's Referral Hospital added to the Health Facility (Laos) 2 group)
2. Select a parent district
3. The parent province of the parent district does not show up

**Expected behavior (clear and concise)**
Any inherited hierarchical information is automatically populated

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/315d392f-2870-462e-ab36-d4359a57d4a7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 106.0.5249.103

**Additional context (if any)**
None

**Comment by rfromthecastle** [comment]
Because this affects some of the core capabilities of the GPR, to manage multiple hierarchies and changes over time, I'd say this is a high priority bug to address. However, because I only saw this bug in this specific instance (see steps to reproduce), it may be an issue with the test data on Staging (which has been through lots of testing, changes, etc.) rather than the platform itself

**Comment by rrowlands** [comment]
Hi @rfromthecastle . For this specific example, the "Province" parent field is empty because that District does not have a parent in this hierarchy (Health Facility Management Hierarchy (Laos) 2).

Here is what the parents look like for the `Dakchung : LA1503` Geo-Object:

![image](https://user-images.githubusercontent.com/1326328/196520558-238f3198-69f8-44d5-8754-2920e8a534c4.png)

You can see that no versions were created for the hierarchy in question.

**Comment by rfromthecastle** [comment]
Hi @rrowlands, thanks for looking into this! How are we meant to create versions for a hierarchy? Is that by configuring a list that contains information from this hierarchy?

**Comment by rrowlands** [comment]
You can create them using the explorer. For this example, you would first want to search for "Dakchung" and select LA1503. Once Dakchung is selected, go to the hierarchies tab and create a version for the "Health Facility Management Hierarchy (Laos) 2" hierarchy. Once Dakchung has a parent in this hierarchy, then the parent information for children of Dakchung will be automatically populated.
