### ISSUE TITLE
When viewing a Geo-Object from a published list in the Explorer, only that Geo-Object is shown in the attribute table, while all Geo-Objects in the list are shown on the map

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#862]
**List the CGR information**
- CGR version: 1.0.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
When viewing a Geo-Object from a published list in the Explorer, only that Geo-Object is shown in the attribute table, while all Geo-Objects in the list are shown on the map

**To Reproduce**
1. As a Registry Maintainer, open a published list
2. Open a Geo-Object in the Explorer
3. The given Geo-Object only is listed in the attribute table, but the map shows all Geo-Objects in the list

**Expected behavior (clear and concise)**
The map only shows the selected Geo-Object or zooms into it.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e5cdb3c03758d213c13e15f/92bdbd8f-f8f3-4c94-b5f8-311b6fb17e4e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 107.0.5304.107

**Additional context (if any)**
None

**Comment by rfromthecastle** [comment]
Low priority bug, as only causes a minor inconvenience to the user

**Comment by SteeveEbener** [comment]
@rfromthecastle : I don't think this is a bug but actually something that has been decided upon in order for the user to be able to "locate" the geo-object in question among the other ones of the same type and I think this should remain as it is now.

The geo-object in question should nevertheless be highlighted to be able to identify it on the map.

**Comment by rrowlands** [comment]
Fixed as a8c6c0441d9f47107b6e0367c9ab01d8c2281d8f

**Comment by rfromthecastle** [comment]
Fix tested on Staging and working well :) Thanks both!

**Comment by SteeveEbener** [comment]
Thanks. Could this be pushed to the sandbox? Thanks

**Comment by rrowlands** [comment]
@SteeveEbener This fix was included in the 1.0.0 release, which was pushed to the demo server.

**Comment by SteeveEbener** [comment]
The UI is now the same in both the sandbox and staging.

This being said, what happens is not what you are describing in your Nov 24th comment as only the geo-object you selected is appearing on the map, not the other ones. Here is for example what you get when logged in as the MOH RA and open the Hillary Avila community health worker:
![image](https://user-images.githubusercontent.com/12602163/208278861-f61b7b01-bda1-49d2-acf4-6776af263169.png)

The other community health workers are not appearing on the map (and this on both staging and demo)

**Comment by rrowlands** [comment]
Hi Steeve, I agree this is an issue for working lists.

**Comment by rrowlands** [comment]
Addressed as 0b5d79fdb508c2b40204ab9e47805cf174cac3ba.

**Comment by SteeveEbener** [comment]
Can we please close tickets when they have been checked by the person who submitted them? thanks

**Comment by rfromthecastle** [comment]
All the requested fixes are working as expected on Staging
