### ISSUE TITLE
Data element order in exported spreadsheet not matching order in the original list and in the data dictionary

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#868]
## User stories
1. When I export a list in a spreadsheet I anticipate the order of the data element to be the same as in the list I looked at in the GPR
2. When I look at the data dictionary in the exported spreadsheet I expect the order of the data element to be the same as in the list

## Problems this relates to
Facilitate user experience

## Proposed solution
1. Get the data elements in the exported list, as well as associated data dictionary, to be ordered in the same way as the list in the GPR
 
## Considered alternatives
None

**Comment by rfromthecastle** [comment]
Ordering of attributes and data dictionary in exported spreadsheet now matching what we see in GeoPrism Registry

**Comment by SteeveEbener** [comment]
The order is indeed the same between the list in the GPR, the list in and the data dictionary in the exported MSExcel file.

 This being said, the label in the MSExcel file is incomplete making it difficult to make the link with the new list header structure in the GPR.

Example in the GPR:
![image](https://user-images.githubusercontent.com/12602163/221350348-0675044d-fde9-4514-ac43-c822e2084060.png)

Resulting MSExcel file

[SHR-2012-09-15.xlsx](https://github.com/terraframe/geoprism-registry/files/10830751/SHR-2012-09-15.xlsx)

=> It is difficult to know that:
-  "Code" in the MSExcel file corresponds to "Shire (MOHA) Code)
-  " Shire (MOHA) (English)" in the MSExcel file corresponds to the " Shire (MOHA) display label (English)"

=> Is there a way this could be standardized to improve consistency?

**Comment by jsmethie** [comment]
The Excel column labels change is captured #869. They will be addressed in that ticket. Please close this ticket if the order matches.

**Comment by SteeveEbener** [comment]
Ok. Closing this ticket
