### ISSUE TITLE
Mismatch between list column header and data dictionary in exported spreadsheet and shape file

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#869]
## User stories
Taking the example of the CHW master list as, and logged in as the MOH RA, an example, here is what you get in the GPR when looking at the list::
![image](https://user-images.githubusercontent.com/12602163/209494716-bfeb33d4-6735-4a22-9ceb-4726e56e2a4c.png)

When you export the list in a spreadsheet you obtain this for the list worksheet:
![image](https://user-images.githubusercontent.com/12602163/209494729-6bf06bef-32dc-46e3-afc9-64ad556153bf.png)

…and this for the data dictionary worksheet:
![image](https://user-images.githubusercontent.com/12602163/209494750-4e3189ef-924c-4198-a051-4e169eb9a893.png)

When you export the spatial data in a shape file you get this for its attribute table:
![image](https://user-images.githubusercontent.com/12602163/209494770-dc3be424-e07a-4493-854d-a9317a3bcf5f.png)

 …and the same data dictionary as here above in the associated MS Excel file.

## Problems this relates to

1. The attributes are not ordered the same way between the GPR list and the exported spreadsheet/shape file attribute table 
2. The headers in the shapefile attribute table and the data dictionaries are not the same as those in the list on the GPR

Because of the above, it is difficult to match the content between these different files and the original list in the GPR, especially since the use of the new design with multiple line headers. 

## Proposed solution
1.	Order the attributes in the same way (left to right and top to bottom) across the lists, attribute table and data dictionaries
2.	Add the following headers to the data dictionary when exporting the list into a spreadsheet (from left to right): “Attribute” and “Description” 
3.	Adjust the labels captured in the data dictionaries and the exported list to present a structure closer to the headers used in the GPR list (new design). Examples: 
a.	“Community health worker gender (code)” instead of “Community health worker gender”  
b.	“CHW - Health post hierarchy (MOH) - Health Post (MOH) (code)” instead of “Health Post (MOH) (CHW - Health post hierarchy (MOH))” 
4.	Include the headers from the shape file attribute table in the data dictionary of the exported MS Excel file. Example here:
![image](https://user-images.githubusercontent.com/12602163/209494833-326a1d30-c86a-4b44-9dcb-2b7ba7c7ff17.png)

## Considered alternatives
Open for discussion

## Additional context
Linked to tickets #628 and #819

**Comment by justinlewis** [comment]
@steeveebener - We won't be able to do #4 because there is a one to many relationship between an attribute on a Geo-Object Type and a list. As an example, localized text attributes have one column per installed locale. Similarly Term and Classification attributes have two columns each (one for the code and the other for the value).

**Comment by SteeveEbener** [comment]
@justinlewis : each of the columns you are referring to should have its own label => one-to-one.

For the localization, the differentiation could for example be made by adding the language iso code (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) in between brackets

For the term and classification (which remains to be merged as per ticket #805) the label for the code and the item should definitely be different

**Comment by SteeveEbener** [comment]
The following item from the initial ticket has been moved to ticket #891: Give the possibility to the RA to define the header his organization wants to see being used in the exported shape file (should be done when defining the attributes at the geo-object type level)

**Comment by justinlewis** [comment]
@SteeveEbener Can this ticket be closed then?

**Comment by SteeveEbener** [comment]
@justinlewis . I did not realize these have been implemented. I just tested them under stagging (Ve 1.2.0).

All work as expected. I am closing this ticket
