### ISSUE TITLE
GeoObject Types setting: Management of the "mother" concept

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#87]
When creating a new GeoObject type, the RA or RM should have the possibility to indicate that the management of this particular type will require to capture the "mother GeoObject" when creating a new GeoObject and this in order to be able to build the historic changes.

This does not only apply to contiguous polygons (administrative or health divisions) but could also apply to point type object such as villages.

Such information will not only be needed to ensure the capture of the "Mother GeoObject" information when applicable but also for the proper management of the COT component of the associated geospatial data as follow:

- In the case of GeoObject types considering mothers, the upload, management and sharing of geospatial data will be bound by specific validity period 

- In the case of GeoObject type not considering mothers, the upload, management and sharing of geosaptial data will not be bound by any specific validity period

**Comment by justinlewis** [comment]
What happens in the situation where there is no valid parent GeoObject? One option in this situation is to indicate to the user that they must create that parent before adding the GeoObject they are attempting but this could force an intensive editing process.

**Comment by SteeveEbener** [comment]
This is one of these cases where the CGR should allow to manage "unknowns".

Such "unknowns" could then always been managed as part of the functionalities of the curation module

**Comment by SteeveEbener** [comment]
This issue is linked to the fact that for the moment there is no field to capture the "mother" of the new GeoObject when this is applicable (Administrative divisions for example). It is therefore not possible to recreate the historic changes or to tell the RA/RM of other organization that they need to re-adjust the attribution of some of their GeoObject based on a given hierarchy

**Comment by CarlyNel** [comment]
Justin: Next step is for TerraFrame to set up a requirements doc to outline how they think this might work.

**Comment by SteeveEbener** [comment]
This ticket has been addressed through the release of the historical events module => I am closing this ticket
