### ISSUE TITLE
Option to expose external IDs associated with Geo-Objects

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#872]
## User stories
Right now there is no way for users to see what external IDs from the different registered external systems are linked to Geo-Objects after they have been imported. This would be useful for any troubleshooting should any synchronization go wrong. It would also be helpful to see the external ID generated by the external system for any new Geo-Objects that have been created in GeoPrism Registry and then synchronized with the external system.

## Problems this relates to
Data quality, external system synchronization

## Proposed solution
Provide an option to display external IDs in lists.

## Considered alternatives
None

## Additional context
N/A

**Comment by rfromthecastle** [comment]
Raised during a GeoPrism Registry-DHIS2 synchronization testing session with the Laos Health Information Division IT team on 11/01/2023.

**Comment by SteeveEbener** [comment]
What about adding new data elements (attributes) to capture these IDs?

**Comment by rfromthecastle** [comment]
Hi @SteeveEbener, this is a workaround that I've done, however, when a new Geo-Object gets synchronized with DHIS2 and a new organization unit gets generated, we'd then have to add in the new DHIS2 organization unit UID manually.

**Comment by rfromthecastle** [comment]
FYI @viengthong2015

**Comment by SteeveEbener** [comment]
Thanks @rfromthecastle . I would then argue that this is an issue on the DHIS2 side and not on the GPR one

**Comment by rfromthecastle** [comment]
Hi @SteeveEbener, once new Geo-Objects get synchronized with DHIS2 and a new organization unit is generated, its ID gets fed back to GeoPrism Registry and linked with the Geo-Objects, because you make subsequent changes to these new Geo-Objects, GeoPrism Registry knows exactly which organization units to push these to. I think this is more a matter of exposing that information in a list.

**Comment by SteeveEbener** [comment]
@rfromthecastle: Thanks for the complement of information. If I understand correctly, what you are describing is an architecture that allows multiple platforms to issue unique IDs. If this is the case, then this is not the model supported by the GPR.

**Comment by rfromthecastle** [comment]
@SteeveEbener your point makes sense. I think still from a Registry Administrator's standpoint being able to see what external IDs are linked to Geo-Objects would be helpful to check if a synchronization profile is correctly configured and whether Geo-Objects match with the right organization units or other objects in other systems.

**Comment by SteeveEbener** [comment]
@rfromthecastle : Definitively and using the GOR as a "key correspondence" table (one place storing the different IDs attributed to the same geo-object) is good use case, especially as this might help the convergence of these IDs towards a single one used across all systems (ideal scenario)

**Comment by rfromthecastle** [comment]
@SteeveEbener A "key correspondence" table sounds useful!

**Comment by rfromthecastle** [comment]
The feature enhancement developed for this ticket is great! It's a lot easier now also to edit external IDs for specific Geo-Objects within the Explorer, rather than only being able to do it through the Import module.
