### ISSUE TITLE
Assign Geo-Object Type to multiple DHIS2 organization unit groups in synchronization configuration

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#873]
## User stories
_Raised by @viengthong2015_
At the moment, Geo-Object Types on a given level can only be assigned to one DHIS2 organization unit group at a time in the synchronization configuration. Often though, organization units may belong to multiple groups.

## Problems this relates to
External system synchronization

## Proposed solution
Allow users to select multiple DHIS2 organization unit groups to synchronize a Geo-Object Type on a single level with.

## Considered alternatives
Create separate synchronization profiles to add Geo-Objects to different organization unit groups, however this may get unwieldy.

## Additional context
None

**Comment by SteeveEbener** [comment]
Is this not once again an issue on the DHIS2 side?

**Comment by rfromthecastle** [comment]
@SteeveEbener no, because the configuration happens on the GeoPrism Registry side. Organization units can belong to multiple groups so it would be helpful if GeoPrism Registry can handle this in the synchronization profile too

**Comment by rfromthecastle** [comment]
Working on Staging
