### ISSUE TITLE
Lao Translation showing in English version

### ISSUE THREAD

**Issue by Mc7434** [terraframe/geoprism-registry#877]
**List** the CGR information**
- CGR version: 1.0.0
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
Lao Translation showing in the English version 

**To Reproduce**
1. switch language to english: 
2. Click on: List module 
3. the Geo-Object type name showing in lao

**Expected behavior (clear and concise)**
Geo-object type name showing in English

**Screenshots**
<img width="1013" alt="Screenshot 2023-01-19 at 10 56 34" src="https://user-images.githubusercontent.com/113510460/213351702-884147ac-22c1-4087-82c3-b06fc1004d88.png">

**Desktop (please complete the following information):**
 - OS: Mac Os 13.1 (22C65)
 - Browser: Chrome
 - Version: Version 109.0.5414.87 (Official Build) (arm64)

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
I am also experiencing this issue on my laptop (Windows 10)

**Comment by Mc7434** [comment]
<img width="1373" alt="Screenshot 2023-01-31 at 10 05 13" src="https://user-images.githubusercontent.com/113510460/215652592-32fa1372-c229-4bce-89fb-3cde56a6453c.png">

could not reach the website, Mac Os, Chrome.

**Comment by jsmethie** [comment]
We are looking into the issue, but this fix has not been released yet. It is slated for the Sprint: Jan 23 - Feb 17, 2023 time line.

**Comment by Mc7434** [comment]
List the CGR information**

CGR version: 1.0.1 (2023-02-16T20:30:24Z)
CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/#/registry/master-lists?typeCode=COM_moz
Describe the bug (clear and concise)
Lao Translation showing in the English version

To Reproduce

switch language to english:
Click on: List module
the Geo-Object type name showing in lao
Expected behavior (clear and concise)
Geo-object type name showing in English

<img width="1800" alt="Screenshot 2023-02-20 at 15 47 47" src="https://user-images.githubusercontent.com/113510460/220057386-531e538e-ebf9-4950-b426-cdb3fa0cc6de.png">

**Comment by justinlewis** [comment]
Thanks for all this input. We found the issue and applied [a fix](https://github.com/terraframe/geoprism-registry/commit/28e982abfa75ff0750819cc76fa324571c1db966) that is live on Staging now.

**Comment by rfromthecastle** [comment]
All showing up correctly for me with the new fix on Staging :)
