### ISSUE TITLE
Generate a list of Geo-Object changes between list versions

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#881]
## User stories
As any user, I would like to be able to automatically generate a list of changes to Geo-Objects between list versions (either between published versions or between lists at given frequencies), so these can easily be communicated to end users.

## Problems this relates to
Data management

## Proposed solution
Develop functionality to compare two versions of lists for the same Geo-Object Type, and output a summary of changes (i.e., Geo-Objects Added: ..., list of Geo-Object IDs and a summary of the changes).

## Considered alternatives
Manually noting down changes in a spreadsheet.

## Additional context
None

**Comment by rfromthecastle** [comment]
During the first quarterly Digital Health Strategy TWG meeting for Laos, one point that was raised is that communication to relevant departments on the changes to the health facility master list is important. Having an easy way to check what changes have been made between versions will be of much benefit to the Laos MoH.

**Comment by rrowlands** [comment]
I assume this feature is expected to work outside of the Change Request mechanism, i.e. if an RA directly modifies a Geo-Object the change should still appear?

**Comment by rfromthecastle** [comment]
Hi @rrowlands, your assumption is correct. The challenge right now is that direct edits by RMs are hard to spot.

**Comment by rfromthecastle** [comment]
Looks like this is a duplicate of a very old ticket, #193

**Comment by rfromthecastle** [comment]
Closed as duplicate of #193
