### ISSUE TITLE
Unspecified error when editing a Geo-Object from the list view

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#883]
**List the CGR information**
- CGR version: 1.1.0 (release candidate)
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
An unspecified error occurs in step 5 from test case RM-10 from https://docs.google.com/spreadsheets/d/1KVVC9jG_CUe9K2cpy-FmTq5quhyAfTJ4as1OTK9TUDE/edit?usp=sharing

**To Reproduce**
1. As a Registry Maintainer, go to the Explorer module
2. Select 2020-01-01
3. Search for Valhalla Capital Health Office
4. Edit: Name to Helheim Capital Health Office (starting from Jan 1 2020), update head of health facility to Drengr
5. Submit changes
6. Go to Lists and Spatial Data module and view the working version for the relevant validity period

**Expected behavior (clear and concise)**
The changes save as expected and are reflected in the refreshed list.

**Screenshots**
![image](https://user-images.githubusercontent.com/18660080/220556926-dda58145-f1b2-4d59-86f7-f15dbacda15b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 110.0.5481.104

**Additional context (if any)**
None

**Comment by Mc7434** [comment]
I have the same issue with a different Geo-Object.
<img width="501" alt="Screenshot 2023-02-22 at 16 15 31" src="https://user-images.githubusercontent.com/113510460/220575359-fceaa0ab-222f-4f64-962a-0475f638f0dc.png">
<img width="499" alt="Screenshot 2023-02-22 at 16 15 48" src="https://user-images.githubusercontent.com/113510460/220575378-736f7215-a9b8-4f89-b512-241fb7549e8d.png">
<img width="1325" alt="Screenshot 2023-02-22 at 16 16 07" src="https://user-images.githubusercontent.com/113510460/220575508-b2bbbc92-a65b-4c7e-9cb1-154ebb31d8cb.png">

**Comment by rrowlands** [comment]
Thanks for the heads up! I have noticed that this issue only happens when you are also adding a new time range to a Geo-Object label.

**Comment by rrowlands** [comment]
Addressed as be505312e2333d3cfbba18c7d5ba5af9c168788d

**Comment by rfromthecastle** [comment]
Fix working on Staging
