### ISSUE TITLE
Unspecified error when making a Geo-Object existent again

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#884]
**List the CGR information**
- CGR version: v1.1.0 (release candidate)
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
An unspecified error occurs in step 4 from test case RM-19 in https://docs.google.com/spreadsheets/d/1KVVC9jG_CUe9K2cpy-FmTq5quhyAfTJ4as1OTK9TUDE/edit?usp=sharing

**To Reproduce**
1. As a Registry Maintainer, go to the Explorer module.
2. Search for the Geo-Object from test case 18 for 15 June 2020
3. Edit the Geo-Object so it exists from 1 October 2021 onwards
4. Submit the edits
5. Return to the Health Facility Master List version for today's date and generate a new version

**Expected behavior (clear and concise)**
The edits for the Geo-Object can be successfully submitted and the changes appear in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/18660080/220564135-f588ff5f-6bb0-4dba-94e8-ecfd740f671c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 110.0.5481.104

**Additional context (if any)**

**Comment by rfromthecastle** [comment]
May potentially be related to [https://github.com/terraframe/geoprism-registry/issues/883](url)

**Comment by rrowlands** [comment]
Addressed as 5a8c34648a74a41533550db27a20ee76dc4ba89d

**Comment by rfromthecastle** [comment]
Fix working on Staging
