### ISSUE TITLE
Point Geo-Object geometries synchronizing as polygons in DHIS2 organization units

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#887]
**List the CGR information**
- CGR version: 1.1.0
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
The geometries of point-type Geo-Objects are synchronizing as polygons in the corresponding DHIS2 organization units, rather than as latitude/longitude pairs.

**To Reproduce**
1. As a Registry Administrator, synchronize a configuration with point type Geo-Objects
2. Visualize the synchronized organization units in the DHIS2 Maps app
3. The organization units are not displaying on the map
4. Go to the Maintenance app, search for a given synchronized Geo-Object and inspect its details
5. The geometry is indicated to be a polygon, replacing the latitude/longitude fields

**Expected behavior (clear and concise)**
Latitude and longitude values are synchronized with the relevant organization units, with the organization units displayable in the Maps app

**Screenshots**
![image](https://user-images.githubusercontent.com/18660080/223369081-2f46ac1e-cb7c-420e-ba2e-80c2518c4b24.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 110.0.5481.178

**Additional context (if any)**
None

**Comment by rfromthecastle** [comment]
@truongnt did some investigating and found that point-type Geo-Objects are being synchronized as MultiPoints in DHIS2 - this should be of the Point type instead

**Comment by justinlewis** [comment]
Relates to #353

**Comment by rrowlands** [comment]
Committed as 784be18fdc834b32ffac7cd51707ffa50cf44298. Will be included into v1.1.1 release. Was decided as a bug on our end since we were exporting point geometries as multi-point which is a geometry type that DHIS2 does not support. Additionally, since our system supports multipoint and DHIS2 does not, if you attempt to export a Geo-Object which has a true multipoint geometry (i.e. a village with more than one point), our system will record an error during the export of that Geo-Object.

**Comment by rfromthecastle** [comment]
Confirming that this fix is working correctly on the Laos instance, and that because of this we've now done a 100% synchronization of administrative divisions and health facilities with the Laos development HMIS (DHIS2). Thanks so much for the rapid turnaround! This ticket can be marked as closed.
