### ISSUE TITLE
Mandatory fields not well emphasized

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#89]
RM/RA>GeoObject types and Hierarchies Manager>Edit a GeoObject Type>Manage attributes>Add/Edit an attribute

The fact that a field is mandatory is not well emphasized visually (red border for the field?) + not enforced when clicking the submit button (you can submit with an empty field)

Possible solution: increase the thickness of the frame when in red

**Comment by dtreatman** [comment]
Agree that mandatory fields should be clearly indicated. Please apply standard UI/UX design principles.

**Comment by justinlewis** [comment]
@SteeveEbener Can you tell me:

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by SteeveEbener** [comment]
OS; Windows 10
Browser with version: Google Chrome (Version 79.0.3945.130)

**Comment by SteeveEbener** [comment]
This issue has been addressed and can therefore be closed
