### ISSUE TITLE
List of close matches showing while typing into Explorer search box

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#895]
**List the CGR information**
- CGR version: v1.2.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
When starting to type something in the Explorer search box, a list of options appears from which you can select a Geo-Object with a name that closely matches what is typed. However, once an option is selected the user still has to press the search button and choose a Geo-Object from the returned search results. This seems like a duplicate workflow. The auto-generated list of search results while typing into the search box should therefore best be removed.

**To Reproduce**
1. As any user, go to the Explorer module.
2. Start typing the name of a Geo-Object you want to search for in the search bar.
3. From the list of close matches that appears, select a Geo-Object.
4. Press the search button.
5. Select the same Geo-Object from the search results.

**Expected behavior (clear and concise)**
Either no list of close matches shows while typing into the search box, or when selecting an option from these close matches, the Explorer already opens the chosen Geo-Object.

**Screenshots**
![image](https://user-images.githubusercontent.com/18660080/231139756-5f7de1c9-9049-46b3-b643-7a7403d059e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 111.0.5563.148

**Additional context (if any)**
None

**Comment by rrowlands** [comment]
I have removed the autocomplete behaviour when typing. Committed as a0004ed3dc94f4d23dde1e8289c77d01ce078e6f.

**Comment by rfromthecastle** [comment]
Working on Staging
