### ISSUE TITLE
Duplicate inherited parent Geo-Object Types displayed in DHIS2 synchronization configuration

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#896]
**List the CGR information**
- CGR version: v1.1.0
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/cgr/manage#/login

**Describe the bug (clear and concise)**
When I set up a DHIS2 synchronization configuration based on a hierarchy with inherited parent Geo-Objects, the Geo-Object Type that inherits parent Geo-Object Types appears twice in the Geo-Object Type selection dropdown when mapping these onto organization unit levels (e.g., provincial hospital located within a province, which inherits the country, with the province appearing twice), and other Geo-Object Types from the inherited hierarchy that are below the level from which the inheritance was made also show up (e.g., the district also showing up in the dropdown).

**To Reproduce**
1. As a Registry Administrator, create a hierarchy with inherited parent Geo-Object Types.
2. Via the Settings module, set up a DHIS2 synchronization configuration based on this hierarchy.
3. When mapping the Geo-Object Types onto levels, the Geo-Object Type that inherits parent Geo-Object Types appears twice in the dropdown.

**Expected behavior (clear and concise)**
Each Geo-Object Type in the hierarchy appears only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/18660080/231152222-b26f443b-025c-464c-92af-1ecbf91e5125.png)
![image](https://user-images.githubusercontent.com/18660080/231152377-3b3d9511-8827-4fa7-b9ca-97345abedc80.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 111.0.5563.148

**Additional context (if any)**
None

**Comment by rrowlands** [comment]
Fix committed as c45c72aaa0ffca1bbba2577779fc61ba3eff40bf.
