### ISSUE TITLE
Showing English language even switch to Lao language

### ISSUE THREAD

**Issue by Mc7434** [terraframe/geoprism-registry#900]
**List the CGR information**
- CGR version: 1.2.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/#/menu

**Describe the bug (clear and concise)**
Showing English language even switch to Lao language

**To Reproduce**
1. As a .....[role]: Go to 
2. Click on 
3. See error

**Expected behavior (clear and concise)**

**Screenshots**
<img width="1800" alt="Screenshot 2023-05-02 at 10 52 49" src="https://user-images.githubusercontent.com/113510460/235575854-5472c258-9a0b-4358-9945-88b97a8acb05.png">

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser: Chrome
 - Version: Version 112.0.5615.137 (Official Build) (arm64)

**Additional context (if any)**

**Comment by Mc7434** [comment]
Also happened with: https://laos-georegistry.geoprism.net/#/menu
version: 1.2.0
<img width="1797" alt="Screenshot 2023-05-02 at 10 59 57" src="https://user-images.githubusercontent.com/113510460/235576549-041279c8-b501-42e9-85ac-661bf340e3c2.png">

**Comment by rfromthecastle** [comment]
Working on Staging

**Comment by Mc7434** [comment]
Closed
