### ISSUE TITLE
Map not zooming to the right place when the not geo-object has no geometry

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#906]
**List the CGR information**
- CGR version: 1.2.0
- CGR instance (e.g. a URL): Demo

**Describe the bug (clear and concise)**
When you click on the view icon of a geo-object that does not have a geometry the map that appears in the editing view does not zoom to the area containing the location/extent of the other geo-objects of the same type.  

**To Reproduce**
As a RA/RM:
1. Go to the lists and spatial data module
2. Click on a geo-object type over which the RA/RM has the curation mandate (point format geo-object type is easier)
3. Open one of the working lists for the geo-object
4. Add a new geo-object without geometry
5. Refresh the list
6. Click on the view icon for the added geo-object
7. See the error: the map in the editing view does not zoom to the area containing the location/extent of the other geo-objects of the same type 

**Expected behavior (clear and concise)**
- The map in the editing zooms to the area containing the location/extent of the other geo-objects of the same type 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 111
 - Browser: Chrome
 - Version: Latest version

**Additional context (if any)**

**Comment by rrowlands** [comment]
Is this map zoom bounds expected to be of the same date from the list from which the Geo-Object was originally created? Should it update when a new version is published? Or are we to use the latest data available for all objects of the same type?

**Comment by SteeveEbener** [comment]
@rrowlands: Good questions:
1 Same date from the list from which the Geo-Object was originally created
2 What should update, the zoom? You are referring to the version of the list? 
3. Does not apply => the answer is under point 1

Thanks

**Comment by SteeveEbener** [comment]
Partly a duplicate of ticket #673 but contains additional information. Closing it anyway and will make mention about this on under #673
