### ISSUE TITLE
Validity 'Yes' and 'No' labels for Geo-Objects swapped

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#908]
**List the CGR information**
- CGR version: 1.3.0
- CGR instance (e.g. a URL): https://staging-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
Geo-Objects that are valid and display in lists have their validity attribute marked as 'No', while invalid Geo-Objects that do not display in lists have their validity attribute marked as 'Yes'.

**To Reproduce**
1. As a Registry Maintainer, go to a list.
2. Open a (valid) Geo-Object in the Explorer. 
3. The 'Validity' attribute is set to 'No'.
4. Return to the list and check the 'Show invalid Geo-Objects' box.
5. Open an invalid Geo-Object in the Explorer.
6. The 'Validity' attribute is set to 'Yes'.

**Expected behavior (clear and concise)**
Geo-Objects that are valid and display in lists have their validity attribute marked as 'Yes', while invalid Geo-Objects that do not display in lists have their validity attribute marked as 'No'.

**Screenshots**
![image](https://github.com/terraframe/geoprism-registry/assets/18660080/9200c12e-ba73-451d-8d10-00377259a6ab)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 114.0.5735.110

**Additional context (if any)**
None

**Comment by rrowlands** [comment]
This appears to be a regression. Those labels are supported to read as valid / invalid.

**Comment by rfromthecastle** [comment]
Fix working on Staging

**Comment by SteeveEbener** [comment]
Any chance we could address ticket #682  at the same time? Thanks
