### ISSUE TITLE
All roles>All modules: Need to refresh after each operation

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#91]
A user should not have to use the refresh function of the browser to see a change he has done been applied. Such change should automatically appear once the button applying the change has been clicked

**Comment by justinlewis** [comment]
Can you describe when and how this happens?

**Comment by SteeveEbener** [comment]
I realize that some modifications have been made in the CGR since I included this comment in the feedback google spreadsheet and it therefore does not apply to all the modules anymore but only some of them.

=> let's close this issue and I will open module specific ones to simplify the process.

**Comment by justinlewis** [comment]
Sounds good.
