### ISSUE TITLE
No data entry fields for inherited parent Geo-Objects in Explorer

### ISSUE THREAD

**Issue by rfromthecastle** [terraframe/geoprism-registry#911]
**List the CGR information**
- CGR version: 1.2.2
- CGR instance (e.g. a URL): https://laos-georegistry.geoprism.net/

**Describe the bug (clear and concise)**
In the Explorer, no fields are showing for inherited parent Geo-Objects in the Hierarchies tab.

**To Reproduce**
1. As a Registry Administrator, search for and open a Geo-Object with hierarchical information containing inherited parent Geo-Objects.
2. No fields are showing for inherited parent Geo-Objects in the Hierarchies tab.

**Expected behavior (clear and concise)**
Fields show for inherited parent Geo-Objects and get autofilled based on the first parent Geo-Object information entered.

**Screenshots**
![image](https://github.com/terraframe/geoprism-registry/assets/18660080/268cb957-ef2f-4fb9-8c0f-40319d085546)
![image](https://github.com/terraframe/geoprism-registry/assets/18660080/d6156be6-3114-4d63-802d-c8c9a9f9e667)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 114.0.5735.199

**Additional context (if any)**
None

**Comment by rrowlands** [comment]
We can add fields for the inherited types, however they must be read-only. Our system does not support directly specifying parents of the inherited types. So, for example, if the goal here is to directly assign a central hospital to a country (whilst skipping province), that is unsupported by our system.

**Comment by rfromthecastle** [comment]
Hi @rrowlands, I remember there being parent fields available before - was this only for non-inherited types? However, agreed, for interited types the fields should be read-only.

**Comment by rrowlands** [comment]
> I remember there being parent fields available before - was this only for non-inherited types?

@rfromthecastle I cannot exactly recall. It's possible we may have had a scenario going on where the inherited types were displaying but were also editable, at which point potentially we may have removed them.

**Comment by rfromthecastle** [comment]
Working on Staging
