### ISSUE TITLE
RA/RM>Burger menu: Need to set geographic coordinate system and eventually projection system

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#92]
We need to add one more setting to define the geographic coordinates system, and potentially projection system, that will be used as the reference for all the lat/long and other geospatial data imported and managed in the CGR. Other easier option: we fix it to WGS84 but some countries might not like it...

This setting should also be used to make sure that any geospatial data being imported in the graph matches both the geographic coordinate and projected system. If not, they should not be imported

**Comment by justinlewis** [comment]
The system is currently fixed to EPSG: 3857.  This could be changed but it would be a significant effort that must be scoped.

**Comment by SteeveEbener** [comment]
Is this the projection system used to display the maps in the navigator or also the projection system in which the geospatial data are stored in the back end?

If the later, what happens when you:

1.  upload data that are unprojected or in a different projection system?
2. Export geospatial data from the CGR? is the shape file being exported projected according to EPSG: 3857 or unprojected?

**Comment by justinlewis** [comment]
EPSG: 3857 is used for both display (e.g. maps) as well as storage in the database. 

For #1 - We have checks to detect the projection of data on import. This happens at the beginning of the process. There is a requirement to project your data before an upload will be excepted.

For #2 - It is projected to EPSG: 3857

**Comment by SteeveEbener** [comment]
Are you sure?

The geospatial data we used for Cambodia, and which are in the CGR, are unprojected (EPSG: 4326) and when I exported them from the CGR and open them in ArcGIS or QGIS they remain as such (EPSG 4326).

=> This would be the geographic coordinate system I would recommend we use because EPSG: 3857 is not a recognised geodetic system (https://epsg.io/3857)

**Comment by justinlewis** [comment]
@steeveebner You are absolutely correct. I thought that sounded odd when I wrote it. I just double checked in the code.

**Comment by SteeveEbener** [comment]
Does that mean that EPSG 4326 is the one being implemented in the CGR? 

That's great if this is the case and something we need to document clearly + cross fingers this will not be an issue in countries that are very sensitive regarding the use of their national projection system...

**Comment by justinlewis** [comment]
Yes EPSG: 4326 is the one implemented in the CGR database storage. Vector tiles are converted to EPSG: 3857 for ingestion with web map client.

**Comment by SteeveEbener** [comment]
Great. Thanks

**Comment by SteeveEbener** [comment]
We should close this issue while remembering to have this being clearly described in the CGR user manual.
