### ISSUE TITLE
Setting multipoint, multiline or multipolygon for a GeoObjectType

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#93]
RA/RM>GeoObject types and Hierarchies Manager>Create a GeoObject type>Geometry type

I am not sure to understand why the RA/RM has the possibility to define GeoObject types that are multipoint, multiline or multipolygon. 

Can the difference with point, line and polygon be explained in the current context to see if the distinction is necessary?

**Comment by justinlewis** [comment]
I think there's some confusion. Multi[point, line, or polygon] would not result in multiple records for the same GeoObject. It would just allow for an area to have disconected features. For example, a village would be able to have two polygons that are separated but still only one record in the database.

**Comment by SteeveEbener** [comment]
Thanks for the clarification => why then making the distinction in the dropdown menu?

Shall we not set it to multi[point, line (if we keep the lines), polygon]  by default?

This would not only avoid any confusion + make sure that a user does not choose "polygon" and then realize that he should have chosen "multipolygon" after some time

**Comment by SteeveEbener** [comment]
One specific use case in favor of removing the point, line and polygon options to keep the multipoint, multiline and multipolygon ones:

By accident, I create a GeoObject type using the polygon geometry type while the shape file I needed to import was of the multipolygon type.

When importing the shape file I got the issue reported under issue #242.

In order to solve the issue, I had to delete the master list already created and delete the geoObject type itself as the geometry can't be changed once set (which makes sense).

Luckily the GeoObject type in question was only at the bottom of one hierarchy and it has not been too much work to redo everything. This would have been a different thing if it would have been in the middle of that hierarchy.

**Comment by justinlewis** [comment]
@steeveebener - It looks like you're suggesting lines should be considered to be removed?

**Comment by SteeveEbener** [comment]
@justinlewis: that's a discussion that we were supposed to have at some point.  The main reason being that lines introduce some additional complexities from a topology (editing) and COT perspective.

**Comment by justinlewis** [comment]
It was agreed on June 1 by @justinlewis, @steeveebener, and @nmceachen That we need to keep line geometry types and to only support MultiLine, MultiPoint, and MultiPolygon types while labeling them as Line, Point, and Polygon on the frontend for simplicity.

**Comment by SteeveEbener** [comment]
Checked and implemented. I am closing this ticket
