### ISSUE TITLE
GeoObject geometry editing window too small

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#94]
RM>Master lists Manager>Master list content>Edit pen>Geometry

If the edit capacity is to remain in the CGR then the editing window should be bigger to allow for a good editing work and the basic functionalities you would expect for editing the different types of geometries (points, lines, polygons) should be available to the user.

**Comment by dtreatman** [comment]
How big should it be? Suggest we get direct feedback from users to inform the exact UI/UX before making changes.

**Comment by SteeveEbener** [comment]
Full screen to account for the different type of devices that will be used and ensure the most accurate editing work possible.

**Comment by justinlewis** [comment]
@steeveebener I velieve this is addressed with the map based iditing released in v 0.13.0?

**Comment by SteeveEbener** [comment]
Indeed, I am closing this ticket
