### ISSUE TITLE
Geometry tab still appearing in the editing window while the "Can geometries be modified in the web" option is unchecked

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#95]
**Describe the bug**
The Geometry tab still appearing in the editing window while the "Can geometries be modified in the web" option is unchecked

**To Reproduce**
1. Go to the "Manage GeoObject Type" window of any given GeoObject type
2. Uncheck the "Can geometries be modified in the web"  (by the way there is a typo in "modified"- missing a "i")
3. Go to the editing window for the given GeoObject type (through the master lists manager for example)
4. Observe that the Geometry tab is still there

**Expected behavior**
The Geometry tab is not appearing when the option to edit is unchecked 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 79.0.3945.130

**Comment by dtreatman** [comment]
Agree should be addressed.

**Comment by justinlewis** [comment]
https://github.com/terraframe/geoprism-registry/pull/139
