### ISSUE TITLE
Submit tab not necessary for RM

### ISSUE THREAD

**Issue by SteeveEbener** [terraframe/geoprism-registry#96]
RM>Change request manager

The "Submit" tab should not be available for a RM  as this would mean that they are submitting a request to themselves and would have to treat them

They would do the changes directly in the lists or geospatial data manager.

**Comment by dtreatman** [comment]
Suggest that this issue be discussed and addressed in a later sprint.

One concern that comes to mind is: when RCs submit change requests that get approved, they are auditable in the list of change requests. If an RM or RA makes a direct change to the master list, it is not auditable in the list of change requests. I would like to ensure that the process to change GeoObjects is identical or nearly identical across all users, and the result of all changes is auditable. Let's first ensure that we have a solution that addresses these points before starting to hide buttons.

Also, I could see a case where user "Jane" is an RM for master list X, but is only RC for master list Y, in which case she needs to be able to see the Submit button, even though she is an RM (for at least one of her master lists).

**Comment by SteeveEbener** [comment]
You mostly addressed the first concern in issue #62.

Regarding Jane's case, a RM who wants to submit a change request for a GeoObject type on which he does not have the mandate will first have to be accepted as a RC by the RA managing the GeoObject type in question => in theory he will first have to log out as a RM to log in as RC.

This being said, and if the systems allows, we could imagine that the RA has the possibility to link the RC to the existing RM account and therefore avoid for the logout-login process.

Another alternative would be to decide that RAs and RMs are automatically RCs for any other master data included in the CGR (need more thinking about this one). 

In both cases, the " Submit" tab would remain but the dropdown for the GeoObject types will have to contain those for which the RM can submit a request.

**Comment by SteeveEbener** [comment]
I have adjusted the title and description of this ticket to account for the change that the inclusion of the SRA role has brought to the governance of the system.

=> The subsequent exchange between Derek and me should normally also be adjusted to account for that and part of it actually be considered as obsolete in view of the rights by role google spreadsheet.

**Comment by SteeveEbener** [comment]
This ticket can be closed in view of the decision taken by the group on July 23rd (Manila time)

**Comment by SteeveEbener** [comment]
This ticket can be closed in view of the decision taken by the group on July 23rd (Manila time)
